CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      ATAGCTAGCGGTCGAGTTACCAGGACCATGCACGTCTGTCCTGTGTCCGTCTACTGCTCC
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
                                                                                    

AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      ACGACAGGACAACCACACCGGGATAGGTAGGAGAGGCCACCCAGAGGATGCGCTAGTGGC
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      --------------------------------------------------------CAGC
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
                                                                                    

AT1G11450               ------------------------------------CCCAAACACAGTACTCTTTCTTAT
TraesCS3B02G026700      AACAATGGCGCCCACTATG-----GCACTATATATACCCCTGCACCCTCCAATTCCTCTC
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      AACAATGGCGACCACTATGGCAGTACACTATATATACCCCTGCACCCTCCAATTCCTCTC
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -----ATGCGCAGCCCAAGCGAAGGCAACCGACCTTGGCTTGCACATATCTTCTTCTTGT
TraesCS7A02G087800      -----ATGCGCAGCCCAAGCGAAGGCAACCGACCTAGGCTTGCACATATCTTCTTCTTGT
                                                                                    

AT1G11450               AAGTTATAAATATGGGAAGGGTGGTTGCCAAACTCAAAGTACTTTGG-GTCTTAACTCTT
TraesCS3B02G026700      -------------------------AACACAACCACAAGCAGTTAGTAATCTGCATTCTT
TraesCS3A02G019600      -------------------------AACACAACCACAAGCAGTTAGTAATCTGTATTATT
TraesCS3D02G027300      -------------------------AGCAGAACCACAAGCAGTTAGCACCCCGCATTGTT
TraesCS4A02G415600      ------------------AGGCTCGACCTGCACTTGGCGTTCTTCTTCGACTCGATCAGT
TraesCS4B02G086600      -----------------------------------CGTGCGTGTGTGTGACTTGGTGTAC
TraesCS4A02G386700      -------------------------TCCAGCGGCATGCGTGCGTGTGCGTCTTGGTGACT
TraesCS7A02G087800      -------------------------TCCAGCGGCATTCGTGCGTGTGCGTCTTGGTGACT
                                                              *    *      *         

AT1G11450               TCTA-ACACACAAACTCACATAGAATTCAAGAAAGAGAGAAC------------------
TraesCS3B02G026700      TCTCTGTACGTAGATCACTGACAAGTTGTAGAGAGAAAGTGA------------------
TraesCS3A02G019600      TCTCTGTACGTAGATCGCTGACAAATTGTAGA----------------------------
TraesCS3D02G027300      TCTCT----GTAGATCACTAACAGGTTGTAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA
TraesCS4A02G415600      TCTTCTGGAGTGAAAC-CTGATCAGCTCGGGCTATAGGCTTGGGCATG------------
TraesCS4B02G086600      TCT-----------------ACGAAGTGGTGGTATAGCGCGAGACAGA------------
TraesCS4A02G386700      T-------GGTGTACT--CTACTACGTGGTGGTATAGCGCGAGACAGAATAGA-------
TraesCS7A02G087800      T-------GGTGTACT-CTACTACGGTGGTGGTATAGCGCGAGACAGA------------
                        *                         *   *                             

AT1G11450               ------------GAGGGAGAGATGGGTGAGGATATGCGA---------------GGAGTG
TraesCS3B02G026700      ------------GGAGGAGAGATGGGGAGGGATCAGCAGGCG------------GGCGCG
TraesCS3A02G019600      ------------GAGGGAGAGATGGGGAGGGATCTGCAGGCCGGTTTGGGTGCAGGCGCG
TraesCS3D02G027300      GAGAGGAGGAAGGAGGGAGAGATGGGGAGGGATCAGCAGGCAGGTGTAGGTGCAGGCGCG
TraesCS4A02G415600      ------GCTGGAGGAGGTGAGACG-ATGGGGCTGGGAGGGCTGTGGAGGAGGTACGCGC-
TraesCS4B02G086600      ------A-----TAGAGAGAGCGATATGGGGAGCGGCGGGTTGTTGTTGCCGACCGTGGT
TraesCS4A02G386700      ------------GAGCGCGATATATATGGGGAGCGGCAGGTTGTTGTTGCCGACGGTGGT
TraesCS7A02G087800      ------A-----TAGAGAGAGCGATATGGGGAGCGGCGGGTTGTTGTTGCCGACGGTGGT
                                        * **         **    *                   * *  

AT1G11450               AAAGTAGTCTCA-------AAATGGCCACCGATGATAGTTATGGTGACATCACAAGTAGC
TraesCS3B02G026700      GCGGC-GGCGCACCGGGAGAAGGTGAAGCTGTTCATGGGCGTGCTGGCGCTGCAGTTCCT
TraesCS3A02G019600      GCGGC-GGCGCACCGGGAGAAGGTGAAGCTGTTCATGGGGGTGCTGGCGCTGCAGTTCCT
TraesCS3D02G027300      GCGGC-GGCGCACCGGGAGAAGGTGAAGCTGTTCATGGGGGTGCTGGCGCTGCAGTTCCT
TraesCS4A02G415600      --------CGCAC------AACATGA---TGATCATGG------------TGCAGCTCTG
TraesCS4B02G086600      GATGCTGGCGCTC------AACGTGT---TGTCGGCGGTGATGGTGGCGCTG--------
TraesCS4A02G386700      GATGCTGGCGCTC------AACGTGA---TGTCCGCGGTGATGGTGGCGCTG--------
TraesCS7A02G087800      GATGCTGGCGCTC------AACGTGT---TGTCGGCGGTGATGGTGGCGCTG--------
                                * *        **   *     *      *                      

AT1G11450               GATGGGTTCGGTGAATGCACTTGTGAAGAAAGCTCTTGATGTTGGTGTGAACCATATGAT
TraesCS3B02G026700      GCTCGCCGGCTTCCACATCGTCAGCCGCGCCGCGCTCAACATGGGCATCAGCAAGCTCGT
TraesCS3A02G019600      GCTCGCCGGCTTCCACATCGTCAGCCGGGCGGCGCTCAACATGGGCATCAGCAAGCTCGT
TraesCS3D02G027300      GCTCGCCGGCTTCCACATCGTCAGCCGGGCGGCGCTCAACATGGGCATCAGCAAGCTCGT
TraesCS4A02G415600      CTACACCCTCATGTACTTCGTCACCGAGGCCGCCTTCAACCGCGGCCTCAACCCCTACGT
TraesCS4B02G086600      ----------------------GTCAAGGTGGCCATGGCCGGCGGCCTCGACCCGCTCGT
TraesCS4A02G386700      ----------------------GTCAAGGTGGCCATGGCCGGCGGCCTCGACCCGCTCGT
TraesCS7A02G087800      ----------------------GTGAAGGTGGCCATGGCCGGCGGCCTCGACCCGCTCGT
                                                       **  *       **  *   *       *

AT1G11450               CATTGGTGCTTATCGAATGGCTATTTCCTCTTTCATTCTGGTTCCTATCGCCTATTTTTT
TraesCS3B02G026700      CTTCATCGTCTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACTTCCT
TraesCS3A02G019600      CTTCATCGTCTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACTTCCT
TraesCS3D02G027300      CTTCATCGTCTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACTTCCT
TraesCS4A02G415600      CTACGTCACCTACCGCCACCTCCTCGTCGCCCTCCTCCTCTGGCCCTTCGCCTACTACCA
TraesCS4B02G086600      GCTCGTCACGCTGCAGCAGCTCGCCGCCGCCATCTTCCTCGGCCCCATCGCGCACTGGAG
TraesCS4A02G386700      GCTCGTCACGCTGCAGCAGCTCGCCGCCGCCATCTTCCTCTGCCCCATCGCGCACTTCAT
TraesCS7A02G087800      GCTCGTCACGCTGCAGCAGCTCGCCGCCGCCATCTTCCTCGGCCCCATCGCGCACTTCAC
                                     *             *     * * **    **  ****  * *    

AT1G11450               GGAAAGGTTTATTGATATTTTGATGAAAATAGTTGAGTTATATATTTTTCTTATGCAAAA
TraesCS3B02G026700      CGAGAAGT------AC------------GTC---GCCGCCTCCATTCTTCTT-CTCTGCT
TraesCS3A02G019600      CGAGAAGT------AC------------GTCCGCGCCTCCACCATTCTTCTT-CTCCGCT
TraesCS3D02G027300      CGAGAAGT------AC------------GTCCGCGCCTCCACCATTCTTCTCGATCTGCT
TraesCS4A02G415600      CGAGAAGT------ACGTAATAAGCTCGGTC--------------TTGCCTTCATCAATT
TraesCS4B02G086600      AGAGGGGT------GAGTGA--------GTCCACACGACATC------------------
TraesCS4A02G386700      AGAGGGGT------GAGGGA--------GTCCACACGACATCCATCCATTTCGA------
TraesCS7A02G087800      AGAGGGGT------GAGTGA--------GTCCACACGACGTCCATTTCGATT-----GCA
                         **   **                     *                              

AT1G11450               TTTTCAAAAATTTGATTATATCAAAATAGTTTTTTCATATTTACATAATTAACAACATTT
TraesCS3B02G026700      TCATC-----TTCCAGCAGTTTCAAGAAAGCTTCTGCCAGTCAGTCAGAAAACAATGGCG
TraesCS3A02G019600      TCTTC-----TTCCAG------------------------------------CAATGGTG
TraesCS3D02G027300      TCTTC-----TTCCAG------------------------------------CAATGGCG
TraesCS4A02G415600      ACACCACGAAATTCAA--------------------------------------------
TraesCS4B02G086600      ----------ATCCAT--------------------------------------------
TraesCS4A02G386700      ----------TTGCAT--------------------------------GAAGCAACAT--
TraesCS7A02G087800      TATTCA----TTGCAT--------------------------------GAAGCTAT----
                                   *  *                                             

AT1G11450               ACTACAATTGAAGATTGTCAGAATGCTCTATTATAACATGTAAATAAACACCACTACATG
TraesCS3B02G026700      ------GTGTACAGTTTTTTGAATCCTG--------------------------------
TraesCS3A02G019600      ------GTGGACGGTTTTCTGAATCCTG--------------------------------
TraesCS3D02G027300      ------GTGGACGGTTTTCTCAATCCTG--------------------------------
TraesCS4A02G415600      ----------ACTTAATTTGGCGATGTG--------------------------------
TraesCS4B02G086600      ------ACATAGCCTTTTTCTCATCTTC--------------------------------
TraesCS4A02G386700      ------ATGTAGCCTTTCTCTCATCTTC--------------------------------
TraesCS7A02G087800      ------ATATAGCCTTGTTCTGATT-----------------------------------
                                  *                                                 

AT1G11450               TTACTAATATATGAAGTAGATTGATATTTTCTTTCCCCTAAAGTTTATGTCTTATTGTTA
TraesCS3B02G026700      ----------G---------CGTGTCTGTTCTTTTTTCCATCATT---------------
TraesCS3A02G019600      ----------GTAGTGTCTCTGTTTTTCTTCTTCTTC---TTCTT---------------
TraesCS3D02G027300      ----------G---------TGTGTTTGTTCTTTTTT---TTCTT---------------
TraesCS4A02G415600      ----------ATGATGAATCTGTCTTCATTTTTGGGCGC---------------------
TraesCS4B02G086600      ----------G---------------GTTGATTGGTCTCATCCAT---------------
TraesCS4A02G386700      ----------GTGTTGA--------------TTGGTCTCATCCAT---------------
TraesCS7A02G087800      ----------ATACTGGTTTCGGTTTCATACTT--TCATATCCAT---------------
                                                       **                           

AT1G11450               ACAGGAAAATAATACCGAAAATAACGTTTAGGCTAATGGTCGATCATTTCATCAGTGGTT
TraesCS3B02G026700      -CAGGAAGGACCGGCCGCCGCTCACCTTCTCGCTGCTGGCGGAGTTCTTCGT---GCTGG
TraesCS3A02G019600      -CAGGAAGGACAGGCCGCCGCTCACCTTCTCGCTGCTGGCCGAGTTCTTCGT---GCTGG
TraesCS3D02G027300      -CAGGAAGGACCGGCCGCCGCTCACCTTCTCGCTGCTGGCGGAGTTCTTCGT---GCTGG
TraesCS4A02G415600      -CAGGAAGCTGAGGCCCAAGATGACCTGGATGCTGTTCCTGGAGATCTTCGT---GCTCT
TraesCS4B02G086600      -CAGCAAGTCGAGGCCCAAGATGACGCTCGAGATCTTCGCCCACCTCTTCATCAGCGCCG
TraesCS4A02G386700      -CAGCAAGTCGAGGCCCAAGATGACGCTCCAGATCTTCGCCTACCTCTTCGTCAGCGCCG
TraesCS7A02G087800      -CAGCAAGTCGAGGCCCAAGATGACGCTCGAGATCTTCGCCTACCTCTTCGTCAGCGCCG
                         *** **       **     * **      * *  *     *    *** *        

AT1G11450               TGCTCGGGTTTGTCTTCTCACAATTTCTTATGTTCTTTTGTCGTCCATTTTCCATTTTCC
TraesCS3B02G026700      CGCTCA------------------------------------------------------
TraesCS3A02G019600      CGCTCA------------------------------------------------------
TraesCS3D02G027300      CGCTCA------------------------------------------------------
TraesCS4A02G415600      CGCT-----------------------------TCTGGGGTAAGAAGTACCAAGGATGAC
TraesCS4B02G086600      CGCTCGGGTACTCTTTCT--------------TTCCTTGATCAAATCTTCTCTGTTCGAT
TraesCS4A02G386700      CGCTCGGGTACTTTTCCA--------------TTCATTGATCAAATCTTCTCCGTTTGAT
TraesCS7A02G087800      CGCTCGGGTACGTATTCT--------------TTCCTTGATCAAATCTTCTCAGTTTGAT
                         ***                                                        

AT1G11450               TTTTCCATTATACATTGATTGTT------TCCACAGAAGAAAGATTTTCTTTCAAGTGAG
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      T---------GAGAAAAACAGTTCATATATATGTAATATGTAGGTTTCATCCTGAGAAAA
TraesCS4B02G086600      CTTCGAACTAAGTAACAACGGCTGGATCATTTCTTGTACTACTACACCATCTTGCATGGT
TraesCS4A02G386700      CTTCAAATCAACAACGTTTGGAT------CATATGGTGTACACGATCGATCTTGCATGGT
TraesCS7A02G087800      CTTCCAATCAACGACGGTTGGAT------CATATAGTGTACACAATCGATCTTGCATGGT
                                                                                    

AT1G11450               CATAAAATCTTCATAAGCTAGCTAAATTGTTTTTAATCTTAGCTTAGTTTTGGGTTTAAA
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ATAAGTGGAATTGTT---------------------------------------------
TraesCS4B02G086600      G-----------------------------------------------------------
TraesCS4A02G386700      GGCAC-------------------------------------------------------
TraesCS7A02G087800      G-----------------------------------------------------------
                                                                                    

AT1G11450               TTTGCAGGGCGAGTTTGATGCAATTTTTCTATTTGCTTGGTCTGTCCTACACGTCAGCAA
TraesCS3B02G026700      ---TCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTGTACCACCTGTCGCCGA
TraesCS3A02G019600      ---TCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTGTACCACCTGTCGCCGA
TraesCS3D02G027300      ---TCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTGTACCACCTGTCGCCGA
TraesCS4A02G415600      ---GCAGGGTGAGCTTGACCCTGAACATGTACTTCGCGAGCCTCAAGTACACGTCCCCGA
TraesCS4B02G086600      ---GCAGGGCGGCGATGAGACAGTACACGGTCTTCGTGGGGCTGCGCTACACCACGGCGA
TraesCS4A02G386700      ---GCAGAGCGGCGATGAGGCAGTACATGGTCTTCGTGGGGCTGCGCTACACCACGGCGA
TraesCS7A02G087800      ---GCAGGGCGGCGATGAGGCAGTACATGGTCTTCGTGGGGCTGCGCTACACCACGGCGA
                            * *         **  *            *     * **     **    *  * *

AT1G11450               CTGTTGCGTGTGCTTTGGTAAGCTTGATGCCTGCAATCACCTTTGCTTTCGCTCTTATTT
TraesCS3B02G026700      CCTACGCCTCCGCGATCCAGAACATGGTGCCGGCCATCACCTTCGTGCTGGCCGCGG---
TraesCS3A02G019600      CGTACGCGTCGGCGATCCAGAACATGGTGCCCGCCATCACCTTCGTGCTGGCCGCGG---
TraesCS3D02G027300      CCTACGCGTCGGCGATCCAGAACATGGTGCCAGCCATCACCTTCGTGCTGGCCACGG---
TraesCS4A02G415600      CCTTCGTCACCTCCATGGTCAACACCGTCGCCTCCATCACCTTCGTCATCGCCATCG---
TraesCS4B02G086600      CCTTCGTCAGCGCCTTCTCCAACATCGCGCCTGTGCTCACCTTCGTGCTTGCCGTCG---
TraesCS4A02G386700      CCTTCGTCAGCGCCTTTTCCAACATCGCGCCCGTGCTCACCTTCGTGCTCGCCGTCG---
TraesCS7A02G087800      CCTTCGTCAGCGCCTTCTCCAACATCGCGCCCGTGCTCACCTTCGTGCTCGCCGTCG---
                        *    *      *  *    * *       *     ******* *   * **        

AT1G11450               TGAGGTAATTATGGAACCATCTAACTTCTTTATCATTAAAATAAGTACTGTATTTACTAT
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
                                                                                    

AT1G11450               TACTATGCAATGGGTTCATGCAGGATTTATTCGTATTTGTTATGTATACAGTGCATATAA
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
                                                                                    

AT1G11450               TTTCTTTTGTTTTTTCATCAAGCATATTATACTTCTATATATAGAAATACTCAAAAGAAC
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
                                                                                    

AT1G11450               CTTACTCATAAATTATCTCAAATTTATCATCTAAAAGGTTATATTACTTTTCAGAACTGA
TraesCS3B02G026700      -----------------------------------------------TCCTCCGGCTGGA
TraesCS3A02G019600      -----------------------------------------------TCCTCCGGCTGGA
TraesCS3D02G027300      -----------------------------------------------TCCTCCGGCTGGA
TraesCS4A02G415600      -----------------------------------------------CGCTCCGGATGGA
TraesCS4B02G086600      -----------------------------------------------CCACCCGCTCCGA
TraesCS4A02G386700      -----------------------------------------------CCACCCGCTCCGA
TraesCS7A02G087800      -----------------------------------------------CCACCCGCGCCGA
                                                                           * *    **

AT1G11450               GAAGATAAAAGATCTAAAGACCCAAGCAGGAATGATAAAAGTGATGGGAACTCTAATATG
TraesCS3B02G026700      GCAGGT---GGACCTGGGCCGGCGGCATGGGGTGGCCAAGGTGGTGGGCACGGTGGTGAG
TraesCS3A02G019600      GCAGGT---GGACCTGGGCCGGCGGCACGGGGTGGCCAAGGTGGTGGGCACGGTGGTGAG
TraesCS3D02G027300      GCAGGT---GGACCTGGGCCGGCGGCACGGGGTGGCCAAGGTGGTGGGCACCGTGGTGAG
TraesCS4A02G415600      GATCGT---GGACCTGCGCAGCGCGCGGGGGCTCGCCAAGGTGGCCGGCACCGCGGTGTC
TraesCS4B02G086600      GTCGCT---CCACCTCAGGGCCGCCACCGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTC
TraesCS4A02G386700      GTCGCT---CCACCTCAGGGCCGCCACCGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTC
TraesCS7A02G087800      GTCGCT---CCACCTCAGGTCCGCCACCGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTC
                        *    *     * **             **       **  *    ** **     *   

AT1G11450               TATAAGTGGAGCTTTGTTCTTAACATTTTACAAAGGCCCTCATATATCAAACTCTCAC--
TraesCS3B02G026700      CATCGGCGGCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCCACAAC--
TraesCS3A02G019600      CATCGGGGGCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCCACAAC--
TraesCS3D02G027300      CATCGGCGGCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCCACAAC--
TraesCS4A02G415600      CTTCGCGGGGGTCACCACCATGACGCTCTACAAGGGCGCGGCCATCGCGAGCCCCTGGAG
TraesCS4B02G086600      GCTCGCCGGCGCCATGCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACGCCAACAG
TraesCS4A02G386700      GCTCGCCGGCGCCATGCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACCCAAACAG
TraesCS7A02G087800      GCTCGCCGGCGCCATGCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACCCAAACAG
                          *    ** *         * **  * ****  ***       *      *        

AT1G11450               ----------TCTCACCTAGAGGCTCTTCCTCACAACAACAGCGATCAC----AACACCA
TraesCS3B02G026700      ----------CTGCACGTGCAGGCCGTGCTCTCCTGGACCTCCGGCAGC----CCCATCT
TraesCS3A02G019600      ----------CTGCACGTGCAGGCCGTCCTCTCCTGGACCTCCGGCAGC----CCCATCT
TraesCS3D02G027300      ----------CTGCACGTGCAGGCCGTCCTCTCCTGGACCTCCGGCAGC----CCCATCT
TraesCS4A02G415600      G---------GCGCCCGTGCG------CATCCCCGGCGCCGGCGGCGACGCCCCGCA-CG
TraesCS4B02G086600      CGCCCACCAGCTCCAC-CGCCCCCCTTCTTCCCCACCGTCCCCGGCAACCGACTCCGGCA
TraesCS4A02G386700      CGCCCACCAGCTCCAC-CGCTCCCCTTCATCCCCGCCGTCGCCAGGAGCGGACTCCGGCA
TraesCS7A02G087800      CGCCCACCAGCTCCAC-CGCTCCCCTTCATCCCCGCTGTCGCCAGGAGCGGACTCCGGCA
                                     * *                 *     *  *     *      *  * 

AT1G11450               AGAATTGGCTTCTTGG----ATGTCTCTACTTAGTCATAGGAATCGTGTTGCTATCTCTA
TraesCS3B02G026700      TCAACTGGACCCTCGGCTGCGTCTTCATCCTCGGCCACTG----CCTCTCCTGGTCGGGA
TraesCS3A02G019600      TCAACTGGACGCTCGGCTGCGTCTTCATCCTCGGCCACTG----CCTCTCCTGGTCGGGA
TraesCS3D02G027300      TCAACTGGACCCTAGGCTGCGTCTTCATCCTCGGCCACTG----CCTCTCCTGGTCCGGC
TraesCS4A02G415600      ACGCCTGGCTCAAGGGGTCCCTCCTTGCCGTCGCCAGCTG----CGTGTGCTGGTCCGTC
TraesCS4B02G086600      GGCTGTGGACGCTGGGAACGGTGGCGATCCTCGGCAACTG----CGTCTGCCTCGCCTGC
TraesCS4A02G386700      GGCGGTGGACGCTTGGCACGGTGGCGATCCTCGGCAACTG----CGTCTGCCTCGCCTGC
TraesCS7A02G087800      GGCGGTGGACGCTGGGCACGGTGGCGATCCTCGGCAACTG----CGTCTGCCTCGCCTGC
                             ***      **     *        *        *    * * *      *    

AT1G11450               TGGATATTGTTTCAAGGGACTTTAAGCATCAAGTATCC-TTGCAAATTCTCAAGCACTTG
TraesCS3B02G026700      TGGATGGTGCTCCAGGTGCCCGTGCTCAAGCGGTACCCGGCGAGGCTGTCGGTC-ATCTC
TraesCS3A02G019600      TGGATGGTGCTCCAGGTGCCGGTCCTCAAGCGGTACCCGGCGCGCCTCTCGGTG-ATCTC
TraesCS3D02G027300      TGGATGGTGCTCCAGGTGCCGGTGCTCAAGCGGTACCCGGCGAGGCTGTCGGTC-ATCTC
TraesCS4A02G415600      TGGTACATCATGCAGGCCACGTCCGTGAAGCGCTACCCGGCGGAGCTGTCGCTG-ACGGC
TraesCS4B02G086600      TGGTACCTGCTTCAGGGCAGGATCGCCAGGAAGTACCC-CTACGTCTACTCCTGCAACGC
TraesCS4A02G386700      TGGTACCTGCTCCAGGGCAGGATCACCAGGAAGTACCC-CTACGTCTACTCCTGCAACGC
TraesCS7A02G087800      TGGTACCTGCTCCAGGGCAGGATCGCCAGGAAGTACCC-CTACGTCTACTCCTGCAACGC
                        ***    *  * ** *           *     ** **        *        *    

AT1G11450               TCTCATGTCAATTTTCGCAGCTTTTCAATGTGCTCTATTGAGTCTTTACAAGAGTAGAGA
TraesCS3B02G026700      GCTCACCTGCGTCTTCGGGCTGCTCCAGTTCCTCGTCATCGCCGCCTTCACCGAGGAGGA
TraesCS3A02G019600      CCTCACCTGCGTCTTCGGGCTACTCCAGTTCCTCGTCATCGCCGCCTTCACGGAGGAGGA
TraesCS3D02G027300      GCTCACCTGCGTCTTCGGGCTGCTCCAGTTCCTCGTCATCGCCGCCTTCACCGAGGAGGA
TraesCS4A02G415600      GTGGATGGCCACCGTGGGCGGCGCCCAGTCGGCGGCCTTCGCGGTGCTGCTGCAGCACGA
TraesCS4B02G086600      CTTCCTGTCCACCTTCAGCTTCCTCCAGGTCGCCGTAGTTGGCCTCTGCGTGCAGCGCAA
TraesCS4A02G386700      CTTCCTGTCCACCTTCAGCTTCCTCCAGGTCGTCGTCGTCGGCCTCTGCGTGAAGCACAA
TraesCS7A02G087800      CTTCCTGTCTACCTTCAGCTTCCTCCAGGTCGCCATCGTCGGCCTCTGCGTGAAGCGCAA
                                      *          **           *                    *

AT1G11450               CCTTAAACATTGGATCATCGACGATGGATTTGTGATTGGTGTCATAATATATGCTGTAAG
TraesCS3B02G026700      CATGAGCCGGTGGAAGGTGCAGTCCGTCGGGGAGCTCTTCACCATCCTCTACGC------
TraesCS3A02G019600      CCTGAGCCGGTGGAAGGTGCGGTCCGGCGGGGAGCTCTTCACCATCCTCTACGC------
TraesCS3D02G027300      CCTCAGCCGGTGGAAGGTGCAGTCCGGCGGGGAGCTGTTCACCATCCTCTACGC------
TraesCS4A02G415600      GAGGCGGGACTGGCTCGTCGGCTTCGGCCTCAACTTCTGGTGCATCATCTACTCCGTACG
TraesCS4B02G086600      CCTCTCCGCCTGGATCATCACCGACAAGCTCCAGATCATCACCGTCCTCTACTCCGTAAG
TraesCS4A02G386700      CCTCGCCTCCTGGATCATCACCAACAAGCTCCAGATCCTCACCATCCTCTACTCCGTAAG
TraesCS7A02G087800      CCTCGCCGCCTGGATCATCACCAACAAGTTCCAGATCCTCACCGTCCTCTACTCAGTAAG
                                  ***    *                 *      * *  * **  *      

AT1G11450               TTATAATACTATATTATCAGAAATCTTAACATTTTTATAAATTATAATGTAGTATATATG
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      TGCCTGCTCTTGTCTCAGATCACCGTCTGTCTTTCTCCCCCGTCCATGCCACTCGCCATG
TraesCS4B02G086600      TAACCAACCAACCAGCCCTCATACGTATATGCTTCTGAAATCTGAATTGCTTGCTACAAT
TraesCS4A02G386700      C--------------------------------------TTCTGAATTGCTTGCGACGGT
TraesCS7A02G087800      C--------------------------------------TTCTGAATTACTTGCAACGGT
                                                                                    

AT1G11450               TAAATAATTAAATAAATTTTGGGGTTTACCTAATATTACCTTATTACTATACACGTATTA
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      CATGTAGCCAGCGCATGCTCATGAACTGCGTGCGTGCACGAACTCGCA------------
TraesCS4B02G086600      ATGCAGCTGGC--------TTGCCACTGATTTTGCCTGAATAAATTCA------------
TraesCS4A02G386700      ATGCCGCCGATCG------TCGTAACTGATTAATTGTGCCTGAACTGAATGAATTCA---
TraesCS7A02G087800      ATGCCGCTGATTG-----------ATTAATTGTGCCTGAATAAATTCA------------
                                                                                    

AT1G11450               TAGGGAGTGATAGGACAAGC---AATGTCGACTGTAGCAGCGACATGGGGAATAAACAGA
TraesCS3B02G026700      --CGGGCTGGTGGCCTCCGG---CGTGGCGTTCGCCCTGCAGATCTGGTGCATCGA-CCG
TraesCS3A02G019600      --GGGGCTGGTGGCCTCCGG---CGTGGCGTTCGCGCTGCAGATCTGGTGCATCGA-CCG
TraesCS3D02G027300      --GGGGCTGGTGGCCTCCGG---CGTGGCGTTCGCGCTGCAGATCTGGTGCATCGA-CCG
TraesCS4A02G415600      --GGGGCTCGCGTGCAGCGGGTTCACGGTGTTCGCGCAGCTG---TGGTGCACGGAGAAG
TraesCS4B02G086600      --GGGCGTGGTCGCGACCGG---CATGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAG
TraesCS4A02G386700      --GGGCGTGGTGGCGACGGG---CATGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAG
TraesCS7A02G087800      --GGGCGTGGTGGCGACCGG---CATGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAG
                           **  *          *       *      *       *   *** * *   *    

AT1G11450               TTAGGAGCTG-TTTTCGCATCAGCAATTATGCCAGTTTCTCTCATATCGGCTACTCTATT
TraesCS3B02G026700      CGGCGGCCCGCTCTTCACCGCCGTGTTCCAGCCCGTGCAGACCGTCGCCGTCGCCGTCAT
TraesCS3A02G019600      CGGGGGCCCGCTCTTCACCGCCGTCTTCCAGCCCGTGCAGACCGTCGCGGTCGCCGTCAT
TraesCS3D02G027300      CGGCGGCCCGCTCTTCACCGCCGTGTTCCAGCCCGTGCAGACCGTCGCCGTCGCCGTCAT
TraesCS4A02G415600      AAGGGGCCCG-TGTTCGTCACCATGTTCAACCCGGTGTCCACCATCATGGTGGCCATCCT
TraesCS4B02G086600      TGGGGGGCTG-TGTTCGTGGCCGCCTTCATCCCGGTGTCTCAGGTCATCGTCTGCATCAT
TraesCS4A02G386700      CGGGGGGCGG-TGTTCGTCGCCGCCTTCGTCCCGGTGTCGCAGGTCATCGTCTGCATCAT
TraesCS7A02G087800      CGGGGGGCTG-TGTTCGTCGCTGCCTTCATCCCGGTGTCGCAGGTCATCGTCTGCATCAT
                            *  * * * ***    *     *    ** **        *    *      *  *

AT1G11450               CGATTTCCTTATCTT--ACACACTCCTTTATACCTCGGAAGGTGCTCTCTTCGATCATCT
TraesCS3B02G026700      GGCCGCCATCATCCTCGGA--GACCAGCTCTACACCGGAGGGTAAGTAGAGAG-TAAAAT
TraesCS3A02G019600      GGCCGCCATCATCCTCGGC--GACCAGCTCTACACCGGAGGGTAAGCACGGAGATACAAT
TraesCS3D02G027300      GGCCGCCGTCATCCTCGGC--GACCAGCTCTACACCGGAGGG------------------
TraesCS4A02G415600      CGCCTACTTCATCTTCGGC--GAGAACCTATACGTCGGAAGGTACGTACGTAG--TACAT
TraesCS4B02G086600      GGACTTCACTGTCCT--GCATGAACCGCTCTACCTTGGAAGGTGCAAACACACTGCACCT
TraesCS4A02G386700      GGACTTCACCGTCCT--GCATGAACCGCTCTACCTTGGAAGGTGCAAACATACATACTGC
TraesCS7A02G087800      GGATTTCACCGTCCT--GCATGAACCGCTCTACCTTGGAAGGTGCAAACACACCTA----
                         *    *    ** *             * ***   *** **                  

AT1G11450               CTATGAAATTTTTTGTA-----------------------------TAGCTTTATAGATG
TraesCS3B02G026700      CCACATACACCAACATTG----------------------------TGACAGCACCATTG
TraesCS3A02G019600      CCACATACACGAGCATTT----------------------------TGACAGCACCATTG
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      CTGTACATGCGTGCGGTGCATGCTCGCTCGCTGCTCCTCAACTAAATCGGTGCTCCGTTC
TraesCS4B02G086600      ATAGAGATTCATGCATGTGTCTGTTTAC------------------CCATGGCATGATTG
TraesCS4A02G386700      TTACCCATG---GCATG-----------------------------GCATGGCGTGATTG
TraesCS7A02G087800      -TAGAAATTCATGCGTGTATCTGTTTAC------------------CCATGGCATGATTG
                                                                                    

AT1G11450               TT--AATGTATTAGG--------------------------TTCATGCTCGTATTACTAA
TraesCS3B02G026700      CACTCTTGTCTGACT--------------------------GACATGATT----------
TraesCS3A02G019600      CA--CTTGTCTGACT--------------------------GACATGATC----------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      CGGCATGGCATGGCAACCTGGACACAACATTGGCATGACTGCCCGCGCTCTCCTGCGTGC
TraesCS4B02G086600      G-----CATCTGAAA--------------------------CTTATGCTT-------TGC
TraesCS4A02G386700      G-----CATCTGACA--------------------------CTCATGCTT-------TGC
TraesCS7A02G087800      C-----CATCTGAAA--------------------------CTTATGCTT-------TGC
                                                                                    

AT1G11450               TTACAATTTATTTTGTA-------------------------------------------
TraesCS3B02G026700      ---CATGGCTGCTTGTG-------------------------------------------
TraesCS3A02G019600      ---CATGGCTGCTTGTG-------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      GTGCGTGCGTGCGTGCACCAACTACGTGTGTCTGTCTCACCGGCTTAATTAATAATTACT
TraesCS4B02G086600      AAACGTGTATGCATGCA-------------------------------------------
TraesCS4A02G386700      AAACGTGTATGCATGCA-------------------------------------------
TraesCS7A02G087800      AAACGTGTATGCATGCA-------------------------------------------
                                                                                    

AT1G11450               ---------------------ACTTTTGCTATACAGTGTGATTGGATCAGTAGGGACAAT
TraesCS3B02G026700      -------------------------------CGCAGGATCATCGGCGCGGTGCTGATCGT
TraesCS3A02G019600      -------------------------------CGCAGGATCATCGGCGCGGTGCTGATCGT
TraesCS3D02G027300      -------------------------------------ATCATCGGCGCGGTGCTGATCGT
TraesCS4A02G415600      GTTGCTTGTTAATTAACCGGCATGCCTGGCCTGCAGCATAATCGGGGGAGTGGTGGTCAT
TraesCS4B02G086600      -------------------------------TGCAGTGTGGTGGGATCTGTGATTGTGAT
TraesCS4A02G386700      -------------------------------TGCAGTGTGGTGGGATCTGTGATTGTGAT
TraesCS7A02G087800      -------------------------------TGCAGTGTGGTGGGATCTGTGATTGTGAT
                                                              *  * **    **        *

AT1G11450               AATAGGTCTCTACGTGTTCTTGTGGGGTAAGAACAAAGAAACGGAA--------------
TraesCS3B02G026700      CATCGGGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAGAAG-------ACGAGGA
TraesCS3A02G019600      CATCGGGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAGAAG-------ACGAGGA
TraesCS3D02G027300      CATCGGGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAGAAG-------ACGAGGA
TraesCS4A02G415600      CCTGGGCCTCTACATGCTGCTCTGGGGCAAGGACAAGGACCAGGAG------TACAACAA
TraesCS4B02G086600      AAGTGGCCTGTATCTTCTGCTGTGGGGCAAGAG------GCAGGAGGCCTTGCAACAGCA
TraesCS4A02G386700      ATGTGGCCTGTATCTTCTGCTGTGGGGCAAGAG------GCAGGAGGCCTTGCAACAGCA
TraesCS7A02G087800      AGCTGGCCTGTATCTTCTGCTGTGGGGCAAGAG------GCAGGAGGCCTTGCAACAGCA
                            ** ** **  *  *  * ***** ***           * *               

AT1G11450               -----------GCAGACATAACTACATTGTCTTC------------------TCGG----
TraesCS3B02G026700      GCCAAGA---TCCCGAGATGGCGA-GGCACCTGC------------------TGGGGGAA
TraesCS3A02G019600      GCCAGGA---CCCGGAGATGGCGA-GGCACCTGC------------------TCGGGGAA
TraesCS3D02G027300      GCCAAGA---CCCGGAGATGGTGA-GGCGCCTGC------------------TCGGGGAA
TraesCS4A02G415600      CGCAGGAGCAGCGGCGAGCGGCGA-GGAGCAGGCCGGCGAGCCCGGTCTGGACTGCGAGA
TraesCS4B02G086600      TCCAAGAGTTGCTAAAGATGACCA-AGAAC---------------------------AAC
TraesCS4A02G386700      TCCAGAAGGTGCTAAAGATGACCA-AGAAC---------------------------AAC
TraesCS7A02G087800      TCCAAGAGTTGCTAAAGATGACCA-AGAAC---------------------------AAC
                                               *                                    

AT1G11450               -------------------ATGAACA--------------------ACGAAGAT------
TraesCS3B02G026700      GACGGCGGC----------GAGGCTG--------------------ACAAAGAT------
TraesCS3A02G019600      GACGGCGGC----------GCGGCTG--------------------ACAAAGAT------
TraesCS3D02G027300      GACGGCGGC----------GCAGCTG--------------------ACAAAGAT------
TraesCS4A02G415600      AGCAGCGACAGGAGGAACAAGAGGAG--------------------ACCAAGAC------
TraesCS4B02G086600      AGCAGCAGCAGCAATTGCAGTCGCAG---------------------CCATGA-------
TraesCS4A02G386700      AGCAGCAGCAGCAAGTGCAATCGCAGCCATGACTGAAGATTGAGAGACAGAGAT------
TraesCS7A02G087800      AGCAGCAGCAGCAAGTGCAGTCGCAGCCATGACTGAAGATTGAAAAACAGAGATCCTCCA
                                                                       *   **       

AT1G11450               ----------------------CAACGAGT------------------------------
TraesCS3B02G026700      ----------------------CAGCAAGTGAGCACCGCTGTG-----------------
TraesCS3A02G019600      ----------------------CAGCAAGTG-----------------------------
TraesCS3D02G027300      ----------------------CAGCAAGTGAGCACCACTGTC-----------------
TraesCS4A02G415600      ----------------------GATGAAGTAGGATAGGAGGAGGGGTC------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ----------------------CCTCAATTG-----------------------------
TraesCS7A02G087800      TTCGGTGATCTGTTAACATGTGCAGCAAATCAGTTCTCCAATAATTTTTCCATGTTCTAG
                                                                                    

AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      --------------------CTGGCGTGA----------------------------AAG
TraesCS3A02G019600      --------------------CTGGCGTGA----------------------------CAG
TraesCS3D02G027300      --------------------CTGGCGTGA----------------------------AAG
TraesCS4A02G415600      -----------------AGAATTGCCTGC----------------------------CAT
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      TAATTATTATGATCACAATTCTGGCGCAAATTAGGCTTCAGGATGCTATCATTCATGAAG
                                                                                    

AT1G11450               -------------------------------CTAGGTCGCCCATTT------------AA
TraesCS3B02G026700      CTG---------------------CTAGCTGCTGGATATCCCTTGG------------AG
TraesCS3A02G019600      CTG---------------------CTG----CTTGATATTCCTTGG------------AG
TraesCS3D02G027300      CTG---------------------CTGCTTGCTGGAT-----TTGG------------AG
TraesCS4A02G415600      CCGTGTGCATGCCCAGCGCCGGTCCTGGAGTTTCGGAGGCCCCGGGGCGAACTCAAATGA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      CTGTTTAGGCTCTAATCCAAACAACAGTAGGGTGACTATTACCATGTTTCTGGAGAAGCG
                                                                                    

AT1G11450               TCA-----AATAATATTGTTGTCATAGAAAGATTCATATGG-C---------TTCA----
TraesCS3B02G026700      ATGTGTGTACTGATGTGGGTGTT-TGAACGTACTCCTACCT-T---------TTTAACTA
TraesCS3A02G019600      ATGTGTGTACTGATGTGGGTGTT-TGTA------CCTACGT-T---------TTTAA---
TraesCS3D02G027300      ATGTGTGTACTGATGTGGGTGTT-TGTA------CCTACGT-T---------TTTAA---
TraesCS4A02G415600      ATGGGCCCAATGACAGCATTGGAGGGAAAAAAATATTCCATAC---------TTTGATAA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -----------------GGTGTT-------------------------------------
TraesCS7A02G087800      TAGTTTGTGGGGACATATATATGTAAAAGTTAACTTTATTTCTGGCTATACATGTAATTT
                                                                                    

AT1G11450               ----------------TTGTCGT-------------------------------------
TraesCS3B02G026700      ----------------CTAGTGT-------------------------------------
TraesCS3A02G019600      ----------------CTAGTGT-------------------------------------
TraesCS3D02G027300      ----------------CTAGTGT-------------------------------------
TraesCS4A02G415600      AAAATATATTGCAAAGCTATAATAAACAACGGTAATTTTTCTTGGTAAATAACACTCCAA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      TGGGGGTAAAAGACAGCTGTTTT---------------TTTTTTGGCAACCAGCCCACGG
                                                                                    

AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      ---------------------------------TTCAAGCGTGCGATGCGACCAAG----
TraesCS3A02G019600      ---------------------------------TTCAAGCGTGCGTTACGACCAAG----
TraesCS3D02G027300      ---------------------------------TTCAAGCGTG-----CGACCAAG----
TraesCS4A02G415600      GTCATAAATAACAATTTCATACTGTAGGTGTAAATCAAACATCATAGAAGTCACAGAGCA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ---------------------------------AACAAGTGCA-----------------
TraesCS7A02G087800      GAGATACATGCATACATCTTGATCGCACGAGTAGGCATGCACACAGTGCAACAGAAAGTG
                                                                                    

AT1G11450               ------------AAATTAGTATT-------------------------------------
TraesCS3B02G026700      -----AAGAAGAAGACCCGTACTAGTTGAC------------------------------
TraesCS3A02G019600      -----AAGAAGAAGACTCGTACTAGTTGAC------------------------------
TraesCS3D02G027300      -----AAGAAGAAGACTCGTACTAGTTGAC------------------------------
TraesCS4A02G415600      TAACAAAAAAGAAATGACATACTAGCGAACCTCCAAGCCT--------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -----GCAAATAAGTTTTACAATAATT---------------------------------
TraesCS7A02G087800      TTGAGAATAAAAATCCAAGAATTAGTAGACATCGTCATTCAATTGCTCGGATTTCTTACT
                                                                                    

AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ---------------------------------CCAGTAATCATGAGAAACGGCTCCATG
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      TGCTTCAAGTAATCCTACTAATTTCTATCATTGAAACAATCTAAATTTCAGTACAACTTG
                                                                                    

AT1G11450               --------------TACT-----ACTGAATACATT---TA---------CCGTAAA----
TraesCS3B02G026700      --------GATGTGAACT-----GCCAAACACACT---CAGACATATT-TGGTACC----
TraesCS3A02G019600      --------GATGTGAACT-----GCCAAACACACT---CAGTCATATT-TGGTACC----
TraesCS3D02G027300      --------GATGTGAACT-----GCCAAACACACT---CAGTCATATT-TGGTACC----
TraesCS4A02G415600      CATTTTTTGATGCAAAATCATTAAATGAAAATGTC---AAGATAAATG-TAGTCTG----
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      --------------------------------------TTTCCATGTTCTAGTAAT----
TraesCS7A02G087800      CATTTATTGAATTAAACT-----GCTTAAAAGATTGGATAGACACAAATTCATAACTATA
                                                                                    

AT1G11450               --------GACCAGTCA-----------------TAAATATTTAGATTTAAATTGTGC--
TraesCS3B02G026700      --------TACTGTGTA-----------------TAGCCCCTTGTCTTCGAGTTGTGT--
TraesCS3A02G019600      --------TACTGTGTA-----------------TAGCCCC-TGTCTTCGAGTTGTGTGT
TraesCS3D02G027300      --------TACTGTGTA-----------------TAGCCCCTTGTCTTCGAGTTGTGTGT
TraesCS4A02G415600      --------TTTCAAACA-----------------CAAGATTTTGTTCCCTTGTAGGCC--
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      --------TATTGTGAT-----------------CACTATTCTGCC--------------
TraesCS7A02G087800      TACTGTAGTATTGTGCAAAAAAAATCATATACTGTAGCGATATTTTTAGAAATTTTGTGT
                                                                                    

AT1G11450               ---------------------------AAGCACACTC---------ACG-----TTAAAG
TraesCS3B02G026700      -------------------GTGTCTATAAATACACTATGCTCCCTAATT-----TTGAAG
TraesCS3A02G019600      G-----------------TGTGTCTATAAATACACTATGCTCCCTAATT-----TTGAAG
TraesCS3D02G027300      -------------------GTGTCTATAAATACACTATGCTCCCTAATT-----TTGAAG
TraesCS4A02G415600      -------------------CTTTTTATAATCAGAATA--TCTCTTGATTTATTGTCAAGA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -----------------------------GCAAATTAGGCTTCACGATG-----------
TraesCS7A02G087800      GGTCAGTGTAAGTTATCATGTGACTACAATTAGAAGATATGTCGTGATGGTTGCTGAATG
                                                                                    

AT1G11450               A-----------------------------------CCAGTCAT---------AAATAT-
TraesCS3B02G026700      C-----------------------------------TCTCCCAGTCTA-GTTGTGGTGT-
TraesCS3A02G019600      C-----------------------------------TCTCCCATTCTA--TTGGGGTGT-
TraesCS3D02G027300      C-----------------------------------CCTCCCATTCTATATTGGGGTGT-
TraesCS4A02G415600      G-----------------------------------TGTCCCAGTTT---CTAGGTTCA-
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -------------------------------------GTTTCATTC---ACGAAGTTGT-
TraesCS7A02G087800      CAATAGATTTGAATTGTGGGTTTTAAATCCTTATCTTCTCTCTATTTTTTTTAAGTTATC
                                                                                    

AT1G11450               -----TCAG-ATTCAAA------------TTGTGCAAGCAGTTTGTA-------------
TraesCS3B02G026700      -----TCAATTTTAGAA------------TT------TTGGATTATGATTTT--------
TraesCS3A02G019600      -----TCAA-TTTAGAA------------TTTAGAATTTGGTTTATGGTTTT--------
TraesCS3D02G027300      -----TCGA-TTTAGAA-------------------------------------------
TraesCS4A02G415600      -----TAGATATCAAAAGGAGAAAATCCTTGTTCATCTACACTTGTGGGATT--------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      -----TTAGGTTCAGGATGCTATTATAAATATGTAGTGTACTATATGT------------
TraesCS7A02G087800      CTCTCCCGATATTAATCATCATAGCTATATCTATATCTATATCTATATCTATACAAAGGG
                                                                                    

AT1G11450               ------------------------------------------------------------
TraesCS3B02G026700      ---------------------------------------------------------CAC
TraesCS3A02G019600      ---------------------------------------------------------TGT
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      ---------------------------------------------------------CTC
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      GCTATGGGTGAACCAACCTGTGGTTGGATGGTTAGAGGGACTATGGTATCCCCACCCCAT
                                                                                    

AT1G11450               --------------------------TAA--------------TTCATACTTTTCGTTTG
TraesCS3B02G026700      TGGGTC---AACGATTTTGATTGAGGTTA--------------TT-TTAAATTTGGTTTA
TraesCS3A02G019600      GGGGTC---AACTATTTTGAT-GAAGTTA--------------TT-TTGAATTTGGTTCA
TraesCS3D02G027300      ---------------------------------------------------TTTGGTT--
TraesCS4A02G415600      ACGGTCACTCAAAATATTTATAGGAGTCCCATATGGGCATTGTTTCCTCAATTGTGGTCT
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ---------AGCAATATTTTTAGAAATTA--------------T----------------
TraesCS7A02G087800      CAGGGTTCAAATCCTGATGCTCGCATTTA--------------TTCCTATATTTATTTCA
                                                                                    

AT1G11450               CAGATTTA----------------------------------------------------
TraesCS3B02G026700      CAATTTTT-------------------------------------------------CTT
TraesCS3A02G019600      TAGTTTTT-------------------------------------------------ATT
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      CATTCTCAGCGGGTTGTTGTTG---------------------------------GCCTT
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      GGATTTCTGACGATACGCATTTAATGGGAGAAGACGTTCCCGTCGACAACGAGGCACCTA
                                                                                    

AT1G11450               ---TAATTTCGTAAAG-------------------------------AGATAACAAAACA
TraesCS3B02G026700      CAGT--------------------------------------------------------
TraesCS3A02G019600      CGGT---TTTGTGTGT-------------------------------GGGTGGGGAGGGG
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS4A02G415600      GTGCCGAGAAGTGTAT-------------------------------GGATGAACCTGGG
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------------------
TraesCS7A02G087800      CGGTGACTTCGTAAATCTCAACATGATATGCTGGCTCAGTCTTTCAGAGGTGCTCATAGG
                                                                                    

AT1G11450               G-----------------------------------------------
TraesCS3B02G026700      ------------------------------------------------
TraesCS3A02G019600      GGAGTGATATCTGACCGTTGGCACTATTTTTAATTGTTTGGATTGCTT
TraesCS3D02G027300      ------------------------------------------------
TraesCS4A02G415600      TACATATGAACCCATTTTGAAAAACACATTTTGCAATG----------
TraesCS4B02G086600      ------------------------------------------------
TraesCS4A02G386700      ------------------------------------------------
TraesCS7A02G087800      GGTAGGGTGTGTGTTCATAGGGGTGAGTGTATGCGCGTG---------
                                                                        
