CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS7A02G409900      -------------AGCAAACGGGGCAGCTCACGCCAACCGGCACAGTGTCTACATTCCTT
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      AGTCGTTCCCCAAGACAAATGGAACAGCTCACGCTACTCATGGCAGCGACCGTACTGCAG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               -----------------TAAATAGGATCAATCCCAATGCATGCTTGTGTCCGAA------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      -------------------ATGGGGAAATCACCTAAAAAACAGTGGGG------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ACT-----------------------------------------CCGTATGGTTGCGTGG
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      CATGTGATGTGCTACTGCAGAGGATCCTAACCCCTGCATACGGGCAGGTTGCGTGCGTGG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------GCATGA
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      AGCCAGAAGCCACCG-----CAGCCTTTCCCCAATAAGTCCGCCACA-----CGACGGCC
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      AGCCAGCAGCCACCGGCCGCATACCTTCCCCCAATAAATCCGCCACGACGGCACGCAGGC
TraesCS1A02G095600      ------------------------------------------------AACTCAACCACT
AT3G45870               TGTCATCATTTGTTAGTTCCCCTGTCTCGTTCGATCAAA-----AAACACGTTTTGACAG
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      -----------------------------------AAAAGTCCTAAAAAAAACAGTGGGG
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      GGCAGAGCCGCAGAGGCAGACACCACAATCAGGGGCCGGTGACATCGCCGTCCATCGCAG
TraesCS7B02G309300      --GAGATTCG-------------------------------------CTTCTCCTAGTCG
TraesCS7D02G403100      GAAAAATCTGGAG-----------------------------TTTTGCTTCTCCTAGTCG
TraesCS1A02G095600      GAGAACTTCTCAA-----------------------------------------------
AT3G45870               AAGAGATTCAAAGTGACAATCAGTTTCAAGATTTAATTCTCTTACCCACTCTCTCACCCT
TraesCS6B02G298700      -GAAAGTTCAAAGAGGAG------------------------------------------
TraesCS6A02G271500      AAAAGGTTCAAAGAGGAG------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      AAAAGTCCAGGTGAGATAGAGAGAGAGATCTTTCTCCGAGCTCAGCCAGCTAGGCTCCCG
TraesCS7B02G309300      GAG--------------------------CCTCGTCGGAGCCCAGCAAG-----------
TraesCS7D02G403100      TCG--------------------------CCTCGTCGGAGCCCAGCAAG----------A
TraesCS1A02G095600      -----------------------------------------TCGATCAG-----------
AT3G45870               GG-----------------------------CTTTCATAACTTTCTCCG-----------
TraesCS6B02G298700      -------------------------------TAGTCGCTACTCAGACCG-----------
TraesCS6A02G271500      -------------------------------TATTCGCTACTCAGACCG-----------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CGGTAGCAGTAGCGCCTAGCGGCCGGCGTG------------------------------
TraesCS7B02G309300      --GCTGGAGTAGTGCCCAGCGGCCGGCGCGAGAGGGAGTC----------------AGAG
TraesCS7D02G403100      CTGCTGGAGTAGTGGCTAGCGGCCGGCGCGCAGAGAGAGCGAGAGAGAGACAGAGGAGAG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      -GAGAGAGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGG
TraesCS7B02G309300      AGAGAAGGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGG
TraesCS7D02G403100      AGAGAGGGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGG
TraesCS1A02G095600      ------------------GAGTCGACCAC-----------------------TCAGGAGT
AT3G45870               ------------------GGAATAAGAAT--------------------CGCCGGAAAAG
TraesCS6B02G298700      -----------------TGGGACGACGAC-----------------------CGTGGGAT
TraesCS6A02G271500      -----------------TGGGACGACGAC-----------------------CGGGGGAT
TraesCS6D02G251700      ------------------GGGACGACGAC-----------------------CGTGGGAT
                                          *     *  *                                

TraesCS7A02G409900      ATGAGC--GGGCGCGAC--CGGCTGCGGCTGTGGGAGGACAAGGCGTGGCGGGCGCACGC
TraesCS7B02G309300      ATGAGC--GGCCGCGAC--AGGCTGCGGCTGTGGGAGGACAAGGCGTGGCGGGCGCACGC
TraesCS7D02G403100      ATGAGC--GGCGGCGAC--CGGCTGCGGCTGTGGGAGGACAAGGCGTGGCGGGCGCACGC
TraesCS1A02G095600      CAGGACAAGGAGGTAGCCATGGCGACGGATGCAGG----------GAAGAAGGCGTATGT
AT3G45870               AAGAAA--ACCGCCAATGGAGAGTACGGT----GGAAAGAGAGGCGTGGAAAGCTCACGT
TraesCS6B02G298700      CGGATC--GGCGGCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAGGCGGGCGCACGC
TraesCS6A02G271500      CGGATC--GGCGGCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAGGCGGGCGCACGC
TraesCS6D02G251700      CGGATC--GGC-GCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAGGCGGGCGCACGC
                          *                 *    ***     **          *  *   **  * * 

TraesCS7A02G409900      GGGCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCCGTGCT
TraesCS7B02G309300      GGCCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCCGTCCT
TraesCS7D02G403100      GGCCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCCGTCCT
TraesCS1A02G095600      TGTTGCCATGGTGATCCAGGTGATCTACACCGGCATGTACGTCGTCTCCAAGGCGGCCTT
AT3G45870               GGCGATGATCGGTGTGCAATTGTTCAACGGAGGATATCATGTCATTACCAAAGTGGCTCT
TraesCS6B02G298700      GGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAGGCGCT
TraesCS6A02G271500      GGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAGGCGCT
TraesCS6D02G251700      GGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAGGCGCT
                         *              **  *   * **   **     * *** *  * **    *   *

TraesCS7A02G409900      CAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCT
TraesCS7B02G309300      GAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCT
TraesCS7D02G403100      CAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCT
TraesCS1A02G095600      CGATGGCGGCATGAACACCTTCGTCTTCATCTTCTACCGCCAGGCAGCCGC-CACTCTCC
AT3G45870               CAACGTTGGTGTAAACCAACTTGTCTTCTGTGTCTTTCGTGATCTCATTGCTCTCTCCAT
TraesCS6B02G298700      CAACGTCGGCGTCAACCGCGTTGTCTTCTGCGTCTACCGCGACCTCCTCGCGCTCTGCGT
TraesCS6A02G271500      CAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGACCTCCTCGCGATCTGCGT
TraesCS6D02G251700      CAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGACCTCCTCGCGCTCTGCGT
                          * *  **  * ***    * ******    ***  **  *       **   *     

TraesCS7A02G409900      CCTCGCC-CCCGCCGCCTACTTCCGAGAGAGGTACGTCGCACTATCATCCCCATGCCCAT
TraesCS7B02G309300      CCTCGCC-CCCGCCGCCTACTTCCGAGAGAGGTACGC------ACCGTACCATCCCCCAT
TraesCS7D02G403100      CCTCGCC-CCCGCCGCCTACTTCCGAGAGAGGTACGTCGTGCTAGGCGCCTCACC-CCAT
TraesCS1A02G095600      TCTTGCTACCCCTCGCCATCCTCCTCGAGAGGTA-ATCAACTGACCATTTACTTACCTAC
AT3G45870               TCTTGCT-CCTCTTGCTTATATCCGTGA--------------------------------
TraesCS6B02G298700      GCTTGCT-CCCATCGCCTTCTTCCGCCA----------------------------CCGC
TraesCS6A02G271500      GCTTGCT-CCCATCGCCTTCTTCCGCCA----------------------------CCGC
TraesCS6D02G251700      GCTTGCT-CCCATCGCCTTCTTCCGCCA----------------------------CCGC
                         ** **  **    **     ***   *                                

TraesCS7A02G409900      GGCTGCTCTGATCTAGAGTTCTAGACCAATTGAC-----ATCGAATTTGACTAGACGCTA
TraesCS7B02G309300      GGCTGCTCTG--------ATCTGGACCAATTGAC-----ATCGAATTTGACTAGATACTA
TraesCS7D02G403100      GGCTGCTCTGCTCT---GATCTGGACGAATTGAC-----ATCGAATTTGACTTGATACTC
TraesCS1A02G095600      TGCTTGATCAAGTCATGATTAGGAAGCTAAAGATCAGTGGCTATATATGCATAGATGCAA
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGCTCGCCCG--------------------------------------------------
TraesCS6A02G271500      GGCTCGCCCG--------------------------------------------------
TraesCS6D02G251700      GGCTCGCCCG--------------------------------------------------
                                                                                    

TraesCS7A02G409900      TTC----------------------------------------------GGGTGCGGATT
TraesCS7B02G309300      TTC----------------------------------------------GGGTGCGGATT
TraesCS7D02G403100      TTC----------------------------------------------GGCTGCGGATT
TraesCS1A02G095600      TCCAACACCTATTAAAATTAGTTGATCCATCTTAACTAATATGAGTGAGGTCCATGACTG
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CTGAATTTCCCGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGC
TraesCS7B02G309300      CTGAATTTC-CGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGC
TraesCS7D02G403100      CTGAATATCCCGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGC
TraesCS1A02G095600      TTAATGATCTTGCAGGAGGAACGCGCCACCCATGTCACTGTGGTTGTTCACCAAGATCTT
AT3G45870               ------------TAAGAGAACAAGACCTCCTTTGAATCGACAGTTTCTCTTAGCTTTCTT
TraesCS6B02G298700      ----------CGCAGGCTCGTCCGCCG-CCCGTCACGCGTCGCCTCCTTACCTCCTTCTT
TraesCS6A02G271500      ----------CGCAGGCTCGTCCGCCG-CCCGTCACGCGTCGCCTCCTTACCTCCTTCTT
TraesCS6D02G251700      ----------CGCAGGCTCGTCCGCCG-CCCGTCACGCGTCGCCTCCTTACCTCCTTCTT
                                     * *         *  **  *    *      *  *        **  

TraesCS7A02G409900      GCTGCTTGGATTCACCGGGTAATTCCCCCACTCCTCCTCCTCCTCCTCA-----TGCTGC
TraesCS7B02G309300      GCTCCTTGGGTTCACCGGGTAAC------------TCTCCTC------------TGCTGC
TraesCS7D02G403100      GCTCCTTGGATTCACCGGGTAAT---------TTTCCCCCTCGTCCTCA-----TGCTGC
TraesCS1A02G095600      CATGTACGCTCTACTCGGGTAAGAACACGGCACCATTGACCTCCCTTTGAATTCATCATC
AT3G45870               CTTCCTTGGTTTAACAGGGTAAT------------TCAAGTTTTCTTCT-----ACCAGT
TraesCS6B02G298700      CTTCCTCGGGCTCACGGGGTAAG----------CCTGGCCACCCGGTCG-----CTCGGT
TraesCS6A02G271500      CTTCCTCGGGCTCACGGGGTAAG----------CCTGGCCACGCGGTCG-----CTCGGT
TraesCS6D02G251700      CTTCCTCGGGCTCACGGGGTAAG----------CCTGGCCTCCCGGTCG-----CTCGGT
                          *    *   *    ******                                  *   

TraesCS7A02G409900      TGCTGCTACTGCTGATGCCCGATG----GAGCAATAAGA-----------------G---
TraesCS7B02G309300      TACTGCTGCTGCTGCTGCCTGATGGGGCGAGCAACAATAACTCTCTTCAGTCTCGTGCTG
TraesCS7D02G403100      TGCTGAT---------GCCTGATG----GAGCAATAAGA-----------------G---
TraesCS1A02G095600      TTCATCATCTATATACGTGTGA------AAGTAACATGTATTGC----------------
AT3G45870               TTCTGTTATCTTCATGATT-----------GCAATCATC--------------ACAG---
TraesCS6B02G298700      GTCAGACACGCTGACCGCTTG-------AAGCAATGCTGCTTATGTACTTGCAAATT---
TraesCS6A02G271500      GTCAGACACGCCGACCGCTTG-------AAGCAATGCTGCTTATGTACTTGCAAATG---
TraesCS6D02G251700      GTCAGACACGCTGACCGCTTG-------AAGCAATGCTGCTTATGTACTTGCAAATT---
                          *                           * **                          

TraesCS7A02G409900      -------------------TCACATTCTGACG--------------GCGTG--CAGGATC
TraesCS7B02G309300      TCTTCCATCGACTAACTCATCACATTCTGGCG--------------GCGTG--CAGGATC
TraesCS7D02G403100      -------------------TCACATTCTGACG--------------GCGTG--CAGGATC
TraesCS1A02G095600      -------------------ACGTACGTT------------------ACGTACGTAGGAAC
AT3G45870               -------------------TGATGTTTTG-----------------GTGTGATTAGGATA
TraesCS6B02G298700      -------------------TCGTGCTCTGATGCGTCTGGTTGTTTGTCCTG--TAGCATC
TraesCS6A02G271500      -------------------TCGTGCTCTGATGCGTCTGGTTGTTTGTCCTG--TAGCATC
TraesCS6D02G251700      -------------------TCGTGCTCTGATGCGTCTGATTGTTTGTCCTG--TAGCATC
                                                   *                     *    ** *  

TraesCS7A02G409900      TTCGGGAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCC
TraesCS7B02G309300      TTCGGTAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCC
TraesCS7D02G403100      TTCGGGAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCC
TraesCS1A02G095600      ACGGTGAGCATGAACCTGCACAACATCAGCCTCAAGTACACCTCGGCGACGGTGGCATCA
AT3G45870               TTTGGTAATCAGCTTTTGTTCCTCATTGGTCTGAATTACACCAATCCAACTTATGCTGCA
TraesCS6B02G298700      TTTGGCAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAATCCGACATACGCCGCC
TraesCS6A02G271500      TTTGGCAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAATCCGACATACGCCGCC
TraesCS6D02G251700      TTTGGCAACCAGCTACTGTTCTTGTTCGGCCTCGGCTACACCAATCCAACCTACGCCGCC
                           *  *    *    *   *    *  * **    * ****    *  *    **  * 

TraesCS7A02G409900      GCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCAATCGTCGGGTGAG--
TraesCS7B02G309300      GCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTGGCCGCAATCGTCGGGTGAG--
TraesCS7D02G403100      GCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCAATCGTCGGGTGAGCA
TraesCS1A02G095600      GCCACGAGCAACTCCATCCCCGTCATCACCTTCCTCTTCGCCGTCCTC------------
AT3G45870               GCCATTCAGCCGTCGATCCCGGTTTTTACTTTCATCTTGGCTCTCATTATGGGGTAAA--
TraesCS6B02G298700      GCCATTCAGCCATCAATTCCCGTCTTCACTTTCATCTTGGCCCTCATCATGGGGTCAG--
TraesCS6A02G271500      GCCATTCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTCGTCATGGGGTCAG--
TraesCS6D02G251700      GCCATTCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTCATCATGGGGTCAG--
                        **           * ** ** **  * ** *** ** * **     *             

TraesCS7A02G409900      ---------CAACCAATCAATCAACGGATGCACATACACGTTTCAGAGTTCTGACATCGC
TraesCS7B02G309300      -----------------CAATCAA-------------------------CCTGAC----C
TraesCS7D02G403100      CTGAGCAATCAACCAATCAATCAACGGATGCACATACACGTTTCAGAGTTCTGACATCGC
TraesCS1A02G095600      ------------------------------------------------------CTCCAC
AT3G45870               -------------GACTCGATCCAGTCTTTCTC----------------TTTTACTTTCT
TraesCS6B02G298700      -------------------------------------------------TCTCACTCAAT
TraesCS6A02G271500      -------------------------------------------------TCTCGCTCAAT
TraesCS6D02G251700      -------------------------------------------------TCTCACTCAAT
                                                                              *     

TraesCS7A02G409900      CTTGGATGCAAAATGCCAAACTGAACCGTAACAAACCCCGAAATGTCCCATTGCCCTGGA
TraesCS7B02G309300      CTTGGATGC-AAATGCCAACCTGAACCGTAACGAACTACGAAATGTC-----------AA
TraesCS7D02G403100      CTTGGATGCAAAATGCCAAACTGAACCGTAACAAACCCCGAAATGTCCCATTGCCGCGGA
TraesCS1A02G095600      CTCGAA------------------GCCAT--CAAGCTCCGCGCCGCTTC-----------
AT3G45870               CTCTGA-------------------CTCTTCCAAACCTAGAACAATCCA-----------
TraesCS6B02G298700      CTTGAA-----------------AAATGTTCAGAGACTCG---CATCTC-----------
TraesCS6A02G271500      CTTGAA-----------------AAATGTTCAGAGACTCG---CATCTC-----------
TraesCS6D02G251700      CTTGAA-----------------AAATATTCAGAGACTCG---CATCTC-----------
                        **   *                      *    *     *                    

TraesCS7A02G409900      TACACTTCTGGATTCTGATCAAATGCTGAACCAAAATGTT-------------------C
TraesCS7B02G309300      TGCATTTCTGGATTCTGACCAGATGCTGAACCGAACCGTAACAGAATTACCAAAATGATC
TraesCS7D02G403100      TACACTTCTGGATTCTGATCAAATGCTGAACCAAAATGTT-------------------C
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ----TTTTCGTGTGTTG-------------------------------------------
TraesCS6B02G298700      ----TCTTTGTTTGCTGGTTTAA---------GCATTTTA-------------------C
TraesCS6A02G271500      ----TCTTTGTTTGTCGGTTTAA---------GCATTTTA-------------------C
TraesCS6D02G251700      ----TCTTTCTTTGCTGGTTTAA---------GCATTTTA-------------------C
                                                                                    

TraesCS7A02G409900      TTATTCCAGTGTCGAAGTGATCAACGTCTTCACCAGAGACGGCCTCTTCAAGGTGGTCGG
TraesCS7B02G309300      TTGTTCCAGCGTCGAAGTGATCAACGTCTTCACCAGAGACGGCGTCTTCAAGGTCGTCGG
TraesCS7D02G403100      TTATTCCAGTGTCGAAGTCATCCACGTCTTCACCAGAGACGGCGTCTTCAAGGTCGTCGG
TraesCS1A02G095600      ---------------------------------------GGGCACGGCGAAGCTCGCCGG
AT3G45870               ---CTGCAGAACAGAGAGACTGAATTTATTCAAGCTAGAAGGTCAAGCTAAGGTAGGAGG
TraesCS6B02G298700      AATTTTCAGGACTGAAACGGCGAGCTTGGTCACACACGAGGGCCGTGCCAAGGTTGGTGG
TraesCS6A02G271500      CATTTTCAGCACTGAAACGGCGAGCTTCGTCACACACGAGGGCCGTGCCAAGGTTGGTGG
TraesCS6D02G251700      CATTTTCAGCACTGAAACGGCGAGCTTGGTCACACACGAGGGCCGTGCCAAGGTTGGTGG
                                                                **       *** * *  **

TraesCS7A02G409900      CACGGCCGTGTGCGTCTTCGGCGCCGTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGAT
TraesCS7B02G309300      CACGGCCGTGTGCGTCTTCGGCGCCGTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGAT
TraesCS7D02G403100      CACGGCCGTGTGCGTCTTCGGCGCCCTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGAT
TraesCS1A02G095600      CGTCGCGCTCTGCGTGGCCGGCATCCTCGTCATCGCCCTCTACGCCGGGCCGCC---GCT
AT3G45870               CACACTGATTTGTGTCGCTGGGGCGGTGCTGATGGTTTTGTTTCGTGGACTGGCTTTGTT
TraesCS6B02G298700      CACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTT
TraesCS6A02G271500      CACCATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTT
TraesCS6D02G251700      CACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTT
                        *       * ** **    **     *  * ** *   * *     **     *   * *

TraesCS7A02G409900      CGGC---------------CTTGGAGGCGCCAATGCGCTGGACGGCGCCGACGCGTCGTG
TraesCS7B02G309300      CGGC---------------CTCGGAGATGCCAATGCGCTGTCTGGCGCCGGCGCGTCATG
TraesCS7D02G403100      CGGC---------------CTCGGAGGCGCCAATGCGCTGGCCGGCGCCGACGCGTCATG
TraesCS1A02G095600      CAGCCCC------------CTCAACCACCACCGCGCCTTC-----CACGCGCACGCCG--
AT3G45870               TGGGGAAACAGAGGCTGAGTCCTTGGGTCATGGTGAATCAAGACACACTGAAACATCT--
TraesCS6B02G298700      TGGTAGCAGCGATCTAGATCTTGATGTTCCTCGTAATGTCGTCATCACTGAGATGTTG--
TraesCS6A02G271500      TGGTAGCAGCGAGTTAGATCTTGATGTTCAGAGCAATGTCGTCATCACCGAGATGTTG--
TraesCS6D02G251700      TGGTAGCAGCGAGCTAGATCTTGATGTTCATAGCAATGTCGTCATCACCGAGATGTTG--
                          *                                          * *            

TraesCS7A02G409900      GAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAGCCACGCTCCAGTTCAGT-----
TraesCS7B02G309300      GAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAACCACGCTCCAGTTCAAT-----
TraesCS7D02G403100      GAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAGCCGTGCTCCAGTTCAGT-----
TraesCS1A02G095600      ----------------------CCGCCACGGCCGCCGGGAA--------------GCAGG
AT3G45870               ----------------------GGACACTTCATGTCTGGCTTTTTT------------AA
TraesCS6B02G298700      ----------------------CAAC--CTGA-GCCAGGATCATCTTGGTTCATTGCATA
TraesCS6A02G271500      ----------------------CAAC--CTGA-GCCAGGATCATCTTGGTTCATTGCATA
TraesCS6D02G251700      ----------------------CAAC--CTGA-GCCAGGATCATCTTGGTTCATTGCATA
                                                         * *                        

TraesCS7A02G409900      ----TTTGGAACCTGGAACCTTGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGG
TraesCS7B02G309300      ----TTTGGAACCTGGAACCTCGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGG
TraesCS7D02G403100      ----TTTGGAACCTGGAACCTTGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGG
TraesCS1A02G095600      GGGAGTGGATGAAAGGCACGT-----TCCTGATGCTCCTGGCCAAC--------------
AT3G45870               TGGACTTGGGCGATGGAATTTGGGAGTTTTGTGTTTGATTGGGAATTGCACTTGCATGGC
TraesCS6B02G298700      TGGGCTGGAAAAGTGGCATATCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGC
TraesCS6A02G271500      TGGGCTGGAAAAGTGGCATATCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGC
TraesCS6D02G251700      TGGGCTGGAAAAGTGGCATATCGGAGTGTTATGTTTAATAGGGAACTGCCTCTGTATGGC
                             * *      ** *  *     *  *     *  * *  **               

TraesCS7A02G409900      GGCTTATCTTGTCATACAGGTAATG-----------------------------------
TraesCS7B02G309300      AGCTTATCTTGTCATACAGGTGATG-----------------------------------
TraesCS7D02G403100      GGCTTATCTTGTCATACAGGTAATG-----------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               TGCTTTTCTTGCTATTCAGGCA-------------------------------TGTCATT
TraesCS6B02G298700      AACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGCCGCGCTCTATTCCATT
TraesCS6A02G271500      AACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTATTGTCGCACTCTATTCCGTT
TraesCS6D02G251700      AACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGTCGCTCTCTATTCCGTT
                                                                                    

TraesCS7A02G409900      ---------------------------------CAGATTGGG------------------
TraesCS7B02G309300      ---------------------------------CAGATTGGG--TTGTTTTCAGC-----
TraesCS7D02G403100      ---------------------------------CGGAATGGGATTTGTTTTTAGC-----
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               TTCTTCTAGATG--------ATCCACACACTTTCAGTTTCAG------------------
TraesCS6B02G298700      TGCATTTTGATGTTTGTCAACTCGGAACACCTTGAGCTTTAGTTTTCTATCAGGCATATA
TraesCS6A02G271500      TGCATTT-GATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATA
TraesCS6D02G251700      TGCATTTTGATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGCATGGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTGTA
TraesCS6A02G271500      TGCATGGCACAAGTACTGAAAGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTATA
TraesCS6D02G251700      TGCATGGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTACATCAGTAAATCTTATA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGGCAACTTCAGATCACATCAACTCTATTTAGAACACTCTATTTTGATGAATATTTCAGT
TraesCS6A02G271500      GGGCAACTTCAGATCACAGCAACTCTATTTAGTACACTCTGTTTTGATGAATATTTCAGT
TraesCS6D02G251700      GGGCAACTTCAGATCACATCAACTCTATTTAGAGCACTCTATTTTGATGAATATTTCAGT
                                                                                    

TraesCS7A02G409900      ---------------TTGTTTGCTCTT--------------AATGAGAAC----TATATC
TraesCS7B02G309300      -----TTCATGATAGTTTTTTGCTCTT--------------AATGAGAAT----TACATC
TraesCS7D02G403100      -----TTCATGATAGTTTTTTGCTCTT--------------AATGAGAATTACATATATC
TraesCS1A02G095600      --------------GTGACGTGGTCCC---------------------------------
AT3G45870               -----------ATATCTTCTTGTCTTT-------------------GGAC----TGACCT
TraesCS6B02G298700      CCCAATTCCTAATGGTTTCTCTGCCTTCTTGACATTCTTAAAGTGAGAAG----GATATT
TraesCS6A02G271500      CCCAATTCCTAACAGTTTCTCTGCCTTCTTGCCATTCTTGAAGTGAGAAG----GATACT
TraesCS6D02G251700      CCCAATTCCTAACGGTTTCTCTGCCTTCTTGACATTCTTGAAGTGAGAAG----GATATT
                                                                                    

TraesCS7A02G409900      TGAATTTGTGTC--CTTTTC-------------------------TGCCGTG------AC
TraesCS7B02G309300      TGAATTTGTGTC--CTTTTC-------------------------TGCTGTG------AC
TraesCS7D02G403100      TGAATTTGTGTC--CTTTTC-------------------------TGCTGTG------AC
TraesCS1A02G095600      ----TCTGGATCGTCCT-------------------------------------------
AT3G45870               TGCATTTGAAACATATATGA----------------------------------------
TraesCS6B02G298700      AAAACTTAGGCCGGGTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAAC
TraesCS6A02G271500      AAAATTTAGGCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAAC
TraesCS6D02G251700      AAAACTTAGGCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGACCAAC
                              *    *                                                

TraesCS7A02G409900      TG----------------------------------------------------------
TraesCS7B02G309300      TG----------------------------------------------------------
TraesCS7D02G403100      TG----------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGGCCATTGCTTAATACTGAACATGGTATGTTATTTGGTGAATTGTCACAAGAAGATTTG
TraesCS6A02G271500      TGGCCTTTGCTTAATATTGAACATGGTATGTTTTTTGGTGAATTGTCACAAGAAGATTTG
TraesCS6D02G251700      TGGCCTTTGCTTATTATTGAACATGGTATGTTGTTTGGTGAATTCTCACAAGAAGATTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCATGGGCCGAGCAAATCATACTTCATTTTAAGAACCAATATCACTATACTAACAGAAGG
TraesCS6A02G271500      TCATGGGCCGAGGAAATCATACTTCATTTTAAGAACCAATATCACTATACTAATAGAAGG
TraesCS6D02G251700      TCATGGGCCGAGGAAATCAAACTTCATTCTAAGAACCAATATCACTATACTAATAGAAGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGATCACCCTTTTAACATTGTTGAAGATATGTTTATGTATTAGACTTACTCTAGTATCTT
TraesCS6A02G271500      AAATCACCCTTTTAACATTGTTGAAAATATGTTTATGTATTAGACTTACTTTGGTATCTT
TraesCS6D02G251700      AGATCACCCTTTTAACGTTGTTGAAAATATGTTTATGTATTAGACTTACTTTAGTATCTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCTATTCAAGGTTGAAACTTATGCTACAAGATCTATGTGCTCTGATTTGTATTGCAGAAA
TraesCS6A02G271500      GCTATTCAAGGTTGAAACTTATGCTACAAGATCTATGTGCTCTGATTTGTATTGCAGAAA
TraesCS6D02G251700      GCT---------------------CACAAGATCTATGTGCTCTGATTTGTATTGCAGAAA
                                                                                    

TraesCS7A02G409900      -----------------------------------------ATTCCAGGCCCCGGTGTTA
TraesCS7B02G309300      -----------------------------------------TTTCCAGGCCCCGGTGTTA
TraesCS7D02G403100      -----------------------------------------ATTCCAGGCCCCGGTGTTA
TraesCS1A02G095600      --------------------------------------------CCAGGCGCGCCTCCTC
AT3G45870               --------------------------------------------TCAGGCTCCGGTCTTA
TraesCS6B02G298700      GTTTTCTTGTTATTTTATACTTATTATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTG
TraesCS6A02G271500      GTTTTCTTGTTATTTTATAC-TACTATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTG
TraesCS6D02G251700      GTTTTCTTGTTATTTTATACTTATTATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTG
                                                                     ***** *   *  * 

TraesCS7A02G409900      GTAAAATATCCCGCGAGCTTATCCTTGACAGCCTATTCTTATTCATTTGCCACCAT---C
TraesCS7B02G309300      GTAAAATATCCTGCGAGCTTATCCTTGACAGCCTATTCTTACTCATTTGCCACCAT---A
TraesCS7D02G403100      GTAAAATATCCTGCGAGCTTATCCTTGACAGCCTACTCTTACTCATTTGCCACCAT---C
TraesCS1A02G095600      AAGGAGTACCCCAACAAGCTGCTGGCCACGGCGCTGCAGTGCCTGCTAAGCACGGTGCAG
AT3G45870               AAGAAGTATCCGGCGAATCTTTCAGTCACAGCATACTCGTATTTCTTTGGGACCAT---G
TraesCS6B02G298700      GTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCATACTTTTTTGGAGCTCT---T
TraesCS6A02G271500      GTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCATACTTTTTTGGAGCTCT---T
TraesCS6D02G251700      GTGAAGTACCCTTGCAGTTTATCATTGACAGCTTACTCATACTTTTTTGGAGCTCT---T
                            * ** **    *   *       ** **       *      *     *  *    

TraesCS7A02G409900      TTCATGGTGTTGACTGGGGTATTT---GCAACCAACGGGCTCCATGAGTGGGCGCTGACA
TraesCS7B02G309300      TTCATGGTGTTGACTGGGGTATTT---GCAACCAACGGGCTCCATGAGTGGGCACTGACA
TraesCS7D02G403100      TTCATGGTGTTGACTGGGGTTTTT---GCAACCAACGGGCTCCATGAGTGGGCGCTGACA
TraesCS1A02G095600      TCGCTCGCGCTGGCCGCGGCC------GTGACCGCTGGCGGCGGGGAGGACATGTCGGCT
AT3G45870               TTTATGGTGACATCT---GCTTTTTTCATGACTAATGAGTCGACGAACTGGAGTCTCACA
TraesCS6B02G298700      TTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAA---AGAAGATTGGACTTTGACT
TraesCS6A02G271500      TTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAA---AGAAGATTGGACTTTGACT
TraesCS6D02G251700      TTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAA---AGAAGATTGGACTTTGACT
                        *   *        *    *           **              *           * 

TraesCS7A02G409900      GGGACCGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAATAAT-AT-------CCA
TraesCS7B02G309300      GGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAATAATAAT-------CTA
TraesCS7D02G403100      GGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAACAATAAT-------CTA
TraesCS1A02G095600      GCGT-GGACGCTGCGGCTG--------GACGTGGGTCTCGTCGCAGT-------------
AT3G45870               AGATCCGAGTTCTTTGCAGTTGTCTACGCAGTATGTTCTTCACACA-----------CCA
TraesCS6B02G298700      GCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAG-ATTGTGTTAGATTTATCTTTCCCA
TraesCS6A02G271500      GCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTTTGTGTTAGTTTTATTTTTCCCA
TraesCS6D02G251700      GCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTTTGTGTCAGATTTATCTTTCCCA
                              **       ** *        *  **  *                         

TraesCS7A02G409900      TGGCTGCTGCCTG----------------TGGATG-------------------------
TraesCS7B02G309300      TGGCCGCCCTTTAGGATTACAATAGAACTTGTATG-------------------------
TraesCS7D02G403100      TGGCCGCCCTTTATGATTACATTAGAACTTGTATG-------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               TATGTTTGTTGATCCATTAAATTTCTCCA-------------------------------
TraesCS6B02G298700      TGCATGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGTGGTGATAATTGTT
TraesCS6A02G271500      TGCGTGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGCGAAGATAATTGTT
TraesCS6D02G251700      TGCACGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGCGGATATAATTGTT
                                                                                    

TraesCS7A02G409900      ------------ACCATGCTAAGATGT--------------GCTTGTTCTAACCACATTT
TraesCS7B02G309300      ------------ACCATGCTACGATGTGCTAACCTCTCCGAGCTTGTTCTAACCACATTT
TraesCS7D02G403100      ------------ACCATGCTATGATGTGCTAACCTCTCCGAGCTTGTTCTAACCACATTT
TraesCS1A02G095600      ----------------CGCC-----------------------------------TACTC
AT3G45870               ------------ATTGAGTAACTCTGT----------------------------TGCTT
TraesCS6B02G298700      GCAAACTTGC--AATAAGCTAGTTTGTGTA-----------GGGTATAGAAG---TAGTT
TraesCS6A02G271500      GCAAACTTGCAAAATACGCTAGTTTGTGTA-----------GGCTATAGAAGAAATAGTT
TraesCS6D02G251700      GCAAACTTGCAAAATACGCTAGTTTGTGTA-----------GGCTATAGAAGAAATAGTT
                                         *                                        * 

TraesCS7A02G409900      CTTGCTTGC-GCCA-----------------------------------------ACAGG
TraesCS7B02G309300      CTTGCTTGCAACCA-----------------------------------------ACAGG
TraesCS7D02G403100      CTTGCTTGC-ACCA-----------------------------------------ACAGG
TraesCS1A02G095600      CGGGTTCGTGGTCA-----------------------------------------CGGGG
AT3G45870               CCTCTATGC------------------------------------------------AGG
TraesCS6B02G298700      GACGCATGCCACCATAAATATACT-ATACTGAAATTCCCCTATTTCCCCCCTATTTCAGG
TraesCS6A02G271500      GACGCATGCCACCATAAATATTCT-ATACTGAAATTCTCCTATTTCCCCCCTATTTCAGG
TraesCS6D02G251700      GACGCATGCCACCATAAATATTCTAATACTGAAATTCTCCTATTTCCCCCCTATTTCAGG
                               *                                                  **

TraesCS7A02G409900      GAGTTGTTGCATCTTGTCTCAACTACGCAATCATGACTTGGGCGAACAAAATTCTTGGAC
TraesCS7B02G309300      GAGTTGTTGCGTCTTGTCTCAACTACGCAATCATGACTTGGGCGAATAAAATTCTCGGAC
TraesCS7D02G403100      GAGTTGTTGCGTCTTGTCTCAACTACGCAATCATGACTTGGGCGAACAAAATTCTTGGAC
TraesCS1A02G095600      GTGTCCTTCTACCTGC-----------------AGGCGTGGTGCATCGAGAGGCGGGGCC
AT3G45870               GAGTAATCGCGTCTGCTCTCAACTATGGTCTCTTGACATGGTCAAATAAGATCTTGGGTC
TraesCS6B02G298700      GAGTTGTTTCATCTGCTCTTAATACTGGTTTATTGACATGGTCCAACAAAATTCTGGGCC
TraesCS6A02G271500      GAGTTGTTTCATCTGCTCTTAATACTGGTTTATTGACATGGTCCAACAAAATTCTGGGCC
TraesCS6D02G251700      GAGTTGTTTCATCTGCTCTTAATACTGGTTTACTGACATGGTCCAACAAAATTCTGGGCC
                        * **  *     **                    * * ***   *   * *     ** *

TraesCS7A02G409900      CATCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTC
TraesCS7B02G309300      CTTCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTC
TraesCS7D02G403100      CATCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTA
TraesCS1A02G095600      CCGTGTTCCTGGCCATGTCTAATCCGGTGGGGCTCGTGCTCACCGTGTTCTGCTCCTCCT
AT3G45870               CTTCCTTGGTTGCTCTCTATAATCCTCTTCAACCCGCAGCCTCAGCTTTCTTGTCCAGAA
TraesCS6B02G298700      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGC
TraesCS6A02G271500      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGC
TraesCS6D02G251700      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGC
                        *     *  * **  * *  *  **  *    *  *    * *     **   **     

TraesCS7A02G409900      TTTTTCTTGGTACCCCAATCTATCTAGGAAGGTATG-----GACCAACCAACACTCTACC
TraesCS7B02G309300      TTTTTCTTGGTACCCCAATCTATCTAGGAAGGTATG-----GACCAACCAACACTCTACC
TraesCS7D02G403100      TTTTTCTTGGTACCCCAATCTATCTAGGAAGGTATG-----GACCAACCAACACTCTACC
TraesCS1A02G095600      TCTTCCTCGGC-----------------GAGGT---------------------------
AT3G45870               TCTTCCTTGGAAGCCCTATCTACTTGGGGAGGTTTA--------------ATATCTCTCT
TraesCS6B02G298700      TCTTTCTGGGCAGTCCAATTTATTTCGGAAGGTAAGAGTATGTTTATCATATGTTCTACT
TraesCS6A02G271500      TCTTTCTGGGCAGTCCAATTTATTTCGGAAGGTAAGAGTATGTTTATCATATGTTCTATT
TraesCS6D02G251700      TCTTTCTGGGCAGTCCAATTTATTTCGGAAGGTAAGAGTATGTTTATCATATGTTCTACT
                        * ** ** **                   ****                           

TraesCS7A02G409900      CT-----------ATCTGCTATTTTAACACTGTGACATCATGAGTTGTT-AGTTTCCGGT
TraesCS7B02G309300      CT-----------ATGTGTTATTTGAACATTGTCACATCATGAGTCGTCAAGTTTCGGGT
TraesCS7D02G403100      CT--ATGTGTTATTTGAATTATTTGAACATTGTCACATCATGAGTTGTCAAGTTTCGGGT
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               CC--------------TTTTCTCTTAGCTATTCTCAGCCATCAA----------------
TraesCS6B02G298700      CTTTAGAGTTAACCTTTTCCATTTTATCCTTTCTTTGAAGTGAAAAATACTTTTCCAGAC
TraesCS6A02G271500      CTTTAGAGTTAACATTTTCTATTT-ATCCTTTCTTTTAAGTGAAAAATACTTTTCCAGAC
TraesCS6D02G251700      CTTTAGAGTTAACCTTTTCTATTT-ATCCTTTCTTTGAAGTGAAAAATACTTTTCCAGAC
                                                                                    

TraesCS7A02G409900      CATTCGAATTGGTCATTTCGCATTGTGTTTATCAGTTGAGCTTGG---------------
TraesCS7B02G309300      AATTCGAATTGGTTATTTTGCATTGTGTTTATCGGTTGAGCTTGG---------------
TraesCS7D02G403100      CATTCGAATTGGTCATTTTGCATTGTGTTTATCGGTTGAGCTTGG---------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               --------------------CGGGATGTGTCTGAAGT-----------------------
TraesCS6B02G298700      CTCTT---CTACTTACTTGTTAATTTGTGTATGTAGT-ATGTAGGATATGCACATTGATG
TraesCS6A02G271500      CTCTT-------CTACTTGTTAATATGTGTATGTAGTAATGTAGGATATGCACATTGATG
TraesCS6D02G251700      CTCTT---CTACTTACTTGTTAATATGTGTATGTAGTAATGTAGGATATGCACATTGATG
                                                                                    

TraesCS7A02G409900      ---TACTCTTTCAA---------TACCACCGTAATGGTGATGGTGCTTGG----AGCTGA
TraesCS7B02G309300      ---TGCTCTTTCAAGCAAAATGGTATGAC-ATAATGGCAATGGTGCTTGGCGTAAACTGG
TraesCS7D02G403100      ---TGCTCTTTCAAGCAAAATGATATGAT-ATAATGGCAATGGTGCTTGGCGTAAACTGG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               --------TTCCTAACTAACTAG-------------------------------------
TraesCS6B02G298700      TCTTGTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCAATAGTCTAAGTTTC
TraesCS6A02G271500      TCTTGTTCTATTTGACCATCTGATAAAGTGATAATCTGAAAGGTCGATAGTCCAAGTTTC
TraesCS6D02G251700      TCCTGTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCGATAGTCCAAGTTTC
                                                                                    

TraesCS7A02G409900      TGTTGTTTTCCATGGATGCCGTTACTGAAATTTGAT-GTTTCTTTATTA-----------
TraesCS7B02G309300      TGTTGTTTTCCATGGATACCGTTACTGAAATTTGACTTTTTTTTTATTA-----------
TraesCS7D02G403100      TGGTGTTTTCCATGTATACCATTACTGAAATTTGAC-TTTTCTTGGTTA-----------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               -------------------------------------GCTTTTTTCTCC-----------
TraesCS6B02G298700      TAACATAT------------GGTAATAAAG-------TAATTCTTTTTGTAGCAATAAAT
TraesCS6A02G271500      TAACATTG------------ATTATTAAAGTTCAGT-TTTTTTTCTTCATAGCAATAAAT
TraesCS6D02G251700      TAACATTG------------ATTAATAAAGTACAGTTTTTTTTTCTTCATAGCAATAAAT
                                                                                    

TraesCS7A02G409900      GTTTGCCT---------GCTATAGAATTCCCACGAATTTATGCAGAACTAAATGCCCACC
TraesCS7B02G309300      GTTTGCCTCACTTATGGGCTATAGAATTCCCACGAATTTATGCAGAACTAAATACCCACC
TraesCS7D02G403100      GTTTGCCTCACTTATAGGCTACAGAATTCCCACGAATTTATGCAGAACTAAATACCCACC
TraesCS1A02G095600      ----------------------------------------------------CGTCCACC
AT3G45870               ----------------------------------------------------TCCTCTCT
TraesCS6B02G298700      GTTTACC-----------------ATCTCTTTTGATCTGAAGT--AATC---TGCTCTGT
TraesCS6A02G271500      GTTTATC-----------------ATCTCCTTTGATCTGAGGTATAATC---TGCTCTGT
TraesCS6D02G251700      GTTTATC-----------------ATCTCTTTTGATCTGAGGTATAATC---TGCTATGT
                                                                                    

TraesCS7A02G409900      T-------TACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTT
TraesCS7B02G309300      TTGTGAACTACTTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTT
TraesCS7D02G403100      TTGTGCACTACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTT
TraesCS1A02G095600      T----------CGGCAGCGTCCTCGGTGGGGCGCTCCTGGTCGCCGGGCTGTACAGCGTG
AT3G45870               T--------------AGCATTTTAGGCGGATGTGCAATCATAGCAGGTCTTTATAGTGTC
TraesCS6B02G298700      T-------TGCTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTC
TraesCS6A02G271500      T-------TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTC
TraesCS6D02G251700      T-------TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTC
                        *              **  *  * ** **        *  *  * **  * **    ** 

TraesCS7A02G409900      ACTTGGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATC--TGAATCCTC
TraesCS7B02G309300      ACTTGGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATC--TGAATCCTC
TraesCS7D02G403100      ACTTGGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATC--TGAATCCTC
TraesCS1A02G095600      CTCTGGGG----------GAAGAGCAAGGAGCAGC----------------CGGCGCCGC
AT3G45870               ACCTGGGC-------------------------------------------------ATC
TraesCS6B02G298700      ACCTGGGC----------ACGACATCGAGAAAAGT------TGACTGCCACTGGAGTACC
TraesCS6A02G271500      ACCTGGGC----------GCGACGTAGAGAAAACT------TGACTGCCACTGGAGTACC
TraesCS6D02G251700      ACCTGGGC----------GCGACGTAGAGAAAAGT------TGACTGCCACTGGAGTACC
                           ****                                                    *

TraesCS7A02G409900      TTCTGGTGGAGGTG--------------GAGGATGCGCCAGCT---CCCAAGAGACAGGA
TraesCS7B02G309300      TTCTTGTGGAGGTG--------------GAGGATGCGCCAGCT---CCCAAGAGACAGGA
TraesCS7D02G403100      TTCTTGTGGAGGTG--------------GAGGATGCGCCAGCT---CCCAAGAGACAGGA
TraesCS1A02G095600      CCCCGCTTAGTGCA--------------GCTCCTGCATCAGCAACCACCATGAAACAAGG
AT3G45870               TTAC----------------------------------------------AAAGAAAAGA
TraesCS6B02G298700      TTATGTAAAATGCGCATCGGAGCCATGTGACAGTGCTTCTCAA---GTCATAAAGGGCGG
TraesCS6A02G271500      TTATGTAAAATGCGCATTGGAGCCATGCGACGGTGCTTCTCAA---GTCATAAAGGGCGG
TraesCS6D02G251700      TTATGTAAAATGCGCATTGGAGCCATGCGACGGTGCTTCTCAA---GTCATAAAGGGCGG
                                                                            *     * 

TraesCS7A02G409900      AAATTCCAGCTCAATTGATCCCTAAGACTCGGAGG-AGAGATGACTCTGTTATTTTTCC-
TraesCS7B02G309300      AAATTCCAGCTCAATCGATCCCTGAGACTC-GACG-AGAGTCCACTGTGTTTTTTTTTTT
TraesCS7D02G403100      AAATTCCAGCTCAATTGATCCCTGATACTCAGACGAAGACTCCACTGTGTTTTTTTTCC-
TraesCS1A02G095600      ATGCGATGGTAGCAATGCTCGCACCGGCGC------------------------------
AT3G45870               AAGCGGCAGCAGCAATGG---CTGTGATCC------------------------------
TraesCS6B02G298700      TAACTTGAGCCCCA--GGCCCTTTATATCC-----------------------CTTTCC-
TraesCS6A02G271500      TAACCTCAGCCCCA--GGCCCTTTATATCC-----------------------CTTTCT-
TraesCS6D02G251700      TAACCTCAGCCCCA--GGCCCTTTATATCC-----------------------CTTTCT-
                                *    *  *            *                              

TraesCS7A02G409900      ------AGAACAGCAGCAGCAGAATTACGTTGTATATTAGTATCAGAAAGCTTGTATTTA
TraesCS7B02G309300      TTCATAACAGCAGCATCAGCAGAATTACGTTGTATATTAGTATCAGAAAGCTTGTAGTTA
TraesCS7D02G403100      ------AGAACAGCAGCAGCAGAATTACGTTGTATATTAGTATCAGAAAGCTTGTAGTTA
TraesCS1A02G095600      ----------------------------------CATGAACA--AGGAAGATGA------
AT3G45870               ------CGA----------------------TCACCTCAA----AGGAAGCTGA------
TraesCS6B02G298700      ------AGG-------CTGTGGAAT---GTGCCACATGAATCTTGAGAAGCTGGTGTTTT
TraesCS6A02G271500      ------AGG-------CTTTGGAAT---GTGCCACATGAATCTTGAGAAGTTGG---TCT
TraesCS6D02G251700      ------AGG-------CTGTGGAAT---GTTCCACATGAATCTTGAGAAGTTGGTGATCT
                                                            * *        *** *        

TraesCS7A02G409900      CCTTCTCTACCATTGGATTAAGTTACAT--------CTCATACCCAAATACCCTCAACAT
TraesCS7B02G309300      CCTTCTCTACCATTGGATTAGGTTACATCATTAAGGCTCATACCCAAATACCCTCAACAT
TraesCS7D02G403100      CCTTCTCTACCATTGGATTAAGTTGCATCATTAAGGCTCATACCCAAATACCCTCGACAT
TraesCS1A02G095600      ---------CGACGAGGTGAAAC-------------CGGAGGAGGAGAGGA----GAACC
AT3G45870               --------------------------ACCC------TTGATCTACAAGGACCATAAAAAC
TraesCS6B02G298700      ATGCAACTTATGCTAGGTATCTCACTATCTCCT---TTGATGAGTAAA-------AATAC
TraesCS6A02G271500      ACGCAACTTCTGCTAGG--------CATCTGCT---TTGATGAGGAAA-------AATAC
TraesCS6D02G251700      ATGCAACTTCTGTTAGG--------TATCTCCT---TTGATGAGTAAA-------AATAC
                                                               *     *          *   

TraesCS7A02G409900      AAGCTGGAATGG-----------AAATGGGTCGCAATTATCGTTCTCCTAGCAGCCGCAG
TraesCS7B02G309300      AAGCTGGAATCG-----------AAATGTGTCGCAATTATCGTTTTCCT-----------
TraesCS7D02G403100      AAGCTGGAATGG-----------AAATGTGTCGCAATTATCGTTCTCCTAGCAGCCGCGG
TraesCS1A02G095600      AAGCTGGATTC------------ACAGGTGTAGCTG----------------------GG
AT3G45870               AAAC--CAATAG------------------------------------------------
TraesCS6B02G298700      ATAATGCATTAGATGTTGGGAAGAGAAGTGCTGCAG----------------------AG
TraesCS6A02G271500      AGAATGCATTAGATGTTAGGAAGAGAAGTGCTGCAG----------------------AG
TraesCS6D02G251700      AGAATGCATTGGATGTTAGGAAGAGAAGTGCTGCAG----------------------AG
                        *      * *                                                  

TraesCS7A02G409900      AAGAT-------------GCTAACGA----------TGTGCGATGATAGTTCAGTTTCA-
TraesCS7B02G309300      -AGATGCTATTGGCACTGGCTAACGA----------TGTGCGATGATAGTTCAGTTTCA-
TraesCS7D02G403100      AAGATGCTACTGGCACTGGCTAACAA----------TGTGCAATGATAGTTCAGTTTCA-
TraesCS1A02G095600      AAATACGTACTACAGAGTTACAGCAGCCATGCATCCTGCAGGCAGGCAGGTCGGCCACG-
AT3G45870               ------------------GACATCTA-----------------------------TTCAC
TraesCS6B02G298700      AAGATTGTACTGACGATTGGTAATGA----------TGTTGGCATCTGTGTCGGCTGCAG
TraesCS6A02G271500      AAGATTGCACTGAAGATTGTTAACGA----------TGTTGGCATCTGTGTCCTCTGCAG
TraesCS6D02G251700      AAGATTGCTCTGAAGATTGTTAATGA----------TATTGGC-----------------
                                             *                                      

TraesCS7A02G409900      ACAGTTGTCTTCATGGGTCA-----AGGAACAGCTTCAGTGATCAAAGGTAATTACTTCA
TraesCS7B02G309300      GCAGTTGTCTTCATGGGTCA-----AGGAACAGCTTCAGTGATCAAAGGTAATTACTTCA
TraesCS7D02G403100      GCAGTTGTCTTCACGGGTCA-----AGGAACAGCTTCAGTGATCAAAGGTAATTACTTCA
TraesCS1A02G095600      -------------------------AGGAGCTGTTTCGT---CTGACAGAGACTCTTGAA
AT3G45870               AAAATC----TCCCATCTCTTCACCAAAA-----TCCGATGATTGAACAAAA--------
TraesCS6B02G298700      AAAATCATACTCTCAGACCTTCCATAGGAGCAGTTAGGTTAATTTAGGCAAA-------A
TraesCS6A02G271500      AAAATCATACTCTCATACCTTCCATAGGAGCTGTTAGGTTAATTTAGACAAA-------A
TraesCS6D02G251700      ATCATCATAATCTCATACCTTCCATAGGAGCAGTTAGGTTAATTTAGACAAA-------A
                                                 *  *     *          *     *        

TraesCS7A02G409900      TCGAACCCAACTTGTTAATAGTTCATTAGTTATCATCGTAATTGCTTAATTGGCA-----
TraesCS7B02G309300      TCGAACCCAACTTGTTAATAGTTCGTTAGCTATCATTGTAATTGCTTAATTGGCA-----
TraesCS7D02G403100      TCCAACCCAACTTGTTAATAGTTCATTAGTTATCATCGTAATTGCTTAATTGGCA-----
TraesCS1A02G095600      TGTAATGCA------TAATACAGCACTAG---------GAAATGCACGAGTAGTA-----
AT3G45870               --------------ACTCTGGCTTCTTGA-------------------ATTA--------
TraesCS6B02G298700      GAGAAGCCATGCTCATTCTGCTTTTTCAG-------------------ACTAACA--ACA
TraesCS6A02G271500      GAGAAGCCATGTTCATGCTGTTTTTCTAG-------------------GCTAACAACACA
TraesCS6D02G251700      GAGAAGCCATGTTCATCCTGTTTTTCTAG-------------------ACTAACA--ACA
                                          *                               *         

TraesCS7A02G409900      -TATGGCTGCCA---TGATTGCTGGT-GTTAACT---TGCATTTTATCTTCTGCTTCAGC
TraesCS7B02G309300      -TATGGTTGCCA---TGATTGCTGTT-GTTAACT---TGCATTTTATCTTTTGCGTCAGC
TraesCS7D02G403100      -TATGGCTGCCA---TGATTGCTGCT-GTTAACT---TGCATTTCATCTTCTGCTTCAGC
TraesCS1A02G095600      ------CTAGAAACTTTATGAACCATCGTCATCCAAGGGC--------------------
AT3G45870               -CTTGGGTGCTCCGATGTTTTCT------TAACCTTTTG---------------------
TraesCS6B02G298700      TTGAGGATGCTGAGTTGATGATT--C-TATTACCAAATGCAAGGTAGCACC---------
TraesCS6A02G271500      CTGAGGATGCTGAATTGATTATT--C-TATAACCAAATGCAAGGTAGCTCC---------
TraesCS6D02G251700      TTGAGGATGCTGAATTGATGATTCTTCTGTAATCAAATGCAAGGTAGCTCC---------
                               *       *  *                   *                     

TraesCS7A02G409900      AGCCTCTATTACTGTCTGGGATCTGACTC--TGCAATACA----GTACAA-ACAAACTGT
TraesCS7B02G309300      AGCTTCCGTTACTGCCAGGGCACCGACTC--TGCAATACA----GTATAAGACAAACTGT
TraesCS7D02G403100      AGCCTCTATTACTGCCTGGGAACCGACGC--TGCAATACA----GTATAAGCCAAACTGT
TraesCS1A02G095600      -------------------------------TGAAACGCAAGTGGCAGAGGATAAT----
AT3G45870               ----------------------CCGAC---------------------------------
TraesCS6B02G298700      ---------------------ACCGACTTTGTGAAATACA----ATAGTATGTATA----
TraesCS6A02G271500      ---------------------ACCGACTTCGTGAAATCCA----GTAGTATGTATA----
TraesCS6D02G251700      ---------------------ACCGATTTCGTGAAATCCA----ATAGCATGTA------
                                                                                    

TraesCS7A02G409900      TCTTCGTTG----------ATTTTCGTAATGCCATACTTGCGAAGCAATTATGT-----C
TraesCS7B02G309300      TCTTCTGTGATGATTTCCAATTTTCATCGTGCCATACTTGCAAAGCAATTATGT-----C
TraesCS7D02G403100      TCTTCTGTTATGATTTCCAATTTCCGTCATGCCATACTTGCGAAGCAATTATGT-----C
TraesCS1A02G095600      --------------------------TGCTGGTATGTAACGGGAGCGGCTATTT-----C
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      --TCCCGTG----------AAATCCCTACATACATACATATGTATAAACTCTGTAGCCAG
TraesCS6A02G271500      --TCCCGTG----------AAATCCCTACATACATACATATGTATGAACTCTGTAGCCAT
TraesCS6D02G251700      --------------------------------CATACATATGTATGAACTCTGTAGCCAT
                                                                                    

TraesCS7A02G409900      TG--GAGCTCAGTGCATAAGTGGGAAAAATCAAAGTAGGAGTTCCAAATTCTTTGGCACA
TraesCS7B02G309300      TG---------------GAGCTGGAAAAATCAAAGTAGGAGCTCCAAATTCTTTGGCACA
TraesCS7D02G403100      TG--GAGCTCAGTGCATAAGTTGGAAAAATCAAAGTAGGAGCTCCAAATTCTTTGGCACA
TraesCS1A02G095600      TAAGATGACATGGG-------------------------------AAATTCATATTTCTA
AT3G45870               -----------------------GAGAGA-------------------------------
TraesCS6B02G298700      TGAGGTCATGTGTGTAGAACTTTGAGAGA--------AATGTTTTACTCTCTTACATCTG
TraesCS6A02G271500      TGATGTCATGTGTGTAAAACTTTGAGAGA------------AATGAAACTCTCTTATCTG
TraesCS6D02G251700      TGAGGTCAT--GTGTAAAACTTTGAGAGA------------AATGAAACTCTCTTACCTG
                                                                                    

TraesCS7A02G409900      TCAGGCCGCTCGAGTGTTCTTACTTTGCTTC-----------------------------
TraesCS7B02G309300      TCAGGCCGCTGGAGTGTTCTTACTTTGCTTC-----------------------------
TraesCS7D02G403100      TCAGGCCGCTTGAGTGTTCTTACTTTGCTTC-----------------------------
TraesCS1A02G095600      ACTGGATGATTCA--------GCTTTGTTT------------------------------
AT3G45870               ---------------GTGACTATTTTATTTTCTAA-------------------------
TraesCS6B02G298700      TTAAGTTCTTGTA--GTTCATGCCTTGTTTCATACTACTACTCGATGAGTTAGCAATTCT
TraesCS6A02G271500      TGAAGTTCTCGTA--GTTCATACCTTGTTTCGT---------------------------
TraesCS6D02G251700      TGAAGTTCGTGTA--GTTCATACCTTGTTTCGTACTACTACTCAATGAGTTGGCAATTCT
                                                **  **                              

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCAGGCTGGACGTGTGTTGCAAGTATTTTCCAGGCTGTTTTTTTGTA------CTGCAGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCAGTCTGGACGCGTGTTGCAACTATTTTTCAGGCTGTTCTTTTGCACTGCACCTGCAAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TATGTTTTTCACCAACAATTCTTTCTTGTAAACATGTAAATGCTACACATGAGATGACCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TATGCTTTTCACCAATAGTTCGTTCTTGCAAACATGTAAATGCTACACATGAGATGACCT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTACCCATGCACCACTCTATT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTACCCATGCACCACTCTGTC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGTCTACTATTATACATCGTGGCGCGCAATCTATGGCGCGGAAACATCGAACGTGTTGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGTCTACTATTGTACATTGTCGCACGCAATCTATGGCGCGGAAACATCGGACGTGTTGGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCCTGAGTGACGAATAGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCCTGCGTGACGAACAGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCGACGATGTCCAGGTCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCGACGATGTCCAGCTCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGCGACTGCGCGTCCATCACCACGAACCTGTTGTCGCCGGTGCCCTCGTCGTGCACGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGCGCCTGCGCGTCCATCACCACGAACCGGTTGTCGCCGGTGCCCTCGTCGTGCACGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCGACGTCATCAGGGACGAAAAAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCAACGTCGTCGGGGACGAAGAAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACGGTGCAGTCGCCGTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACGGTGCAGTCGCCGTGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCAGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGCATGGGGTCGCCAACA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGCATGGGGTCGCCCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCTCGGGTTGATCACCCCGAAGTCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCCCGGGTTGATCACGCCGAAGTCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGTTCGCCGCCGCGAGCGGCGTGCGTGTGACGTTGCCGGTGCGGAGGTTGATGCGCACC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGGTTCGCCGCCGCGAGCGGCGTGCGGGTGACGTTGCCGGTGCGGAGGTTGATGCGCACC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGCTCGATGGACAGGATG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGCTCGATGGACAGGATG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTGGGTGCCACCATCACGATCTCGTCGCCGCCGGCCTCCTCCCACGCGTTCACCGAGTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTGGGCGCCACCATCACGATCTCCTCGCCGCCGGCCTCCTCCCACGCGTTCACCGAGTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACTCGTCCGCGGCGTACTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACTCGTCCGCGGCGTACTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGGATCACGCCGAGGCGAGGCACCATGCCGGGGTCCGCCCCGACGGGCGAGCCGCCGCCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGGATCACGCCGAGGCGTGGCACCATGCCCGGGTCCGCCCCGACGGGCGAGCCGCCGCCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCACCATGCCCATGGGGTTCATCACGATTTGTATCTCCGGGAATATCGCATAATGCTCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCACCATGCCCATGGGGTTCATCACGATCTGTATCTCCGGGAATATCGCATAATGCTCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTCACGGCGAAGTCGTGCAGGAAAGACGGTTGCTTCACGGAGAAGATGGGCACGTCGGCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTCACGGCGAAGTCGTGCAGGAATGACGGCTGCTTGACGGAGAAGATGGGCACGTCGGCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCCTTGTTCCCTGCAGGGTCGAACCGGAAATAGGTGACGAACGGCGGCATGGGGCCGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCCTTGTTCCCTGCCGGGTCGAACCTGAAGTAGGTGACGAACGGTGGCATGGGGCCGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CGGAACGCGAAGAGCTCGCCGGTGATGGGGTCCTTCTTGGGGTGCGCGGTCATGCCCATG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGAACGCGAAGAGCTCGCCAGTGATGGGGTCCTTCTTGGGGTGCGCGGTCATGCCCATG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCACCGGTGGCCGGGTCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCACCGGTGGCCGGGTCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGTGCGTAGAGGCGGCCGCCGAAGACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGCGCGTAGAGGCGGCCGCCGAAGACG
                                                                                    

TraesCS7A02G409900      -------TGTTGTATCTGCCTTCCACTGTT------------GTGTAAATTGTTGGCA--
TraesCS7B02G309300      -------TGTTGTATCTGCCTTCCACTGTTGTGCCTCTTGCGATGTAAATTGTTGACA--
TraesCS7D02G403100      -------TGTTGTATGTGCCTCCCTCTT--------------ATGTAAATTGTTGGCA--
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATCTGGCCTGTCAGCACC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATCTGGCCTGTCAGCACC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCGTGGAAGCCGGAGAAGACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCATGGAACCCGGAGAAGACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTGGGCAAGACCGGCTCGCCCGCGTTGCGCTCCACGATGTACTTGTACGTCTGCACGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTGGGCAAGACCGGCTCGCCGGCGTTGCGCTCCACGATGTACTTGTACGTCTGCACGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGCAGGGAGTGCAGCATG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGCAGGGAGTGCAGCATG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGATGCTGCGGGTTGGGCCCGTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGGTGCTGCGGGTTGGGCCCGTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CGGATGTAGGCGCCGCCGGCGAGGCAGCGCGGGATGACGCCGCGCACCACGGGGCAGGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGATGTAGGCGCCACCGGCGAGGCAGCGCGGGATGACGCCGCGCACCACGGGGCAGGGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACGTGCCGCGGGTCCACC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACGTGCCGCGGATCCACC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCCTCCAGCGCGTTGCAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCCTCCAGCGCGTTGCAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AACGCCGCCTGTAGCGAAGTGACGGGCCGGCGGCGAGGCCTGGACGACCGAGCCGCCTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AACGCCGCCTGTAGCGAAGCAGTAGGCCGGCGGCGAGGCCTGGACGACCGA---------
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CGCGGCGCATCGGATGCCCTGCTCGTTCTCGCGGTAGCAACTCGTGTACCAGTTGCATTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ---GGCGCATCAGACGGCCTGCTCGTTCTCGCGGTAGTCACTCTTGTAGCACTTACATTG
                                                                                    

TraesCS7A02G409900      -----------------CGGTTACAAAACAATCTTGTGTTGCCCAACTGCT---------
TraesCS7B02G309300      -----------------CGGTTAGAAAGCCATCTTGTGTCGCCCAACTGCT---------
TraesCS7D02G403100      -----------------CGGTTACAAAACCATCTTGTGTCGCCCAACTTATGTTTTAGGG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTCACGGACGTGTCGACCAGGTGCTCTTCCGTTTCTTGTTGCTCGACCGGCTTGGGCGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTAGTCGACGTGTCGACCAAGTGCTCTTCCGTCTCTTGTTGCTCGACCGGCTTCGGCGGC
                                                                                    

TraesCS7A02G409900      TATGTT------------------------------------------------------
TraesCS7B02G309300      TATGTT------------------------------------------------------
TraesCS7D02G403100      TATGTTTAGTTTGTGCCCAAGGTTGCCCCACCAAAGCATTGGCTGGTTGAGGTTTTGGTT
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GAGGTGAGGACGGTGGCGGTGGCGGCAGCCCACGGCGGCGGGGGCGACGTGCCCTTCCTC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GAGGTGAGGACGGTGGCGGTGGCGGCAGCCGACGGCGGCGGGGGCGACGTGCCCTTCCTC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GCCCATGATTTGGCAACATTGGTAAGAAAAATGAACTAGAGTTGGCTAGAGTTCATTTGG
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCGGGGGAGATGT--------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCAGGGGAGATGT--------
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      CATGCCAAAAATTTGGCAACCATCCAAACAAAGACCAATCTTTGGGTCCAAAATTTTGAT
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ---------AGGAGAGCCTCCTCGATCTCGCAGCATGAGCAGCATTGGCTTTGGCAGGGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ---------AGGAGAGCCTCCTCGATCTCGGAGCATGAGCAGCATTGGCTTTGGCGGGGT
                                                                                    

TraesCS7A02G409900      ---------------------------------TTACCCCCTTTGCTTG-TATATAGAGA
TraesCS7B02G309300      ---------------------------------TTACTCCCTTCGCTCACTATTATGAGA
TraesCS7D02G403100      AAGGTGCACTTTGGCCACAATCCAAACACACCCTTACTCCCTTCG-TCACTATTATGAGA
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGAGATCAGGCATGCTGAAGTTGGAGGTGACAAGTGCTCCCTCCATTTTCTGCAATCTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGAGATCAGACATGCTGAAGTTGGAGGTGACAAGTGCTCCCTCCATTTTCTGCAATCTGC
                                                                                    

TraesCS7A02G409900      AATTTTATTGTGTTTGTTCT--TCCATATATTTGTGAACGGTGGTAGTACTTGGACAT--
TraesCS7B02G309300      TGTTCTAACTTTTTCCTGAT---TTGTATGTATATAGACAAATTTAGTATTTGTTCTTCC
TraesCS7D02G403100      TGTTCCAACTTTTTTCTGAT----------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGATCAATGGCTCTTTGGATTGTTAGTGGATGAGTAGCAATTTCTTTGTTGGAACTTGGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGATCAATGGCTCTTTGGATTACTAGTGGATAACTAG-------CAATTTTTGTGTTGGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ATATACTGTGAACCGAACGGA---------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCCAGGTGAGTAGCAGCAAACGCTGATACCAGTTCGCAGGCTACTGCCTTT--------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCCAGGTGAGTAGCAGCAAATGCTGACACCAGTTCGCACACTACTGCCTTTGCTACTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TATGCTATGGCTATATATAGCCTCGGTAAAAGGCAAACTTACCTGGTGGAAATGTTTATT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS1A02G095600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGGTGAAAACTTCAAAGATTACGTGGACCGCTGGATCACAGCGACCGCACAATGTGGGAG
                                                                                    

TraesCS7A02G409900      ---------------------
TraesCS7B02G309300      ---------------------
TraesCS7D02G403100      ---------------------
TraesCS1A02G095600      ---------------------
AT3G45870               ---------------------
TraesCS6B02G298700      ---------------------
TraesCS6A02G271500      ---------------------
TraesCS6D02G251700      GATGAAGAGTTGCGCTAGGGT
                                             
