CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS7A02G409900      -------------------------------------------------AGCAAACGGGG
TraesCS7B02G309300      -------------------------------------------------------GAGAT
TraesCS7D02G403100      ------------------------------------AGTCGTTCCCCAAGACAAATGGAA
TraesCS3D02G003600      AGGCATGCATGATAGGAGTGGGATGAAGGGGTCGGTCGGCCTATGCCCATGCATGAAGGT
AT3G45870               ---------------------------------------------------TAAATAGGA
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      -----------------------------------------------------ATGGGGA
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CAGCTCACGCCAACCGGCACAGTGTCTACATTCCTTACTCCGT-----------------
TraesCS7B02G309300      TCGCTTCTCCTAGTCGGAG-----------------------------------------
TraesCS7D02G403100      CAGCTCACGCTACTCATGGCAGCGACCGTACTGCAGCATGTGATGTGCTACTGCAGAGGA
TraesCS3D02G003600      CTTCTCCGACCAACCATCGCTCACTTCACTGTCTGCCTCTAGCTGAGTGTCACTCTGTAG
AT3G45870               TCAATCCCAATGC-----------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      AATCACCTAAAAAACAGTGGGG--------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ------------------------ATGGTTGCGTG------GAGCCAGAAGCCACCGCAG
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      TCCTAACCCCTGCATACGGGCAGGTTGCGTGCGTG------GAGCCAGCAGCCACCGGCC
TraesCS3D02G003600      CATGCTCACCTACTGTCCAAGTGGAATGTCGCGCGTCTATATAGCTAGACACCCCTGGTT
AT3G45870               ------------------------ATGCTTGTGTCCGAAGCATGATGTCATCATTTGTTA
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CCTTTCCCCA-----ATAAGTCCGCCACACGACGGCCGGCAGAGCCGCAGAGGCAGACAC
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GCATACCTTCCCCCAATAAATCCGC--CACGACGGCACGCAGGCGAAAAATCTGGAGTTT
TraesCS3D02G003600      GCACTCCTCACTCACCTCATCCCTGGCCTAGGCCGT------------------------
AT3G45870               GTTCCCCTGTCTCGTTCGATCAAAAAACACGTTTTGACAGAAGAGATTCAAAGTGACAAT
TraesCS6B02G298700      ---------------GAAAGT---------------------------------------
TraesCS6A02G271500      ---------------AAAAGTCCTAAAAAAAACAGTGGGGAAAAGGT-------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CACAATCAGGGGCCGGTGACATCGCCGTCCATCGCAGAAAAGTCCAGGTGAGATAGAGAG
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      TGCTTCTCCTAGTCGTCG------------------------------------------
TraesCS3D02G003600      -------------CCTCTCTCTCGTCTCTCAGTGCCA-----------------------
AT3G45870               CAGTTTCAAGATTTAATTCTCTTACC----------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      AGAGATCTTTCTCCGAGCTCAGCCAGCTAGGCTCCCGCGGTAGCAGTAGCGCCTAGCGGC
TraesCS7B02G309300      ------CCTCGTCGGAGCCCAGCAA-------------GGCTGGAGTAGTGCCCAGCGGC
TraesCS7D02G403100      ------CCTCGTCGGAGCCCAGCAA----------GACTGCTGGAGTAGTGGCTAGCGGC
TraesCS3D02G003600      -----------CCTCGCTCCAGCAGCTTCTATCTCGATCTAGGGA---------------
AT3G45870               ------CACTCTCTCACCCTGGCTTTCATAACTTTCTCCG-GGAA--------TAAGAAT
TraesCS6B02G298700      -----------TCAAAGAGGAGTAGTCGCTACTCAGACCGTGGGA--------CGACGAC
TraesCS6A02G271500      -----------TCAAAGAGGAGTATTCGCTACTCAGACCGTGGGA--------CGACGAC
TraesCS6D02G251700      -----------------------------------------GGGA--------CGACGAC
                                                                  * *               

TraesCS7A02G409900      CGGCGTG-------------------------------GAGAGAGGATGGGGACGGAGCC
TraesCS7B02G309300      CGGCGCGAGAGGGAGTC----------------AGAGAGAGAAGGGATGGGGACGGAGCC
TraesCS7D02G403100      CGGCGCGCAGAGAGAGCGAGAGAGAGACAGAGGAGAGAGAGAGGGGATGGGGACGGAGCC
TraesCS3D02G003600      --------------------------------------GAGATCAAGTGAGGAGAGGGTG
AT3G45870               CGC-----------------------------------CGGAAAAGAAGAAAAC------
TraesCS6B02G298700      CGT-----------------------------------GGGATCGGATCGG---------
TraesCS6A02G271500      CGG-----------------------------------GGGATCGGATCGG---------
TraesCS6D02G251700      CGT-----------------------------------GGGATCGGATCGG---------
                                                                **                  

TraesCS7A02G409900      GACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGGATGAGCGGGCGCGACCGGCTGCG
TraesCS7B02G309300      GACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGGATGAGCGGCCGCGACAGGCTGCG
TraesCS7D02G403100      GACGATGCTGCAGCGGTGGTCGTCGTCGATGTGGGGGATGAGCGGCGGCGACCGGCTGCG
TraesCS3D02G003600      -----------------------CAGCAATGGCGGACGCGGTGGACGCCCGTCGGGTGT-
AT3G45870               -----------------------CGCCAATGGAGAGTACG--------------------
TraesCS6B02G298700      -----------------------CGGCGATGGCGG-----------------CGGCGGC-
TraesCS6A02G271500      -----------------------CGGCGATGGCGG-----------------CGGCGGC-
TraesCS6D02G251700      -----------------------CG-CGATGGCGG-----------------CGGCGGC-
                                               *  * ***  *                          

TraesCS7A02G409900      GCTGTGGGAGGACAAGGCGTG-GCGGGCGCACGCGGGCATGGCCTTCACGCAGCTCGCCT
TraesCS7B02G309300      GCTGTGGGAGGACAAGGCGTG-GCGGGCGCACGCGGCCATGGCCTTCACGCAGCTCGCCT
TraesCS7D02G403100      GCTGTGGGAGGACAAGGCGTG-GCGGGCGCACGCGGCCATGGCCTTCACGCAGCTCGCCT
TraesCS3D02G003600      ---GCGGGATGCCGGAGAAGGCGCAGCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCT
AT3G45870               ---GTGGAAAGA-GAGGCGTG-GAAAGCTCACGTGGCGATGATCGGTGTGCAATTGTTCA
TraesCS6B02G298700      ---GCGGGATGGGGAAGCGAG-GCGGGCGCACGCGGCGATGGTGGGGTCGCAGTTCATCA
TraesCS6A02G271500      ---GCGGGATGGGGAAGCGAG-GCGGGCGCACGCGGCGATGGTGGGGTCGCAGTTCATCA
TraesCS6D02G251700      ---GCGGGATGGGGAAGCGAG-GCGGGCGCACGCGGCGATGGTGGGGTCGCAGTTCATCA
                           * ** * *     *   * *      **** **  ***        ***  *   * 

TraesCS7A02G409900      ACGGCGGCTACCACGTCCTCACCAAGTCCGTGCTCAACGTCGGCATGAACCAGATCGTCT
TraesCS7B02G309300      ACGGCGGCTACCACGTCCTCACCAAGTCCGTCCTGAACGTCGGCATGAACCAGATCGTCT
TraesCS7D02G403100      ACGGCGGCTACCACGTCCTCACCAAGTCCGTCCTCAACGTCGGCATGAACCAGATCGTCT
TraesCS3D02G003600      ACGCCGGCTTCCACGTCGTGTCGCGCCTCGCGCTCAACATGGGCATCAGCAAGCTCGTCT
AT3G45870               ACGGAGGATATCATGTCATTACCAAAGTGGCTCTCAACGTTGGTGTAAACCAACTTGTCT
TraesCS6B02G298700      ACGCGGGGTACCACGTCATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTTGTCT
TraesCS6A02G271500      ACGCGGGGTACCACGTCATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTCGTCT
TraesCS6D02G251700      ACGCGGGGTACCACGTCATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTCGTCT
                        ***  ** *  ** *** *  *       *  ** *** * **  * * *    * ****

TraesCS7A02G409900      TCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAG
TraesCS7B02G309300      TCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAG
TraesCS7D02G403100      TCTGCGTCTACCGCGACCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAG
TraesCS3D02G003600      TCCCCGTCTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACTTCCTCG
AT3G45870               TCTGTGTCTTTCGTGATCTCATTGCTCTCTCCATTCTTGCTCCTCTTGCTTATATCCGTG
TraesCS6B02G298700      TCTGCGTCTACCGCGACCTCCTCGCGCTCTGCGTGCTTGCTCCCATCGCCTTCTTCCGCC
TraesCS6A02G271500      TCTGCGTCTACCGCGACCTCCTCGCGATCTGCGTGCTTGCTCCCATCGCCTTCTTCCGCC
TraesCS6D02G251700      TCTGCGTCTACCGCGACCTCCTCGCGCTCTGCGTGCTTGCTCCCATCGCCTTCTTCCGCC
                        **   ****  **  *  ** * **  **  * * ** *  **    ** *   ***   

TraesCS7A02G409900      AGAGGTACGTCGCACTATCATCCCCATGCCCATGGCTGCTCTGATCTAGAGTTCTAGACC
TraesCS7B02G309300      AGAGGTACG------CACCGTACCATCCCCCATGGCTGCTCTG--------ATCTGGACC
TraesCS7D02G403100      AGAGGTACGTCGTGCTAGGCGCCTCACC-CCATGGCTGCTCTGCTCT---GATCTGGACG
TraesCS3D02G003600      AG----------------------------------------------------------
AT3G45870               A-----------------------------------------------------------
TraesCS6B02G298700      A----------------------------CCGCGGCTCGCCCG-----------------
TraesCS6A02G271500      A----------------------------CCGCGGCTCGCCCG-----------------
TraesCS6D02G251700      A----------------------------CCGCGGCTCGCCCG-----------------
                        *                                                           

TraesCS7A02G409900      AATTGACATCGAATTTGACTAGACGCTATTCGGGTGCGGATTCTGAATTTCCCGCAGGAG
TraesCS7B02G309300      AATTGACATCGAATTTGACTAGATACTATTCGGGTGCGGATTCTGAATTTC-CGCAGGAG
TraesCS7D02G403100      AATTGACATCGAATTTGACTTGATACTCTTCGGCTGCGGATTCTGAATATCCCGCAGGAG
TraesCS3D02G003600      -------------------------------------------------------AAGAA
AT3G45870               ------------------------------------------------------TAAGAG
TraesCS6B02G298700      ----------------------------------------------------CGCAGGCT
TraesCS6A02G271500      ----------------------------------------------------CGCAGGCT
TraesCS6D02G251700      ----------------------------------------------------CGCAGGCT
                                                                               * *  

TraesCS7A02G409900      GGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGCGCTGCTTGGATTCACCGG
TraesCS7B02G309300      GGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGCGCTCCTTGGGTTCACCGG
TraesCS7D02G403100      GGTGCGGCGCCCCGTCACCCCGCAGCTGCTCGGCTCCTTCGCGCTCCTTGGATTCACCGG
TraesCS3D02G003600      GGACCGCCCCAGGCTCACCCTCGGCTTCGCCGTCCAGTTCTTCTTCCTCGCCCTC-----
AT3G45870               AACAAGACCTCCTTTGAATCGACAGTTTCTCTTAGCTTTCTTCTTCCTTGGTTTAACAGG
TraesCS6B02G298700      CGTCCGCCGCCC-GTCACGCGTCGCCTCCTTACCTCCTTCTTCTTCCTCGGGCTCACGGG
TraesCS6A02G271500      CGTCCGCCGCCC-GTCACGCGTCGCCTCCTTACCTCCTTCTTCTTCCTCGGGCTCACGGG
TraesCS6D02G251700      CGTCCGCCGCCC-GTCACGCGTCGCCTCCTTACCTCCTTCTTCTTCCTCGGGCTCACGGG
                             * *      * *  *      *          ***    * ** *   *      

TraesCS7A02G409900      GTAATTCCCCCACTCCTCCTCCTCCTCCTCATGCTGCTGCTGCTACTGCTGATGCCCGAT
TraesCS7B02G309300      GTAACTCTCCT-------------------CTGCTGCTACTGCTGCTGCTGCTGCCTGAT
TraesCS7D02G403100      GTAATTTTCCC---------CCTCGTCCTCATGCTGCTGCTGAT---------GCCTGAT
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               GTAATTCAAGT------------TTTCTTCTACCAGTTTCTGTTAT--------CTTCAT
TraesCS6B02G298700      GTAAGCCTGGC----------CACCCGGTCGCTCGGTGTCAGACACGCTGACCGCTTG--
TraesCS6A02G271500      GTAAGCCTGGC----------CACGCGGTCGCTCGGTGTCAGACACGCCGACCGCTTG--
TraesCS6D02G251700      GTAAGCCTGGC----------CTCCCGGTCGCTCGGTGTCAGACACGCTGACCGCTTG--
                                                                                    

TraesCS7A02G409900      G----GAGCAATAAGAG---------------------------------------TCAC
TraesCS7B02G309300      GGGGCGAGCAACAATAACTCTCTTCAGTCTCGTGCTGTCTTCCATCGACTAACTCATCAC
TraesCS7D02G403100      G----GAGCAATAAGAG---------------------------------------TCAC
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               GATTGCAATCATCACAG---------------------------------------TGAT
TraesCS6B02G298700      -----AAGCAATGCTGCTTATGTACTTGCAAATT----------------------TCGT
TraesCS6A02G271500      -----AAGCAATGCTGCTTATGTACTTGCAAATG----------------------TCGT
TraesCS6D02G251700      -----AAGCAATGCTGCTTATGTACTTGCAAATT----------------------TCGT
                                                                                    

TraesCS7A02G409900      ATTCTGACG--------------GCGTGCAGGATCTTCGGGAACCAGCTCCTCTTCCTGC
TraesCS7B02G309300      ATTCTGGCG--------------GCGTGCAGGATCTTCGGTAACCAGCTCCTCTTCCTGC
TraesCS7D02G403100      ATTCTGACG--------------GCGTGCAGGATCTTCGGGAACCAGCTCCTCTTCCTGC
TraesCS3D02G003600      --------------------------TGCGGCATCACCGCCAACCAGGGCTTCTACCTCC
AT3G45870               GTTTTGGTGTGAT---------------TAGGATATTTGGTAATCAGCTTTTGTTCCTCA
TraesCS6B02G298700      GCTCTGATGCGTCTGGTTGTTTGTCCTGTAGCATCTTTGGCAACCAGCTGCTGTTCTTGT
TraesCS6A02G271500      GCTCTGATGCGTCTGGTTGTTTGTCCTGTAGCATCTTTGGCAACCAGCTGCTGTTCTTGT
TraesCS6D02G251700      GCTCTGATGCGTCTGATTGTTTGTCCTGTAGCATCTTTGGCAACCAGCTACTGTTCTTGT
                                                      * **    *  ** ***    * * * *  

TraesCS7A02G409900      TCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCT
TraesCS7B02G309300      TCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCT
TraesCS7D02G403100      TCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCT
TraesCS3D02G003600      TGGGCCTCGACAACACGTCCCCCACCTTCGCCTCCGCCATCCAGAACTCCGTGCCCGCCA
AT3G45870               TTGGTCTGAATTACACCAATCCAACTTATGCTGCAGCCATTCAGCCGTCGATCCCGGTTT
TraesCS6B02G298700      TCGGCCTCGGCTACACCAATCCGACATACGCCGCCGCCATTCAGCCATCAATTCCCGTCT
TraesCS6A02G271500      TCGGCCTCGGCTACACCAATCCGACATACGCCGCCGCCATTCAGCCGTCAATTCCCGTCT
TraesCS6D02G251700      TCGGCCTCGGCTACACCAATCCAACCTACGCCGCCGCCATTCAGCCGTCAATTCCCGTCT
                        * ** **      ***     *  * *  **  * **  * ***    *  * ** *   

TraesCS7A02G409900      TCACCTTCCTCCTCGCCGCAATCGTCGGGTGAG-----------CAACCAATCAATCAAC
TraesCS7B02G309300      TCACCTTCCTCCTGGCCGCAATCGTCGGGTGAG---------------------------
TraesCS7D02G403100      TCACCTTCCTCCTCGCCGCAATCGTCGGGTGAGCACTGAGCAATCAACCAATCAATCAAC
TraesCS3D02G003600      TCACCTTCGGCATGGCCG------------------------------------------
AT3G45870               TTACTTTCATCTTGGCTCTCATTATGGGGTAAA---------------------------
TraesCS6B02G298700      TCACTTTCATCTTGGCCCTCATCATGGGGTCAG---------------------------
TraesCS6A02G271500      TCACTTTCATCTTGGCCCTCGTCATGGGGTCAG---------------------------
TraesCS6D02G251700      TCACTTTCATCTTGGCCCTCATCATGGGGTCAG---------------------------
                        * ** ***  * * **                                            

TraesCS7A02G409900      GGATGCACATACACGTTTCAGAGTTCTGACATCGCCTTGGATGCAAAATGCCAAACTGAA
TraesCS7B02G309300      ---------------------CAATCAACCTGACCCTTGGATGC-AAATGCCAACCTGAA
TraesCS7D02G403100      GGATGCACATACACGTTTCAGAGTTCTGACATCGCCTTGGATGCAAAATGCCAAACTGAA
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ----GACTCGATCCAGTCTTTCTCTTTTACTTTCTCTCTGA-------------------
TraesCS6B02G298700      ------------------------TCTCACTCAATCTTGAA-----------------AA
TraesCS6A02G271500      ------------------------TCTCGCTCAATCTTGAA-----------------AA
TraesCS6D02G251700      ------------------------TCTCACTCAATCTTGAA-----------------AA
                                                                                    

TraesCS7A02G409900      CCGTAACAAACCCCGAAATGTCCCATTGCCCTGGATACACTTCTGGATTCTGATCAAATG
TraesCS7B02G309300      CCGTAACGAACTACGAAATGTC-----------AATGCATTTCTGGATTCTGACCAGATG
TraesCS7D02G403100      CCGTAACAAACCCCGAAATGTCCCATTGCCGCGGATACACTTCTGGATTCTGATCAAATG
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               CTCTTCCAAACCTAGAAC---------------AATCCATTTTCGTGTGTTG--------
TraesCS6B02G298700      ATGTTCAGAGACTCG------------------CATCTCTCTTTGTTTGCTGGTTTAA--
TraesCS6A02G271500      ATGTTCAGAGACTCG------------------CATCTCTCTTTGTTTGTCGGTTTAA--
TraesCS6D02G251700      ATATTCAGAGACTCG------------------CATCTCTCTTTCTTTGCTGGTTTAA--
                                                                                    

TraesCS7A02G409900      CTGAACCAAAATGTT-------------------CTTATTCCAGTGTCGAAGTGATCAAC
TraesCS7B02G309300      CTGAACCGAACCGTAACAGAATTACCAAAATGATCTTGTTCCAGCGTCGAAGTGATCAAC
TraesCS7D02G403100      CTGAACCAAAATGTT-------------------CTTATTCCAGTGTCGAAGTCATCCAC
TraesCS3D02G003600      ----------------------------------CCGCGCTCCGCATCGAGAAGGTGCGC
AT3G45870               --------------------------------------CTGCAGAACAGAGAGACTGAAT
TraesCS6B02G298700      -------GCATTTTA-------------------CAATTTTCAGGACTGAAACGGCGAGC
TraesCS6A02G271500      -------GCATTTTA-------------------CCATTTTCAGCACTGAAACGGCGAGC
TraesCS6D02G251700      -------GCATTTTA-------------------CCATTTTCAGCACTGAAACGGCGAGC
                                                                 * *    **          

TraesCS7A02G409900      GTCTTCACCAGAGACGGCCTCTTCAAGGTGGTCGGCACGGCCGTGTGCGTCTTCGGCGCC
TraesCS7B02G309300      GTCTTCACCAGAGACGGCGTCTTCAAGGTCGTCGGCACGGCCGTGTGCGTCTTCGGCGCC
TraesCS7D02G403100      GTCTTCACCAGAGACGGCGTCTTCAAGGTCGTCGGCACGGCCGTGTGCGTCTTCGGCGCC
TraesCS3D02G003600      CTCGACCGCCGCGACGGCGTCGCCAAGGTGCTGGGCACCCTCGCGTGCGTCGCGGGCGCG
AT3G45870               TTATTCAAGCTAGAAGGTCAAGCTAAGGTAGGAGGCACACTGATTTGTGTCGCTGGGGCG
TraesCS6B02G298700      TTGGTCACACACGAGGGCCGTGCCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCT
TraesCS6A02G271500      TTCGTCACACACGAGGGCCGTGCCAAGGTTGGTGGCACCATCGTCTGTGTGCTTGGTGCT
TraesCS6D02G251700      TTGGTCACACACGAGGGCCGTGCCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCT
                         *   *      ** **       *****    *****       ** **    ** ** 

TraesCS7A02G409900      GTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGATC-----------------GGCCTTG
TraesCS7B02G309300      GTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGATC-----------------GGCCTCG
TraesCS7D02G403100      CTCCTCATGGTCTTCTACCGAGGCCCCTCCCTGATC-----------------GGCCTCG
TraesCS3D02G003600      TCCGTCATCACGCTCTACCAGGGCCCAACCATCTTC-----------------GCCCCTA
AT3G45870               GTGCTGATGGTTTTGTTTCGTGGACTGGCTTTGTTTGGGGAAACAGAGGCTGAGTCCTTG
TraesCS6B02G298700      GTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTTTGGT--AGCAGCGATCTAGATCTTG
TraesCS6A02G271500      GTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTTTGGT--AGCAGCGAGTTAGATCTTG
TraesCS6D02G251700      GTTCTCATGGTGTTGTACAGGGGGGCAGCTGTGTTTGGT--AGCAGCGAGCTAGATCTTG
                            * **     * *     **     *  *  *                  *  *   

TraesCS7A02G409900      GAGGCGCCAATGCGCTGGACGGCGCCGACGCGTCGTGGAGCGGCAGTTCCTATCCTGCTC
TraesCS7B02G309300      GAGATGCCAATGCGCTGTCTGGCGCCGGCGCGTCATGGAGCGGCAGTTCCTATCCTGCTC
TraesCS7D02G403100      GAGGCGCCAATGCGCTGGCCGGCGCCGACGCGTCATGGAGCGGCAGTTCCTATCCTGCTC
TraesCS3D02G003600      ---------------CCGCCGGCGACGACAAGCCGTCG----------------------
AT3G45870               --GGTCATGGTGAATCAAGACACACTGAAACATCTGGACAC-------------------
TraesCS6B02G298700      ATGTTCCTCGTAATGTCGTCATCACTGAGATGTTGCAAC---------------------
TraesCS6A02G271500      ATGTTCAGAGCAATGTCGTCATCACCGAGATGTTGCAAC---------------------
TraesCS6D02G251700      ATGTTCATAGCAATGTCGTCATCACCGAGATGTTGCAAC---------------------
                                              *   *                                 

TraesCS7A02G409900      AGTGGCTGACGCCAGCCACGCTCCAGTTCAGT---------TTTGG---AACCTGGAACC
TraesCS7B02G309300      AGTGGCTGACGCCAACCACGCTCCAGTTCAAT---------TTTGG---AACCTGGAACC
TraesCS7D02G403100      AGTGGCTGACGCCAGCCGTGCTCCAGTTCAGT---------TTTGG---AACCTGGAACC
TraesCS3D02G003600      -----TTGCAGGAGGTGCCGTTTCTGGCCGCCGTGGCCGGGGAGGGCAAGAACTGGACGC
AT3G45870               -----TTCATGTCTGGCTTTTTT------------AATGGACTTGG---GCGATGGAATT
TraesCS6B02G298700      -----CTGA-GCCAGGATCATCTTGGTTCATTGCATATGGGCTGGA---AAAGTGGCATA
TraesCS6A02G271500      -----CTGA-GCCAGGATCATCTTGGTTCATTGCATATGGGCTGGA---AAAGTGGCATA
TraesCS6D02G251700      -----CTGA-GCCAGGATCATCTTGGTTCATTGCATATGGGCTGGA---AAAGTGGCATA
                              *   *                                 *        ***    

TraesCS7A02G409900      TTGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGGGGCTTATCTTGTCATACAGG
TraesCS7B02G309300      TCGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGGAGCTTATCTTGTCATACAGG
TraesCS7D02G403100      TTGGTGTCCTGTGCCTCTTAGGCAACTGCTTCCTCATGGGGGCTTATCTTGTCATACAGG
TraesCS3D02G003600      TGGGCTGCGTCTACCTCATCGGCCACTGCCTCT---------CGTGGTCCGGCTGGCTGG
AT3G45870               TGGGAGTTTTGTGTTTGATTGGGAATTGCACTTGCATGGCTGCTTTTCTTGCTATTCAGG
TraesCS6B02G298700      TCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGG
TraesCS6A02G271500      TCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGG
TraesCS6D02G251700      TCGGAGTGTTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGG
                        * **     * *   *  * **  * ***             * *     *     * **

TraesCS7A02G409900      TAA---------------------------------------------------------
TraesCS7B02G309300      TGA---------------------------------------------------------
TraesCS7D02G403100      TAA---------------------------------------------------------
TraesCS3D02G003600      TGC---------------------------------------------------------
AT3G45870               CAT-------------------------------GTCATTTTCTTCTAGATG--------
TraesCS6B02G298700      TATTAATGATTTTCAGGCTGTTGCCGCGCTCTATTCCATTTGCATTTTGATGTTTGTCAA
TraesCS6A02G271500      TATTAATGATTTTCAGGCTATTGTCGCACTCTATTCCGTTTGCATTT-GATGTTTGTCAA
TraesCS6D02G251700      TATTAATGATTTTCAGGCTGTTGTCGCTCTCTATTCCGTTTGCATTTTGATGTTTGTCAA
                                                                                    

TraesCS7A02G409900      -----------TGCAGATTGGGTT------------------------------------
TraesCS7B02G309300      -----------TGCAGATTGGGTT--GTTTTCAGC-------------------------
TraesCS7D02G403100      -----------TGCGGAATGGGATTTGTTTTTAGC-------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ATCCACACACTTTCAGTTTCAGATATCTTCTTGTC-------------------------
TraesCS6B02G298700      CTCGGAACACCTTGAGCTTTAGTTTTCTATCAGGCATATATGCATGGCACAAGTTCTGAA
TraesCS6A02G271500      CTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATATGCATGGCACAAGTACTGAA
TraesCS6D02G251700      CTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATATGCATGGCACAAGTTCTGAA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTGTAGGGCAACTTCAGATCACATC
TraesCS6A02G271500      AGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTATAGGGCAACTTCAGATCACAGC
TraesCS6D02G251700      AGGCTGAAAGCCTCTGTAAGTTACATCAGTAAATCTTATAGGGCAACTTCAGATCACATC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ---------------------------------------------TTCATGATAGTTT--
TraesCS7D02G403100      ---------------------------------------------TTCATGATAGTTT--
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AACTCTATTTAGAACACTCTATTTTGATGAATATTTCAGTCCCAATTCCTAATGGTTTCT
TraesCS6A02G271500      AACTCTATTTAGTACACTCTGTTTTGATGAATATTTCAGTCCCAATTCCTAACAGTTTCT
TraesCS6D02G251700      AACTCTATTTAGAGCACTCTATTTTGATGAATATTTCAGTCCCAATTCCTAACGGTTTCT
                                                                                    

TraesCS7A02G409900      --------------------------------------------------GTTTGCTCTT
TraesCS7B02G309300      ---------------------------------------------------TTTGCTCTT
TraesCS7D02G403100      ---------------------------------------------------TTTGCTCTT
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ----------------------------------------TTTGGACTGACCTTGCATTT
TraesCS6B02G298700      CTGCCTTCTTGACATTCTTAAAGTGAGAAGGATATTAAAACTTAGGCCGGGTTTGCTCTT
TraesCS6A02G271500      CTGCCTTCTTGCCATTCTTGAAGTGAGAAGGATACTAAAATTTAGGCCGGCTTTGCTCTT
TraesCS6D02G251700      CTGCCTTCTTGACATTCTTGAAGTGAGAAGGATATTAAAACTTAGGCCGGCTTTGCTCTT
                                                                                    

TraesCS7A02G409900      AATGAGAA----CTATATCT----------------------------------------
TraesCS7B02G309300      AATGAGAA----TTACATCT----------------------------------------
TraesCS7D02G403100      AATGAGAATTACATATATCT----------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ----GAAA-----CATATAT----------------------------------------
TraesCS6B02G298700      CCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAACTGGCCATTGCTTAATACTGAACAT
TraesCS6A02G271500      CCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAACTGGCCTTTGCTTAATATTGAACAT
TraesCS6D02G251700      CCTAGAAAAGGCCCATATTTATGCTGTGTGACCAACTGGCCTTTGCTTATTATTGAACAT
                                                                                    

TraesCS7A02G409900      -----------------------------GAATTTG------------------------
TraesCS7B02G309300      -----------------------------GAATTTG------------------------
TraesCS7D02G403100      -----------------------------GAATTTG------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGTATGTTATTTGGTGAATTGTCACAAGAAGATTTGTCATGGGCCGAGCAAATCATACTT
TraesCS6A02G271500      GGTATGTTTTTTGGTGAATTGTCACAAGAAGATTTGTCATGGGCCGAGGAAATCATACTT
TraesCS6D02G251700      GGTATGTTGTTTGGTGAATTCTCACAAGAAGATTTGTCATGGGCCGAGGAAATCAAACTT
                                                                                    

TraesCS7A02G409900      ----------------------------------------TGTCCTTTTC----------
TraesCS7B02G309300      ----------------------------------------TGTCCTTTTC----------
TraesCS7D02G403100      ----------------------------------------TGTCCTTTTC----------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CATTTTAAGAACCAATATCACTATACTAACAGAAGGAGATCACCCTTTTAACATTGTTGA
TraesCS6A02G271500      CATTTTAAGAACCAATATCACTATACTAATAGAAGGAAATCACCCTTTTAACATTGTTGA
TraesCS6D02G251700      CATTCTAAGAACCAATATCACTATACTAATAGAAGGAGATCACCCTTTTAACGTTGTTGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGATATGTTTATGTATTAGACTTACTCTAGTATCTTGCTATTCAAGGTTGAAACTTATGC
TraesCS6A02G271500      AAATATGTTTATGTATTAGACTTACTTTGGTATCTTGCTATTCAAGGTTGAAACTTATGC
TraesCS6D02G251700      AAATATGTTTATGTATTAGACTTACTTTAGTATCTTGCT---------------------
                                                                                    

TraesCS7A02G409900      -------------TGCCGTGAC--------------------------------------
TraesCS7B02G309300      -------------TGCTGTGAC--------------------------------------
TraesCS7D02G403100      -------------TGCTGTGAC--------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               -------------------GAT--------------------------------------
TraesCS6B02G298700      TACAAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTTGTTATTTTATACTTAT
TraesCS6A02G271500      TACAAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTTGTTATTTTATAC-TAC
TraesCS6D02G251700      CACAAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTTGTTATTTTATACTTAT
                                                                                    

TraesCS7A02G409900      ---------------TGATTCCAGGCCCCGGTGTTAGTAAAATATCCCGCGAGCTTATCC
TraesCS7B02G309300      ---------------TGTTTCCAGGCCCCGGTGTTAGTAAAATATCCTGCGAGCTTATCC
TraesCS7D02G403100      ---------------TGATTCCAGGCCCCGGTGTTAGTAAAATATCCTGCGAGCTTATCC
TraesCS3D02G003600      -------------------TGCAGGCGCCCGTGCTCAAGAAGTACCCCGCGAAGCTGTCC
AT3G45870               ---------------------CAGGCTCCGGTCTTAAAGAAGTATCCGGCGAATCTTTCA
TraesCS6B02G298700      TATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTGTCA
TraesCS6A02G271500      TATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTGTCA
TraesCS6D02G251700      TATGTTCATGTGTTGTTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTATCA
                                             ***** **  *  *    ** ** **    *   * ** 

TraesCS7A02G409900      TTGACAGCCTATTCTTATTCATTTGCCACCATCTTCATGGTGTTGACTGGGGTATTT---
TraesCS7B02G309300      TTGACAGCCTATTCTTACTCATTTGCCACCATATTCATGGTGTTGACTGGGGTATTT---
TraesCS7D02G403100      TTGACAGCCTACTCTTACTCATTTGCCACCATCTTCATGGTGTTGACTGGGGTTTTT---
TraesCS3D02G003600      GTCACCTCCTACACCTGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCTTCTTC
AT3G45870               GTCACAGCATACTCGTATTTCTTTGGGACCATGTTTATGGTGACATCT---GCTTTTTTC
TraesCS6B02G298700      TTGACAGCTTACTCATACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCA
TraesCS6A02G271500      TTGACAGCTTACTCATACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCA
TraesCS6D02G251700      TTGACAGCTTACTCATACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCA
                         * **  * **  * *  *  ** *      *     *  *          *  **    

TraesCS7A02G409900      GCAACCAACGGGCTCCATGAGTGGGCGCTGA---CAGGGACCGAAATCATAGCCGTTCTA
TraesCS7B02G309300      GCAACCAACGGGCTCCATGAGTGGGCACTGA---CAGGGACAGAAATCATAGCCGTTCTA
TraesCS7D02G403100      GCAACCAACGGGCTCCATGAGTGGGCGCTGA---CAGGGACAGAAATCATAGCCGTTCTA
TraesCS3D02G003600      GAGAGGGACGC---CGGCGCATGGGTCTTCCACTCCGGCTCCGAAGTCTTCACTATCCTC
AT3G45870               ATGACTAATGAGTCGACGAACTGGAGTCTCA---CAAGATCCGAGTTCTTTGCAGTTGTC
TraesCS6B02G298700      ACAACCAGTAA---AGAAGATTGGACTTTGA---CTGCATCTGAGTTTGCGGCTGTTGTA
TraesCS6A02G271500      ACAACCAGTAA---AGAAGATTGGACTTTGA---CTGCATCTGAGTTTGCGGCTGTTGTA
TraesCS6D02G251700      ACAACCAGTAA---AGAAGATTGGACTTTGA---CTGCATCTGAGTTTGCGGCTGTTGTA
                           *                 ***    *     *     * **  *     *  *  * 

TraesCS7A02G409900      TATGCTGTGAGTATCTGAATAATAT--------CCATGGCTGCTGCC-------------
TraesCS7B02G309300      TATGCTGTGAGTATCTGAATAATAAT-------CTATGGCCGCCCTTTAGGATTACAATA
TraesCS7D02G403100      TATGCTGTGAGTATCTGAACAATAAT-------CTATGGCCGCCCTTTATGATTACATTA
TraesCS3D02G003600      TACGCCGTAAGCATT----TATTAGTGTCCTATATAATTTCGCAGTTAAAAATT-AATTA
AT3G45870               TACGCAGTATGTTCT--------------------------------------TCACACA
TraesCS6B02G298700      TATGCTGTAAG-ATTGTGTTAGATTTATCTTTCCCATGCATGGGACCATGAATTGAATTT
TraesCS6A02G271500      TATGCTGTAAGCTTTGTGTTAGTTTTATTTTTCCCATGCGTGGGACCATGAATTGAATTT
TraesCS6D02G251700      TATGCTGTAAGCTTTGTGTCAGATTTATCTTTCCCATGCACGGGACCATGAATTGAATTT
                        ** ** **  *                                                 

TraesCS7A02G409900      ---TGTGGATGACCATGCT----------------------------AAGATGTGCT---
TraesCS7B02G309300      GAACTTGTATGACCATGCT----------------------------ACGATGTGCTAA-
TraesCS7D02G403100      GAACTTGTATGACCATGCT----------------------------ATGATGTGCTAA-
TraesCS3D02G003600      CTCCTTCCATC-TCATAATATAAAAGCGTTTTTT-----------------TACACTAGT
AT3G45870               CCATATGTTTG------------------------------------TTGATCCATTAA-
TraesCS6B02G298700      CTACATGTATG-TAGTACTGTGGTGGTGATAATTGTTGCAAACTTGCA--ATAAGCTAG-
TraesCS6A02G271500      CTACATGTATG-TAGTACTGTGGCGAAGATAATTGTTGCAAACTTGCAAAATACGCTAG-
TraesCS6D02G251700      CTACATGTATG-TAGTACTGTGGCGGATATAATTGTTGCAAACTTGCAAAATACGCTAG-
                             *   *                                         *    *   

TraesCS7A02G409900      -------------------------------------------------TGTTCTAACCA
TraesCS7B02G309300      ----CCTCTCCGAGCT---------------------------------TGTTCTAACCA
TraesCS7D02G403100      ----CCTCTCCGAGCT---------------------------------TGTTCTAACCA
TraesCS3D02G003600      ACTTTCTTCGTAAACTA----------------------ATATAAAAGATGATCTAAACG
AT3G45870               -----------------------------------------------ATTTCTCCAATTG
TraesCS6B02G298700      ----TTTGTGTAGGGTATAGAAG---TAGTTGACGCATGCCACCATAAATATACT-ATAC
TraesCS6A02G271500      ----TTTGTGTAGGCTATAGAAGAAATAGTTGACGCATGCCACCATAAATATTCT-ATAC
TraesCS6D02G251700      ----TTTGTGTAGGCTATAGAAGAAATAGTTGACGCATGCCACCATAAATATTCTAATAC
                                                                         *   *  *   

TraesCS7A02G409900      CA----TTTCTTGCTTGCGCCAA---------CAGGGAGTTGTTGCATCTTGTCTC----
TraesCS7B02G309300      CA----TTTCTTGCTTGCAACCAA--------CAGGGAGTTGTTGCGTCTTGTCTC----
TraesCS7D02G403100      CA----TTTCTTGCTTGCACCAA---------CAGGGAGTTGTTGCGTCTTGTCTC----
TraesCS3D02G003600      C-----TCTTATATTAGGCCTGGAATCCCAATCACATACTAATTACTACTACTCTCTATC
AT3G45870               AGTAACTCTGTTGCTTCCTCTATG--------CAGGGAGTAATCGCGTCTGCTCTC----
TraesCS6B02G298700      TGAAATTCCCCTATTTCCCCCCTATT-----TCAGGGAGTTGTTTCATCTGCTCTT----
TraesCS6A02G271500      TGAAATTCTCCTATTTCCCCCCTATT-----TCAGGGAGTTGTTTCATCTGCTCTT----
TraesCS6D02G251700      TGAAATTCTCCTATTTCCCCCCTATT-----TCAGGGAGTTGTTTCATCTGCTCTT----
                              *    *  *                 **   * *  *  *  **  ***     

TraesCS7A02G409900      ---------------AACTACGCAATCATGA-----CTTGGGCGAACAAAATTCTTGGAC
TraesCS7B02G309300      ---------------AACTACGCAATCATGA-----CTTGGGCGAATAAAATTCTCGGAC
TraesCS7D02G403100      ---------------AACTACGCAATCATGA-----CTTGGGCGAACAAAATTCTTGGAC
TraesCS3D02G003600      TGAGGTGCAAATGAAAATGATAATTTGCTAAAGGAGTAGAGGTAAACAAATTTATTAAA-
AT3G45870               ---------------AACTATGGTCTCTTGA-----CATGGTCAAATAAGATCTTGGGTC
TraesCS6B02G298700      ---------------AATACTGGTTTATTGA-----CATGGTCCAACAAAATTCTGGGCC
TraesCS6A02G271500      ---------------AATACTGGTTTATTGA-----CATGGTCCAACAAAATTCTGGGCC
TraesCS6D02G251700      ---------------AATACTGGTTTACTGA-----CATGGTCCAACAAAATTCTGGGCC
                                       **        *  * *         *   ** **  *  *     

TraesCS7A02G409900      CATCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCC-----TCTC
TraesCS7B02G309300      CTTCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCC-----TCTC
TraesCS7D02G403100      CATCTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCC-----TCTC
TraesCS3D02G003600      -------AGTGGTGCAATGCAA-------CAACCTGTACACCTCTCTCTCTGTCAGGATC
AT3G45870               CTTCCTTGGTTGCTCTCTATAATCCTCTTCAACCCGCAGCCTCAGCTTTCT-----TGTC
TraesCS6B02G298700      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCT-----TGTC
TraesCS6A02G271500      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCT-----TGTC
TraesCS6D02G251700      CAGCTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCT-----TGTC
                                ** *  *  *  *        ** ** *    *    *  **        **

TraesCS7A02G409900      AACTCTTTTTCTTGGTACCCC-------------------AATCTATCTA----------
TraesCS7B02G309300      AACTCTTTTTCTTGGTACCCC-------------------AATCTATCTA----------
TraesCS7D02G403100      AACTATTTTTCTTGGTACCCC-------------------AATCTATCTA----------
TraesCS3D02G003600      ACCGATCTGCACCAGTACTCCTTTAGCAAACTATAGTATTATTTTATTCAGTGTAAATAT
AT3G45870               CAGAATCTTCCTTGGAAGCCC-------------------TATCTACTTG----------
TraesCS6B02G298700      AGTGCTCTTTCTGGGCAGTCC-------------------AATTTATTTC----------
TraesCS6A02G271500      AGTGCTCTTTCTGGGCAGTCC-------------------AATTTATTTC----------
TraesCS6D02G251700      AGTGCTCTTTCTGGGCAGTCC-------------------AATTTATTTC----------
                             * *      * *  **                     * **              

TraesCS7A02G409900      -----------------GGAAGGTATGGACC--------------------------AAC
TraesCS7B02G309300      -----------------GGAAGGTATGGACC--------------------------AAC
TraesCS7D02G403100      -----------------GGAAGGTATGGACC--------------------------AAC
TraesCS3D02G003600      ACATCAAGTCAGTGAGTGGAAGGCATGATGATCCATGTCTCAGATCTTA--------AGC
AT3G45870               -----------------GGGAGGT-----------------------------------T
TraesCS6B02G298700      -----------------GGAAGGTAAGAGTATGTTTATCATATGTTCTACTCTTTAGAGT
TraesCS6A02G271500      -----------------GGAAGGTAAGAGTATGTTTATCATATGTTCTATTCTTTAGAGT
TraesCS6D02G251700      -----------------GGAAGGTAAGAGTATGTTTATCATATGTTCTACTCTTTAGAGT
                                         ** ***                                     

TraesCS7A02G409900      CAACAC-------TCTACCCTATCTG---------CTATTTTAACACTGTGACATCATGA
TraesCS7B02G309300      CAACAC-------TCTACCCTATGTG---------TTATTTGAACATTGTCACATCATGA
TraesCS7D02G403100      CAACAC-------TCTACCCTATGTGTTATTTGAATTATTTGAACATTGTCACATCATGA
TraesCS3D02G003600      TGCTGCTTGCT--TTTGACTCTCAAG---------AGATATGGAAATGATTATGCAAA--
AT3G45870               TAATATC------TCTCTCCTTTTCT----------------------------------
TraesCS6B02G298700      TAACCTTTTCCATTTTATCCTTTCTT---------TGAAGTGAAAAATACTTTTCCAGAC
TraesCS6A02G271500      TAACATTTTCTA-TTTATCCTTTCTT---------TTAAGTGAAAAATACTTTTCCAGAC
TraesCS6D02G251700      TAACCTTTTCTA-TTTATCCTTTCTT---------TGAAGTGAAAAATACTTTTCCAGAC
                                     * *  *                                         

TraesCS7A02G409900      GTTGTT-AGTTTCCGGTCATTCGAATTGGTCATTTCGCATTGT--GTTTATCAG------
TraesCS7B02G309300      GTCGTCAAGTTTCGGGTAATTCGAATTGGTTATTTTGCATTGT--GTTTATCGG------
TraesCS7D02G403100      GTTGTCAAGTTTCGGGTCATTCGAATTGGTCATTTTGCATTGT--GTTTATCGG------
TraesCS3D02G003600      --TGTAAGCTGGCTGCTGACATGGCAAATGAAAACGGTAATATATAATATGCAGGGCTTC
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTCTTCTACTTACTTG----TTAATTTGTGTATGTAGTA-TGTAGGATATGCAC------
TraesCS6A02G271500      CTCTTCTACTTG--------TTAATATGTGTATGTAGTAATGTAGGATATGCAC------
TraesCS6D02G251700      CTCTTCTACTTACTTG----TTAATATGTGTATGTAGTAATGTAGGATATGCAC------
                                                                                    

TraesCS7A02G409900      ------TTGAGCTTGGTACTCTTTCAA---------TACCACCGTAATGGTGATGGTGCT
TraesCS7B02G309300      ------TTGAGCTTGGTGCTCTTTCAAGCAAAATGGTATGAC-ATAATGGCAATGGTGCT
TraesCS7D02G403100      ------TTGAGCTTGGTGCTCTTTCAAGCAAAATGATATGAT-ATAATGGCAATGGTGCT
TraesCS3D02G003600      ATCGCCTCCGGCGTGGCGTTCGCAGTGCAGATATGGTGCATCGACCGCG-----GGGGCC
AT3G45870               ------CTTAGC----TATTCT----------------CAGCCATCAACGGGATG-----
TraesCS6B02G298700      ------ATTGATGTCTTGTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCAA
TraesCS6A02G271500      ------ATTGATGTCTTGTTCTATTTGACCATCTGATAAAGTGATAATCTGAAAGGTCGA
TraesCS6D02G251700      ------ATTGATGTCCTGTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCGA
                                           **                                 *     

TraesCS7A02G409900      TGG----AGCTGATGTTGTTTTCCATGGATGCCGTTACTGA--AATTTGA-TGTTTCTTT
TraesCS7B02G309300      TGGCGTAAACTGGTGTTGTTTTCCATGGATACCGTTACTGA--AATTTGACTTTTTTTTT
TraesCS7D02G403100      TGGCGTAAACTGGTGGTGTTTTCCATGTATACCATTACTGA--AATTTGA-CTTTTCTTG
TraesCS3D02G003600      CGGT----GTTCGTGGCCGTG--------------TACCAGCCCGTGCAG----ACGCTC
AT3G45870               TGTCTGAAGTT------------------------TCCTAACTAACTAGGCTTTTTTCTC
TraesCS6B02G298700      TAGTCTAAGTTTCTAACATAT------------GGTAATAA--AGTA-------ATTCTT
TraesCS6A02G271500      TAGTCCAAGTTTCTAACATTG------------ATTATTAA--AGTTCAG-TTTTTTTTC
TraesCS6D02G251700      TAGTCCAAGTTTCTAACATTG------------ATTAATAA--AGTACAGTTTTTTTTTC
                                  *                        *                      * 

TraesCS7A02G409900      ATTA-----------GTTTGCC---------TGCTATAGAATTCCCACGAATTTATGCAG
TraesCS7B02G309300      ATTA-----------GTTTGCCTCACTTATGGGCTATAGAATTCCCACGAATTTATGCAG
TraesCS7D02G403100      GTTA-----------GTTTGCCTCACTTATAGGCTACAGAATTCCCACGAATTTATGCAG
TraesCS3D02G003600      GTCGTCGCCATCATGGCCTCCC------------------TCACCCTCGGCGAGAAGTTC
AT3G45870               CTC---------------------------------------------------------
TraesCS6B02G298700      TTTGTAGCAATAAATGTTTACC-----------------ATCTCTTTTGATCTGAAGT--
TraesCS6A02G271500      TTCATAGCAATAAATGTTTATC-----------------ATCTCCTTTGATCTGAGGTAT
TraesCS6D02G251700      TTCATAGCAATAAATGTTTATC-----------------ATCTCTTTTGATCTGAGGTAT
                         *                                                          

TraesCS7A02G409900      AACTAAATGCCCACCT-------TACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCT
TraesCS7B02G309300      AACTAAATACCCACCTTGTGAACTACTTGCAGCCTCATTGGAGGAGTCTTCATCATTGCT
TraesCS7D02G403100      AACTAAATACCCACCTTGTGCACTACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCT
TraesCS3D02G003600      TACC---------------------TCGGCGGGATCATCGGTGCCGCGCTCATCATCACC
AT3G45870               ---------CTCTCTT--------------AGCATTTTAGGCGGATGTGCAATCATAGCA
TraesCS6B02G298700      AATC---TGCTCTGTT-------TGCTTGCAGTATTATTGGAGGGTTTCTAATCATCTCT
TraesCS6A02G271500      AATC---TGCTCTGTT-------TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCT
TraesCS6D02G251700      AATC---TGCTATGTT-------TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCT
                                                       *  *  * ** *        *****  * 

TraesCS7A02G409900      GGTCTATACCTGGTTACTTGGGCCCGTTACAATGA-------------GGCGCAGAGAAT
TraesCS7B02G309300      GGTCTATACCTGGTTACTTGGGCCCGTTACAATGA-------------GGCGCAGAGAAT
TraesCS7D02G403100      GGTCTATACCTGGTTACTTGGGCCCGTTACAATGA-------------GGCGCAGAGAAT
TraesCS3D02G003600      GGCCTCTACCTCGTGCTCTGGGGCAAGAGCGAGGAGAGGTCGCGCATCGGCAAGGAGGCG
AT3G45870               GGTCTTTATAGTGTCACCTGGGCATCTTACAAAGA------------------AAAGAAA
TraesCS6B02G298700      GGTTTATACATTGTCACCTGGGCACGACATCGAGA------------------AAAGTTG
TraesCS6A02G271500      GGTTTATACATTGTCACCTGGGCGCGACGTAGAGA------------------AAACTTG
TraesCS6D02G251700      GGTTTATACATTGTCACCTGGGCGCGACGTAGAGA------------------AAAGTTG
                        **  * **    **    ****           **                    *    

TraesCS7A02G409900      ACTGATGTCTGGTTATCTGAATCCTCTTCTGGTGGAGGTGGAGGATGCGC-CAGCTCCCA
TraesCS7B02G309300      ACTGATGTCTGGTTATCTGAATCCTCTTCTTGTGGAGGTGGAGGATGCGC-CAGCTCCCA
TraesCS7D02G403100      ACTGATGTCTGGTTATCTGAATCCTCTTCTTGTGGAGGTGGAGGATGCGC-CAGCTCCCA
TraesCS3D02G003600      GCCGCCGCATCGGCAGCTTCCTCC---------GGCAGCGGCGAGCGCGA---GGTCCGG
AT3G45870               GCGGCAGCAGCAATGGCT------------------------------------------
TraesCS6B02G298700      ACTGCCACTGGAGTACCTTA------------------TGTAAAATGCGCATCGGAGCCA
TraesCS6A02G271500      ACTGCCACTGGAGTACCTTA------------------TGTAAAATGCGCATTGGAGCCA
TraesCS6D02G251700      ACTGCCACTGGAGTACCTTA------------------TGTAAAATGCGCATTGGAGCCA
                         * *            **                                          

TraesCS7A02G409900      AGAGACAGG--------------------AAAATTCCAGCTCAATTGATC-----CCTAA
TraesCS7B02G309300      AGAGACAGG--------------------AAAATTCCAGCTCAATCGATC-----CCTGA
TraesCS7D02G403100      AGAGACAGG--------------------AAAATTCCAGCTCAATTGATC-----CCTGA
TraesCS3D02G003600      AGCGCCAAGCTGGCCTCCTCCATCACCCAGCCTCTCCTGCCGCCCTCCTCCACCACCTCC
AT3G45870               -----------------------------GTGATCCCGATCA-------------CCTCA
TraesCS6B02G298700      TGTGACAGT--------------------GCTTCTCAAGTCATAAAGGGCGGTAACTTGA
TraesCS6A02G271500      TGCGACGGT--------------------GCTTCTCAAGTCATAAAGGGCGGTAACCTCA
TraesCS6D02G251700      TGCGACGGT--------------------GCTTCTCAAGTCATAAAGGGCGGTAACCTCA
                                                           *                   * *  

TraesCS7A02G409900      GACTCGGAGG-AGAGATGACTCTGTTATTTTTCCA-------GAACAGCAGCAGCAGAAT
TraesCS7B02G309300      GACTCGA--CGAGAGTCCACTGTGTTTTTTTTTTTTTCATAACAGCAGCATCAGCAGAAT
TraesCS7D02G403100      TACTCAGACGAAGACTCCACTGTGTTTTTTTTCCA-------GAACAGCAGCAGCAGAAT
TraesCS3D02G003600      GACAACGTCTGAAA-----CTTAATTGCTACCT----------AGCTACCGTCGCTTCTC
AT3G45870               A-----------------------------------------------------------
TraesCS6B02G298700      GCCCCAGGCC---------CTTTATATCCCTTTCC-------AGGCTGTGG---------
TraesCS6A02G271500      GCCCCAGGCC---------CTTTATATCCCTTTCT-------AGGCTTTGG---------
TraesCS6D02G251700      GCCCCAGGCC---------CTTTATATCCCTTTCT-------AGGCTGTGG---------
                                                                                    

TraesCS7A02G409900      TACGTTGTATATTAGTATCAGAAAGCTTG-----TATTTACCTTCTC-------TACCA-
TraesCS7B02G309300      TACGTTGTATATTAGTATCAGAAAGCTTG-----TAGTTACCTTCTC-------TACCA-
TraesCS7D02G403100      TACGTTGTATATTAGTATCAGAAAGCTTG-----TAGTTACCTTCTC-------TACCA-
TraesCS3D02G003600      AACG------ATGGATTGTGAGGAGTTTT---CTTGTTTAAAT-----------------
AT3G45870               -------------------AGGAAGCTGA-------------------------------
TraesCS6B02G298700      AATGTGCCACATGAATCTTGAGAAGCTGGTGTTTTATGCAACTTATGCTAGGTATCTCAC
TraesCS6A02G271500      AATGTGCCACATGAATCTTGAGAAGTTGG---TCTACGCAACTTCTGCTAGGCATCTGC-
TraesCS6D02G251700      AATGTTCCACATGAATCTTGAGAAGTTGGTGATCTATGCAACTTCTGTTAGGTATCTCC-
                                               ** *                                 

TraesCS7A02G409900      -------TTGGATTAAGTTACAT--------CTCATACCCAAATACCCTCAACATAAGCT
TraesCS7B02G309300      -------TTGGATTAGGTTACATCATTAAGGCTCATACCCAAATACCCTCAACATAAGCT
TraesCS7D02G403100      -------TTGGATTAAGTTGCATCATTAAGGCTCATACCCAAATACCCTCGACATAAGCT
TraesCS3D02G003600      -------TCAGGCGGGCATGCAT-----------------GCACGCCTATGGTGT-----
AT3G45870               --------------------------------------------ACCCTTGATCT-----
TraesCS6B02G298700      TATCTCCTTTGATGAGTAAAAAT--------------ACATAATGCATTAGATGTTGG--
TraesCS6A02G271500      -------TTTGATGAGGAAAAAT--------------ACAGAATGCATTAGATGTTAG--
TraesCS6D02G251700      -------TTTGATGAGTAAAAAT--------------ACAGAATGCATTGGATGTTAG--
                                                                     *        *     

TraesCS7A02G409900      GGAATGGAAATGGGTCGCAATTATCGTTCTCCTAGCAGCCGCAGAAGAT-----------
TraesCS7B02G309300      GGAATCGAAATGTGTCGCAATTATCGTTTTCCT------------AGATGCTATTGGCAC
TraesCS7D02G403100      GGAATGGAAATGTGTCGCAATTATCGTTCTCCTAGCAGCCGCGGAAGATGCTACTGGCAC
TraesCS3D02G003600      ---GGTGAGCGAGTATGCAG-----------------------ACGGATTTGATTAAAAC
AT3G45870               -------ACAAGGACCATAA---------------------AAACAAACCAATAGGACAT
TraesCS6B02G298700      ---GAAGAGAAGTGCTGCAG----------------------AGAAGATTGTACTGACGA
TraesCS6A02G271500      ---GAAGAGAAGTGCTGCAG----------------------AGAAGATTGCACTGAAGA
TraesCS6D02G251700      ---GAAGAGAAGTGCTGCAG----------------------AGAAGATTGCTCTGAAGA
                               *          *                            *            

TraesCS7A02G409900      --GCTAACGATGT-GCGATGATAGTTCAGTTTCAACAGTTGTCTTCATGGGTC-----AA
TraesCS7B02G309300      TGGCTAACGATGT-GCGATGATAGTTCAGTTTCAGCAGTTGTCTTCATGGGTC-----AA
TraesCS7D02G403100      TGGCTAACAATGT-GCAATGATAGTTCAGTTTCAGCAGTTGTCTTCACGGGTC-----AA
TraesCS3D02G003600      TAGCTAGGATTGTTTGGATCGTGCTTGATTAT-----GGTGTGTGCATT---------AA
AT3G45870               CTATTCACAAAAT------------------------------CTCCCATCTCTTCACCA
TraesCS6B02G298700      TTGGTAATGATGTTGGCATCTGTGTCGGCTGCAGAAAATCATACTCTCAGACCTTCCATA
TraesCS6A02G271500      TTGTTAACGATGTTGGCATCTGTGTCCTCTGCAGAAAATCATACTCTCATACCTTCCATA
TraesCS6D02G251700      TTGTTAATGATATTGGCATC-----------------ATCATAATCTCATACCTTCCATA
                            *       *                                *             *

TraesCS7A02G409900      GGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCGAACCCAACTTGTTAATAGTTCAT
TraesCS7B02G309300      GGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCGAACCCAACTTGTTAATAGTTCGT
TraesCS7D02G403100      GGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCCAACCCAACTTGTTAATAGTTCAT
TraesCS3D02G003600      GG------CTTGTCAATTGGAGTAGATCA-------GAAAACTTGTGCTTGATGTATTGG
AT3G45870               AAA-----TCCGATGATTGAACAAAAACT----------------------CTGGCTTCT
TraesCS6B02G298700      GGAGCAGTTAGGTTAATTTAGGCAAAAGA-------GAAGCCATGCTCATTCTGCTTTTT
TraesCS6A02G271500      GGAGCTGTTAGGTTAATTTAGACAAAAGA-------GAAGCCATGTTCATGCTGTTTTTC
TraesCS6D02G251700      GGAGCAGTTAGGTTAATTTAGACAAAAGA-------GAAGCCATGTTCATCCTGTTTTTC
                                       **        *                          *   *   

TraesCS7A02G409900      TAGTTATCATCGTAATTGCTTAATTGGCATATGGCTGCCATGATTGCTGGTGTTAAC--T
TraesCS7B02G309300      TAGCTATCATTGTAATTGCTTAATTGGCATATGGTTGCCATGATTGCTGTTGTTAAC--T
TraesCS7D02G403100      TAGTTATCATCGTAATTGCTTAATTGGCATATGGCTGCCATGATTGCTGCTGTTAAC--T
TraesCS3D02G003600      TACCC-------TATCTA---------------------ATGATTATTACTATCA-----
AT3G45870               TGAAT---------------TACTTGGG----TGCTCCGATGTTT-----TCTTAAC---
TraesCS6B02G298700      CAGAC-------TAACAAC--ATTGAGGATGCTGAGTTGATGATT----CTATTACCAAA
TraesCS6A02G271500      TAGGC-------TAACAACACACTGAGGATGCTGAATTGATTATT----CTATAACCAAA
TraesCS6D02G251700      TAGAC-------TAACAAC--ATTGAGGATGCTGAATTGATGATT-CTTCTGTAATCAAA
                                                               **  **     * * *     

TraesCS7A02G409900      TGCATTTTATCTTCTGCTTCAGCAGCCTCTATTACTGTCTGGGATCTGACTC--TGCAAT
TraesCS7B02G309300      TGCATTTTATCTTTTGCGTCAGCAGCTTCCGTTACTGCCAGGGCACCGACTC--TGCAAT
TraesCS7D02G403100      TGCATTTCATCTTCTGCTTCAGCAGCCTCTATTACTGCCTGGGAACCGACGC--TGCAAT
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGCAAGGTAGCACC------------------------------ACCGACTTTGTGAAAT
TraesCS6A02G271500      TGCAAGGTAGCTCC------------------------------ACCGACTTCGTGAAAT
TraesCS6D02G251700      TGCAAGGTAGCTCC------------------------------ACCGATTTCGTGAAAT
                                                                                    

TraesCS7A02G409900      ACAGTACAA-ACAAACTGTTCTTC----------GTTGATTTTCGTAATGCCATACTTGC
TraesCS7B02G309300      ACAGTATAAGACAAACTGTTCTTCTGTGATGATTTCCAATTTTCATCGTGCCATACTTGC
TraesCS7D02G403100      ACAGTATAAGCCAAACTGTTCTTCTGTTATGATTTCCAATTTCCGTCATGCCATACTTGC
TraesCS3D02G003600      -CAATAG---------GGTTTGTTCACTATGGATTCTA-------------CGTACTTA-
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACAATAGTA-------TGTATATCCCGTGAAATCCCTA-------------CATACATAC
TraesCS6A02G271500      CCAGTAGTA-------TGTATATCCCGTGAAATCCCTA-------------CATACATAC
TraesCS6D02G251700      CCAATAGCA------------------------------------------TGTACATAC
                                                                                    

TraesCS7A02G409900      GAAGCAATTATGTCTGGAGCTCAGTGCATAA-GTGGGAAAAATCAAAGTAGGAGTTCCAA
TraesCS7B02G309300      AAAGCAATTATGTCTGGAGCT--------------GGAAAAATCAAAGTAGGAGCTCCAA
TraesCS7D02G403100      GAAGCAATTATGTCTGGAGCTCAGTGCATAA-GTTGGAAAAATCAAAGTAGGAGCTCCAA
TraesCS3D02G003600      ---------ATGTCTACATCG---------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATATGTATAAACTCTGTAGCCAGTGAGGTCATGTGTGTAGAACTTTGAGAGAAATGTTTT
TraesCS6A02G271500      ATATGTATGAACTCTGTAGCCATTGATGTCATGTGTGTAAAACTTTGAGAGAAATG--AA
TraesCS6D02G251700      ATATGTATGAACTCTGTAGCCATTGAGGTCA--TGTGTAAAACTTTGAGAGAAATG--AA
                                                                                    

TraesCS7A02G409900      ATTCTTTGGCA--CATCAGGCCGCTCGAGTGTTCTTACTTTGCTTC--------------
TraesCS7B02G309300      ATTCTTTGGCA--CATCAGGCCGCTGGAGTGTTCTTACTTTGCTTC--------------
TraesCS7D02G403100      ATTCTTTGGCA--CATCAGGCCGCTTGAGTGTTCTTACTTTGCTTC--------------
TraesCS3D02G003600      ---TTTTTGCA-------------------ATCAGTAATTAAGTGC--------------
AT3G45870               ---CTTTTGCCGACGAGAGA----------GTGACTATTTTATTTTCTAA----------
TraesCS6B02G298700      ACTCTCTTACATCTGTTAAGTTCTTGTA--GTTCATGCCTTGTTTCATACTACTACTCGA
TraesCS6A02G271500      ACTCTCTTATC--TGTGAAGTTCTCGTA--GTTCATACCTTGTTTCGT------------
TraesCS6D02G251700      ACTCTCTTACC--TGTGAAGTTCGTGTA--GTTCATACCTTGTTTCGTACTACTACTCAA
                            * *                        *   *   *   *                

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGAGTTAGCAATTCTGCAGGCTGGACGTGTGTTGCAAGTATTTTCCAGGCTGTTTTTTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGAGTTGGCAATTCTGCAGTCTGGACGCGTGTTGCAACTATTTTTCAGGCTGTTCTTTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TA------CTGCAGGTATGTTTTTCACCAACAATTCTTTCTTGTAAACATGTAAATGCTA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CACTGCACCTGCAAGTATGCTTTTCACCAATAGTTCGTTCTTGCAAACATGTAAATGCTA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CACATGAGATGACCTATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTACCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CACATGAGATGACCTATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTACCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATGCACCACTCTATTGGTCTACTATTATACATCGTGGCGCGCAATCTATGGCGCGGAAAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATGCACCACTCTGTCGGTCTACTATTGTACATTGTCGCACGCAATCTATGGCGCGGAAAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATCGAACGTGTTGGCGTGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATCGGACGTGTTGGCATGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGAGTGACGAATAGGCCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGCGTGACGAACAGGCCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACGATGTCCAGGTCGGGCGACTGCGCGTCCATCACCACGAACCTGTTGTCGCCGGTGCCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGATGTCCAGCTCGGGCGCCTGCGCGTCCATCACCACGAACCGGTTGTCGCCGGTGCCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCGTCGTGCACGTAGCACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCGACGTCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCGTCGTGCACGTAGCACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCAACGTCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCAGGGACGAAAAACGGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCGGGGACGAAGAACGGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGCAGTCGCCGTGGCCAGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGCAGTCGCCGTGGCCGGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATGGGGTCGCCAACACCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCTCGGGTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATGGGGTCGCCCACGCCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCCCGGGTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATCACCCCGAAGTCGAGGTTCGCCGCCGCGAGCGGCGTGCGTGTGACGTTGCCGGTGCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATCACGCCGAAGTCGAGGTTCGCCGCCGCGAGCGGCGTGCGGGTGACGTTGCCGGTGCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGTTGATGCGCACCAGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGGTTGATGCGCACCAGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCGATGGACAGGATGTTGGGTGCCACCATCACGATCTCGTCGCCGCCGGCCTCCTCCCAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCGATGGACAGGATGTTGGGCGCCACCATCACGATCTCCTCGCCGCCGGCCTCCTCCCAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGTTCACCGAGTGCATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACTCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGTTCACCGAGTGCATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACTCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCCGCGGCGTACTTGGGGATCACGCCGAGGCGAGGCACCATGCCGGGGTCCGCCCCGACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCCGCGGCGTACTTGGGGATCACGCCGAGGCGTGGCACCATGCCCGGGTCCGCCCCGACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGCGAGCCGCCGCCCACCACCATGCCCATGGGGTTCATCACGATTTGTATCTCCGGGAAT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGCGAGCCGCCGCCCACCACCATGCCCATGGGGTTCATCACGATCTGTATCTCCGGGAAT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATCGCATAATGCTCCGTCACGGCGAAGTCGTGCAGGAAAGACGGTTGCTTCACGGAGAAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATCGCATAATGCTCCGTCACGGCGAAGTCGTGCAGGAATGACGGCTGCTTGACGGAGAAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATGGGCACGTCGGCGCCCTTGTTCCCTGCAGGGTCGAACCGGAAATAGGTGACGAACGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATGGGCACGTCGGCGCCCTTGTTCCCTGCCGGGTCGAACCTGAAGTAGGTGACGAACGGT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGCATGGGGCCGTAGCGGAACGCGAAGAGCTCGCCGGTGATGGGGTCCTTCTTGGGGTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGCATGGGGCCGTAGCGGAACGCGAAGAGCTCGCCAGTGATGGGGTCCTTCTTGGGGTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGGTCATGCCCATGCTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGGTCATGCCCATGCTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGGTGGCCGGGTCGACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGTGCGTAGAGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGGTGGCCGGGTCGACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGCGCGTAGAGG
                                                                                    

TraesCS7A02G409900      ----------------------TGTTGTATCTGCCTTCCACTGTT------------GTG
TraesCS7B02G309300      ----------------------TGTTGTATCTGCCTTCCACTGTTGTGCCTCTTGCGATG
TraesCS7D02G403100      ----------------------TGTTGTATGTGCCTCCCTCTT--------------ATG
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CGGCCGCCGAAGACGGCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGCCGCCGAAGACGGCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATC
                                                                                    

TraesCS7A02G409900      TAAATTGTTGGCA-----------------------------------------------
TraesCS7B02G309300      TAAATTGTTGACA-----------------------------------------------
TraesCS7D02G403100      TAAATTGTTGGCA-----------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGGCCTGTCAGCACCCTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCGTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGGCCTGTCAGCACCCTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCATGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AAGCCGGAGAAGACGTTGGGCAAGACCGGCTCGCCCGCGTTGCGCTCCACGATGTACTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AACCCGGAGAAGACGTTGGGCAAGACCGGCTCGCCGGCGTTGCGCTCCACGATGTACTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TACGTCTGCACGTAGCGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TACGTCTGCACGTAGCGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGGAGTGCAGCATGCCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGATGCTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGGGAGTGCAGCATGCCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGGTGCTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GGGTTGGGCCCGTTGCGGATGTAGGCGCCGCCGGCGAGGCAGCGCGGGATGACGCCGCGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGGTTGGGCCCGTTGCGGATGTAGGCGCCACCGGCGAGGCAGCGCGGGATGACGCCGCGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCACGGGGCAGGGCGTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCACGGGGCAGGGCGTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGCCGCGGGTCCACCGACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGCCGCGGATCCACCGACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCCAGCGCGTTGCAGAACGCCGCCTGTAGCGAAGTGACGGGCCGGCGGCGAGGCCTGGAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCCAGCGCGTTGCAGAACGCCGCCTGTAGCGAAGCAGTAGGCCGGCGGCGAGGCCTGGAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GACCGAGCCGCCTGGCGCGGCGCATCGGATGCCCTGCTCGTTCTCGCGGTAGCAACTCGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GACCGA------------GGCGCATCAGACGGCCTGCTCGTTCTCGCGGTAGTCACTCTT
                                                                                    

TraesCS7A02G409900      --------------------------------CGGTTACAAAACAATCTTGTGTTGCCCA
TraesCS7B02G309300      --------------------------------CGGTTAGAAAGCCATCTTGTGTCGCCCA
TraesCS7D02G403100      --------------------------------CGGTTACAAAACCATCTTGTGTCGCCCA
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTACCAGTTGCATTGTTCACGGACGTGTCGACCAGGTGCTCTTCCGTTTCTTGTTGCTCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTAGCACTTACATTGTTAGTCGACGTGTCGACCAAGTGCTCTTCCGTCTCTTGTTGCTCG
                                                                                    

TraesCS7A02G409900      ACTGCTTATGTT------------------------------------------------
TraesCS7B02G309300      ACTGCTTATGTT------------------------------------------------
TraesCS7D02G403100      ACTTATGTTTTAGGGTATGTTTAGTTTGTGCCCAAGGTTGCCCCACCAAAGCATTGGCTG
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCGGCTTGGGCGGCGAGGTGAGGACGGTGGCGGTGGCGGCAGCCCACGGCGGCGGGGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCGGCTTCGGCGGCGAGGTGAGGACGGTGGCGGTGGCGGCAGCCGACGGCGGCGGGGGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GTTGAGGTTTTGGTTGCCCATGATTTGGCAACATTGGTAAGAAAAATGAACTAGAGTTGG
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GACGTGCCCTTCCTCCTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCGGGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GACGTGCCCTTCCTCCTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCAGGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      CTAGAGTTCATTTGGCATGCCAAAAATTTGGCAACCATCCAAACAAAGACCAATCTTTGG
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GAGATGT-----------------AGGAGAGCCTCCTCGATCTCGCAGCATGAGCAGCAT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GAGATGT-----------------AGGAGAGCCTCCTCGATCTCGGAGCATGAGCAGCAT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------TTACCCCCTTTG
TraesCS7B02G309300      ------------------------------------------------TTACTCCCTTCG
TraesCS7D02G403100      GTCCAAAATTTTGATAAGGTGCACTTTGGCCACAATCCAAACACACCCTTACTCCCTTCG
TraesCS3D02G003600      -----------------------------------------------------CCCTCTG
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGGCTTTGGCAGGGTAGAGATCAGGCATGCTGAAGTTGGAGGTGACAAGTGCTCCCTCCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGGCTTTGGCGGGGTAGAGATCAGACATGCTGAAGTTGGAGGTGACAAGTGCTCCCTCCA
                                                                                    

TraesCS7A02G409900      CTTGTATATAGAGAAATTTTATTGTGTTTGTTCTTCCATATATTTGTGAACGGTGGTAGT
TraesCS7B02G309300      CTCACTATTATGAGATGTTCTAACTTTTTCCTGATTTGTATGTATATAGACAAATTTAGT
TraesCS7D02G403100      -TCACTATTATGAGATGTTCCAACTTTTTTCTGAT-------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTGTTA-------GTGGATGAGTAGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTACTA--------------GTGGAT
                                                                                    

TraesCS7A02G409900      ACTTGGACAT--------------------------------------------------
TraesCS7B02G309300      ATTTGTTCTTCCATATACTGTGAACCGAACGGA---------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AATTTCTTTGTTGGAACTTGGAACCCAGGTGAGTAGCAGCAAACGCTGATACCAGTTCGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AACTAGCAATTTTTGTGTTGGAACCCAGGTGAGTAGCAGCAAATGCTGACACCAGTTCGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGCTACTGCCTTT----------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACACTACTGCCTTTGCTACTTGTATGCTATGGCTATATATAGCCTCGGTAAAAGGCAAAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTACCTGGTGGAAATGTTTATTTGGTGAAAACTTCAAAGATTACGTGGACCGCTGGATCA
                                                                                    

TraesCS7A02G409900      -------------------------------------------
TraesCS7B02G309300      -------------------------------------------
TraesCS7D02G403100      -------------------------------------------
TraesCS3D02G003600      -------------------------------------------
AT3G45870               -------------------------------------------
TraesCS6B02G298700      -------------------------------------------
TraesCS6A02G271500      -------------------------------------------
TraesCS6D02G251700      CAGCGACCGCACAATGTGGGAGGATGAAGAGTTGCGCTAGGGT
                                                                   
