CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS7A02G409900      --------------AGCAAACGGGGCAGCTCACGCCAACCGGCACAGTGTCTACATTCCT
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      -AGTCGTTCCCCAAGACAAATGGAACAGCTCACGCTACTCATGGCAGCGACCGTACTGCA
TraesCS3B02G011600      TCGGCGTATGCCCATGCACCAAGGTCTTCTCCGACCAACCATGGCTCACTTCAC------
AT3G45870               ----------------TAAATAGGATCAATCCCAAT------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      -------------------ATGGGG-----------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      TACT-----------------------------------------CCGTATGGTTGCGTG
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GCATGTGATGTGCTACTGCAGAGGATCCTAACCCCTGCATACGGGCAGGTTGCGTGCGTG
TraesCS3B02G011600      --------------------------------------------------TGTCTGCCTC
AT3G45870               ---------------------------------------------GCATGCTTGTGTCCG
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      GAGCCAGAAGCCACCG-CAG----CCTTTCCCCAATAAGTCCGCCACACGACG------G
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GAGCCAGCAGCCACCGGCCGCATACCTTCCCCCAATAAATCCGCCAC------------G
TraesCS3B02G011600      TAGCTGAGTGTCA------------CTCTCTGTAGCATGCTCACCTACTGACG------T
AT3G45870               AAGCATGATGTCATCA-TTTGTTAGTTCCCCTGTCTCGTTCGATCAAAAAACACGTTTTG
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------AAATCACCTAAAAAACA------G
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CCGGCAGAGCCGCAGAGGCAGACACCACAATCAGGGGCCGGTGACATCGCCGTCCATCGC
TraesCS7B02G309300      --------------------------------GAGATTCGCTTCTCCTAGTC--------
TraesCS7D02G403100      ACGGCACGCAGGCGAAA---------AATCTGGAGTTTTGCTTCTCCTAGTCGTC-----
TraesCS3B02G011600      CCAAGTGGAATGTCGCG--------CGTCTATATAGCTAGACACCCCTGGTTGCACTCCT
AT3G45870               ACAGAAGAGATTCAAAGTGACA-ATCAGTTTCAAGATTTAATTCTCTTACCCACTCTCTC
TraesCS6B02G298700      -------------------------------GAAAGTTCAAAG-----------------
TraesCS6A02G271500      TGGGGAAAAGTCCTAAAAAAAACAGTGGGGAAAAGGTTCAAAG-----------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      AGAAAAGTCCAGGTGAGATAGAGAGAGAGATCTTTCTCCGAGCTCAGCCAGCTAGGCTCC
TraesCS7B02G309300      ---------------------------GGAGCCTCGTCGGAGCCCAGCAAGGC-------
TraesCS7D02G403100      ------------------------------GCCTCGTCGGAGCCCAGCAAGAC-------
TraesCS3B02G011600      CACTCACCTCATCCCTGGCCTAGGCCTTCCTCTCTCTAGTCTCTCATCGCCAC-----CT
AT3G45870               ACCC--------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      CGCGGTAGCAGTAGCGCCTAGC--GGCCGGCGTG--------------------------
TraesCS7B02G309300      ------TGGAGTAGTGCCCAGC--GGCCGGCGCGAGAGGGAGTC----------------
TraesCS7D02G403100      ---TGCTGGAGTAGTGGCTAGC--GGCCGGCGCGCAGAGAGAGCGAGAGAGAGACAGAGG
TraesCS3B02G011600      CGCTCCAGCAGCAGCTTCTATCTCGATCTA------------------------------
AT3G45870               --------------TGGCTTTCATAACTTTCTCC--------------------------
TraesCS6B02G298700      ------AGGAGTAGTCGCTACTCAGACCGT------------------------------
TraesCS6A02G271500      ------AGGAGTATTCGCTACTCAGACCGT------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      -----GAGAGAGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTG
TraesCS7B02G309300      AGAGAGAGAAGGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTG
TraesCS7D02G403100      AGAGAGAGAGGGGATGGGGACGGAGCCGACGATGCTGCAGCGGTGGTCGTCGTCGATGTG
TraesCS3B02G011600      -----GGGAGAGATCAAGTGAGGAGAGGGTGCAGCCATGGCG------------GACGCG
AT3G45870               -----GGGA---------ATAAGAATCGC-----------------------------CG
TraesCS6B02G298700      -----GGGA-----------------CGACGAC-------------------------CG
TraesCS6A02G271500      -----GGGA-----------------CGACGAC-------------------------CG
TraesCS6D02G251700      -----GGGA-----------------CGACGAC-------------------------CG
                             * **                  *                               *

TraesCS7A02G409900      GGGGAT--GAGCGGGCGCGAC--CGGCTGCGGCTGTGGGAGGACAAGGCGTG-GCGGGCG
TraesCS7B02G309300      GGGGAT--GAGCGGCCGCGAC--AGGCTGCGGCTGTGGGAGGACAAGGCGTG-GCGGGCG
TraesCS7D02G403100      GGGGAT--GAGCGGCGGCGAC--CGGCTGCGGCTGTGGGAGGACAAGGCGTG-GCGGGCG
TraesCS3B02G011600      GTGGAT--GCTCGCCGG-------------GTCTGCGGGATGCCGGAGAAGGCGCAGCTC
AT3G45870               GAAAAGAAGAAAACCGCCAATGGAGAGTACGGT----GGAAAGAGAGGCGTG-GAAAGCT
TraesCS6B02G298700      TGGGATCGGATCGGCGGCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAG-GCGGGCG
TraesCS6A02G271500      GGGGATCGGATCGGCGGCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAG-GCGGGCG
TraesCS6D02G251700      TGGGATCGGATCGGC-GCGATGGCGGCGGCGGC-GCGGGATGGGGAAGCGAG-GCGGGCG
                            *   *                     *      ***       *   * *      

TraesCS7A02G409900      CACGCGGGCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCC
TraesCS7B02G309300      CACGCGGCCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCC
TraesCS7D02G403100      CACGCGGCCATGGCCTTCACGCAGCTCGCCTACGGCGGCTACCACGTCCTCACCAAGTCC
TraesCS3B02G011600      CACGTGGCGATGCTGGCGCTGCAGTTCGGCTACGCCGGCTTCCACGTCGTGTCCCGCCTC
AT3G45870               CACGTGGCGATGATCGGTGTGCAATTGTTCAACGGAGGATATCATGTCATTACCAAAGTG
TraesCS6B02G298700      CACGCGGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAG
TraesCS6A02G271500      CACGCGGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAG
TraesCS6D02G251700      CACGCGGCGATGGTGGGGTCGCAGTTCATCAACGCGGGGTACCACGTCATCGCGAAGCAG
                        **** **  ***        ***  *   * ***  ** *  ** *** *  *       

TraesCS7A02G409900      GTGCTCAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTC
TraesCS7B02G309300      GTCCTGAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTC
TraesCS7D02G403100      GTCCTCAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGACCTCGTCGCGCTC
TraesCS3B02G011600      GCGCTCAACATGGGGATCAGCAAGCTCGTCTTCCCCGTCTACCGCAACATCATCGCGCTC
AT3G45870               GCTCTCAACGTTGGTGTAAACCAACTTGTCTTCTGTGTCTTTCGTGATCTCATTGCTCTC
TraesCS6B02G298700      GCGCTCAACGTCGGCGTCAACCGCGTTGTCTTCTGCGTCTACCGCGACCTCCTCGCGCTC
TraesCS6A02G271500      GCGCTCAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGACCTCCTCGCGATC
TraesCS6D02G251700      GCGCTCAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGACCTCCTCGCGCTC
                        *  ** *** * **  * * *    * ******   ****  **  *  ** * **  **

TraesCS7A02G409900      GCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTACGTCGCACTATCATCCCCATGC
TraesCS7B02G309300      GCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTACG------CACCGTACCATCCC
TraesCS7D02G403100      GCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTACGTCGTGCTAGGCGCCTCACC-
TraesCS3B02G011600      TTCCTCCTCGTCCCCTTCGCCTACTTCCTCGAG---------------------------
AT3G45870               TCCATTCTTGCTCCTCTTGCTTATATCCGTGA----------------------------
TraesCS6B02G298700      TGCGTGCTTGCTCCCATCGCCTTCTTCCGCCA----------------------------
TraesCS6A02G271500      TGCGTGCTTGCTCCCATCGCCTTCTTCCGCCA----------------------------
TraesCS6D02G251700      TGCGTGCTTGCTCCCATCGCCTTCTTCCGCCA----------------------------
                          * * ** *  **    ** *   ***   *                            

TraesCS7A02G409900      CCATGGCTGCTCTGATCTAGAGTTCTAGACCAATTGACATCGAATTTGACTAGACGCTAT
TraesCS7B02G309300      CCATGGCTGCTCTG--------ATCTGGACCAATTGACATCGAATTTGACTAGATACTAT
TraesCS7D02G403100      CCATGGCTGCTCTGCTCT---GATCTGGACGAATTGACATCGAATTTGACTTGATACTCT
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGCGGCTCGCCCG----------------------------------------------
TraesCS6A02G271500      CCGCGGCTCGCCCG----------------------------------------------
TraesCS6D02G251700      CCGCGGCTCGCCCG----------------------------------------------
                                                                                    

TraesCS7A02G409900      TCGGGTGCGGATTCTGAATTTCCCGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGC
TraesCS7B02G309300      TCGGGTGCGGATTCTGAATTTC-CGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGC
TraesCS7D02G403100      TCGGCTGCGGATTCTGAATATCCCGCAGGAGGGTGCGGCGCCCCGTCACCCCGCAGCTGC
TraesCS3B02G011600      --------------------------AAGAAGGACCGACCCAGGCTCACCCTCGGCCTCG
AT3G45870               -------------------------TAAGAGAACAAGACCTCCTTTGAATCGACAGTTTC
TraesCS6B02G298700      -----------------------CGCAGGCTCGTCCGCCGCCC-GTCACGCGTCGCCTCC
TraesCS6A02G271500      -----------------------CGCAGGCTCGTCCGCCGCCC-GTCACGCGTCGCCTCC
TraesCS6D02G251700      -----------------------CGCAGGCTCGTCCGCCGCCC-GTCACGCGTCGCCTCC
                                                  * *       * *      * *  *      *  

TraesCS7A02G409900      TCGGCTCCTTCGCGCTGCTTGGATTCACCGGGTAATTCCCCCACTCCTCCTCCTCCTCCT
TraesCS7B02G309300      TCGGCTCCTTCGCGCTCCTTGGGTTCACCGGGTAACTCTCCTC-----------------
TraesCS7D02G403100      TCGGCTCCTTCGCGCTCCTTGGATTCACCGGGTAATTTTCCCC---------CTCGTCCT
TraesCS3B02G011600      CCGTCCACTTCTTCTTCCTCGCCCTC----------------------------------
AT3G45870               TCTTAGCTTTCTTCTTCCTTGGTTTAACAGGGTAATTCAAGTTTTCT--TCTACCAGTTT
TraesCS6B02G298700      TTACCTCCTTCTTCTTCCTCGGGCTCACGGGGTAAGCCTGGCCACCCGGTCGCTCGGTGT
TraesCS6A02G271500      TTACCTCCTTCTTCTTCCTCGGGCTCACGGGGTAAGCCTGGCCACGCGGTCGCTCGGTGT
TraesCS6D02G251700      TTACCTCCTTCTTCTTCCTCGGGCTCACGGGGTAAGCCTGGCCTCCCGGTCGCTCGGTGT
                                ***    * ** *   *                                   

TraesCS7A02G409900      C-----------------------ATGCTGCTGCTGCTACTGCTGATGCCCGATGGAGC-
TraesCS7B02G309300      -------------------------TGCTGCTACTGCTGCTGCTGCTGCCTGATGGGGCG
TraesCS7D02G403100      C-----------------------ATGCTGC---------TGCTGATGCCTGATGGAGC-
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               C------------------------TGTTATCTTCATGATTGCAATCATC----------
TraesCS6B02G298700      CAGACACGCTGACCGCTTGAAGCAATGCTGCTTATGTACTTGCAAATTTC-----GTGC-
TraesCS6A02G271500      CAGACACGCCGACCGCTTGAAGCAATGCTGCTTATGTACTTGCAAATGTC-----GTGC-
TraesCS6D02G251700      CAGACACGCTGACCGCTTGAAGCAATGCTGCTTATGTACTTGCAAATTTC-----GTGC-
                                                                                    

TraesCS7A02G409900      -----------------------------------------AATAAGA-GTCACATTCTG
TraesCS7B02G309300      AGCAACAATAACTCTCTTCAGTCTCGTGCTGTCTTCCATCGACTAACTCATCACATTCTG
TraesCS7D02G403100      -----------------------------------------AATAAGA-GTCACATTCTG
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               -----------------------------------------ACAGTGATGTTTTGGTGTG
TraesCS6B02G298700      -----------------------------------------TCTGATGCGTCTGGTTGTT
TraesCS6A02G271500      -----------------------------------------TCTGATGCGTCTGGTTGTT
TraesCS6D02G251700      -----------------------------------------TCTGATGCGTCTGATTGTT
                                                                                    

TraesCS7A02G409900      ACGGCGTGCAGGATCTTCGGGAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAAC
TraesCS7B02G309300      GCGGCGTGCAGGATCTTCGGTAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAAC
TraesCS7D02G403100      ACGGCGTGCAGGATCTTCGGGAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAAC
TraesCS3B02G011600      ------TGCGGCATCACCGCCAACCAGGGCTTCTACCTCCTCGGCCTCGACAACACCTCC
AT3G45870               AT------TAGGATATTTGGTAATCAGCTTTTGTTCCTCATTGGTCTGAATTACACCAAT
TraesCS6B02G298700      -TGTCCTGTAGCATCTTTGGCAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAAT
TraesCS6A02G271500      -TGTCCTGTAGCATCTTTGGCAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAAT
TraesCS6D02G251700      -TGTCCTGTAGCATCTTTGGCAACCAGCTACTGTTCTTGTTCGGCCTCGGCTACACCAAT
                                  * **    *  ** ***    * * * *  * ** **      ****   

TraesCS7A02G409900      GCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCA
TraesCS7B02G309300      GCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTGGCCGCA
TraesCS7D02G403100      GCCTCCTACGCCGCCGCGTTCCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCA
TraesCS3B02G011600      CCCACCTTCGCCTCCGCCATCCAGAACTCCGTTCCGGCCATCACCTTCGGCATGGCCG--
AT3G45870               CCAACTTATGCTGCAGCCATTCAGCCGTCGATCCCGGTTTTTACTTTCATCTTGGCTCTC
TraesCS6B02G298700      CCGACATACGCCGCCGCCATTCAGCCATCAATTCCCGTCTTCACTTTCATCTTGGCCCTC
TraesCS6A02G271500      CCGACATACGCCGCCGCCATTCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTC
TraesCS6D02G251700      CCAACCTACGCCGCCGCCATTCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTC
                         *  * *  **  * **  * ***    *  * ** *   * ** ***  * * **    

TraesCS7A02G409900      ATCGTCGGGTGAG-----------CAACCAATCAATCAACGGATGCACATACACGTTTCA
TraesCS7B02G309300      ATCGTCGGGTGAG-----------------------------------------------
TraesCS7D02G403100      ATCGTCGGGTGAGCACTGAGCAATCAACCAATCAATCAACGGATGCACATACACGTTTCA
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ATTATGGGGTAAA-----------------------GACTCGATCCAGTCTTTCTCTTTT
TraesCS6B02G298700      ATCATGGGGTCAG-----------------------------------------------
TraesCS6A02G271500      GTCATGGGGTCAG-----------------------------------------------
TraesCS6D02G251700      ATCATGGGGTCAG-----------------------------------------------
                                                                                    

TraesCS7A02G409900      GAGTTCTGACATCGCCTTGGATGCAAAATGCCAAACTGAACCGTAACAAACCCCGAAATG
TraesCS7B02G309300      -CAATCAACCTGACCCTTGGATGC-AAATGCCAACCTGAACCGTAACGAACTACGAAATG
TraesCS7D02G403100      GAGTTCTGACATCGCCTTGGATGCAAAATGCCAAACTGAACCGTAACAAACCCCGAAATG
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ACTTTCTCTCTGACTCTTCCA---------------------------AACCTAGAAC--
TraesCS6B02G298700      ----TCTCACTCAATCTTGAA----------------------------------AAATG
TraesCS6A02G271500      ----TCTCGCTCAATCTTGAA----------------------------------AAATG
TraesCS6D02G251700      ----TCTCACTCAATCTTGAA----------------------------------AAATA
                                                                                    

TraesCS7A02G409900      TCCCATTGCCCTGGATACACTTCTGGATTCTGATCAAATGCTGAACCAAAATGTT-----
TraesCS7B02G309300      TC-----------AATGCATTTCTGGATTCTGACCAGATGCTGAACCGAACCGTAACAGA
TraesCS7D02G403100      TCCCATTGCCGCGGATACACTTCTGGATTCTGATCAAATGCTGAACCAAAATGTT-----
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               -------------AATCCATTTTCGTGTGTTG----------------------------
TraesCS6B02G298700      TT-CAGAGACTCGCATCTCTCTTTGTTTGCTGGTTTAA---------GCATTTTA-----
TraesCS6A02G271500      TT-CAGAGACTCGCATCTCTCTTTGTTTGTCGGTTTAA---------GCATTTTA-----
TraesCS6D02G251700      TT-CAGAGACTCGCATCTCTCTTTCTTTGCTGGTTTAA---------GCATTTTA-----
                                                                                    

TraesCS7A02G409900      --------------CTTATTCCAGTGTCGAAGTGATCAACGTCTTCACCAGAGACGGCCT
TraesCS7B02G309300      ATTACCAAAATGATCTTGTTCCAGCGTCGAAGTGATCAACGTCTTCACCAGAGACGGCGT
TraesCS7D02G403100      --------------CTTATTCCAGTGTCGAAGTCATCCACGTCTTCACCAGAGACGGCGT
TraesCS3B02G011600      --------------CCGCGCTCCGCATCGAGAAGGTGCGCCTCGACCGCCGCGACGGCGT
AT3G45870               ------------------CTGCAGAACAGAGAGACTGAATTTATTCAAGCTAGAAGGTCA
TraesCS6B02G298700      --------------CAATTTTCAGGACTGAAACGGCGAGCTTGGTCACACACGAGGGCCG
TraesCS6A02G271500      --------------CCATTTTCAGCACTGAAACGGCGAGCTTCGTCACACACGAGGGCCG
TraesCS6D02G251700      --------------CCATTTTCAGCACTGAAACGGCGAGCTTGGTCACACACGAGGGCCG
                                             * *    **           *   *      ** **   

TraesCS7A02G409900      CTTCAAGGTGGTCGGCACGGCCGTGTGCGTCTTCGGCGCCGTCCTCATGGTCTTCTACCG
TraesCS7B02G309300      CTTCAAGGTCGTCGGCACGGCCGTGTGCGTCTTCGGCGCCGTCCTCATGGTCTTCTACCG
TraesCS7D02G403100      CTTCAAGGTCGTCGGCACGGCCGTGTGCGTCTTCGGCGCCCTCCTCATGGTCTTCTACCG
TraesCS3B02G011600      CGCCAAGGTGCTGGGCACGCTCGCGTGCGTCGCAGGCGCGTCCGTCATCACGCTCTACCA
AT3G45870               AGCTAAGGTAGGAGGCACACTGATTTGTGTCGCTGGGGCGGTGCTGATGGTTTTGTTTCG
TraesCS6B02G298700      TGCCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAG
TraesCS6A02G271500      TGCCAAGGTTGGTGGCACCATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAG
TraesCS6D02G251700      TGCCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAG
                            *****    *****       ** **    ** **     * **     * *    

TraesCS7A02G409900      AGGCCCCTCCCTGATCGGC---------------CTTGGAGGCGCCAATGCGCTGGACGG
TraesCS7B02G309300      AGGCCCCTCCCTGATCGGC---------------CTCGGAGATGCCAATGCGCTGTCTGG
TraesCS7D02G403100      AGGCCCCTCCCTGATCGGC---------------CTCGGAGGCGCCAATGCGCTGGCCGG
TraesCS3B02G011600      AGGCCCCACCATCTTCGCC---------------CCTACCGGCGACGACAAGC-------
AT3G45870               TGGACTGGCTTTGTTTGGGGAAACAGAGGCTGAGTCCTTGGGTCATGGTGAATCAAGACA
TraesCS6B02G298700      GGGGGCAGCTGTGTTTGGTAGCAGCGATCTAGATCTTGATGTTCCTCGTAATGTCGTCAT
TraesCS6A02G271500      GGGGGCAGCTGTGTTTGGTAGCAGCGAGTTAGATCTTGATGTTCAGAGCAATGTCGTCAT
TraesCS6D02G251700      GGGGGCAGCTGTGTTTGGTAGCAGCGAGCTAGATCTTGATGTTCATAGCAATGTCGTCAT
                         **     *  *  * *                       *                   

TraesCS7A02G409900      CGCCGACGCGTCGTGGAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAGCCACGCT
TraesCS7B02G309300      CGCCGGCGCGTCATGGAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAACCACGCT
TraesCS7D02G403100      CGCCGACGCGTCATGGAGCGGCAGTTCCTATCCTGCTCAGTGGCTGACGCCAGCCGTGCT
TraesCS3B02G011600      CGTCGTTGCAGCAGGAGGTGCCGTTTC----------TGGCGGCCGTGGCCGGGGAGGGC
AT3G45870               CACTGAAACATCT------------------------GGACACTTCATGTCTGGCTTTTT
TraesCS6B02G298700      CACTGAGATGTTG------------------------CAAC--CTGA-GCCAGGATCATC
TraesCS6A02G271500      CACCGAGATGTTG------------------------CAAC--CTGA-GCCAGGATCATC
TraesCS6D02G251700      CACCGAGATGTTG------------------------CAAC--CTGA-GCCAGGATCATC
                        *   *                                           * *         

TraesCS7A02G409900      CCAGTTCAGT---------TTTGGAACCTGGAACCTTGGTGTCC-TGTGCCTCTTAGGCA
TraesCS7B02G309300      CCAGTTCAAT---------TTTGGAACCTGGAACCTCGGTGTCC-TGTGCCTCTTAGGCA
TraesCS7D02G403100      CCAGTTCAGT---------TTTGGAACCTGGAACCTTGGTGTCC-TGTGCCTCTTAGGCA
TraesCS3B02G011600      ----------------------AAGAACTGG-ACGCTGGGGTGCGTCTACCTCATCGGCC
AT3G45870               T------------AATGGACTTGGGCGATGGAATTTGGGAGTTT-TGTGTTTGATTGGGA
TraesCS6B02G298700      TTGGTTCATTGCATATGGGCTGGAAAAGTGGCATATCGGAGTGC-TATGTTTAATAGGGA
TraesCS6A02G271500      TTGGTTCATTGCATATGGGCTGGAAAAGTGGCATATCGGAGTGC-TATGTTTAATAGGGA
TraesCS6D02G251700      TTGGTTCATTGCATATGGGCTGGAAAAGTGGCATATCGGAGTGT-TATGTTTAATAGGGA
                                                    *** *    ** **   * *   *  * **  

TraesCS7A02G409900      ACTGCTTCCTCATGGGGGCTTATCTTGTCATACAGGTAATGCAGATTG------------
TraesCS7B02G309300      ACTGCTTCCTCATGGGAGCTTATCTTGTCATACAGGTGATGCAGATTG------------
TraesCS7D02G403100      ACTGCTTCCTCATGGGGGCTTATCTTGTCATACAGGTAATGCGGAATG------------
TraesCS3B02G011600      ACTGCCTCT---------CGTGGTCCGGCTGGCTGGTG----------------------
AT3G45870               ATTGCACTTGCATGGCTGCTTTTCTTGCTATTCAGGCA----------------------
TraesCS6B02G298700      ACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGC
TraesCS6A02G271500      ACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTATTGT
TraesCS6D02G251700      ACTGCCTCTGTATGGCAACTTATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGT
                        * ***             * *     *     * **                        

TraesCS7A02G409900      ---------------------------GGTTG----------------------------
TraesCS7B02G309300      ---------GGTTGTTTTCAGCTTCATGATAGTTT-------------------------
TraesCS7D02G403100      -------GGATTTGTTTTTAGCTTCATGATAGTTT-------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ---------TGTCATTTTCTTCTAGATGATCCACA-------------------------
TraesCS6B02G298700      CGCGCTCTATTCCATTTGCATTTTGATGTTTGTCAACTCGGAACACCTTGAGCTTTAGTT
TraesCS6A02G271500      CGCACTCTATTCCGTTTGCA-TTTGATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTT
TraesCS6D02G251700      CGCTCTCTATTCCGTTTGCATTTTGATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTCTATCAGGCATATATGCATGGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTAG
TraesCS6A02G271500      TTCTATCAAGC--ATATGCATGGCACAAGTACTGAAAGGCTGAAAGCCTCTGTAAGTTAG
TraesCS6D02G251700      TTCTATCAAGC--ATATGCATGGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATCAGTAAATCTTGTAGGGCAACTTCAGATCACATCAACTCTATTTAGAACACTCTATTT
TraesCS6A02G271500      ATCAGTAAATCTTATAGGGCAACTTCAGATCACAGCAACTCTATTTAGTACACTCTGTTT
TraesCS6D02G251700      ATCAGTAAATCTTATAGGGCAACTTCAGATCACATCAACTCTATTTAGAGCACTCTATTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGATGAATATTTCAGTCCCAATTCCTAATGGTTTCTCTGCCTTCTTGACATTCTTAAAGT
TraesCS6A02G271500      TGATGAATATTTCAGTCCCAATTCCTAACAGTTTCTCTGCCTTCTTGCCATTCTTGAAGT
TraesCS6D02G251700      TGATGAATATTTCAGTCCCAATTCCTAACGGTTTCTCTGCCTTCTTGACATTCTTGAAGT
                                                                                    

TraesCS7A02G409900      ---------------------------TTTGCTCTTAATGAGAA----CTATATCT----
TraesCS7B02G309300      ---------------------------TTTGCTCTTAATGAGAA----TTACATCT----
TraesCS7D02G403100      ---------------------------TTTGCTCTTAATGAGAATTACATATATCT----
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               -----------------------------CACTTTCAGTTTCAG------ATATCT----
TraesCS6B02G298700      GAGAAGGATATTAAAACTTAGGCCGGGTTTGCTCTTCCTAGAAAAGGCCCATATTTATGC
TraesCS6A02G271500      GAGAAGGATACTAAAATTTAGGCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGC
TraesCS6D02G251700      GAGAAGGATATTAAAACTTAGGCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGTGTGGCCAACTGGCCATTGCTTAATACTGAACATGGTATGTTATTTGGTGAATTGTCA
TraesCS6A02G271500      TGTGTGGCCAACTGGCCTTTGCTTAATATTGAACATGGTATGTTTTTTGGTGAATTGTCA
TraesCS6D02G251700      TGTGTGACCAACTGGCCTTTGCTTATTATTGAACATGGTATGTTGTTTGGTGAATTCTCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CAAGAAGATTTGTCATGGGCCGAGCAAATCATACTTCATTTTAAGAACCAATATCACTAT
TraesCS6A02G271500      CAAGAAGATTTGTCATGGGCCGAGGAAATCATACTTCATTTTAAGAACCAATATCACTAT
TraesCS6D02G251700      CAAGAAGATTTGTCATGGGCCGAGGAAATCAAACTTCATTCTAAGAACCAATATCACTAT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACTAACAGAAGGAGATCACCCTTTTAACATTGTTGAAGATATGTTTATGTATTAGACTTA
TraesCS6A02G271500      ACTAATAGAAGGAAATCACCCTTTTAACATTGTTGAAAATATGTTTATGTATTAGACTTA
TraesCS6D02G251700      ACTAATAGAAGGAGATCACCCTTTTAACGTTGTTGAAAATATGTTTATGTATTAGACTTA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTCTAGTATCTTGCTATTCAAGGTTGAAACTTATGCTACAAGATCTATGTGCTCTGATTT
TraesCS6A02G271500      CTTTGGTATCTTGCTATTCAAGGTTGAAACTTATGCTACAAGATCTATGTGCTCTGATTT
TraesCS6D02G251700      CTTTAGTATCTTGCT---------------------CACAAGATCTATGTGCTCTGATTT
                                                                                    

TraesCS7A02G409900      ------------GAATTTGTGTCCTT---------TTCTGC------CGTGACTGA----
TraesCS7B02G309300      ------------GAATTTGTGTCCTT---------TTCTGC------TGTGACTGT----
TraesCS7D02G403100      ------------GAATTTGTGTCCTT---------TTCTGC------TGTGACTGA----
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ----------------TCTTGTCTTTGGACTGACCTTGCATTTGAAACATATATGA----
TraesCS6B02G298700      GTATTGCAGAAAGTTTTCTTGTTATT---------TTATACTTATTATGTTCATGTGTTG
TraesCS6A02G271500      GTATTGCAGAAAGTTTTCTTGTTATT---------TTATAC-TACTATGTTCATGTGTTG
TraesCS6D02G251700      GTATTGCAGAAAGTTTTCTTGTTATT---------TTATACTTATTATGTTCATGTGTTG
                                                                                    

TraesCS7A02G409900      ---TTCCAGGCCCCGGTGTTAGTAAAATATCCCGCGAGCTTATCCTTGACAGCCTATTCT
TraesCS7B02G309300      ---TTCCAGGCCCCGGTGTTAGTAAAATATCCTGCGAGCTTATCCTTGACAGCCTATTCT
TraesCS7D02G403100      ---TTCCAGGCCCCGGTGTTAGTAAAATATCCTGCGAGCTTATCCTTGACAGCCTACTCT
TraesCS3B02G011600      ---CTGCAGGCTCCCGTGCTCAAGAAGTACCCCGCGAGGCTGTCGGTCACCTCCTACACC
AT3G45870               -----TCAGGCTCCGGTCTTAAAGAAGTATCCGGCGAATCTTTCAGTCACAGCATACTCG
TraesCS6B02G298700      TTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCA
TraesCS6A02G271500      TTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCA
TraesCS6D02G251700      TTATTTCAGGCTCCAATTTTGGTGAAGTACCCTTGCAGTTTATCATTGACAGCTTACTCA
                              ***** **  *  *    ** ** **    *   * **  * **  * **  * 

TraesCS7A02G409900      TATTCATTTGCCACCATCTTCATGGTGTTGACTGGGGTATTT---GCAACCAACGGGCTC
TraesCS7B02G309300      TACTCATTTGCCACCATATTCATGGTGTTGACTGGGGTATTT---GCAACCAACGGGCTC
TraesCS7D02G403100      TACTCATTTGCCACCATCTTCATGGTGTTGACTGGGGTTTTT---GCAACCAACGGGCTC
TraesCS3B02G011600      TGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCTTCTTCGAGAGGGACG---CC
AT3G45870               TATTTCTTTGGGACCATGTTTATGGTGACATCT---GCTTTTTTCATGACTAATGAGTCG
TraesCS6B02G298700      TACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAA---
TraesCS6A02G271500      TACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAA---
TraesCS6D02G251700      TACTTTTTTGGAGCTCTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAA---
                        *  *  ** *      *     *  *          *  **       *           

TraesCS7A02G409900      CATGAGTGGGCGCT---GACAGGGACCGAAATCATAGCCGTTCTATATGCTGTGAGTATC
TraesCS7B02G309300      CATGAGTGGGCACT---GACAGGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATC
TraesCS7D02G403100      CATGAGTGGGCGCT---GACAGGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATC
TraesCS3B02G011600      GGCGCATGGGTCTTCCAGTCCGGCTCCGAAGTCTTCACCATCCTCTACGCCGTAAGC---
AT3G45870               ACGAACTGGAGTCT---CACAAGATCCGAGTTCTTTGCAGTTGTCTACGCAGTATGT---
TraesCS6B02G298700      GAAGATTGGACTTT---GACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAG-ATT
TraesCS6A02G271500      GAAGATTGGACTTT---GACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTTT
TraesCS6D02G251700      GAAGATTGGACTTT---GACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTTT
                              ***    *     *     * **  *     *  *  * ** ** **  *    

TraesCS7A02G409900      TGAATAA-TATCCATGGCTGCTGCCTGTGG-----------------ATGACCATGCTAA
TraesCS7B02G309300      TGAATAATAATCTATGGCCGCCCTTTAGGATTAC-AATAGAACTTGTATGACCATGCTAC
TraesCS7D02G403100      TGAACAATAATCTATGGCCGCCCTTTATGATTAC-ATTAGAACTTGTATGACCATGCTAT
TraesCS3B02G011600      -----------------------------------------ATTTCTATTAGCACCCTAT
AT3G45870               --------TCTTCACACACCATATGTTTGTTGATCCATTAAATTTCTCCAATTGAGTAAC
TraesCS6B02G298700      GTGTTAGATTTATCTTTCCCATGCATGGGACCATGAATTGAATTTCTACATGTATGTAGT
TraesCS6A02G271500      GTGTTAGTTTTATTTTTCCCATGCGTGGGACCATGAATTGAATTTCTACATGTATGTAGT
TraesCS6D02G251700      GTGTCAGATTTATCTTTCCCATGCACGGGACCATGAATTGAATTTCTACATGTATGTAGT
                                                                                    

TraesCS7A02G409900      GATGTG--------------------CTTGT-----------------------------
TraesCS7B02G309300      GATGTG------CTAACCTCTCCGAGCTTGT-----------------------------
TraesCS7D02G403100      GATGTG------CTAACCTCTCCGAGCTTGT-----------------------------
TraesCS3B02G011600      ATAATTTCGCAGTTAAGAGTT----AGTTG------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACTGTGGTGGTGATAATTGTTGCAAACTTGC--AATAAGCTAGTTTGTGTAGGGTATAGA
TraesCS6A02G271500      ACTGTGGCGAAGATAATTGTTGCAAACTTGCAAAATACGCTAGTTTGTGTAGGCTATAGA
TraesCS6D02G251700      ACTGTGGCGGATATAATTGTTGCAAACTTGCAAAATACGCTAGTTTGTGTAGGCTATAGA
                                                                                    

TraesCS7A02G409900      ----------------TCTAACCACA-------------------TTTCTTGCTTGCGCC
TraesCS7B02G309300      ----------------TCTAACCACA-------------------TTTCTTGCTTGCAAC
TraesCS7D02G403100      ----------------TCTAACCACA-------------------TTTCTTGCTTGCACC
TraesCS3B02G011600      ---------------------------------------------TTTTCTACTCTCCGT
AT3G45870               ---------------------------------------------TCTGTTGCTTCCTCT
TraesCS6B02G298700      AG---TAGTTGACGCATGCCACCATAAATATACT-ATACTGAAATTCCCCTATTTCCCCC
TraesCS6A02G271500      AGAAATAGTTGACGCATGCCACCATAAATATTCT-ATACTGAAATTCTCCTATTTCCCCC
TraesCS6D02G251700      AGAAATAGTTGACGCATGCCACCATAAATATTCTAATACTGAAATTCTCCTATTTCCCCC
                                                                     *    *  *  *   

TraesCS7A02G409900      AA----CAGGGAGTTGTTGCATCTTGTCTCAACTACGCAATCATGACTTGGGCGAACAAA
TraesCS7B02G309300      CAA---CAGGGAGTTGTTGCGTCTTGTCTCAACTACGCAATCATGACTTGGGCGAATAAA
TraesCS7D02G403100      AA----CAGGGAGTTGTTGCGTCTTGTCTCAACTACGCAATCATGACTTGGGCGAACAAA
TraesCS3B02G011600      CTG-----------TGGTGCAAATGATACGATAATTTGCTAAAGGACTAGAGGTAAACAA
AT3G45870               ATG---CAGGGAGTAATCGCGTCTGCTCTCAACTATGGTCTCTTGACATGGTCAAATAAG
TraesCS6B02G298700      CTATTTCAGGGAGTTGTTTCATCTGCTCTTAATACTGGTTTATTGACATGGTCCAACAAA
TraesCS6A02G271500      CTATTTCAGGGAGTTGTTTCATCTGCTCTTAATACTGGTTTATTGACATGGTCCAACAAA
TraesCS6D02G251700      CTATTTCAGGGAGTTGTTTCATCTGCTCTTAATACTGGTTTACTGACATGGTCCAACAAA
                                           *   *  *   *             ***  *    **  * 

TraesCS7A02G409900      ATTC----------------TTGGACCATCTCTGGTCGCCCTCTACAATCCGCTCCAACC
TraesCS7B02G309300      ATTC----------------TCGGACCTTCTCTGGTCGCCCTCTACAATCCGCTCCAACC
TraesCS7D02G403100      ATTC----------------TTGGACCATCTCTGGTCGCCCTCTACAATCCGCTCCAACC
TraesCS3B02G011600      ATTTATTAAAAGTGGTGCAATGCAACAACCTTTTACACCTCTCTGTCAGGATCACCGATT
AT3G45870               ATCT----------------TGGGTCCTTCCTTGGTTGCTCTCTATAATCCTCTTCAACC
TraesCS6B02G298700      ATTC----------------TGGGCCCAGCTATGGTGGCACTATATATGCCTCTCCAGCC
TraesCS6A02G271500      ATTC----------------TGGGCCCAGCTATGGTGGCACTATATATGCCTCTCCAGCC
TraesCS6D02G251700      ATTC----------------TGGGCCCAGCTATGGTGGCACTATATATGCCTCTCCAGCC
                        **                  *    *   *  *     * ** *        *  *    

TraesCS7A02G409900      AGCATGCTCTACCATCCTCTCA---------ACTCTTTTTCTTGGTACCCCAATCTATCT
TraesCS7B02G309300      AGCATGCTCTACCATCCTCTCA---------ACTCTTTTTCTTGGTACCCCAATCTATCT
TraesCS7D02G403100      AGCATGCTCTACCATCCTCTCA---------ACTATTTTTCTTGGTACCCCAATCTATCT
TraesCS3B02G011600      AGCAG----TACTCCTTTAGCAAATTATAGTATTATTTTATTCAGTGTAAATATATATCA
AT3G45870               CGCAGCCTCAGCTTTCTTGTCC---------AGAATCTTCCTTGGAAGCCCTATCTACTT
TraesCS6B02G298700      AGTGCTCTCTGCTCTCTTGTCA---------GTGCTCTTTCTGGGCAGTCCAATTTATTT
TraesCS6A02G271500      AGTGCTCTCTGCTCTCTTGTCA---------GTGCTCTTTCTGGGCAGTCCAATTTATTT
TraesCS6D02G251700      AGTGCTCTCTGCTCTCTTGTCA---------GTGCTCTTTCTGGGCAGTCCAATTTATTT
                         *         *     *  *              * **  *  *       ** **   

TraesCS7A02G409900      A----------GGAAGGTATGGAC-----CAACCAACAC-TCTACCCTA-----------
TraesCS7B02G309300      A----------GGAAGGTATGGAC-----CAACCAACAC-TCTACCCTA-----------
TraesCS7D02G403100      A----------GGAAGGTATGGAC-----CAACCAACAC-TCTACCCTA-----------
TraesCS3B02G011600      AGTCACTGAGTGGAAGGCATGA-------TGATCCATGTCTCAGATCTT-------AAGC
AT3G45870               G----------GGGAGGT--------------TTAATATCTCTCTCCTT-----------
TraesCS6B02G298700      C----------GGAAGGTAAGAGTATGTTTATCATATGT-TCTACTCTTTAGAGTTAACC
TraesCS6A02G271500      C----------GGAAGGTAAGAGTATGTTTATCATATGT-TCTATTCTTTAGAGTTAACA
TraesCS6D02G251700      C----------GGAAGGTAAGAGTATGTTTATCATATGT-TCTACTCTTTAGAGTTAACC
                                   ** ***                  *    **    **            

TraesCS7A02G409900      -----------------TCTGCTATTTTAACACTGTGACAT-----CATGAGTTGTT-AG
TraesCS7B02G309300      -----------------TGTGTTATTTGAACATTGTCACAT-----CATGAGTCGTCAAG
TraesCS7D02G403100      --------TGTGTTATTTGAATTATTTGAACATTGTCACAT-----CATGAGTTGTCAAG
TraesCS3B02G011600      TGCTTGCTTTTGACTCTCAAGAGATATGCAAATGATTACGCAGACGTAAGGCGTGGCAGC
AT3G45870               ----------------TTCTCTTA------------------------------------
TraesCS6B02G298700      TTTTCCATTTTATCCTTTCTTTGAAGTGAAAAATACTTTTC-----CAGACCTCTTCTAC
TraesCS6A02G271500      TTTTCTA-TTTATCCTTTCTTTTAAGTGAAAAATACTTTTC-----CAGACCTCTTCTAC
TraesCS6D02G251700      TTTTCTA-TTTATCCTTTCTTTGAAGTGAAAAATACTTTTC-----CAGACCTCTTCTAC
                                               *                                    

TraesCS7A02G409900      TTTCCGGTCATTCG-AATTGGTCATTTCGCATTGT---GTTT--ATCAGTTGAGCTTGGT
TraesCS7B02G309300      TTTCGGGTAATTCG-AATTGGTTATTTTGCATTGT---GTTT--ATCGGTTGAGCTTGGT
TraesCS7D02G403100      TTTCGGGTCATTCG-AATTGGTCATTTTGCATTGT---GTTT--ATCGGTTGAGCTTGGT
TraesCS3B02G011600      TGACATGTCAAATGAAAACGGTAATATATGCATGCAGGGTTTCATCGCGTCCGGCGTGGC
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTACTTGTTA-----ATTTGTGTATGTAGTA-TGTAGGATAT--GCACATTGATGTC-TT
TraesCS6A02G271500      TT----GTTA-----ATATGTGTATGTAGTAATGTAGGATAT--GCACATTGATGTC-TT
TraesCS6D02G251700      TTACTTGTTA-----ATATGTGTATGTAGTAATGTAGGATAT--GCACATTGATGTC-CT
                                                                                    

TraesCS7A02G409900      ACTCTTTC---------AATACCACCGTAATGGTGATGGTGCTTGG----AGCTGATGTT
TraesCS7B02G309300      GCTCTTTCAAGCAAAATGGTATGAC-ATAATGGCAATGGTGCTTGGCGTAAACTGGTGTT
TraesCS7D02G403100      GCTCTTTCAAGCAAAATGATATGAT-ATAATGGCAATGGTGCTTGGCGTAAACTGGTGGT
TraesCS3B02G011600      GTTCGCAGTGCAGATCTGGTGCATCGACCGCG-----GGGGCCCGGTGTTCGTG---GCC
AT3G45870               GCTATTCTCAGCCATC------------------AACGGGATGTGTCTGAAGTT------
TraesCS6B02G298700      GTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCAATAGTCTAAGTT------
TraesCS6A02G271500      GTTCTATTTGACCATCTGATAAAGTGATAATCTGAAAGGTCGATAGTCCAAGTT------
TraesCS6D02G251700      GTTCTATTTGACCATCTG--------ATAATCTGAAAGGTCGATAGTCCAAGTT------
                          *                                  **                     

TraesCS7A02G409900      GTTTTCCATGGATGCCGTTACTGA--AATTTGAT-GTTTCTTTATTAGTTTGCCT-----
TraesCS7B02G309300      GTTTTCCATGGATACCGTTACTGA--AATTTGACTTTTTTTTTATTAGTTTGCCTCACTT
TraesCS7D02G403100      GTTTTCCATGTATACCATTACTGA--AATTTGAC-TTTTCTTGGTTAGTTTGCCTCACTT
TraesCS3B02G011600      GTGTACCA-----GCCCGTGCAGA--CGCTCGTC-GTCGCC-------------------
AT3G45870               ------------------TCCTAACTAACTAGGC-TTTTTT-------------------
TraesCS6B02G298700      -TCTAACATATG-----GTAATAA--AGTAA----TTCTTTTTGTA--------------
TraesCS6A02G271500      -TCTAACATTGA-----TTATTAA--AGTTCAG--TTTTTTTTCTTCATA----------
TraesCS6D02G251700      -TCTAACATTGA-----TTAATAA--AGTACAGT-TTTTTTTTCTTCATA----------
                                          *    *            *                       

TraesCS7A02G409900      ----GCTATAGAA---------TTCCCACGAATTTATGCAGAACTAAATGCCCACCT---
TraesCS7B02G309300      ATGGGCTATAGAA---------TTCCCACGAATTTATGCAGAACTAAATACCCACCTTGT
TraesCS7D02G403100      ATAGGCTACAGAA---------TTCCCACGAATTTATGCAGAACTAAATACCCACCTTGT
TraesCS3B02G011600      ----ATCATGGC----------CTCCCTCACCCTCGGCGAGAAGT-----TCTACCT---
AT3G45870               ----------------------CTCC----------------------TCCTCTCTT---
TraesCS6B02G298700      ----GCAATAAATGTTTACCATCTCTTTTGATCTGAAGT--AATC---TGCTCTGTT---
TraesCS6A02G271500      ----GCAATAAATGTTTATCATCTCCTTTGATCTGAGGTATAATC---TGCTCTGTT---
TraesCS6D02G251700      ----GCAATAAATGTTTATCATCTCTTTTGATCTGAGGTATAATC---TGCTATGTT---
                                               **                               *   

TraesCS7A02G409900      ----TACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTT
TraesCS7B02G309300      GAACTACTTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTT
TraesCS7D02G403100      GCACTACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTT
TraesCS3B02G011600      -------CGGCGGGATCATCGGCGCCGCGCTCATCATCACCGGCCTCTACCTCGTGCTCT
AT3G45870               -----------AGCATTTTAGGCGGATGTGCAATCATAGCAGGTCTTTATAGTGTCACCT
TraesCS6B02G298700      ----TGCTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCT
TraesCS6A02G271500      ----TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCT
TraesCS6D02G251700      ----TACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCT
                                    *  *  * ** *        *****  * **  * **    **    *

TraesCS7A02G409900      GGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATCTGAATCCTCTTCTGG
TraesCS7B02G309300      GGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATCTGAATCCTCTTCTTG
TraesCS7D02G403100      GGGCCCGTTACAATGAGGCGCAGAGAATACTGATGTCTGGTTATCTGAATCCTCTTCTTG
TraesCS3B02G011600      GGG-------------GCAAGAGCGAGGACAGGT---CGCGCATCGGCA-----------
AT3G45870               GGGCATCTTA----------CAAAGAAA--------------------------------
TraesCS6B02G298700      GGGCAC----------GACATCGAGAAAAGTTGA---CTGCCACTGGAGTACCTTA----
TraesCS6A02G271500      GGGCGC----------GACGTAGAGAAAACTTGA---CTGCCACTGGAGTACCTTA----
TraesCS6D02G251700      GGGCGC----------GACGTAGAGAAAAGTTGA---CTGCCACTGGAGTACCTTA----
                        ***                     **                                  

TraesCS7A02G409900      TGGAGGTGGAGGATGCG--C-CAGCTCCCAAGAGACAGGAAAATTCCAGCTCAATTGATC
TraesCS7B02G309300      TGGAGGTGGAGGATGCG--C-CAGCTCCCAAGAGACAGGAAAATTCCAGCTCAATCGATC
TraesCS7D02G403100      TGGAGGTGGAGGATGCG--C-CAGCTCCCAAGAGACAGGAAAATTCCAGCTCAATTGATC
TraesCS3B02G011600      ------AGGAGGCCGCGGTCATGGCCGCCGCGTCCGCAGGTTCCTCCGGCGGCGCCGAGC
AT3G45870               ---------AGAAAGCG-------------------------------GCAGCAGCAATG
TraesCS6B02G298700      ------TGTAAAATGCG--CATCGGAGCCATGTGACAGTGCTTCTCAAGTC--ATAAAGG
TraesCS6A02G271500      ------TGTAAAATGCG--CATTGGAGCCATGCGACGGTGCTTCTCAAGTC--ATAAAGG
TraesCS6D02G251700      ------TGTAAAATGCG--CATTGGAGCCATGCGACGGTGCTTCTCAAGTC--ATAAAGG
                                 *    ***                               *        *  

TraesCS7A02G409900      CCTAAGACTC-----GGAGGAGAGATGACTCTGTTATTTTTCC-AGAACAGCAGCAGCAG
TraesCS7B02G309300      CCTGAGACTCGACGAGAGTCCACTGTGTTTTTTTTTTTTTCATAACAGCAGCATCAGCAG
TraesCS7D02G403100      CCTGATACTC-----AGACGAAGACTCCACTGTGTTTTTTTTCCAGAACAGCAGCAGCAG
TraesCS3B02G011600      GCGAGGTCCG-----GAGCGCCAAGCTCGCCTCCTCCATCACC--------------CAG
AT3G45870               GCTGTGATCC-----CGAT-----------------------------------------
TraesCS6B02G298700      GCGGTAACTT-----GAGCCCCAGGCCCTTTATATCCCTTTCC-----------AGGCTG
TraesCS6A02G271500      GCGGTAACCT-----CAGCCCCAGGCCCTTTATATCCCTTTCT-----------AGGCTT
TraesCS6D02G251700      GCGGTAACCT-----CAGCCCCAGGCCCTTTATATCCCTTTCT-----------AGGCTG
                         *                                                          

TraesCS7A02G409900      AATTACGTTGTATATT-----------------AGTATCAGAAAGCTTGTATT-TACCTT
TraesCS7B02G309300      AATTACGTTGTATATT-----------------AGTATCAGAAAGCTTGTAGT-TACCTT
TraesCS7D02G403100      AATTACGTTGTATATT-----------------AGTATCAGAAAGCTTGTAGT-TACCTT
TraesCS3B02G011600      CCTCTCCTGCCGCCTTCCTCCACCACCTCCGACAATGTCTGAAACTTAATTGTGCTACCT
AT3G45870               ----------CACCTC-----------------AA----AGGAAGCTGA-----------
TraesCS6B02G298700      TGGAATGTGCCACATG-----------------AATCTTGAGAAGCTGGTGTT-TTATGC
TraesCS6A02G271500      TGGAATGTGCCACATG-----------------AATCTTGAGAAGTTGGT----CTACGC
TraesCS6D02G251700      TGGAATGTTCCACATG-----------------AATCTTGAGAAGTTGGTGAT-CTATGC
                                      *                  *        **  *             

TraesCS7A02G409900      CTCTACCATTGGATTAAGTTACATC--------TCATACCCAAATACCCTCAACATAAGC
TraesCS7B02G309300      CTCTACCATTGGATTAGGTTACATCATTAAGGCTCATACCCAAATACCCTCAACATAAGC
TraesCS7D02G403100      CTCTACCATTGGATTAAGTTGCATCATTAAGGCTCATACCCAAATACCCTCGACATAAGC
TraesCS3B02G011600      TGCTACTGCGAGG---AGTTTTCTCGTTTAAATTCAGGCGGGCATGCATGCACGCCTATG
AT3G45870               ----ACCCTTG-----------ATCTACAAGGACCATAAAAACAAACC------------
TraesCS6B02G298700      AACTTATGCTAGGTATCTCACTATCTCCTTTGATGA-GTAAAAATACATAATGCATTAGA
TraesCS6A02G271500      AACTTCTGCTAGG--------CATCTGCTTTGATGA-GGAAAAATACAGAATGCATTAGA
TraesCS6D02G251700      AACTTCTGTTAGG--------TATCTCCTTTGATGA-GTAAAAATACAGAATGCATTGGA
                                               **          *       *  *             

TraesCS7A02G409900      TG--GAATGGAAATGGGTCGCAATTATCGTTCTCCTAGCAGCCGCAGAAGAT--------
TraesCS7B02G309300      TG--GAATCGAAATGTGTCGCAATTATCGTTTTCCT------------AGATGCTATTGG
TraesCS7D02G403100      TG--GAATGGAAATGTGTCGCAATTATCGTTCTCCTAGCAGCCGCGGAAGATGCTACTGG
TraesCS3B02G011600      TGTGGTGAGCGAGTATGCAGACG--------------------------GATTTGATTAA
AT3G45870               ----AATAGGACATCTATT-------------------------CACAAAAT--------
TraesCS6B02G298700      TGTTGGGAAGAGAAGTGCTGCAG----------------------AGAAGATTGTACTGA
TraesCS6A02G271500      TGTTAGGAAGAGAAGTGCTGCAG----------------------AGAAGATTGCACTGA
TraesCS6D02G251700      TGTTAGGAAGAGAAGTGCTGCAG----------------------AGAAGATTGCTCTGA
                                                                          **        

TraesCS7A02G409900      -----GCTAACGATGTGCGATGATAGTTCAGTTTCAACA-GTTGTCTTCATGGGTC----
TraesCS7B02G309300      CACTGGCTAACGATGTGCGATGATAGTTCAGTTTCAGCA-GTTGTCTTCATGGGTC----
TraesCS7D02G403100      CACTGGCTAACAATGTGCAATGATAGTTCAGTTTCAGCA-GTTGTCTTCACGGGTC----
TraesCS3B02G011600      AACTAGCTAGGGTTGTTTGG--------------------ATCGTGCT------------
AT3G45870               ----------------------------------------------CTCCCATCTCTTCA
TraesCS6B02G298700      CGATTGGTAATGATGTTGGCATCTGTGTCGGCTGCAGAAAATCATACTCTCAGACCTTCC
TraesCS6A02G271500      AGATTGTTAACGATGTTGGCATCTGTGTCCTCTGCAGAAAATCATACTCTCATACCTTCC
TraesCS6D02G251700      AGATTGTTAATGATATTGGCATC-----------------ATCATAATCTCATACCTTCC
                                                                       *            

TraesCS7A02G409900      -AAGGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCGAACCCAACTTGTTAATAGTT
TraesCS7B02G309300      -AAGGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCGAACCCAACTTGTTAATAGTT
TraesCS7D02G403100      -AAGGAACAGCTTCAGTGATCAAAGGTAATTACTTCATCCAACCCAACTTGTTAATAGTT
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               CCAAAATCCGAT---------------------------------GATTGAACAAAA---
TraesCS6B02G298700      ATAGGAGCAGTT----------AGGTTAATT-----------------TAGGCAAAAGAG
TraesCS6A02G271500      ATAGGAGCTGTT----------AGGTTAATT-----------------TAGACAAAAGAG
TraesCS6D02G251700      ATAGGAGCAGTT----------AGGTTAATT-----------------TAGACAAAAGAG
                                                                                    

TraesCS7A02G409900      CATTAGTTATCATCGTAATTGCTTAATTGGCATATGGCTGCCA--TGATTGCTGGTGTTA
TraesCS7B02G309300      CGTTAGCTATCATTGTAATTGCTTAATTGGCATATGGTTGCCA--TGATTGCTGTTGTTA
TraesCS7D02G403100      CATTAGTTATCATCGTAATTGCTTAATTGGCATATGGCTGCCA--TGATTGCTGCTGTTA
TraesCS3B02G011600      ------TGATTATGGTGTGT-------------------------GCATTAAGGCTTGTC
AT3G45870               -----------ACTCTGGCTTCTTGA----------------------------------
TraesCS6B02G298700      AAGCCATGCTCATTCTGCTTTTTCA----------GACTAACA--ACATTGAGGATGCTG
TraesCS6A02G271500      AAGCCATGTTCATGCTGTTTTTCTA----------GGCTAACAACACACTGAGGATGCTG
TraesCS6D02G251700      AAGCCATGTTCATCCTGTTTTTCTA----------GACTAACA--ACATTGAGGATGCTG
                                   *   *   *                                        

TraesCS7A02G409900      ACTTGCATTTTATCTTCTGCTTCAGCAGCCTCTATTACTGTCTGGGA-----TCTGACTC
TraesCS7B02G309300      ACTTGCATTTTATCTTTTGCGTCAGCAGCTTCCGTTACTGCCAGGGC-----ACCGACTC
TraesCS7D02G403100      ACTTGCATTTCATCTTCTGCTTCAGCAGCCTCTATTACTGCCTGGGA-----ACCGACGC
TraesCS3B02G011600      AATTGGA-------------------------------------GTAGATCAGAAAACTT
AT3G45870               ------------------------------------ATTACTTGGGTGCTCCGATGTTTT
TraesCS6B02G298700      AGTTGATGA-------TTCTATTACCA---------AATGCAAGGTAGCACCACCGACTT
TraesCS6A02G271500      AATTGATTA-------TTCTATAACCA---------AATGCAAGGTAGCTCCACCGACTT
TraesCS6D02G251700      AATTGATGATTC----TTCTGTAATCA---------AATGCAAGGTAGCTCCACCGATTT
                                                                    *               

TraesCS7A02G409900      -TGC--AATACAGTACAA-ACAAACTGTTCTTCGTTGAT----------TTTCGTAATGC
TraesCS7B02G309300      -TGC--AATACAGTATAAGACAAACTGTTCTTCTGTGATGATTTCCAATTTTCATCGTGC
TraesCS7D02G403100      -TGC--AATACAGTATAAGCCAAACTGTTCTTCTGTTATGATTTCCAATTTCCGTCATGC
TraesCS3B02G011600      GTGCTTGATGTATTGGTA------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      -TGTGAAATACAATAGTATGTATA------TCCCGTGAA--------------ATCCCTA
TraesCS6A02G271500      -CGTGAAATCCAGTAGTATGTATA------TCCCGTGAA--------------ATCCCTA
TraesCS6D02G251700      -CGTGAAATCCAATAGCA------------------------------------------
                                                                                    

TraesCS7A02G409900      CATACTTGCGAAGCAATTATGTCTGGAGCTCAGTGCATAA-GTGGGAAAAATCAAAGTAG
TraesCS7B02G309300      CATACTTGCAAAGCAATTATGTCTGGAGCT--------------GGAAAAATCAAAGTAG
TraesCS7D02G403100      CATACTTGCGAAGCAATTATGTCTGGAGCTCAGTGCATAA-GTTGGAAAAATCAAAGTAG
TraesCS3B02G011600      ---CCCTATCTAATTATTATTACT--------------------------ATCACAATAG
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CATACATACATATGTATAAACTCTGTAGCCAGTGAGGTCATGTGTGTAGAACTTTGAGAG
TraesCS6A02G271500      CATACATACATATGTATGAACTCTGTAGCCATTGATGTCATGTGTGTAAAACTTTGAGAG
TraesCS6D02G251700      TGTACATACATATGTATGAACTCTGTAGCCATTGAGGTCA--TGTGTAAAACTTTGAGAG
                                                                                    

TraesCS7A02G409900      GAGTTCCAAATTCTTTGGC--ACATCAGGCCGCTCGAGTGTTCTTACTTTGCTTCTGTTG
TraesCS7B02G309300      GAGCTCCAAATTCTTTGGC--ACATCAGGCCGCTGGAGTGTTCTTACTTTGCTTCTGTTG
TraesCS7D02G403100      GAGCTCCAAATTCTTTGGC--ACATCAGGCCGCTTGAGTGTTCTTACTTTGCTTCTGTTG
TraesCS3B02G011600      GG------------TTTGTTCACTATAGATTGCCTTAGTGTTTACACTGTTTTTGC----
AT3G45870               ------CTTAACCTTTTGCCGACGAGAGA----------GTGACTATTTTATTTTCTAA-
TraesCS6B02G298700      AAATGTTTTACTCTCTTACATCTGTTAAGTTCTTGTA--GTTCATGCCTTGTTTCATACT
TraesCS6A02G271500      AAATG--AAACTCTCTTAT--CTGTGAAGTTCTCGTA--GTTCATACCTTGTTTCGT---
TraesCS6D02G251700      AAATG--AAACTCTCTTAC--CTGTGAAGTTCGTGTA--GTTCATACCTTGTTTCGTACT
                                       *          *            **        *  **      

TraesCS7A02G409900      TATCTGCCTTCCACTGTT------------GTGTAAATTGTTGGCACGGTTACAAAACAA
TraesCS7B02G309300      TATCTGCCTTCCACTGTTGTGCCTCTTGCGATGTAAATTGTTGACACGGTTAGAAAGCCA
TraesCS7D02G403100      TATGTGCCTCCCTCTT--------------ATGTAAATTGTTGGCACGGTTACAAAACCA
TraesCS3B02G011600      ------------------------------AATCAGTAATTAAGTAATTTCACAAC----
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACT---------------------------ACTCGATGAGTTAGCAATTCTGCAGGCTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACT---------------------------ACTCAATGAGTTGGCAATTCTGCAGTCTGG
                                                                                    

TraesCS7A02G409900      TCTTGTGTTGCCCAACTGCT----------------------------------------
TraesCS7B02G309300      TCTTGTGTCGCCCAACTGCT----------------------------------------
TraesCS7D02G403100      TCTTGTGTCGCCCAACTTAT----------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACGTGTGTTGCAAGTATTTTCCAGGCTGTTTTTTTGTA------CTGCAGGTATGTTTTT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGCGTGTTGCAACTATTTTTCAGGCTGTTCTTTTGCACTGCACCTGCAAGTATGCTTTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CACCAACAATTCTTTCTTGTAAACATGTAAATGCTACACATGAGATGACCTATTTCTCCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CACCAATAGTTCGTTCTTGCAAACATGTAAATGCTACACATGAGATGACCTATTTCTCCT
                                                                                    

TraesCS7A02G409900      -------------------------------TATGTTTTACCCCCTTTGCTTGTATATAG
TraesCS7B02G309300      -------------------------------TATGTTTTACTCCCTTCGCTCA-CTATTA
TraesCS7D02G403100      ----------------------------------------------GTTTTAGGGTATGT
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATGTGTATGTCATGGGATCCTATACATGACCTACCCATGCACCACTCTATTGGTCTACTA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATGTGTATGTCATGGGATCCTATACATGACCTACCCATGCACCACTCTGTCGGTCTACTA
                                                                                    

TraesCS7A02G409900      AGAAATTTTATTGTGTTTGTTCT--TCCATATATTTGTGAACGGTGGTAGTACTTGGACA
TraesCS7B02G309300      TGAGATGTTCTAAC-TTTTTCCTGATTTGTATGTATATAGACAAATTTAGTATTTGTTCT
TraesCS7D02G403100      TTAGTTTGTGCCCAAGGTTGCCCCACCAAAGCATTGGCTGGTTGAGGTTTTGGTTGCCCA
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TTATACATCGTGGCGCGCAATCTATGGCGCGGAAACATCGAACGTGTTGGCGTGTCTGAA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTGTACATTGTCGCACGCAATCTATGGCGCGGAAACATCGGACGTGTTGGCATGTCTGAA
                                                                                    

TraesCS7A02G409900      T-----------------------------------------------------------
TraesCS7B02G309300      TCCATATACTGTGAACCGAACGGA------------------------------------
TraesCS7D02G403100      T-----------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCCTGAGTGACGAATAGGCCGTGGAAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCTGATGATCATTGGTGCTGTGACCGGAGCTCGGCCTGCGTGACGAACAGGCCGTGGAAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCGACGATGTCCAGGTCGGGCGACTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGGCGACGATGTCCAGCTCGGGCGCCTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGTCCATCACCACGAACCTGTTGTCGCCGGTGCCCTCGTCGTGCACGTAGCACACCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGTCCATCACCACGAACCGGTTGTCGCCGGTGCCCTCGTCGTGCACGTAGCACACCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TAGCCGTCGTCCTCGTCGCCGTTCCCCTCGACGTCATCAGGGACGAAAAACGGCTCCCCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TAGCCGTCGTCCTCGTCGCCGTTCCCCTCAACGTCGTCGGGGACGAAGAACGGCTCCCCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACGGTGCAGTCGCCGTGGCCAGCGCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCACGGTGCAGTCGCCGTGGCCGGCGCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGCATGGGGTCGCCAACACCGAAGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGGGCATGGGGTCGCCCACGCCGAAGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGTAGCGGTTGCGGCGGCCGAGGCAGCTCGGGTTGATCACCCCGAAGTCGAGGTTCGCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGTAGCGGTTGCGGCGGCCGAGGCAGCCCGGGTTGATCACGCCGAAGTCGAGGTTCGCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCCGCGAGCGGCGTGCGTGTGACGTTGCCGGTGCGGAGGTTGATGCGCACCAGCTCCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCCGCGAGCGGCGTGCGGGTGACGTTGCCGGTGCGGAGGTTGATGCGCACCAGCTCCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGCTCGATGGACAGGATGTTGGGTGCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGTGCTCGATGGACAGGATGTTGGGCGCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCATCACGATCTCGTCGCCGCCGGCCTCCTCCCACGCGTTCACCGAGTGCATCATGTTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCATCACGATCTCCTCGCCGCCGGCCTCCTCCCACGCGTTCACCGAGTGCATCATGTTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AACCCCGGCACCTCGAACCACCGCATCTCCGACTCGTCCGCGGCGTACTTGGGGATCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AACCCCGGCACCTCGAACCACCGCATCTCCGACTCGTCCGCGGCGTACTTGGGGATCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCGAGGCGAGGCACCATGCCGGGGTCCGCCCCGACGGGCGAGCCGCCGCCCACCACCATG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCGAGGCGTGGCACCATGCCCGGGTCCGCCCCGACGGGCGAGCCGCCGCCCACCACCATG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCCATGGGGTTCATCACGATTTGTATCTCCGGGAATATCGCATAATGCTCCGTCACGGCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCCATGGGGTTCATCACGATCTGTATCTCCGGGAATATCGCATAATGCTCCGTCACGGCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AAGTCGTGCAGGAAAGACGGTTGCTTCACGGAGAAGATGGGCACGTCGGCGCCCTTGTTC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AAGTCGTGCAGGAATGACGGCTGCTTGACGGAGAAGATGGGCACGTCGGCGCCCTTGTTC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCTGCAGGGTCGAACCGGAAATAGGTGACGAACGGCGGCATGGGGCCGTAGCGGAACGCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCTGCCGGGTCGAACCTGAAGTAGGTGACGAACGGTGGCATGGGGCCGTAGCGGAACGCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AAGAGCTCGCCGGTGATGGGGTCCTTCTTGGGGTGCGCGGTCATGCCCATGCTGAGGCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AAGAGCTCGCCAGTGATGGGGTCCTTCTTGGGGTGCGCGGTCATGCCCATGCTGAGGCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCACCGGTGGCCGGGTCGACGCGCACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCACCGAAGTCGCACCTGCCGAGCGTGGTCACCTCACCGGTGGCCGGGTCGACGCGCACG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ---------------------------------------------GATTTGGCAACATTG
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGTACGGGAGGTCCGACTCGCCGAGTGCGTAGAGGCGGCCGCCGAAGACGGCGAGGCTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGTACGGGAGGTCCGACTCGCCGAGCGCGTAGAGGCGGCCGCCGAAGACGGCGAGGCTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      GTAAGAAAAATGAACTAGAGTTGGCTAGAGTTCATTTGGCATGCCAAAAATTTGGCAACC
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATCTGGCCTGTCAGCACCCTGGCCGCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCATCTGGCCTGTCAGCACCCTGGCCGCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ATCCAAACAAAGACCAATCTTTGGGTCCAAAATTTTGATAAGGTGCACTTTGGCCACAAT
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGACGGCGCCGCGCGCCATCCCGGCCAGGCCGTGGAAGCCGGAGAAGACGTTGGGCAAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGACGGCGCCGCGCGCCATCCCGGCCAGGCCATGGAACCCGGAGAAGACGTTGGGCAAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      CCAAACACACCCTTACTCCCTTCGTCACTATTATGAGATGTTCCAACTTTTTTCTGAT--
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACCGGCTCGCCCGCGTTGCGCTCCACGATGTACTTGTACGTCTGCACGTAGCGGGAGCAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACCGGCTCGCCGGCGTTGCGCTCCACGATGTACTTGTACGTCTGCACGTAGCGGGAGCAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGCAGGGAGTGCAGCATGCCGTCGCCG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGAGCAGGGAGTGCAGCATGCCGTCGCCG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCGAAGAGGTGGTGCGGCCCGCGCGGGAGATGCTGCGGGTTGGGCCCGTTGCGGATGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCGAAGAGGTGGTGCGGCCCGCGCGGGAGGTGCTGCGGGTTGGGCCCGTTGCGGATGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GCGCCGCCGGCGAGGCAGCGCGGGATGACGCCGCGCACCACGGGGCAGGGCGTGGGCGGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGCCACCGGCGAGGCAGCGCGGGATGACGCCGCGCACCACGGGGCAGGGCGTGGGCGGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACGTGCCGCGGGTCCACCGACGGACGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCACGTGCCGCGGATCCACCGACGGACGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      AGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCCTCCAGCGCGTTGCAGAACGCCGCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGCACCGGCGGGTCGACGAACGTGTTGATCGCCTCCTCCAGCGCGTTGCAGAACGCCGCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGTAGCGAAGTGACGGGCCGGCGGCGAGGCCTGGACGACCGAGCCGCCTGGCGCGGCGCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGTAGCGAAGCAGTAGGCCGGCGGCGAGGCCTGGACGACCGA------------GGCGCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TCGGATGCCCTGCTCGTTCTCGCGGTAGCAACTCGTGTACCAGTTGCATTGTTCACGGAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCAGACGGCCTGCTCGTTCTCGCGGTAGTCACTCTTGTAGCACTTACATTGTTAGTCGAC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGTCGACCAGGTGCTCTTCCGTTTCTTGTTGCTCGACCGGCTTGGGCGGCGAGGTGAGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGTCGACCAAGTGCTCTTCCGTCTCTTGTTGCTCGACCGGCTTCGGCGGCGAGGTGAGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ACGGTGGCGGTGGCGGCAGCCCACGGCGGCGGGGGCGACGTGCCCTTCCTCCTTCTGTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGGTGGCGGTGGCGGCAGCCGACGGCGGCGGGGGCGACGTGCCCTTCCTCCTTCTGTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCGGGGGAGATGTAGGAGAGCCTCCTCGAT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCAGGGGAGATGTAGGAGAGCCTCCTCGAT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      CTCGCAGCATGAGCAGCATTGGCTTTGGCAGGGTAGAGATCAGGCATGCTGAAGTTGGAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CTCGGAGCATGAGCAGCATTGGCTTTGGCGGGGTAGAGATCAGACATGCTGAAGTTGGAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      GTGACAAGTGCTCCCTCCATTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTGTTAG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGACAAGTGCTCCCTCCATTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTACTAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      TGGATGAGTAGCAATTTCTTTGTTGGAACTTGGAACCCAGGTGAGTAGCAGCAAACGCTG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGGATAACTAGCAATTTTTGTG-------TTGGAACCCAGGTGAGTAGCAGCAAATGCTG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ATACCAGTTCGCAGGCTACTGCCTTT----------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACACCAGTTCGCACACTACTGCCTTTGCTACTTGTATGCTATGGCTATATATAGCCTCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
AT3G45870               ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TAAAAGGCAAACTTACCTGGTGGAAATGTTTATTTGGTGAAAACTTCAAAGATTACGTGG
                                                                                    

TraesCS7A02G409900      -------------------------------------------------------
TraesCS7B02G309300      -------------------------------------------------------
TraesCS7D02G403100      -------------------------------------------------------
TraesCS3B02G011600      -------------------------------------------------------
AT3G45870               -------------------------------------------------------
TraesCS6B02G298700      -------------------------------------------------------
TraesCS6A02G271500      -------------------------------------------------------
TraesCS6D02G251700      ACCGCTGGATCACAGCGACCGCACAATGTGGGAGGATGAAGAGTTGCGCTAGGGT
                                                                               
