CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AT3G28070               -------------------CAAGAAACTAACAATTATTGGACCCATAAATTGACATTTCC
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------ATCACACTCACCATAAAGCTTTTTTCGAAAAGGAAGGCAAAG
TraesCS1B02G267300      ---AGGCGAAGGAGCAACGGGCACACCACACCACTCCTCCACTCC--------ACTCCAC
TraesCS1A02G310300      ----AGCTCACACTC---GCTTGCTTCACTCCATCTTTGAGTTCTCGATACACGCGACCC
TraesCS1B02G321500      ----AGCTCACACTC---GCTTGCTTCACTCCATCTTTGAGTTCTCAATACACGCGGCCC
TraesCS1D02G309800      ---------ACACTC---CCTTGCTTCACTCGATCTTTGAGTTCTGAACACA-----CCC
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      ---CAGCTCAAGGTCTAGCTTGGTCTCTCTTGCTCCTTGAGTTCCCTAACCAGAAGCTTC
TraesCS3D02G325400      CTTCAACTCAAGGTCTAGCTTGGCCTCTCTTGCTCCTTGAGTTCCCTAACCAGAAGCTTC
                                                                                    

AT3G28070               TTTTACTTGTAACATAAAGAAAAGTAACAAAGGG--------ATAACAAATTAAAGA---
TraesCS5B02G014100      ------------------------------------------------GATCAAGAG---
TraesCS5D02G021800      -ATCCCTCGCCATATAGTTCTTGCTAG-----TTCACTTGACTGTGTTGATCAAGAG---
TraesCS5A02G015800      CCTCCCTCGCCATATAGTTCTTGCTAG-----TTCACTTGACTGTGTTGATCAAGAG---
TraesCS1B02G267300      TCCCCGCCAGCACTT--CACGTACCTAG--------------CCAGCCAGCAATGGC---
TraesCS1A02G310300      T-GGCATTGGCACCTTTCACAAAACAAGAAG-----------CTAGCTAGGGAAAGT---
TraesCS1B02G321500      T-GCCATTGCCACCTTTCACAAAACAAGAAG-----------CTAGCTAGGGAAAGC---
TraesCS1D02G309800      T-GCCATTGCCACCTTTCACAAAACAAGAAGCTGCTATATATCTAGCTAGGGAAAGT---
TraesCS3A02G331900      ---------------------------------------CTTCTACTTAACCAAGGC-TT
TraesCS3B02G362000      TAGGCTTTAGCCTCTAGCCCTAGCTAA-------CTTATCTTCTAGTTAACCAAGGC-TT
TraesCS3D02G325400      TAGGCTTTAGCCTCTAGCCCTAGCTAA-------CTTATCCTCTAGTTAACCAAGGCTTT
                                                                            *       

AT3G28070               -----CTCACATTCCACAACAAATTTTTCTACCAATGCCAATAATGGCCGGAACCGCAAG
TraesCS5B02G014100      -------TGCAGGATGGAC---------------------TGGAAACCA---ACGGTGAT
TraesCS5D02G021800      -------TGTAGGATGGAC---------------------TGGAAACCT---ACGGTGAT
TraesCS5A02G015800      -------TGTAGGATGGAC---------------------TGGAAACCT---ACGGTGAT
TraesCS1B02G267300      ------------GATGCAGC--------------------CGGGCGGCG---AGGGGGAG
TraesCS1A02G310300      -------TGAAACAAGGAACAGTTTGGTCG---ATCGCCATGGCTTTCT---GCGGTGGT
TraesCS1B02G321500      -------TGAAACAAGGAACAGTTTGGTCGTCCATCGCCATGGCTTTCT---GTGGTGGT
TraesCS1D02G309800      -------TGAAACAAGGAACAGTTTGGTCG---ATCGCCATGGCTTTCT---GTGGTGGT
TraesCS3A02G331900      TGCAGCCAGCAAGAAGTACCATATATATC----ATCACCATGGGTGGCT---ACGGCGAC
TraesCS3B02G362000      TGCAGCCAGCAAGAAGTACCATATATTTC----ATCACCATGGGTGGCT---ACGGCGAC
TraesCS3D02G325400      TGCAGCCAGCAAGAAGTACCATCTATATC----ATCACCATGGGTGGCT---ACGGCGAC
                                         *                             *       *    

AT3G28070               TCCTTGGCGGAGAGAGGCCGTGTTCTTGACGGCAATGCTGGTGGTCGAAACCAGCGTCGT
TraesCS5B02G014100      ---------------------------------GATGATGGCGGTGGTGATCATGTATGC
TraesCS5D02G021800      ---------------------------------GATGATGGCGGTGGTGATCATGTATGC
TraesCS5A02G015800      ---------------------------------GATGATAGCGGTGGTGATCATGTATGC
TraesCS1B02G267300      ACGCTGATGCAGC-GGTGCAAGCCGTACGTGGCGATGATCTCGCTGCAGTTCGGGTACGC
TraesCS1A02G310300      ---TTCATGGACA-AGGCCAAGCCTTACATCGCCATGATCTCGCTGCAGTTCGGCTACGC
TraesCS1B02G321500      ---TTCATGGAGA-AGGCCAAGCCTTACATCGCCATGATCTCGCTGCAGTTCGGCTACGC
TraesCS1D02G309800      ---TTCATGGACA-AGGCCAAGCCATACATCGCCATGATCTCCCTACAGTTTGGCTACGC
TraesCS3A02G331900      ---TTGTTCGAGA-AGGCCAAGCCTTACATCGCCATGATCTGCCTGCAGTTCGGCTACGC
TraesCS3B02G362000      ---TTGTTCGAGA-AGGCCAAGCCCTACATCGCCATGATCTGCTTGCAGTTCGGCTATGC
TraesCS3D02G325400      ---TTGTTCGAGA-AGGCCAAGCCCTACATCGCCATGATCTGCTTGCAGTTCGGCTATGC
                                                          *** *     *             * 

AT3G28070               CGGAATAAGTACTTTGTTTAAATTTGCAACTTCAAAG--GGACTCAACATTTATCCTTTC
TraesCS5B02G014100      GGTGTTGAATGTGCTGACGAAGATGGT--TTTCAATGAAGGGATGCACACCACTGTCTTC
TraesCS5D02G021800      GGTGTTGAATGTGCTGACGAAGATGGC--TTTCAATGAAGGGATGCACACCACTGTCTTC
TraesCS5A02G015800      GGTGTTGAATGTGCTCACGAAGATGGC--TTTCAATGAAGGGATGCACACCACTGTCTTC
TraesCS1B02G267300      CGGGATGAACGTGATCACCAAGGTGTC--GCTGAACCACGGCATGAGCCACTACGTGCTG
TraesCS1A02G310300      CGGCATGAACGTCCTCACCAAGGTCTC--CCTCAACGGCGGGATGAGCCACTACGTGCTC
TraesCS1B02G321500      CGGCATGAACGTCCTTACCAAGGTCTC--CCTCAACGGCGGGATGAGCCACTACGTGCTC
TraesCS1D02G309800      CGGCATGAACGTCCTTACCAAGGTCTC--TCTCAACGGCGGGATGAGCCACTACGTGCTC
TraesCS3A02G331900      CGGCATGAACGTCATCACCAAGGTCTC--GCTCAACGGCGGCATGAGCCACTACGTGCTC
TraesCS3B02G362000      CGGCATGAACGTCATCACCAAGGTCTC--GCTCAACGGCGGCATGAGCCACTACGTGCTC
TraesCS3D02G325400      CGGCATGAACGTCATCACCAAGGTCTC--GCTCAACGGCGGCATGAGCCACTACGTGCTC
                         *   * *      *    **  *       * **    **  *   *          * 

AT3G28070               CTCGGCTATTCTTATCTTCTTGCTTCTCTTCTTCTTCTTCCTTCTCTTTTCTTCACTAAC
TraesCS5B02G014100      ATCGTCCTCCGCCTGCTCGTCGCCGCGCTCTTCCTCTCCCCGATCGCATACTTCAAAGAG
TraesCS5D02G021800      ATCGTCCTCCGCCTGCTCGTCGCCGCGCTCTTCCTCTCCCCGATCGCATACTTCAAAGAG
TraesCS5A02G015800      ATCGTCCTCCGCCTGCTCGTCGCCGCGCTCTTCCTCTCCCCGATCGCATACTTCAAAGAG
TraesCS1B02G267300      GTGGTGTACCGCCACGCCTTCGCCACCCTCTCCATCGCGCCCTTCGCGCTCTTCCTGGAG
TraesCS1A02G310300      GTCGTGTACCGCCACGCCTTCGCCACACTCGCCATTGCACCCTTCGCTCTCTTCCTCGAA
TraesCS1B02G321500      GTCGTGTACCGACACGCCTTCGCCACACTCGCCATTGCACCCTTCGCTCTCTTCATCGAG
TraesCS1D02G309800      GTCGTGTACCGACACGCCTTCGCCACACTCGCCATTGCACCCTTCGCTCTCTTCATCGAG
TraesCS3A02G331900      GTCGTGTACCGCCACGCCTTCGCCACCGTCTCCATCGCGCCATTTGCCCTAATTTTCGAG
TraesCS3B02G362000      GTCGTGTACCGCCACGCCTTCGCCACCGTCTCCATCGCGCCATTTGCCCTAATTTTCGAA
TraesCS3D02G325400      GTCGTGTACCGCCACGCCTTCGCCACCGTCTCCATCGCGCCATTTGCCCTAATTCTCGAG
                         * *               * **  *  *     *    **           *     * 

AT3G28070               AGGTTTCTAAT-------------------------------------------------
TraesCS5B02G014100      AGGTTTGTATC-------------------------------------------------
TraesCS5D02G021800      AGGTTTGTATC-------------------------------------------------
TraesCS5A02G015800      AGGTTTATATC-------------------------------------------------
TraesCS1B02G267300      CG----------------------------------------------------------
TraesCS1A02G310300      AGGTA----TA-------------------------------------------------
TraesCS1B02G321500      AGGTATAGCTA-------------------------------------------------
TraesCS1D02G309800      AGGTATAGCTA-------------------------------------------------
TraesCS3A02G331900      AGGTAT------------------------------------------------------
TraesCS3B02G362000      AGGTATATATACACATATATATACTCCCTTCGTTTTTAAATATTTGTCTTTTTAGAGATT
TraesCS3D02G325400      AGGTATACGTAT------------------------------------------------
                         *                                                          

AT3G28070               ------------------------------------------------------------
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ------------------------------------------------------------
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      ------------------------------------------------------------
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      TTAAATGGACTATCACTTACGGATGTATATAGACATACTTTTGAAGTGTGGATTCATTCA
TraesCS3D02G325400      ------------------------------------------------------------
                                                                                    

AT3G28070               ------------------------------------------------------------
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ------------------------------------------------------------
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      ------------------------------------------------------------
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      TTTTGCTCTGCATGTAGTCATTTATTGAAATCTCTAGAAAGACAAATATTTAGAAACGGA
TraesCS3D02G325400      ------------------------------------------------------------
                                                                                    

AT3G28070               -------ATCTTTAATCTTTACAAGACCATTTTTCTTCTTCTTTGTCAAAATCTCTTAAA
TraesCS5B02G014100      ----------------------AGCACTAACT----------------GATGTCCTTAC-
TraesCS5D02G021800      ----------------------AGCACTAACT----------------GATGTCCTTAC-
TraesCS5A02G015800      ----------------------AGCACTAACT----------------GATGTCCTTACA
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ----------GCTAGCTACTCAATTAC---------------------------------
TraesCS1B02G321500      ----------GCTAGCTATTCAATTAC---------------------------------
TraesCS1D02G309800      ----------GCTAGCTACTCAATTAC---------------------------------
TraesCS3A02G331900      ----GTAGACACGAACGATCCATGGACGAGCT----------------AGGGCCGACCAG
TraesCS3B02G362000      GGGAGTAGACACGAACGATCCATGGACGAGCT----------------AGGGCCGACCAG
TraesCS3D02G325400      ----GTAGACACGAACGATCCATGGACGAGCT----------------AGGGCCGACCAG
                                                                                    

AT3G28070               ACCATTTATAACAATTCTTTTGTATTGATTTGT------ATGTTTTTGTTTTACAGGTCA
TraesCS5B02G014100      -GAGTTTA--------GTTGTATCTCGATTGCTTGGGCCATATATATGCATCACTGATGA
TraesCS5D02G021800      -AAGTTTA--------ATTGCATCTCGATTGCTAGGGTCATATGCATCACTGATGAAGAA
TraesCS5A02G015800      AAAGTTTA--------ATTGTATCTCAATTGCTTGGGCCATATGCATCACTGATGAAGAA
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      -TAGTGTA------------------------------CACATGTATTAAT---------
TraesCS1B02G321500      -TAGTGTACACTTGATCATATATAGATCTTTGCTAGCCCACATGTAT-------------
TraesCS1D02G309800      -TAGTGTA------------------------------CGCATG------T---------
TraesCS3A02G331900      ATAGTGTG--------CATGCATTTTCTTCTTCTTTGCTACATGCATGGTTCACTAGCCT
TraesCS3B02G362000      ATAGTGTG--------CATGCATTTTCTTCTTCTTTGCTACATGCATGGTTCACTGGCCT
TraesCS3D02G325400      ATAGTGTG--------CATGCATTTTCTTCTTCTTTGCTACATGCATGGTTCACTGGCCT
                                                                                    

AT3G28070               AGTTC---ACTTCCTCCACTAAGTGTCTCAATACTTTCAAAAATTGGACTTCTTGGATTT
TraesCS5B02G014100      AGAAGCATGGGTAACGAAAGATTTTATTTTGACCGTTTTAAAATGAGAAATCGTGGCCAC
TraesCS5D02G021800      GCATG---GGGTAACGAAAGCTTTTATTTTA-----TTTTAAATGAGAAATCATGGCCAC
TraesCS5A02G015800      GCAT----GGGTAACGAAAGATTTTATTTTGACGGTTTTAAAATGAAAAATCGTGGCCAC
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ----------------------------------------------------------AT
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      ----------------------------------------------------------AT
TraesCS3A02G331900      GAAT--------------------------------------------------TGAAAC
TraesCS3B02G362000      GAAT--------------------------------------------------TGAAAC
TraesCS3D02G325400      GAAT--------------------------------------------------TGAAAC
                                                                                    

AT3G28070               CTAGGGTAATATCCAAATAACACATTCCTTACTCCAATTTCGAATATGTAACTAGCTTCC
TraesCS5B02G014100      TGATTTCTGTTC------------------------------------------------
TraesCS5D02G021800      TGATTTCTGTTT------------------------------------------------
TraesCS5A02G015800      TGATTTCTGTTC------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      TAGTGGTATTTT------------------------------------------------
TraesCS1B02G321500      TAGTGGTATTTT------------------------------------------------
TraesCS1D02G309800      TGGTGGTATTTT------------------------------------------------
TraesCS3A02G331900      TAATGGTACGAT------------------------------------------------
TraesCS3B02G362000      TGATGGTACGAT------------------------------------------------
TraesCS3D02G325400      TGATGGTACGAT------------------------------------------------
                                                                                    

AT3G28070               ACTAAATGTTGCTAATATATGATTTTTGGCTGGAAAAAAAAAGAACAGATCAATGTATGT
TraesCS5B02G014100      --TAAAGTTAACTAATTTCTGTATATGGTT-------------------TCAATG--TAT
TraesCS5D02G021800      --AGAAGTTAGCTAATTTCTGTATTTCGAT-------------------TCCTTGTATAT
TraesCS5A02G015800      --TAAAGTTAGCTAATTTCTGTATATGGTT-------------------TCCATG--TAT
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      --------TATCTAACTCGTGAAACTTGAC-------------------A-------TGA
TraesCS1B02G321500      --------TATCTAACTTGTGAAACTTGAC--------------------------ATGA
TraesCS1D02G309800      --TTTATCTAACTAGCTTGTGAAACTTGAC-------------------A-------TGA
TraesCS3A02G331900      ---------------------GAACTTGAT-------------------C-------TGA
TraesCS3B02G362000      ---------------------GAACTTGAT-------------------C-------TGA
TraesCS3D02G325400      ---------------------GAACTTGAT-------------------C-------TGA
                                                                                    

AT3G28070               GATCACAGGATACATAG---GCATCGAATACAGCAGCCCAACCTTAGCCTCCGCCATAAA
TraesCS5B02G014100      ATATGTAGGAAGAGTAG---ACCTAAGCT-----------------------------GA
TraesCS5D02G021800      ATATGTAGGAAGAGTAG---ACCTAAGCT-----------------------------GA
TraesCS5A02G015800      ATATGTAGGAAGAGTAG---ACCTAAGCT-----------------------------GA
TraesCS1B02G267300      -----CGGCAAGGCCCGCCCGCCGCGGAT-----------------------------GA
TraesCS1A02G310300      AATGGCAGGAAGGTGAG---GCCGAAGAT-----------------------------GA
TraesCS1B02G321500      AACGGCAGGAAGGTGAG---GCCGAAGAT-----------------------------GA
TraesCS1D02G309800      AATGGCAGGAAAGTGAG---GCCGAAGAT-----------------------------GA
TraesCS3A02G331900      AATGACAGAAAGGTGAG---GCCGAAGAT-----------------------------GA
TraesCS3B02G362000      AATGGCAGAAAGGTGAG---GCCGAAGAT-----------------------------GA
TraesCS3D02G325400      AATGGCAGAAAGGTGAG---GCCGAAGAT-----------------------------GA
                               * *      *    *      *                              *

AT3G28070               CAATATCACTCCTGCTCT-TACCTTCATCCTCGCCATTATCTTCAGGTTTTTGTTTTCTT
TraesCS5B02G014100      CCATGGAGATATTCGTCTACCTCTTCTTCAGTGCCTTG---CTCGGGTAATTAATTAATC
TraesCS5D02G021800      CCATGGAGATATTCGTGTACCTCTTCTTCAGTGCCTTG---CTCGGGTAATTAATCTC--
TraesCS5A02G015800      CCATGGAGATATTCGTCTACCTCTTCTTCAGTGCCTTG---CTCGGGTAATTAATCTC--
TraesCS1B02G267300      CCCCCCTCGTCTTCCTCAACATCTTCCTCCTCGCCCT-----------------------
TraesCS1A02G310300      CGTGGTCCATCTTCTTCCAAATCTTCGTCCTTGCGCTG---CTCGGG---TTAGT-----
TraesCS1B02G321500      CGTGGTCCATCTTCTTCCAAATCTTCGTCCTTGCGCTG---CTCGGG---TTAGT-----
TraesCS1D02G309800      CGTGGTCCATCTTCTTCCAAATCTTCGTCCTTGCGCTG---CTCGGG---TTAGT-----
TraesCS3A02G331900      CGTGGTCGTCCTTCCTCCAGATCTTCGTGCTGGCACTT---CTCGGG---TTAGTTCTCC
TraesCS3B02G362000      CGTGGTCGTCCTTCCTCCAGATCTTCGTGCTGGCACTG---CTCGGG---TTAGTTCTCC
TraesCS3D02G325400      CGTGGTCGTCCTTCCTCCAGATCTTCGTGCTGGCACTG---CTCGGG---TTAGTTCTCC
                        *           *  *      **** *    **  *                       

AT3G28070               TGACTAATTATTAAGTTTTTGCTGATTTCAATTTTAGTTTTTCGGATTATTCTAGTCAAC
TraesCS5B02G014100      TC--------------TTTTGCATAATTATACGTAGTCTTGAGTAGTAGTT---------
TraesCS5D02G021800      ----------------TTTTGCATAATTATAGGAAGTCTTG-------------------
TraesCS5A02G015800      ----------------TTTTGCATAATTATAGGAAGTCTTG-------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      --------------------------------GCATGCCTGGCTAGCTACCT--------
TraesCS1B02G321500      ------------------------------------GCATGCCTAGCTACCT--------
TraesCS1D02G309800      --------------------------------GCATG-CTAGCTAGCTACCT--------
TraesCS3A02G331900      TG--------------TCATTTTGACTTTTGAGCACC-CAGCCTAAGTACTTTAAGAAGG
TraesCS3B02G362000      TG--------------TCA-------TTTTGTGCACC-CAGCCCAAGTACTTTAAGAACG
TraesCS3D02G325400      TG--------------TCA-------TTTTGTGCACC-CAGCCTAAGTACTTTAAGAACG
                                                                                    

AT3G28070               AAGTCGAAATTGTAACCATTCCATTTCCGGCTAATTTAATTTTAATAATTATAA------
TraesCS5B02G014100      -------AATTTTTAACCCTAATTTCCTTTGCATTGTAATACTGTAAATAACAACTGTTG
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      --------------------------------------------------GCAA------
TraesCS1B02G321500      --------------------------------------------------GCAA------
TraesCS1D02G309800      --------------------------------------------------GCAA------
TraesCS3A02G331900      GAGACATAAGTGGACACTCCAATATGGAGACTT-ACCCTTTTGTCAAGAAACAA------
TraesCS3B02G362000      GAGACATAAGTGGACACTCCAATATGGGGGCTCGGCTCTTTTGTCAAGAAACAA------
TraesCS3D02G325400      ATGACATGAGTGGACACTCCAATACGGGGACTCGACTCTTTTGTCAAGAAACAA------
                                                                                    

AT3G28070               ---------TAGTTTTTTATGTTAACCGAAATTAATTAAACTCAAAAGAACTAATCCCGA
TraesCS5B02G014100      GCCAGTCATAAATTATTTG-----------------------------------------
TraesCS5D02G021800      ----------AATTATTTG-----------------------------------------
TraesCS5A02G015800      ----------AATTATTTG-----------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ---------AAATCATCTG-----------------------------------------
TraesCS1B02G321500      ---------AAATCATCTG-----------------------------------------
TraesCS1D02G309800      ---------AAATCATCTG-----------------------------------------
TraesCS3A02G331900      ---------AAGGTGTCCG-----------------------CCAAATGTTCTTTTTTTC
TraesCS3B02G362000      ---------AAGGTGTCCG-----------------------CCAAATGTTATATTTTT-
TraesCS3D02G325400      ---------AAGGTGTCCG-----------------------CCAAATGTTCCTTTTTA-
                                                                                    

AT3G28070               AAGATATTGTTTACATAT----GTGATGAAGCCGTTCGCTATGAATTTTTCGTGCATTAT
TraesCS5B02G014100      -------TAATTTCATAT------------------------------------------
TraesCS5D02G021800      -------AAATTTCACAT------------------------------------------
TraesCS5A02G015800      -------TAATTTCATAT------------------------------------------
TraesCS1B02G267300      -------------CATGG------------------------------------------
TraesCS1A02G310300      --------ATATGCATGT---------------------------------CTGAAATGA
TraesCS1B02G321500      -------AAGATGCATGT---------------------------------CTGGAATGC
TraesCS1D02G309800      --------AGATGCATGT---------------------------------CTGAAATGA
TraesCS3A02G331900      CAGCAGCTAGCTGCATGTACGCCA-------TTTTTTTTTTGTCAGCTTGCCTGATATAC
TraesCS3B02G362000      CAGCAGCTAGGTGCATGTACGCCAAAAAAATGTATTTTTTTGCCAGCTTTCCTGAAATAC
TraesCS3D02G325400      CAGCAGCTAGCTGCATGTACGCCAA------TTTTTTTTTTGTCAGCTTTCCTGAAATAC
                                     **                                             

AT3G28070               AATAAAGTTCTTTAGAATAATTACTTCAAAGTTCCCCTATAATTTTTTCAATTCGACTAT
TraesCS5B02G014100      ---------------------------------AGTACATGG-----CAATTGCAGAGCC
TraesCS5D02G021800      ---------------GCTAATTGATGCATGCATGGCAATTGC----------ACAGAGCC
TraesCS5A02G015800      ---------------GCTAATTGATGCATGCATCGCAATTGC----------ACAGAGCC
TraesCS1B02G267300      -------------------------------------------------------GCCCC
TraesCS1A02G310300      CAC------------GCC----CATCTCA-CCCTCTTCTTGACCTC-TTGCTGCAGACCG
TraesCS1B02G321500      CAC----------------GCCCATCTTACCCCTGTTCTTGATTTCTTTACTGCAGACCG
TraesCS1D02G309800      CAC------------GCC----CATCTTACCCCTGTTCTTGATTTCTTTACTGCAGACCG
TraesCS3A02G331900      TAACGTGTAACATGAGCTA---AACCCTATGCATGTTGTCGA-----TTACTGCAGGCCT
TraesCS3B02G362000      TAACGTGTAACATGAGCTAATGAACCTTATGCATGCTGTTGA-----TTATTTCAGGCCT
TraesCS3D02G325400      CAAT-----------GCTAATGAACCTTATGCATGTTGTTGA-----TTACTGCAGGCCT
                                                                                    

AT3G28070               TTTTTTTTCCATAAATCATGTTAGTTTTCACTTCACTATATTCAACACTATAGTTTGCTA
TraesCS5B02G014100      TCTCTGATCCAGTGGCTCTTTTTCCTGGGCCTGAGGTA----------------------
TraesCS5D02G021800      TCTCTGATCCAGTGGCTCTTCTTCCTCGGCCTGCGGTA----------------------
TraesCS5A02G015800      TCTCTGATCCAGTGGCTCTTCTTCCTTGGCCTGCGGTA----------------------
TraesCS1B02G267300      GTCATCGACCAGAACTTCTACTACGCCGGCCTCAAGTA----------------------
TraesCS1A02G310300      GTGATCGACCAGAATTTCTACTACGTGGGCCTGAAGTA----------------------
TraesCS1B02G321500      GTGATCGATCAGAATTTCTACTACGTGGGGCTGAAGTA----------------------
TraesCS1D02G309800      GTGATCGATCAGAATTTCTACTACGTGGGGCTGAAGTA----------------------
TraesCS3A02G331900      GTGATCGACCAGAACTTCTACTATGTGGGTCTCAAGTA----------------------
TraesCS3B02G362000      GTGATTGACCAGAACTTCTACTATGTGGGTCTCAAGTA----------------------
TraesCS3D02G325400      GTGATTGACCAGAACTTCTACTATGTGGGTCTCAAGTA----------------------
                            *    **       *  *        **    **                      

AT3G28070               ACCAATTCTTTACCACTAGCCGCCTTACCCCTATCCCACAACTGTCTCATACTCTTATCA
TraesCS5B02G014100      -------------CACGACGG-----------------CCACGTTCGCGAGCGC-CTTCA
TraesCS5D02G021800      -------------CACGACGG-----------------CCACGTTCGCGAGCGC-GTTCA
TraesCS5A02G015800      -------------CACGACCG-----------------CCACGTTCGCGAGCGC-CTTCA
TraesCS1B02G267300      -------------CACCTCGC-----------------CCACCTTCTCCTGCGC-CATGA
TraesCS1A02G310300      -------------CACCGGTC-----------------CGACGTTCGCCTGCGC-GATGA
TraesCS1B02G321500      -------------CACCGGCC-----------------CGACGTTCGCCTGCGC-GATGA
TraesCS1D02G309800      -------------CACCGGCC-----------------CGACGTTCGCCTGCGC-GATGA
TraesCS3A02G331900      -------------CACTGGCC-----------------CGACCTTCGCATGCGC-CATGA
TraesCS3B02G362000      -------------CACCGGCC-----------------CAACCTTCGCATGCGC-CATGA
TraesCS3D02G325400      -------------CACCGGCC-----------------CGACCTTCGCATGCGC-CATGA
                                     ***                      * **  ** *   * *   * *

AT3G28070               GTAACTAGGTAAATAATCTATATTTATGGTAAATGCGTTTAATATGTTCTTCTTTCTTTC
TraesCS5B02G014100      ACAAC--------------------------------------ACGACTCCCATGTTCAC
TraesCS5D02G021800      ACAAC--------------------------------------ACGACCCCCATGTTTAC
TraesCS5A02G015800      ACAAC--------------------------------------ACGACCCCCATGTTCAC
TraesCS1B02G267300      GCAAC--------------------------------------ATGCTCCCCGCCATGAC
TraesCS1A02G310300      GCAAC--------------------------------------ATCCTGCCGGCGATGAC
TraesCS1B02G321500      GCAAC--------------------------------------ATCCTGCCGGCGATGAC
TraesCS1D02G309800      GCAAC--------------------------------------ATCCTGCCGGCGATGAC
TraesCS3A02G331900      GCAAC--------------------------------------ATCCTTCCAGCCATGAC
TraesCS3B02G362000      GCAAC--------------------------------------ATCCTTCCTGCCATGAC
TraesCS3D02G325400      GCAAC--------------------------------------ATCCTTCCCGCCATGAC
                          ***                                      *            *  *

AT3G28070               TTTCAATGCATACATTAATTCAGGTTTTCGGCATCTATATTTATGGCAATTGATATGAAG
TraesCS5B02G014100      CTTCC-----------------------------------TCCTCGCACTGGCCTTCAAG
TraesCS5D02G021800      CTTCC-----------------------------------TCCTCGCACTCGCCTTCAAG
TraesCS5A02G015800      TTTCC-----------------------------------TCCTCGCACTCGCCTTCAAG
TraesCS1B02G267300      CTTCG-----------------------------------TCATGGCGGTCATCTTCCGG
TraesCS1A02G310300      CTTCG-----------------------------------TCATGGCGGTGATCTTCAGG
TraesCS1B02G321500      CTTCG-----------------------------------TCATGGCGGTGATCTTCAGG
TraesCS1D02G309800      CTTCG-----------------------------------TCATGGCGGTGATCTTCAGG
TraesCS3A02G331900      CTTCG-----------------------------------TGATGGCCTTCATCTTCAGG
TraesCS3B02G362000      CTTCG-----------------------------------TGATGGCCTTCATCTTCAGG
TraesCS3D02G325400      CTTCG-----------------------------------TGATGGCCTTCATCTTCAGG
                         ***                                    *  * **  *     *   *

AT3G28070               ATTTAAGTTACTATCGCACTATTGCTCAATCTTGTGGTCCAAATCATACAAGGCTGTTTG
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      TGCAATTTCACTACCAGCTT----ACTTTGCATGC-----------CGTGCATC------
TraesCS1B02G321500      TGCAATTTCACTACCAGCTTACTGACTTTGGGTGC-----------CGTGCATC------
TraesCS1D02G309800      TACAATTTCACTACCAGCTT----ACTTTGTATGT-----------CGTGCATC------
TraesCS3A02G331900      TATATACTCCGTACATGC------ATGATGCATGCATCTCTTC---TGAGAATC------
TraesCS3B02G362000      TATA-------TAC-------------ATACATGCATCTCTTCTGATGAGAATC------
TraesCS3D02G325400      TATA-------TACATGC------ATGATGCATGCGTCTCTTC---TGGGAATC------
                                                                                    

AT3G28070               CATGAATGAAATAAATGCGTATTAATTGTGTTTGATCATT--GATTATTTCTTAGCCTTC
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      ----ATATGCATATACATGCGCACG------TGGAACGAG--AAACCATTGCTAACATGG
TraesCS1B02G321500      ----ATATGCATATCCATGCGCACG------TGGAACGAG--AAACCATTGCTAAC----
TraesCS1D02G309800      ----ATATGCATA--CATGCGCACA------TGGAACGAG--AAACCATTGCTAAC----
TraesCS3A02G331900      --TGAGATGAATACTAGCGTGATCGCGACGTTGGAGCTAGCAAAACATTTTTTGACAT--
TraesCS3B02G362000      --TGAAAAGAATAGTAGTGCGACGGTGCCGTTGGATCTGGC-AAACATTATTTGACAG--
TraesCS3D02G325400      --TGAGATGAATATTAGCGTGACCGCGCCGTTGGAGCTAGCAAAACATTATTTGACAT--
                                                                                    

AT3G28070               TTTTGGAATAAACACTTAACACACTAAATTTCATTTTGTGAATAAAGAATGGAAAAAGTA
TraesCS5B02G014100      ------------------------------------------------GTCGAGAAGATC
TraesCS5D02G021800      ------------------------------------------------GTCGAGAAGATC
TraesCS5A02G015800      ------------------------------------------------GTTGAGAAGATC
TraesCS1B02G267300      ------------------------------------------------ATGGAGAAGGTG
TraesCS1A02G310300      ATTTTGCAT-----------------GATGTTCGGTA-----CATAGGATGGAGAAGATA
TraesCS1B02G321500      GTTGTGCAT-----------------GACGTTTGGTA-----CATAGGATGGAGAAGATA
TraesCS1D02G309800      ATTTTGCAT-----------------GATGTTCGGTA-----CATAGGATGGAGAAGATA
TraesCS3A02G331900      TTTTTGGAT-----------------TGTGTCCGAAAAAAATCATAGGATGGAGAAGGTG
TraesCS3B02G362000      TTTTTCGAT-----------------CGTGCCCG-AAAAATTCATAGAATGGAGAAGGTG
TraesCS3D02G325400      CTTTTGGAT-----------------GGTGTCCG-AAAATATCATAGGATGGAGAAGGTG
                                                                         * ** **  * 

AT3G28070               TCTTTCA--AAGAGAGGAGTAGTCTAGCCAAATTGATGGGGACGATATTGTCACTGATAG
TraesCS5B02G014100      GATGCCGCCAGCCGCTCCGGTGCA--GCCAAGCTCACCGGCACGGCCGTGGGGCTGGCCG
TraesCS5D02G021800      GATGTCGCCAGCCGATCCGGCGTC--GCCAAGCTCACCGGCACGGCCGTGGGGCTGGCCG
TraesCS5A02G015800      GATGTTGCCAGCCGCTCCGGCGCA--GCGAAGCTCACCGGCACGGCCGTGGGGCTGGCCG
TraesCS1B02G267300      GACCTCA--AGAAGGCCAGGTGCATGGCCAAGGTGGCCGGCACGCTCGTCACGGTGGCCG
TraesCS1A02G310300      GAGTTGA--AGAAGGTGCGGTGCCAGGCCAAGATCTTCGGGACTGTGGTGACGGTGGCCG
TraesCS1B02G321500      GAGTTGA--AGAAGGTGCGGTGCCAGGCCAAAATCTTCGGGACGGTGGTGACCGTGGCCG
TraesCS1D02G309800      GAGTTGA--AGAAGGTGCGGTGCCAGGCCAAGATCTTCGGAACGGTGGTGACGGTGGCCG
TraesCS3A02G331900      GACCTGA--GAAAGGTGCGGTGCCAGGCGAAGGTGGCCGGGACGGTGGTGACGGTGGCCG
TraesCS3B02G362000      GACCTGA--GAAAGGTGCGGTGCCAGGCGAAGGTGGCCGGGACGGTGGTGACGGTGGCCG
TraesCS3D02G325400      GACCTGA--GAAATTTGCGGTGCCAGGCGAAGGTGGCGGGGACGGTGGTGACGGTGGCCG
                                          *  *    ** **  *    ** **     *     **   *

AT3G28070               GTGCACTTGTGGTGATTTTCTACCACGGTC-----------CACGTGTCTTCCTCGCATC
TraesCS5B02G014100      GAGCGACGGTGCTGGCACTCTACCATGGCCCGACCCTGGTGGGGGCGCCGTCGGGGGACC
TraesCS5D02G021800      GAGCGACGGTGCTGGCATTCTACCAAGGGCCGACACTGATGGGGGTGGCGTCGGGGGACC
TraesCS5A02G015800      GAGCGGCGGTGCTGGCACTCTACCATGGCCCGACCCTGATGGGAGCGCCGTCGGGGGACC
TraesCS1B02G267300      GCGCCATGCTCATGACGCTCTACAAGGGCC---GCGCCGTGGAGATGATCT----GGTCC
TraesCS1A02G310300      GCGCGATGCTCATGACGCTCTACAAGGGCC---CCCTCATGCACCTGCCAT----GGACC
TraesCS1B02G321500      GCGCGATGCTCATGACGCTCTACAAGGGCC---CCCTCATGCACCTGCCAT----GGACC
TraesCS1D02G309800      GCGCTATGCTCATGACGCTTTACAAGGGGC---CCCTCATGCACCTGCCAT----GGACC
TraesCS3A02G331900      GCGCGATGCTGATGACGCTCTACAAGGGCC---CGCTGATGCGGATGGCGT----GGACG
TraesCS3B02G362000      GCGCGATGCTGATGACGCTCTACAAGGGCC---CGCTGATACGGATGGCGT----GGACG
TraesCS3D02G325400      GCGCGATGCTGATGACGCTCTACAAAGGCC---CGCTGATGCGGATGGCGT----GGACG
                        * **     *  **    * *** * ** *                *   *    *    

AT3G28070               TTCTCCGCCCTATGTAAACTTCC----------------GTCAGTTTTCTCCACCGTTGT
TraesCS5B02G014100      ACCT--AGCCGCCGCTGCCACCC------ACGGCGGTGCGCGGAGGTG----GGCGGTGG
TraesCS5D02G021800      ACCT--GGCCGCCGGTTCCACCCATAGAGACGGCGGTGCGCGGAGGTG----GGCGGTGG
TraesCS5A02G015800      ACAT--GGACTCCACAGCCACCC------ACGGCGGTGCGCGGAGGTG----GGCGGTGG
TraesCS1B02G267300      A-----GGCACGCGCACCTCCCC-----GGCCC----GCACCAG--------GACGCCGC
TraesCS1A02G310300      AACG--GCCACGCGCAGCCCAGC-----GGCGGCGAGGCCTCAGGTGCCGCCGGCGTCGA
TraesCS1B02G321500      AACG--GCCACGCGCAGCCCAGC-----GGCGTCGAGGCCCCGGGTGCCGCCGGCGTCGA
TraesCS1D02G309800      AACG--GCCACGCGCAGCCCAGC-----GGCGGCGAGGCCCCGGGTGCCGCCGGCGTCGA
TraesCS3A02G331900      A-----GCCACGGACAGGCCCAC-----GGCGGCGAGGCCCCG---------GCCGTCGA
TraesCS3B02G362000      A-----GCCACGGGCAGCCCCAC-----GGCGGCGAGGACCCG---------GCCGTCGA
TraesCS3D02G325400      A-----GCCACGGACAGGCCCAC-----GGCGGCGAGGCCCCG---------GCCGTCGA
                                              *                               **  * 

AT3G28070               CATCTTCAAACTCCGATTGGCTCATCGGTGGAGCTCTTCTAACCATGCAAGGCATATTCG
TraesCS5B02G014100      GCTCGGT-GGCGTTGCTGGGCTTCTCGGC---AAGCTGGTCGCTGTGG------------
TraesCS5D02G021800      GCTCGGT-GGCGCTGCTGGGCTTCTCGGC---GAGCTGGTCGTTGTGG------------
TraesCS5A02G015800      GCTCGGT-GGCGCTGCTGGGCTTCTCGGC---GAGCTGGTCGTTGTGG------------
TraesCS1B02G267300      CGCCGCC-GCCAAGGACTGGTTCAAGGGG---TCCATATTCCTCATCATCGCCACCCTTG
TraesCS1A02G310300      CCCCACC-GCGAGGGAGTGGTTCCTGGGC---TCCCTCTTCATCATCATCGCCACCCTCG
TraesCS1B02G321500      CCCCACC-GCGAGGGAGTGGTTTCTGGGC---TCCCTCTTCATCATCATCGCCACCCTCG
TraesCS1D02G309800      CCCCACC-GCGAGGGAGTGGTTCCTGGGC---TCCCTCTTCATCATCATCGCCACCCTCG
TraesCS3A02G331900      TCCCACG-GGCAGGGAGTGGTTCCTCGGC---TCGCTCTTCATCATCATCGCCACCCTCG
TraesCS3B02G362000      CCCCACG-GGCAGGGAGTGGTTCCTCGGC---TCGCTCTTCATCATCATCGCCACCCTCG
TraesCS3D02G325400      TCCCACG-GGCAGGGAGTGGTTCCTCGGC---TCGCTCTTCATCATCATCGCCACCCTCG
                           *          *   ** *    **        *  *     *              

AT3G28070               TTTCTGTTTCT---TTCATTCTTCAGGTACCAAT-----------TTTTTTTCCTTATAT
TraesCS5B02G014100      --------------TTCATCCTGCAGT--CCAAG--------------------------
TraesCS5D02G021800      --------------TTCATCCTGCAGT--CCAAG--------------------------
TraesCS5A02G015800      --------------TTCATCCTACAGT--CCAAG--------------------------
TraesCS1B02G267300      CATGGGCCTCCCTCTTCATCCTCCAGG--TCTATATATAGCTAGCTCGCTTCCCTCCTGT
TraesCS1A02G310300      CCTGGGCCTCGCTCTTCATCCTGCAGA--CCCAC--------------------------
TraesCS1B02G321500      CCTGGGCCTCGCTCTTCATCCTGCAGA--CCCAC--------------------------
TraesCS1D02G309800      CCTGGGCCTCGCTCTTCATCCTGCAGA--CCCAC--------------------------
TraesCS3A02G331900      CCTGGGCTTCTCTCTTCATCCTCCAGG--CTCAC--------------------------
TraesCS3B02G362000      CCTGGGCCTCTCTCTTCATCCTCCAGG--CTCAC--------------------------
TraesCS3D02G325400      CCTGGGCCTCGCTCTTCATCCTCCAGG--CTCAC--------------------------
                                      ***** ** ***      *                           

AT3G28070               ATAGTAGAAATAATTTTAAATTTATGGTTAAGTCAAAAATTAGTCATTAAAAAAGGTGGA
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      CCATGCGACCATACATGCATGAACTGAGAATCCTAACAGGTAGTGTTTGGTGCATGCAGG
TraesCS1A02G310300      ------------------------------------------------------------
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      ------------------------------------------------------------
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      ------------------------------------------------------------
TraesCS3D02G325400      ------------------------------------------------------------
                                                                                    

AT3G28070               AACATACGAACACATGGTTTAGAGTAGACCTAGGCGTTCAGATATTTGGTTCGGTTCTAG
TraesCS5B02G014100      -----ATCGGGACAAAGT----------ACCCGGCG--CTCTACTCCGGCACGGCGTGGA
TraesCS5D02G021800      -----ATCGGGACAAAGT----------ACCCGGCG--CTCTACTCCGGTACAGCGTGGA
TraesCS5A02G015800      -----ATCGGGACAAAGT----------ACCCGGCG--CTCTACTCCGGCACAGCGTGGA
TraesCS1B02G267300      GCCCGACGCTGACGAGGT----------ACGACGCG--CCGCTGACCCTGACGACGCTCA
TraesCS1A02G310300      -----ACCATCAGGAAGT----------ACACCGCG--CAGCTCTCCCTGACCACGCTCA
TraesCS1B02G321500      -----ACCATCAAGAAGT----------ACACCGCC--CAGCTCTCCCTCACCACCCTCA
TraesCS1D02G309800      -----ACCATCAAGAAGT----------ACACTGCC--CAGCTCTCCCTCACCACCCTCA
TraesCS3A02G331900      -----ACCCTGAAGCAGT----------ACTCGGCA--CCGCTCTCCCTTACCACGCTCA
TraesCS3B02G362000      -----ACCCTGAAGCAGT----------ACTCGGCG--CCGCTCTCGCTCACCACGCTCA
TraesCS3D02G325400      -----ACCCTGAAGCAGT----------ACTCGGCG--CCGCTCTCCCTCACCACGCTCA
                             *     *    **           *   **   *            *        

AT3G28070               TTCGGTTCCAATTCTTTCGGCTCTCGAGTTTAGGATTCATATAGGAACTAAAACAGTTTT
TraesCS5B02G014100      TGTTCCTGC-------TCAGCTTCT----------TCCAGATGGCCGCCG----------
TraesCS5D02G021800      TGTTCGTGC-------TCAGCTTCA----------TCCAGATGGCCACCG----------
TraesCS5A02G015800      TGTTCGTGC-------TCAGCTTCA----------TCCAGATGGCCACAG----------
TraesCS1B02G267300      TCTGCTTCG-------TGGGCACCC----------TGCA---GGCCATCG----------
TraesCS1A02G310300      TCTGCTTCA-------TCGGCACCA----------TACA---GGCCATCG----------
TraesCS1B02G321500      TCTGCTTCA-------TCGGCACCC----------TCCA---AGCGATCG----------
TraesCS1D02G309800      TCTGCTTCA-------TCGGCACCA----------TCCA---GGCCATCG----------
TraesCS3A02G331900      TCTGCTTCG-------TCGGCACCC----------TCCA---GGCCATCG----------
TraesCS3B02G362000      TCTGCTTCG-------TCGGCACCC----------TCCA---GGCCATCG----------
TraesCS3D02G325400      TCTGCTTCG-------TCGGCACCC----------TCCA---GGCCATCG----------
                        *     *         *  **              * **    *                

AT3G28070               GGTTTGGTTTGGGTTCGGGTTCGGTTTTTTCGGTTCTGAAGTTTAATTAGGACCCATTCG
TraesCS5B02G014100      ---------------------TCGGGGCTGCCACCGAGAAGATGAGCTTG--CTGGTCTG
TraesCS5D02G021800      ---------------------TCGGGGCTGCCACCGAGAAGATGAGCTTG--CAGATCTG
TraesCS5A02G015800      ---------------------TCGGGGCTGCCACCGAGAAGATGAACTTG--CAGATCTG
TraesCS1B02G267300      ---------------------TGGTCACCTTGGCCATGGAGCACACCACC--GACGTCTG
TraesCS1A02G310300      ---------------------CCGTCACCTTCGTCATGGAGCGCCGCGTC--TCCGTCTG
TraesCS1B02G321500      ---------------------CCGTCACCTTCGTCATGGAGCGCCGCGTC--TCCGTCTG
TraesCS1D02G309800      ---------------------CCGTAACCTTCATCATGGAGCGCCGCGTC--TCCGTCTG
TraesCS3A02G331900      ---------------------TCGTCACCTTGGCCATGGAGCACCGCCCC--TCCGTCTG
TraesCS3B02G362000      ---------------------TCGTCACCTTGGCCATGGAGCACCGCCCC--TCCGTCTG
TraesCS3D02G325400      ---------------------TCGTCACCTTGGCCATGGAGCACCGCCCC--TCCGTCTG
                                               *             * **               *  *

AT3G28070               GATATTTATTTCAGATATTTTTTAGTATTTTCGGATATTTTCGAGTATTTTTGGATATTT
TraesCS5B02G014100      G------GTTCCCCGCAC--------------GGCGCTCCAGG-----------------
TraesCS5D02G021800      G------GTCCCACGCAC--------------GGCGCTCCAGG-----------------
TraesCS5A02G015800      G------GTCCCACGCAC--------------GGCGCTCCAGG-----------------
TraesCS1B02G267300      GAAGATCGGCTTCGACAT--------------GAACCTCCTCG-----------------
TraesCS1A02G310300      GACCATCGGCTTCGACAT--------------GAACCTCCTCG-----------------
TraesCS1B02G321500      GACCATCGGCTTCGACAT--------------GAATCTCCTCG-----------------
TraesCS1D02G309800      GACCATCGGCTTCGACAT--------------GAACCTCCTCG-----------------
TraesCS3A02G331900      GACCATCGGCTTCGACAT--------------GAACCTCCTCG-----------------
TraesCS3B02G362000      GACCATCGGCTTCGACAT--------------GAACCTCCTCG-----------------
TraesCS3D02G325400      GACCATAGGCTTCGACAT--------------GAACCTCCTCG-----------------
                        *               *               *    *    *                 

AT3G28070               TGGTATTTTTATATATTTTTCAACTATATTTTCGGTATTTTTGAATGTTCAATCTAAAAA
TraesCS5B02G014100      ----------------CCGTCAC-------------------------------------
TraesCS5D02G021800      ----------------CCGTGAC-------------------------------------
TraesCS5A02G015800      ----------------CTGTGAC-------------------------------------
TraesCS1B02G267300      ----------------CCGCCGCCTACGCCGTAAG-------------------------
TraesCS1A02G310300      ----------------CCGCCGCCTACGCGGTACGATCACTT------------------
TraesCS1B02G321500      ----------------CCGCCGCCTACGCGGTACGATCACTT------------------
TraesCS1D02G309800      ----------------CCGCCGCCTACGCAGTACGACCACTT------------------
TraesCS3A02G331900      ----------------CCGCCGCATACGCCGTCAGTACACTT------------------
TraesCS3B02G362000      ----------------CCGCAGCATACGCCGTCAGTACACTT------------------
TraesCS3D02G325400      ----------------CCGCCGCATACGCCGTCAGTACACTT------------------
                                                                                    

AT3G28070               TAACTAATATTTTTGGATATATAATCATATTTAGATATTCTCGGATACCCGAAATATTTC
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      ------------------------------------------------------------
TraesCS1A02G310300      -----------------------------------------------------ACCACTG
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      -----------------------------------------------------ACCATTG
TraesCS3A02G331900      ---------------------------------------------------------CTC
TraesCS3B02G362000      ---------------------------------------------------------CTC
TraesCS3D02G325400      ---------------------------------------------------------CTC
                                                                                    

AT3G28070               AGTTCGGTTCGGGTTCGGTTCCAATTATTTTGGTTCTAGAATTTAGGATTCATTTGAGTA
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      -CCTCACAGGCCATACTAGCACCATCAGAT--------------------CGAGACAATA
TraesCS1A02G310300      TCCTCTTCATCGCCATG-ACCTCTTCCATT-----------------------ACCAGTT
TraesCS1B02G321500      --ACCATTGTACGACATGATCTCTTCCATT-----------------------ACCATTT
TraesCS1D02G309800      TCCACTTCGTGGCCATG-ATCTCTTCCATT-----------------------ACCAGTT
TraesCS3A02G331900      TACTCACCATATGCATGCGTCTTGTCTCCTCATACATCG---ATCGATCGCATGCAAGAT
TraesCS3B02G362000      CACTCACC--AC----GCGTCTCATCTCCTCAATCGTCATACATCGATCGCA-GCCGAAT
TraesCS3D02G325400      TGCTCACC--ACGCATGCGTCTTGTCTCCT--------------------CA-GCCAAAT
                                                                                    

AT3G28070               TTTTACCAT----TTTGGTTTGGCTTCGGATTCGGTTCTTTTTGCTTTGGTTCCAGT---
TraesCS5B02G014100      -------------CGTGGTGTT-----------------------------TGC-TGGCG
TraesCS5D02G021800      -------------CGTGGTATT-----------------------------TGC-TGGCG
TraesCS5A02G015800      -------------CGTGGTATT-----------------------------TGC-TGGCG
TraesCS1B02G267300      ACTAAACATGG--CATGGTACTGACCATGAATCTCTGTGAATATGTATGTGTGCAGGGTA
TraesCS1A02G310300      CTTG---------ACCAGTTTTGGTGATATTT-------------------TGCAGGGCA
TraesCS1B02G321500      CTTA---------ACCGGTTTTGGTGGTATTT-------------------TGCAGGGCA
TraesCS1D02G309800      CTTG---------ACCGGTTTTGCTGGTATTT-------------------TGCAGGGCA
TraesCS3A02G331900      CTCATATGTAG--TATCGTATGACTGATG--T-------------------TGCAGGGCA
TraesCS3B02G362000      CTCA----TCG--TGTCGCATGACTGATG--T-------------------TGCAGGGCA
TraesCS3D02G325400      CTCA----TAGTATATCGTATGACTGATG--T-------------------TGCAGGGCA
                                         *                                 * *      

AT3G28070               TCGTTTTTTTTTGGTTCGGGTATTATGCCCATGCATAGAGGGGTGAACTTTGGTTTTTGG
TraesCS5B02G014100      TGGGGTCGTCCGGGCTGGGGTTCCTGG-----CCATGTCATGGTGTGTGGAGC-----GG
TraesCS5D02G021800      TGGGGTCGTCCGGGCTGGGGTTCCTGG----T-CATGTCATGGTGTGTGGAGC-----GG
TraesCS5A02G015800      TGGGGTCGTCCGGGCTGGGGTTCCTGG----T-CATGTCATGGTGTGTGGAGC-----GG
TraesCS1B02G267300      TCGTGACGTCGAGCATTGCCTACTACG----TGCAAGGGCTGGTG-ATCCAGA-----GT
TraesCS1A02G310300      TCGTGACGTCGAGCATCGCGTACTACG----TGCAGGGGTTGGTG-ATCCAGA-----AG
TraesCS1B02G321500      TCGTGACGTCGAGCATCGCGTACTACG----TGCAGGGGCTGGTG-ATCCAGA-----AG
TraesCS1D02G309800      TCGTGACGTCGAGCATCGCGTACTACG----TGCAGGGGCTGGTG-ATCCAGA-----AG
TraesCS3A02G331900      TCGTGACGTCGAGCATAGCATACTACG----TGCAAGGCCTGGTG-ATCCAGA-----AG
TraesCS3B02G362000      TCGTGACGTCGAGCATAGCGTACTACG----TGCAAGGCCTGGTG-ATCCAGA-----AG
TraesCS3D02G325400      TCGTGACATCGAGCATAGCGTACTACG----TGCAAGGCCTGGTG-ATCCAGA-----AG
                        * *     *   *  * *  *     *      **      ****      *        

AT3G28070               TTGGAGATGATGTTATAATACATGTGGGAAAACACATATCTTCATTTAGTAAACATCATT
TraesCS5B02G014100      CGAGGGCCGGTGTT--------------------CACCACGGCCT----------TCATG
TraesCS5D02G021800      CGAGGGCCTGTGTT--------------------CACCACCGCCT----------TCATG
TraesCS5A02G015800      CGAGGGCCTGTGTT--------------------CACCACCGCCT----------TCATG
TraesCS1B02G267300      CGGGGCCCGGTCTT--------------------CGCCTCGGCCT----------TCAGC
TraesCS1A02G310300      ACGGGGCCGGTGTT--------------------TGCGTCGGCGT----------TCAGC
TraesCS1B02G321500      ACGGGGCCGGTGTT--------------------CGCGTCGGCGT----------TCAGC
TraesCS1D02G309800      ACGGGGCCGGTGTT--------------------CGCGTCGGCGT----------TCAGC
TraesCS3A02G331900      ACCGGGCCGGTTTT--------------------CGCGTCGGCCT----------TCAGC
TraesCS3B02G362000      ACCGGGCCGGTGTT--------------------CGCGTCGGCGT----------TCAGC
TraesCS3D02G325400      ACCGGGCCGGTGTT--------------------CGCCTCGGCGT----------TCAGC
                           *      * **                         *  * *          ***  

AT3G28070               TCATTCTAATATTTATTCTATATAATGATTTTTGGACAGGCACATATAATGAGTGTATAT
TraesCS5B02G014100      CCGCTG---------------ATCCAGATCGTCA--------------------------
TraesCS5D02G021800      CCGCTA---------------ATCCAGATCGTCA--------------------------
TraesCS5A02G015800      CCGCTA---------------ATCCAGATCGTCA--------------------------
TraesCS1B02G267300      CCGCTC---------------ATGATGATCGTGG--------------------------
TraesCS1A02G310300      CCGCTG---------------ATGATGATCATCG--------------------------
TraesCS1B02G321500      CCGCTG---------------ATGATGATCATCG--------------------------
TraesCS1D02G309800      CCGCTG---------------ATGATGATCATCG--------------------------
TraesCS3A02G331900      CCGCTG---------------ATGATGATCGTGG--------------------------
TraesCS3B02G362000      CCACTG---------------ATGATGATCGTGG--------------------------
TraesCS3D02G325400      CCACTG---------------ATGATGATCGTGG--------------------------
                         *  *                **   ***  *                            

AT3G28070               CCAGCAGCATTCAGAGTCTCCTTTCTTTACACTGTATGTGTTTCAATCGTGACCTCGACG
TraesCS5B02G014100      -CCGCCGGGATCGATGTCGCCGTCCTCCAC------------------------------
TraesCS5D02G021800      -CCGCCGGGCTCGATGTCAGCGTCCTCCAT------------------------------
TraesCS5A02G015800      -CGGCCGGGCTCGATGTCACCGTCCTCCAT------------------------------
TraesCS1B02G267300      -TGGCCATCATGGGCTCCTTCATCCTCGCC------------------------------
TraesCS1A02G310300      -TGGCCGTCATGGGGTCCTTCATCCTGTCC------------------------------
TraesCS1B02G321500      -TGGCCGTCATGGGGTCCTTCATCCTGTCC------------------------------
TraesCS1D02G309800      -TGGCCGTCATGGGGTCCTTCATCCTGTCC------------------------------
TraesCS3A02G331900      -TGGCCGTGATGGGCTCCTTCATCCTCTCC------------------------------
TraesCS3B02G362000      -TGGCCGTGATGGGCTCCTTCATCCTCTCC------------------------------
TraesCS3D02G325400      -TGGCCGTGATGGGCTCCTTCATCCTCTCC------------------------------
                           **     *      *  * * **                                  

AT3G28070               ATTGGACTAGTAGTTGAAAAGAACAACCCAAGCGTTTGGATCATTCATTTCGATATTACT
TraesCS5B02G014100      ---------------GAGCAGCTCCACCTCGGGA---G---TGTCG--------------
TraesCS5D02G021800      ---------------GAGCAGCTCCACCTCGGGA---G---CGTTG--------------
TraesCS5A02G015800      ---------------GAGCAGCTCCACCTCGGGA---G---CGTTG--------------
TraesCS1B02G267300      ---------------GAGAACATCTACCTCGGAG---GGTACGTGCATCTCAATCCTCAT
TraesCS1A02G310300      ---------------GAGAAGATATACCTCGGGG---C---CGTGC--------------
TraesCS1B02G321500      ---------------GAGAAGATATACCTCGGGG---C---CGTGC--------------
TraesCS1D02G309800      ---------------GAGAAGATATACCTCGGGG---C---CGTGC--------------
TraesCS3A02G331900      ---------------GAGAAGATATACCTGGGCG---G---CGTCC--------------
TraesCS3B02G362000      ---------------GAGAAGATATACCTGGGCG---G---CGTCC--------------
TraesCS3D02G325400      ---------------GAGAAGATATACCTGGGGG---G---CGTCC--------------
                                       **  *     ***   *           *                

AT3G28070               T-----------------------------------------------------------
TraesCS5B02G014100      ------------------------------------------------------------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      ------------------------------------------------------------
TraesCS1B02G267300      CTCCATGCATGAGAGACAAGATAGAGCAACAGTCAGTTACATTATTCTTGCTGTTTCTGG
TraesCS1A02G310300      ------------------------------------------------------------
TraesCS1B02G321500      ------------------------------------------------------------
TraesCS1D02G309800      ------------------------------------------------------------
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      ------------------------------------------------------------
TraesCS3D02G325400      ------------------------------------------------------------
                                                                                    

AT3G28070               ---------TGATTACAATTGTTACCATGGTATGTTATATATATATATATATTTTAAAGA
TraesCS5B02G014100      ---------TCGGGTCGGCGGTCGTGGTCGTGGGGC------------------------
TraesCS5D02G021800      ---------TCGGGTCGGCGGTCGTGGTCATGGGGC------------------------
TraesCS5A02G015800      ---------TCGGGTCGGCGGTCGTGGTCGTGGGGC------------------------
TraesCS1B02G267300      CCAGGATCATCGGGTCCGTCCTGATCGTGGCCGGGC------------------------
TraesCS1A02G310300      ---------TGGGCGCCGTGGTGATCGTGGTCGGGC------------------------
TraesCS1B02G321500      ---------TGGGCGCCGTGGTGATCGTGGTCGGGC------------------------
TraesCS1D02G309800      ---------TGGGCGCCGTGGTGATCGTGGTCGGGC------------------------
TraesCS3A02G331900      ---------TCGGCTCCGTCCTCATCGTCATCGGGC------------------------
TraesCS3B02G362000      ---------TCGGCTCCGTCCTCATCGTCATCGGGC------------------------
TraesCS3D02G325400      ---------TCGGCTCCGTCCTCATCGTCATCGGGC------------------------
                                 *     *     *     *     *                          

AT3G28070               TATCAAAATATCTACTTTTTGATCTTAACACTTTTTTAAAAATAAAATATTTCAGGCAAT
TraesCS5B02G014100      ----------TCTACTTGGTCCTGTG---------------------------GGGAAAG
TraesCS5D02G021800      ----------TCTACTTGGTCCTGTG---------------------------GGGAAAG
TraesCS5A02G015800      ----------TCTACTTGGTCCTGTG---------------------------GGGAAAG
TraesCS1B02G267300      ----------TCTACTCGGTGCTCTG---------------------------GGGGAAG
TraesCS1A02G310300      ----------TCTACGCCGTGCTCTG---------------------------GGGCAAG
TraesCS1B02G321500      ----------TCTACGCCGTGCTCTG---------------------------GGGCAAG
TraesCS1D02G309800      ----------TCTACGCCGTGCTCTG---------------------------GGGCAAG
TraesCS3A02G331900      ----------TCTACTCCGTGCTCTG---------------------------GGGAAAG
TraesCS3B02G362000      ----------TCTACTCCGTGCTCTG---------------------------GGGAAAG
TraesCS3D02G325400      ----------TCTACTCCGTGCTCTG---------------------------GGGAAAG
                                  *****    *  * *                             ** ** 

AT3G28070               AGTAACTTCAGTATACTATGTGATTCATTCATGGACAGTACGACATAAAGGACCTCTGTA
TraesCS5B02G014100      AGCAAC-------------GAG---------------GCGAGCATCGGATCCAAACTCCC
TraesCS5D02G021800      AGCAAC-------------GAG---------------GCGAGCATCGGATCCAAACTCCC
TraesCS5A02G015800      AGCAAC-------------GAG---------------GCGAGCATCGGATCCAAACTCCC
TraesCS1B02G267300      CACAAG-------------GAGGACGTGGAGAAGAAGGAGATCGAGGCGAGGGAGATCCC
TraesCS1A02G310300      CACAAG-------------GAGAAGCAGGAGCAGGAGGCGGACGCCAAGGCGGCACTGCC
TraesCS1B02G321500      CACAAG-------------GAGACGCAGGAGCAGGAAGCGGACGCCAAGGCGGCGCTGCC
TraesCS1D02G309800      CACAAG-------------GAGACGCAGGAGCAGGAGGCGGACGCCAAGGCGGCGCTGCC
TraesCS3A02G331900      CACAAG-------------GAGACGCAGGCAGAGTCTGCGGCTCTGCGGGA---------
TraesCS3B02G362000      CACAAG-------------GAGACCCAGGCGGAGTCCGCGGCTCTTCGGGAGGCGCTACC
TraesCS3D02G325400      CACAAG-------------GAGACCCAGGCGGAGTCCGCGGCCCTGCGGGAGGCGCTGCC
                           **              * *               *                      

AT3G28070               CTTAGCCATATTTAAACCTTTGTCCATTTTAATAGCAGTGGTTATGGGGGCCATTTTTCT
TraesCS5B02G014100      TC-------------------CTCCA----------------------------------
TraesCS5D02G021800      TG-------------------------------------------------CGT------
TraesCS5A02G015800      TG----------------------------------------CGTGAC---CGCACCCAG
TraesCS1B02G267300      CGTGGCGAT------CAAGGGCGTCGAGGGCAACGGCAGGATCATGGA---CATGGTGGA
TraesCS1A02G310300      GGTCGC---------------CTCCAAGGGACCAGACGG---CGCGAG---CGTCCTGCA
TraesCS1B02G321500      GGTGGC---------------CTCCAAGGGACCAGACGG---CGCGAG---CGTCGTGCA
TraesCS1D02G309800      GGTGGC---------------CTCCAAGGGACCAGACGG---CGCGAG---CGTCCTGCA
TraesCS3A02G331900      ---GGCCATGGCCTCCATCAACTCCAAGGGAGACGGAGA---CGC------CGTAC---A
TraesCS3B02G362000      CATGGCCATGGCCTCCTGCAGCTCCAAGGTGACCGGAGA---CGC------CGCGTCGGC
TraesCS3D02G325400      TATGGCCATGGCCTCCTACACCTCCAAGGTGACCGGAGA---CGC------CGCGTCGGC
                                                                                    

AT3G28070               CAATGATTCTCTCTATCTCGGATGGTATTAATGAATC-----AATAGTCTTCATAAACAT
TraesCS5B02G014100      -------------------------------------------TCACTTTCCA-------
TraesCS5D02G021800      ------------------------------------------------------------
TraesCS5A02G015800      TGGCTGAGCTAGGCAAGGTTGGGGTACTGGTGTTGGAGTAGCACTAGTACCAC-------
TraesCS1B02G267300      GCTGGACGAGGTGGAGCTGGAGAAGGCCCAGGCCAACGGCAAGGCGGTCACCATCTCGGT
TraesCS1A02G310300      AGGAGCTGCTACCGCAGCCGGAGATGATGATGGGATG---AGGTCGGCCTCCA-------
TraesCS1B02G321500      AGGAGCTGCTGCCGCCGCCGGAGATGATGATGGGATG---AGGTCGGCCTCCA-------
TraesCS1D02G309800      AGGAGCTGCTGCCGCCGCCGGAGATGATGATGGGATG---AGGTCGGCCTCCA-------
TraesCS3A02G331900      CGGGCACGATCCTGAGTGCGAGAAAGCCAACGGAGCACCCAAGCCATCCTCCA-------
TraesCS3B02G362000      CGGACACGATCCGGAGTGCGAGAAAGCCAACGGAGCAGCCAAGCCATCCTCCA-------
TraesCS3D02G325400      CGGACACGATCCGGAGTGCGAGAAAGCCAACGGAGCAGCCAAGCCATCCTCCA-------
                                                                                    

AT3G28070               ATCTATAAACAAAAACATCTACTCACCTTCGATTTTGTCCTTCGTTTTGCAGTTTGATCG
TraesCS5B02G014100      --------------------------------------------------AGCCCGATTG
TraesCS5D02G021800      --------------------------------------------GACTGCACCCAGACCT
TraesCS5A02G015800      ----GCAATCATGACCGTGAATCGGC---------------ATGGGACGGAATTAATTAA
TraesCS1B02G267300      GCCCGCCGCCGCCGGGGAAGCTGCCC------------------GGGTGCAGCGCGACGA
TraesCS1A02G310300      ----ACGGACGAGGAGCTGGATCAGC------------------TAGTGCAGTTTGATGG
TraesCS1B02G321500      ----ACGGACGTGGAGGTGGATCGGC------------------TAGTGCAGTTTGATGG
TraesCS1D02G309800      ----ACGGACGTGGAGCTGGGTCAGC------------------CAGTGCAGTTTGATGG
TraesCS3A02G331900      ----ACGGACACGGA---------GC------------------TAGTGCAGTCTGATCA
TraesCS3B02G362000      ----ACGGGCACGGA---------GC------------------TAGTGCGGTCTGATCA
TraesCS3D02G325400      ----ACGGACACGGA---------GC------------------TAGTGCAGTCTGATCA
                                                                                    

AT3G28070               --GAGGAA-------TTTTGATAACATTAGGCTTTTACGCT----------------GTG
TraesCS5B02G014100      G--------------------------------------------------------GAT
TraesCS5D02G021800      GCAGAGAT----------------------------------------------------
TraesCS5A02G015800      ACGATGAGCATTTCTTTTCAAGTGTTTTCGCTTTTCAGCACAATATATATAAGTACAGTA
TraesCS1B02G267300      ----------------------------------CGAGAAC----------------TGA
TraesCS1A02G310300      ACTGGGAA-------CTCAAATAATCTGTGCCCTTGAGGAC----------------TTG
TraesCS1B02G321500      ACTGGGAA-------CTGCAATAATCTGTGCC-------------------------CTG
TraesCS1D02G309800      ACTGGGAA-------CTCCAATAATCTGTGCCCTTGA-----------------------
TraesCS3A02G331900      AGAG---A-------TTCCAAC------TGCTTCCAAGTGC----------------TAA
TraesCS3B02G362000      ATCG---A-------TTCCAAC------TGCTTCCAAGTGC----------------CAA
TraesCS3D02G325400      ATCG---A-------TTCCAAC------TGCTTCCAAGTGC----------------TAA
                                                                                    

AT3G28070               ATGTGGGGCAAAGCAA-----------ACGAAGAGAAGGATCAGTTATCATTTTCAGAAA
TraesCS5B02G014100      ATACCAGAAGAAACAGAG---------AATCGTACGTAGTTCAAGGATTGTTCAGAGCGT
TraesCS5D02G021800      ---------------------------GCACGTAGCTTCGGTAGTGACTGCACCCATGGT
TraesCS5A02G015800      CCATAAGAGCACAC-------------GCACACCAGTGAGCTAGCTAGGTATCTGATAGC
TraesCS1B02G267300      TCGTTGGAGCA----------------AGAGATAGGTG-----GATCTTGATGCTGTGGT
TraesCS1A02G310300      TCATGAGA-------------------AGACGTAGGTC-----GTCGTCGTCCACGACGC
TraesCS1B02G321500      ACATGAGA-------------------AGACGTAGGTC-----ATCGTCGTCCTCGACGC
TraesCS1D02G309800      -CATGAGA-------------------AGACGTAGGTC-----GTCGTCGTCCACGACGC
TraesCS3A02G331900      CTGCGGGTGCGCGCGCGCGTCTGAACGAAATGTC----------TCGTCACTGACGTTGC
TraesCS3B02G362000      GTGC-----------------------AAATGTC----------TCGTCACTGACGTTGC
TraesCS3D02G325400      CTGC-----------------------AAATGTC----------TCGTCACTGACGTTGC
                                                                                    

AT3G28070               AAGAGAAAACGCCTCTTC-----TATTAAACCGCAAAAACGACCAAGTTTAAAAAGAA--
TraesCS5B02G014100      GTGATCGATGAGCAGCCC----------------------GAGCAAGGAGGCAAGGAGAT
TraesCS5D02G021800      GTTTA-----------------------------AAAGCTGAATCATTTTTACTGGTGTT
TraesCS5A02G015800      AAGAAAAAAAAACAGGTA-----TCGCATAGCATACCGAGAGACTATGTTGAAATATACT
TraesCS1B02G267300      G-GTGCGGTGGTCTAGTG----------------------------CTCTGAGCAGTG--
TraesCS1A02G310300      ACGCACTACGGCCCCGTC----------------GGAATGGAGGTTTTCTGCTAGGAATC
TraesCS1B02G321500      ACGCACTACGGCCCCGTC----------------GAAATGGAGGTTTTCTGCTAGGAATC
TraesCS1D02G309800      ACGCACTACGGCCCCGTC----------------GGAATGGAGGTTTTCTGCTAGGAATC
TraesCS3A02G331900      ATGCACTAGGGCTGCATG------------------------ATAATTTTGCGCCGTGCC
TraesCS3B02G362000      ATGCACTAGGGCCGTGTGCGCTGCATGCAAGGGGAGAGTGGAATAATTTTGCGCCGTGCC
TraesCS3D02G325400      ATGCACTAGGGCCGTGTGCGCTGCATGCAAGGGGAGAGTGGAATAATTTTGCGCCGTGCC
                                                                                    

AT3G28070               ------------------AAAGAATATAGAC-----AATAAAACTACTAATAGTTAACAA
TraesCS5B02G014100      T---------------------AATT----------AAGCACACGGTGCACGATT-----
TraesCS5D02G021800      G-----------------GAGTAGTAGCTATGTACGGACCACGCAATC-ATGACCGTGAA
TraesCS5A02G015800      TCCCGCCTTCCTCCATC-----AATTCAGACTTTCGAATGA----GTTGATCGGTGCAAG
TraesCS1B02G267300      ------------------GTGGTAGT---------------AACAGT--AAGAGTATAA-
TraesCS1A02G310300      TCGTGCTGTTGTCC----GTGAAATTTCTGCTTTCCAAGCACACGACCCACCAGCATTAG
TraesCS1B02G321500      TCGTGCTGTTGTCC----GTGAAATTTCTGCTTTCCAAGCACACGACCCACCAGCATTAG
TraesCS1D02G309800      TCGTGCTGTTGTCC----GTGAAATTTCTGCTTTCCAAGCACACGACCCACCAGCATTAG
TraesCS3A02G331900      TTTTATTTTTGTCCTCTTGTATGATTTC-------------CACAACCAACGACTATATT
TraesCS3B02G362000      TTTTATTTTTGTCCTCTTGTATGATTTC-------------CACAACCAACGGCTATACT
TraesCS3D02G325400      TTTTATTTTTGTCCTCTTGTATGATTTC-------------CACAACCAACGACTATAGT
                                                                         *          

AT3G28070               ATACTGTTATTAATACCATATTTATAAAATTGTCTTATGTCTCTATGAACCTAGGAGTTG
TraesCS5B02G014100      ------------------------TTATTTTATTTTACTTTAGT-------AGGTAGGCT
TraesCS5D02G021800      TCGTCATG-------------------------------------------GGACGGCAT
TraesCS5A02G015800      CATTCAGAGAGATTCTCATGAAACTT-------------------------TAAGTGACA
TraesCS1B02G267300      ---CTGGTCTTCCTGGTGACGAACCT-------------------------------GGT
TraesCS1A02G310300      CCGCCAGAAGGGCTAGTAGCTCGCAT-TTTTGTTTTACGA-----------TGTGTGATT
TraesCS1B02G321500      CCGCCAGAAGGGCTAGTGGCTCGCAT-TTTTGTTTTACGA-----------AGTGTGATT
TraesCS1D02G309800      CCGCCAGAAGGGCTAGTGGCTCGAAT-TTTTGTTTTACGA-----------TGTGTGATT
TraesCS3A02G331900      ACCCCAGTACGCCCTGTACTTTTGTTCTTCTGTTTTAT----------------------
TraesCS3B02G362000      ACTCCAGTACGCCTTGTATTTTTCTT----GTTTTCATAT-----------CGGGGGA--
TraesCS3D02G325400      ACTCCAGTACGCCTTGTATTTTTCTTCTTCTTTTTTTTAT-----------CGGGGGA--
                                                                                    

AT3G28070               GAAAAAAATGTGTGTATTT------------AGATTTTTTTTTCAAAATACTCCAACATT
TraesCS5B02G014100      AATGGAAATAAT--------------------------TCACGCTTAATTTTCGACAGAA
TraesCS5D02G021800      TAATTAAACGAT-----------------------------------------GAGCATT
TraesCS5A02G015800      AACGCATACCATTGTAC------------------GGCTGATCTAATGTTGCACTGAACC
TraesCS1B02G267300      AAAACATATGCT-GTGA--------------GGAAGAGCTTTGTAACGTCTCTAGCTAAT
TraesCS1A02G310300      GATCGATATGCT-ACACTTAATTG-------TCACTAGTACTGCTACATCTCTGTCCATC
TraesCS1B02G321500      GATCGATATGCT-ACACTTATTTGTCACTACTCACTAGTACTGCTACATGTCTGTCCATC
TraesCS1D02G309800      GATCGATATGCT-ACACTTATTTG-------TCATTAGTACTGCTACATCTCTGTCCATC
TraesCS3A02G331900      ------------------------------------------------------------
TraesCS3B02G362000      GAAAGAAATGTT-GTGTTCCGGCA-------AGGG---------TATGCACGTGTTCATG
TraesCS3D02G325400      GAAAGAAATGTT-GTGCTCCGGCA-------AGGGGCATGTACCGATGTACGTGTTGGTG
                                                                                    

AT3G28070               TA-TAAATACGA-------GTTAACATTTTTCCTTGACTCCTTTGGAACATATGAAAAGC
TraesCS5B02G014100      TA-----------------AACTCTCTTACACC---------------------------
TraesCS5D02G021800      TC-----------------ATTT-------------------------------------
TraesCS5A02G015800      TAGGGACACTCCTTTCAAGAACCGATACGCAAGCTAATTTTCTTAGTGCAAAAGAAAGAG
TraesCS1B02G267300      TA-AGCCGATGCT------TTCTGT-----------------------------------
TraesCS1A02G310300      TC-GGAGAGTGATGTG---ATTCGCCTTTCCACTTTACCTGTCTATGATATTAAGTGTAT
TraesCS1B02G321500      TC-GGAGAGTGATGTG---ATTTGCCTTTCCACTTTACTTGTCTGTAATTTTAAGTGTAT
TraesCS1D02G309800      TC-GGAGAGTGATGTG---ATTTGCCTTTCCACTTTACTTGTCTA---------------
TraesCS3A02G331900      TA----------------------------------------------------------
TraesCS3B02G362000      TA-AGAGAATTTTGAGTG-GTTTATGATCC------------------------------
TraesCS3D02G325400      TA-AGAGAATTTTGAGTGTTTTTGTGATCCCGGCTTAATTTCGAAATAAATATCAGTTTG
                        *                                                           

AT3G28070               TTAAATTGATATTCTT----
TraesCS5B02G014100      --------------------
TraesCS5D02G021800      --------------------
TraesCS5A02G015800      CTTCATTAAT----------
TraesCS1B02G267300      --------------------
TraesCS1A02G310300      CAATGTTATGAGATTC----
TraesCS1B02G321500      CAATGTTATGAGATTCCAAG
TraesCS1D02G309800      --------------------
TraesCS3A02G331900      --------------------
TraesCS3B02G362000      --------------------
TraesCS3D02G325400      --------------------
                                            
