CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------ATAGCTAGCGGTCGAGTTACCAGG
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AATCCTGAGGCATTCATGATACGAGTGGGATGCATGAAGGGGTCGCTCGGTCGGCCTATG
TraesCS3D02G003600      -------AGGCATGCATGATAGGAGTGGGATGAAGG--------GGTCGGTCGGCCTATG
TraesCS3B02G011600      --------------------------------------------------TCGGCGTATG
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ACCATGCACGTCTGTC--CTGTGTCCGTCTACTGCTCCACGACAGGACAACCACACCGGG
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CCCATGCATGAAGGTCTTCTCCGACCAACCATCGCTCACTCCACTGTCTGCCTC------
TraesCS3D02G003600      CCCATGCATGAAGGTCTTCTCCGACCAACCATCGCTCACTTCACTGTCTGCCTC------
TraesCS3B02G011600      CCCATGCACCAAGGTCTTCTCCGACCAACCATGGCTCACTTCACTGTCTGCCTC------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      -------------------------ATGCGCA---------GCCCAAGCGAAG-------
TraesCS4D02G313000      CTAGCTG-----------CTGCTTCACCATCACC-------------------------A
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ATAGGTAGGAGAGGCCACCCAGAGGATGCG---CTAGTGGCAACAATGGCGCCCACTATG
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------CAGCAACAATGGCGACCACT--------------ATGGCAGT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      -TAGCTGAGTGTCACT--CTGTAGCATGCTTACCTACT---GTCCAAGTGGAATGTCG--
TraesCS3D02G003600      -TAGCTGAGTGTCACT--CTGTAGCATGCTCACCTACT---GTCCAAGTGGAATGTCGCG
TraesCS3B02G011600      -TAGCTGAGTGTCACTCTCTGTAGCATGCTCACCTACTGACGTCCAAGTGGAATGTCGCG
TraesCS3B02G006900      --AGCTGAGTGTCACTCTCTGTAGCATGCTCACCTACTGACGTCCAAGTGGAATGTCGCG
                                                                                    

TraesCS4A02G386700      ------------------------------------------GCAACCGACCTTGGCTTG
TraesCS4D02G313000      CAGCTATATA-------ACCTACGGCACCACCGCCTTTTATAAAGACAGGCTCTGCACTC
AT3G18200               -----------------------------------------------------------A
TraesCS3B02G026700      GCACTATATAT------ACCCCTGCACCCTCCAATTCCTCTCAACACAACCACAAGC--A
TraesCS3A02G019600      ------------------------------------------AACACAACCACAAGC--A
TraesCS3D02G027300      ACACTATATAT------ACCCCTGCACCCTCCAATTCCTCTCAGCAGAACCACAAGC--A
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      --TCTATATAG-TAGACACCCCTGGCTGCACTTCTCACTCACCTCATCCCTCCTGGCCTA
TraesCS3D02G003600      CGTCTATATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCAT---CCCTGGCCTA
TraesCS3B02G011600      CGTCTATATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCAT---CCCTGGCCTA
TraesCS3B02G006900      CGTCTATATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCAT---CCCTGGCCTA
                                                                                    

TraesCS4A02G386700      CACATATCTTCTTCTTGTTCCAGCGGCATGCGTGCGTGTGCGTCTTGGTGACTTGGTGTA
TraesCS4D02G313000      GGCGTTCTTCTTCGAT----------------CCAGTTCAAACCGAGCGACACCGATCAA
AT3G18200               AGCAATCCT-----------------------GATGTGC-TATCAAACTTCAAAAAAAA-
TraesCS3B02G026700      GTTAGTAATCTGCATTCTTTC-----------TCTGTACGTAGATCACT-----GACAAG
TraesCS3A02G019600      GTTAGTAATCTGTATTATTTC-----------TCTGTACGTAGATCGCT-----GACAAA
TraesCS3D02G027300      GTTAGCACCCCGCATTGTTTC-----------TCTG----TAGATCACT-----AACAGG
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      GGCCGTCCTCTCTCTCGTCTC-----------TCAGCGT-CACCTCGCTCC---AGCAGC
TraesCS3D02G003600      GGCCGTCCTCTCTCTCGTCTC-----------TCAGTGC-CACCTCGCTCC---AGCAGC
TraesCS3B02G011600      GGCCTTCCTCTCTCTAGTCTC-----------TCATCGC-CACCTCGCTCCAGCAGCAGC
TraesCS3B02G006900      GGCCTTCCTCTCTCTAGTCTC-----------TCATCGT-CACCTCGCTCCAGCAGCAGC
                                                                                    

TraesCS4A02G386700      CTCTA-------CTACGTGGTGG-----------------------------TATAGCGC
TraesCS4D02G313000      CTTGGGC-------------------------------------------------ATGG
AT3G18200               ------------------AAAGA-----------------------------AGAAGTA-
TraesCS3B02G026700      TTGTAGAGAGAAAGTGA-GGAGG-----------------------------AGAGATG-
TraesCS3A02G019600      TTGTAGA-----------GAGGG-----------------------------AGAGATG-
TraesCS3D02G027300      TTGTAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGGAGGAAGGAGGGAGAGATG-
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TTCGAGCTCGATC---------------------------------------TCAAGCG-
TraesCS3D02G003600      TTCTATCTCGATCTAGGGAGAGA-----------------------------TCAAGTG-
TraesCS3B02G011600      TTCTATCTCGATCTAGGGAGAGA-----------------------------TCAAGTG-
TraesCS3B02G006900      TTCTATCTCGATCTAGGGAGAGA-----------------------------TCAAGTG-
                                                                                    

TraesCS4A02G386700      GAGACAGAATAGA----------------------GAGCGCGATA-------------TA
TraesCS4D02G313000      CTGGAGGAGCTGC-----------------GACGGGGCTGCGAGGGCTGT----------
AT3G18200               GGAAAAGAAGAGCTCAAGAAGAAAAA-------GAGAAAATGGGGAAAG-----------
TraesCS3B02G026700      GGGAGGGATCAGC------AG------------GCGGGCGCGGCGGCGGCGCACCG----
TraesCS3A02G019600      GGGAGGGATCTGC------AGGCCGGTTTGGGTGCAGGCGCGGCGGCGGCGCACCG----
TraesCS3D02G027300      GGGAGGGATCAGC------AGGCAGGTGTAGGTGCAGGCGCGGCGGCGGCGCACCG----
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AGGAAAGGGCAGC------AGCAATG-------GCGGACGCGGTGGATGCCCGTCGGGTC
TraesCS3D02G003600      AGGAGAGGGT-GC------AGCAATG-------GCGGACGCGGTGGACGCCCGTCGGGTG
TraesCS3B02G011600      AGGAGAGGGT-GC------AGCCATG-------GCGGACGCGGTGGATGCTCGCCGGGTC
TraesCS3B02G006900      AGGAGAGGGT-GC------AGCCATG-------GCGGACGCGGTGGATGCTCGCCGGGTC
                                                                                    

TraesCS4A02G386700      TATGGGGAGCGGCAGGTTGTTGTTGCCGACGGTGGTGATGCTGGCGCTCAACGTGATGTC
TraesCS4D02G313000      -----------GGAGGAGGTACGCACCGCACAACATGATGATCATGGTGCAGCTGTGCTA
AT3G18200               -GAGTAGTATCAGAGAAGGTGAA-GCTCGTGGTGGCATTGATCACACTTCAGTTTTGTTT
TraesCS3B02G026700      -----------GGAGAAGGTGAA-GCTGTTCATGGGCGTGCTGGCGCTGCAGTTCCTGCT
TraesCS3A02G019600      -----------GGAGAAGGTGAA-GCTGTTCATGGGGGTGCTGGCGCTGCAGTTCCTGCT
TraesCS3D02G027300      -----------GGAGAAGGTGAA-GCTGTTCATGGGGGTGCTGGCGCTGCAGTTCCTGCT
TraesCS7A02G281700      -------------------------------------ATGCTGGCGCTGCAGTTCGGGTA
TraesCS3A02G007100      TGCGGGATGCCGGAGAAGGCGCA-GCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTA
TraesCS3D02G003600      TGCGGGATGCCGGAGAAGGCGCA-GCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTA
TraesCS3B02G011600      TGCGGGATGCCGGAGAAGGCGCA-GCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTA
TraesCS3B02G006900      TGCGGGATGCCGGAGAAGGCGCA-GCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTA
                                                              ** *     *  *  *      

TraesCS4A02G386700      CGCGGTG------ATGGTGGCGCTGGTCAAGGTGGCCATGGCCGGCGGCCTCGACCCGCT
TraesCS4D02G313000      CACCTTGATGTACTTCGTCACCGAGGCCGCCTTCAACCGG------GGGCTCAACCCCTA
AT3G18200               CGCAGGCTTCCACATTGTCTCAAGAGTTGCTCTTAACATT------GGTGTCAGCAAAGT
TraesCS3B02G026700      CGCCGGCTTCCACATCGTCAGCCGCGCCGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS3A02G019600      CGCCGGCTTCCACATCGTCAGCCGGGCGGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS3D02G027300      CGCCGGCTTCCACATCGTCAGCCGGGCGGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS7A02G281700      CGCCGGCTTCCACATGGTGTCACGTCTGGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS3A02G007100      CGCCGGCTTCCACGTCGTGTCGCGCCTCGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS3D02G003600      CGCCGGCTTCCACGTCGTGTCGCGCCTCGCGCTCAACATG------GGCATCAGCAAGCT
TraesCS3B02G011600      CGCCGGCTTCCACGTCGTGTCCCGCCTCGCGCTCAACATG------GGGATCAGCAAGCT
TraesCS3B02G006900      CGCCGGCTTCCACGTCGTGTCCCGCCTCGCGCTCAACATG------GGGATCAGCAAGCT
                        * *           * **              *   *         **  **  *     

TraesCS4A02G386700      CGTGCTCGTCACGCTGCAGCAGC-TCGCCGCCGCCATCTTCCTCTGCCCCATCGCGCACT
TraesCS4D02G313000      CGTCTACGTCAC-CTACCGCCACCTCCTCGTCGCCGTCCTCCTCTGGCCCTTCGCCTACT
AT3G18200               TGTGTACCCTGT-TTATAGGAATCTCCTTGCCCTTCTCCTCATAGGTCCCTTCGCTTACT
TraesCS3B02G026700      CGTCTTCATCGT-CTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACT
TraesCS3A02G019600      CGTCTTCATCGT-CTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACT
TraesCS3D02G027300      CGTCTTCATCGT-CTACCGCAACGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACT
TraesCS7A02G281700      CGTCTTGCCCGT-GTACCGCAACATCAT--------------------------------
TraesCS3A02G007100      CGTCTTCCCCGT-CTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACT
TraesCS3D02G003600      CGTCTTCCCCGT-CTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACT
TraesCS3B02G011600      CGTCTTCCCCGT-CTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACT
TraesCS3B02G006900      CGTCTTCCCCGT-CTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACT
                         **           *   *     **                                  

TraesCS4A02G386700      TCATAGAGGGGTGAGGGAGTCCACACGACATCCATCCATTT-------------------
TraesCS4D02G313000      ACCACGAGAAGTAATAAGCTCTTGCGTTCATCAATT------------------------
AT3G18200               TCTTCGAAAAGTAAGCCTCCACATCTTTCAGAGCTCTAGGG-CTTTTTGGTACGATCTCA
TraesCS3B02G026700      TCCTCGAGAAG---TACGTCGCCGCCTCCATTCTTCTTCTC-TGCTTCATCTTCCAGCAG
TraesCS3A02G019600      TCCTCGAGAAG---TACGTCCGCGCCTCCACCATTCTTCTT-CTCCGCTTCTTCTTCCAG
TraesCS3D02G027300      TCCTCGAGAAG---TACGTCCGCGCCTCCACCATTCTTCTCGATCTGCTTCTTCTTCCAG
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TCCTCGAGAA--------------------------------------------------
TraesCS3D02G003600      TCCTCGAGAA--------------------------------------------------
TraesCS3B02G011600      TCCTCGAGAA--------------------------------------------------
TraesCS3B02G006900      TCCTCGAGAA--------------------------------------------------
                                                                                    

TraesCS4A02G386700      ---------------------------------CGATTGCATGAAGCAACATATGTAGCC
TraesCS4D02G313000      ---------------------------------ACACCAGGAGATTCAGACTTTGGCGAT
AT3G18200               AGTTTGA--------------------------ATATTGTATTCTTTGGTTGATAGTACT
TraesCS3B02G026700      TTTCAAGAAAGCTTCTGCCAGTCAGTCAGAAAACAATGGCGGTGTACAGTTTTTTGAATC
TraesCS3A02G019600      ---------------------------------CAATGGTGGTGGACGGTTTTCTGAATC
TraesCS3D02G027300      ---------------------------------CAATGGCGGTGGACGGTTTTCTCAATC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      TTTCTCTCATCTTCGTGTTGATTGGTCTCATCCATCAGCAAGTCGAGGCCCAAGATGACG
TraesCS4D02G313000      ATGATGATGAATATGTGTTCATTTTT---GGGCGTCAGGAAGTTGAGGCCCAAGATGACC
AT3G18200               CTTACAATG-------------CTTTGTTTATCAACAGAAAAGAAAGACCTCCACTTACA
TraesCS3B02G026700      CTGG------CGTGTCTGTTCTTTTTTCCATCATTCAGGAAGGACCGGCCGCCGCTCACC
TraesCS3A02G019600      CTGGTAGTGTCTCTGTTTTTCTTCTTCTTCTTCTTCAGGAAGGACAGGCCGCCGCTCACC
TraesCS3D02G027300      CTGG---------TGTGTTTGTTCTTTTTTTTCTTCAGGAAGGACCGGCCGCCGCTCACC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      --------------------------------------GAAGGACCGGCCGAGGCTCACC
TraesCS3D02G003600      --------------------------------------GAAGGACCGCCCCAGGCTCACC
TraesCS3B02G011600      --------------------------------------GAAGGACCGACCCAGGCTCACC
TraesCS3B02G006900      --------------------------------------GAAGGACCGCCCCAGGCTCACC
                                                                                    

TraesCS4A02G386700      CTCCAGATCTTCGCCTACCTCTTCGTCAGCGCCGCGCTCGGGTACTTTTCCATTCATTGA
TraesCS4D02G313000      TGGATGCTGTTCCTGGAGATCTTCGTGC---TCTCACT------------TCTAGGGTAA
AT3G18200               ATCTCTTTACTGGCTCAGTTCTTCTTCT---TGGCACTCATAGGGTATAGCTTAACCTGA
TraesCS3B02G026700      TTCTCGCTGCTGGCGGAGTTCTTCGTGC---TGGCGCT----------------------
TraesCS3A02G019600      TTCTCGCTGCTGGCCGAGTTCTTCGTGC---TGGCGCT----------------------
TraesCS3D02G027300      TTCTCGCTGCTGGCGGAGTTCTTCGTGC---TGGCGCT----------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CTCAGCTTCGCCGTCCAGTTCTTCTTCC---TCGCCCT----------------------
TraesCS3D02G003600      CTCGGCTTCGCCGTCCAGTTCTTCTTCC---TCGCCCT----------------------
TraesCS3B02G011600      CTCGGCCTCGCCGTCCACTTCTTCTTCC---TCGCCCT----------------------
TraesCS3B02G006900      CTCGGCCTCGCCGTCCACTTCTTCTTCC---TCGCCCT----------------------
                                                                                    

TraesCS4A02G386700      TCAAATCTTCTCCGTTTGATCTTCAAATCAACAACGTTTGGATCATATGGTGTACACGAT
TraesCS4D02G313000      GAAGAAGAACCGCTGAGAAGAGTGCATATATACGTAGATGAACATTTGTCTAGTGATCCT
AT3G18200               GAACACAATAATAAGAACCGATTCCTCAATCCTTAAATCAATGATTATAATGCTGAAACT
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      CGATCTTGCATGGTGGCACGCAGAGCGGCGATGAGGCAGTACATGGTCTTCGTGGGGCTG
TraesCS4D02G313000      GAGAGGAAGTCGGATTTTTGCAGGGTGAGCTTGACCCTGAACATGTACTTCGCGAGCCTC
AT3G18200               TTGCTTGTGTATTTTAACATCAGCATCACAGCGAACCAAGGATTCTACCTATTAGGACTT
TraesCS3B02G026700      -----------------CATCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTG
TraesCS3A02G019600      -----------------CATCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTG
TraesCS3D02G027300      -----------------CATCGGGATCACGGCGAACCAGGGGTTCTACCTGCTGGGGCTG
TraesCS7A02G281700      ----------------------------------AGCAGGGCTTCTGCCTGCTGGGCCTG
TraesCS3A02G007100      -----------------CTGCGGCATCACCGCCAACCAGGGCTTCTACCTGCTCGGCCTC
TraesCS3D02G003600      -----------------CTGCGGCATCACCGCCAACCAGGGCTTCTACCTCCTGGGCCTC
TraesCS3B02G011600      -----------------CTGCGGCATCACCGCCAACCAGGGCTTCTACCTCCTCGGCCTC
TraesCS3B02G006900      -----------------CTGCGGCATCACAGCCAACCAGGGCTTCTACCTCCTCGGCCTC
                                                            *      *   * *     * ** 

TraesCS4A02G386700      CGCTACACCACGGCGACCTTCGTCAGCGCCTTTTCCAACATCGCGCCCGTGCTCACCTTC
TraesCS4D02G313000      AAGTACACGTCCCCGACCTTCGTCACCTCCATGGTCAACACCGTGGCCTCCATCACATTC
AT3G18200               TACTATGCAACTCCAACTTTTGCTTCCGCAATGCAGAACTCTGTTCCTGCCATCACTTTC
TraesCS3B02G026700      TACCACCTGTCGCCGACCTACGCCTCCGCGATCCAGAACATGGTGCCGGCCATCACCTTC
TraesCS3A02G019600      TACCACCTGTCGCCGACGTACGCGTCGGCGATCCAGAACATGGTGCCCGCCATCACCTTC
TraesCS3D02G027300      TACCACCTGTCGCCGACCTACGCGTCGGCGATCCAGAACATGGTGCCAGCCATCACCTTC
TraesCS7A02G281700      GACAACACGTCGCCGACGTTCGCCTCCGCCATCTAGAACTCCGTGCCGGCCATCACCTTC
TraesCS3A02G007100      GACAACACCTCCCCCACCTTCGCCTCCGCCATCCAGAACTCCGTGCCGGCCATCACCTTC
TraesCS3D02G003600      GACAACACGTCCCCCACCTTCGCCTCCGCCATCCAGAACTCCGTGCCCGCCATCACCTTC
TraesCS3B02G011600      GACAACACCTCCCCCACCTTCGCCTCCGCCATCCAGAACTCCGTTCCGGCCATCACCTTC
TraesCS3B02G006900      GACAACACCTCCCCCACCTTCGCCTCCGCCATCCAGAACTCCGTTCCGGCCATCACCTTC
                            *     *  * ** *  *      *  *    ***   *   *     **** ***

TraesCS4A02G386700      GTGCTCGC------------------------CGTCGCCACCC-----------------
TraesCS4D02G313000      GTCATCGC------------------------CATCGCGCTCC-----------------
AT3G18200               ATCATGGCTTGTGCCTTAAGGTACCCTAGCAACTTCGTCCTCCTAGAAATACCATTCTAA
TraesCS3B02G026700      GTGCTGGC------------------------CGCGGTCCTCC-----------------
TraesCS3A02G019600      GTGCTGGC------------------------CGCGGTCCTCC-----------------
TraesCS3D02G027300      GTGCTGGC------------------------CACGGTCCTCC-----------------
TraesCS7A02G281700      GCCATGGC------------------------CGCCGCGCTCC-----------------
TraesCS3A02G007100      GGCATGGC------------------------CGCCGCGCTCC-----------------
TraesCS3D02G003600      GGCATGGC------------------------CGCCGCGCTCC-----------------
TraesCS3B02G011600      GGCATGGC------------------------CGCCGCGCTCC-----------------
TraesCS3B02G006900      GGCATGGC------------------------CGCCGCGCTCC-----------------
                            * **                        *   *    **                 

TraesCS4A02G386700      ----------------------------------------------GCTCCGAGTCGCTC
TraesCS4D02G313000      ----------------------------------------------GGATGGAGATCGTG
AT3G18200               TCATTTTCATGGCTGGGTCTAACATTGATCTTCCTCTATGAATCAAGGCTAGAGCACATA
TraesCS3B02G026700      ----------------------------------------------GGCTGGAGCAGGTG
TraesCS3A02G019600      ----------------------------------------------GGCTGGAGCAGGTG
TraesCS3D02G027300      ----------------------------------------------GGCTGGAGCAGGTG
TraesCS7A02G281700      ----------------------------------------------GGATCGAGAAGGTG
TraesCS3A02G007100      ----------------------------------------------GCATCGAGAAGGTG
TraesCS3D02G003600      ----------------------------------------------GCATCGAGAAGGTG
TraesCS3B02G011600      ----------------------------------------------GCATCGAGAAGGTG
TraesCS3B02G006900      ----------------------------------------------GCATCGAGAAGGTG
                                                                      *    ***    * 

TraesCS4A02G386700      CACCTCAGGGCCGCCAC--CGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTCGCTCGCCG
TraesCS4D02G313000      GACCTG--CGCAGCGCGCGGGGCCTCGCCAAGGTGGCCGGCACGGCGGTGTCCTTCGCGG
AT3G18200               GACCTG--GTCAGGAAACATGGTGTGGCAAAAGTATTGGGAACTCTTGTGAGCATCGGTG
TraesCS3B02G026700      GACCTG--GGCCGGCGGCATGGGGTGGCCAAGGTGGTGGGCACGGTGGTGAGCATCGGCG
TraesCS3A02G019600      GACCTG--GGCCGGCGGCACGGGGTGGCCAAGGTGGTGGGCACGGTGGTGAGCATCGGGG
TraesCS3D02G027300      GACCTG--GGCCGGCGGCACGGGGTGGCCAAGGTGGTGGGCACCGTGGTGAGCATCGGCG
TraesCS7A02G281700      CGGCTC--GACCGGCGCGACGGCGTGGCCAAGGTGGTGGGCACGCTGGCGTGCGTGGCGG
TraesCS3A02G007100      CGGCTC--GACCGCCGCGACGGCGTCGCCAAGGTGCTGGGCACGCTCGCGTGCGTCGCCG
TraesCS3D02G003600      CGCCTC--GACCGCCGCGACGGCGTCGCCAAGGTGCTGGGCACCCTCGCGTGCGTCGCGG
TraesCS3B02G011600      CGCCTC--GACCGCCGCGACGGCGTCGCCAAGGTGCTGGGCACGCTCGCGTGCGTCGCAG
TraesCS3B02G006900      CGCCTC--GACCGCCGCGACGGCGTCGCCAAGGTGCTGGGCACGCTCGCGTGCGTCGCAG
                           **     * *       **    ** **  *    ** **    *      * *  *

TraesCS4A02G386700      GCGCCATGCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACC---CAAACAGCGCCC
TraesCS4D02G313000      GGGTCACCACCATGACGCTGTACAAGGGCGCGGCGATCGCGAGCC------------CCT
AT3G18200               GAGCCACCGTGATCACATTGTACAGAGGATTTCCGATATTTGACC--AGGGCCTTAACAT
TraesCS3B02G026700      GCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCC--ACAACCTGCACGT
TraesCS3A02G019600      GCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCC--ACAACCTGCACGT
TraesCS3D02G027300      GCGCCACGGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCC--ACAACCTGCACGT
TraesCS7A02G281700      GCGCATCGGTGATCATGTTGTACAAGGGCCCAACCATCTTCGGCC---CTGCCGGCGCCG
TraesCS3A02G007100      GCGCGTCCGTCATCACGCTCTACCAGGGCCCAACCATCTTCGCCC------CTGCCGACG
TraesCS3D02G003600      GCGCGTCCGTCATCACGCTCTACCAGGGCCCAACCATCTTCGCCCCTACCGCCGGCGACG
TraesCS3B02G011600      GCGCGTCCGTCATCACGCTCTACCAAGGCCCCACCATCTTCGCCC---CTACCGGCGACG
TraesCS3B02G006900      GCGCGTCCGTCATCACGCTCTACCAAGGCCCCACCATCTTCGCCC---CTACCGGCGACG
                        * *         * *   * ***   **     *  *      **               

TraesCS4A02G386700      ACCAGCTCCACCGCTCCCCTTCATCCCCGCCGTCGC--CAGGA---GCGGACTCCGGCAG
TraesCS4D02G313000      GGAGG---------------------GCGCCGGTGC-----------ACATCCCCAGCGG
AT3G18200               GCAAA----------------------------------AGGAAGA---------GGTGG
TraesCS3B02G026700      GCAGG---------------------CCGTGCTCTC--CTGGA-------CCTCCGGCAG
TraesCS3A02G019600      GCAGG---------------------CCGTCCTCTC--CTGGA-------CCTCCGGCAG
TraesCS3D02G027300      GCAGG---------------------CCGTCCTCTC--CTGGA-------CCTCCGGCAG
TraesCS7A02G281700      GCGAC------------------GATAAGTCGTTGC------AGGTGCCGTTTTTGGTAG
TraesCS3A02G007100      ACAAG---------------------CCGTCGTTGCAGCAGGAGGTGCCGTTTCTGGCGG
TraesCS3D02G003600      ACAAG---------------------CCGTCGTTGC---AGGAGGTGCCGTTTCTGGCCG
TraesCS3B02G011600      ACAAG---------------------CCGTCGTTGCAGCAGGAGGTGCCGTTTCTGGCGG
TraesCS3B02G006900      ACAAG---------------------CCGTCGTT---GCACGAGGTGCCGTTTCTGGCGG
                                                                                *  *

TraesCS4A02G386700      GCGG-------------------TGGACGCTTGGCACGGTGGCGATCCTCGGCAACTGCG
TraesCS4D02G313000      CGGCGAC-GCCGCGCACAACGCCTGGCTCAAGGGGTCGCTCCTCGCCGTGGCCAGCTGCG
AT3G18200               TCGGATCTGACAACTCGCACAGCTTGACACTCGGATGGTTATACCTTATGGGACATTGTC
TraesCS3B02G026700      CCCCATCTT----------CAACTGGACCCTCGGCTGCGTCTTCATCCTCGGCCACTGCC
TraesCS3A02G019600      CCCCATCTT----------CAACTGGACGCTCGGCTGCGTCTTCATCCTCGGCCACTGCC
TraesCS3D02G027300      CCCCATCTT----------CAACTGGACCCTAGGCTGCGTCTTCATCCTCGGCCACTGCC
TraesCS7A02G281700      CGGTGGCCGGGGAGGGGAAGAACTGGACGCTGGGGTGCGTGTACCTTATCGGGCACTGCC
TraesCS3A02G007100      CCGTGGCTGGGGAGGGCAAGAACTGGACGCTGGGGTGCGTGTACCTCATCGGCCACTGCC
TraesCS3D02G003600      CCGTGGCCGGGGAGGGCAAGAACTGGACGCTGGGCTGCGTCTACCTCATCGGCCACTGCC
TraesCS3B02G011600      CCGTGGCCGGGGAGGGCAAGAACTGGACGCTGGGGTGCGTCTACCTCATCGGCCACTGCC
TraesCS3B02G006900      CCGTGGCCGGAGAGGGCAAGAACTGGACGCTGGGGTGCGTCTACCTCATCGGCCACTGCC
                                               * *      **     *        * *     **  

TraesCS4A02G386700      TCTGCCTCGCCTGCTGGTACCTGCTCCAGGGCAGGATCACCAGGAAGTACCCCTACGTCT
TraesCS4D02G313000      TGTGCTGGTCCGTCTGGTACATCATGCAGGCCACGTCCGTGAAGCGGTACCCGGCGGAGC
AT3G18200               TGTCATGGGCTGGTTGGATGGTTCTTCAAGCTCCTGTTCTAAAGCAATACCCGGCGAAGC
TraesCS3B02G026700      TCTCCTGGTCGGGATGGATGGTGCTCCAGGTGCCCGTGCTCAAGCGGTACCCGGCGAGGC
TraesCS3A02G019600      TCTCCTGGTCGGGATGGATGGTGCTCCAGGTGCCGGTCCTCAAGCGGTACCCGGCGCGCC
TraesCS3D02G027300      TCTCCTGGTCCGGCTGGATGGTGCTCCAGGTGCCGGTGCTCAAGCGGTACCCGGCGAGGC
TraesCS7A02G281700      TGTCGTGGTCCGGCTGGCTGGTGCTGCAGGCACCGGTGCTTAAGAAGTACCTCGCGAGGC
TraesCS3A02G007100      TCTCGTGGTCCGGCTGGCTGGTGCTGCAGGCGCCCGTGCTCAAGAAGTACCCCGCGAGGC
TraesCS3D02G003600      TCTCGTGGTCCGGCTGGCTGGTGCTGCAGGCGCCCGTGCTCAAGAAGTACCCCGCGAAGC
TraesCS3B02G011600      TCTCGTGGTCCGGCTGGCTGGTGCTGCAGGCTCCCGTGCTCAAGAAGTACCCCGCGAGGC
TraesCS3B02G006900      TCTCGTGGTCCGGCTGGCTGGTGCTACAGGCACCCGTGCTCAAGAAGTACCCCGCGAGGC
                        * *      *    ***    *  * ** *           * *   ****         

TraesCS4A02G386700      ACTCCTGCAACGCCTTCCTGTCCACCTTCAGCTTCCTCCAGGTCGTCGTCGTCGGCCTCT
TraesCS4D02G313000      TGTCGCTGACGGCGTGGATGGCCACGGTGGGCGGGGTCCAGTCGCTGGCCTTCGCGGTGC
AT3G18200               TCACTTTAACATCCTTCACATGTTTCTTTGGTCTGATTCAGTTTCTGGTTATTGCTCTCT
TraesCS3B02G026700      TGTCGGTCATCTCGCTCACCTGCGTCTTCGGGCTGCTCCAGTTCCTCGTCATCGCCGCCT
TraesCS3A02G019600      TCTCGGTGATCTCCCTCACCTGCGTCTTCGGGCTACTCCAGTTCCTCGTCATCGCCGCCT
TraesCS3D02G027300      TGTCGGTCATCTCGCTCACCTGCGTCTTCGGGCTGCTCCAGTTCCTCGTCATCGCCGCCT
TraesCS7A02G281700      TGTCAGTCACCTCCTACACCTGCTTCTTCGGTGTCATCCAGTTCCTCGTCATCGCCGCCT
TraesCS3A02G007100      TGTCCGTCACCTCCTACACCTGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCT
TraesCS3D02G003600      TGTCCGTCACCTCCTACACCTGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCT
TraesCS3B02G011600      TGTCGGTCACCTCCTACACCTGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCT
TraesCS3B02G006900      TGTCGGTCACCTCCTACACCTGCTTCTTCGGCGTCATCCAGTTCCTCATCATCGCCGCCT
                           *    *   *              *  *     * ***    *     * *      

TraesCS4A02G386700      GCGTGAAGCACAACCTCGCCTCCTGGATCATCACCAACAAGCTCCAGATCCTCACCATCC
TraesCS4D02G313000      TGCTGCAGCACGAGAGGCAGGACTGGCTCATCGGCTTCGGCCTCAAGTTCTGGTGCATCA
AT3G18200               TTGTGGAAACTGATCTAAATAATTGGATCATCGTCTCTTGGGAAGAGCTCTTCACCATCC
TraesCS3B02G026700      TCACCGAGGAGGACATGAGCCGGTGGAAGGTGCAGTCCGTCGGGGAGCTCTTCACCATCC
TraesCS3A02G019600      TCACGGAGGAGGACCTGAGCCGGTGGAAGGTGCGGTCCGGCGGGGAGCTCTTCACCATCC
TraesCS3D02G027300      TCACCGAGGAGGACCTCAGCCGGTGGAAGGTGCAGTCCGGCGGGGAGCTGTTCACCATCC
TraesCS7A02G281700      TCTTCGAGAGGGACGCCGGCGCGTGGGTTTTCCACTTCGGCTCCGAAATCTTCACCATCC
TraesCS3A02G007100      TCTTCGAGAGGGATGCCGGCGCCTGGGTCTTCCACTCCGGCTCCGAAGTCTTCACCATCC
TraesCS3D02G003600      TCTTCGAGAGGGACGCCGGCGCATGGGTCTTCCACTCCGGCTCCGAAGTCTTCACTATCC
TraesCS3B02G011600      TCTTCGAGAGGGACGCCGGCGCATGGGTCTTCCAGTCCGGCTCCGAAGTCTTCACCATCC
TraesCS3B02G006900      TCTTCGAGAGGGACGCCGGCGCCTGGGTCTTCCACTCCGGCTCCGAAGTCTTCACCATCC
                              *     *          ***    *              *  *       *** 

TraesCS4A02G386700      TCTACTCCGTAAGCTTCTG-----------------------------------------
TraesCS4D02G313000      TCTACTCCGTACGCGCCTGCCCTTGTCTCTCTCAGATTATTACCGTC-------------
AT3G18200               TATACGCCGTAAGCTCCCTCCCTCTGTCTCTCT---------------------------
TraesCS3B02G026700      TCTACGCCGG--------------------------------------------------
TraesCS3A02G019600      TCTACGCGGG--------------------------------------------------
TraesCS3D02G027300      TCTACGCGGG--------------------------------------------------
TraesCS7A02G281700      TCTACGCCGTAAGCA---------------------------------------------
TraesCS3A02G007100      TCTACGCCGTAAGCATATTCATTAGTATCTTATACAATTTCGCAGTTAAGAATTAACTAC
TraesCS3D02G003600      TCTACGCCGTAAGCATTT--ATTAGTGTCCTATATAATTTCGCAGTTAAAAATTAATTAC
TraesCS3B02G011600      TCTACGCCGTAAGCATTTCTATTAGCACCCTATATAATTTCGCAGTTAAGAGTTAGTTGT
TraesCS3B02G006900      TCTACGCCGTAAGCATTTCTATTAGCACCCTATATAATTTCGCAGTTAAGAGTTAGTTGT
                        * *** * *                                                   

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TCCGTCTCATAACATAACATAAGAACGTTTATATAA------------------------
TraesCS3D02G003600      TCC-TTCCATCTCATAATATAAAAGCGTTTTTTTACACTAGTACTTTCTTCGTAAACTAA
TraesCS3B02G011600      T-----------------------------------------------------------
TraesCS3B02G006900      T-----------------------------------------------------------
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ----------------------TATATATTAGACCTGGAATCTCAATCACGTACTAAT--
TraesCS3D02G003600      TATAAAAGATGATCTAAACGCTCTTATATTAGGCCTGGAATCCCAATCACATACTAATTA
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      -----------------------AATTGCTTGCGACGGTATGCC----------------
TraesCS4D02G313000      ---TTCTCCCCCGTCCTCCATGTCACTC--------------------------------
AT3G18200               ---CTCTTCCTTTTCCTTGATCTGAATC--AATGGAAATTAGCTAAATGA----------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ---GCGCATCCTAACTAAGTCGCACTTA--------------------------------
TraesCS3A02G007100      -TACTACTCTCTATCTGTGGTGCAAATG-ATACGATAATTTGCTAAAGGAGTAGAGGTAA
TraesCS3D02G003600      CTACTACTCTCTATCTGAGGTGCAAATGAAAATGATAATTTGCTAAAGGAGTAGAGGTAA
TraesCS3B02G011600      -TTCTACTCTCCGTCTGTGGTGCAAATG-ATACGATAATTTGCTAAAGGACTAGAGGTAA
TraesCS3B02G006900      -TTGTACTCTCCGTCTGTGGTGCAAATG-ATACGATAATTTGCTAAAAGACTAGAGGTAA
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ACAAATTGATTTAAAAGTGGTGCAATGCAACAACCTGT----ACACCTCTCTGCCAGGAT
TraesCS3D02G003600      ACAAATTTA-TTAAAAGTGGTGCAATGCAACAACCTGTACACCTCTCTCTCTGTCAGGAT
TraesCS3B02G011600      ACAAATTTA-TTAAAAGTGGTGCAATGCAACAACCTTT---TACACCTCTCTGTCAGGAT
TraesCS3B02G006900      ACAAATTTA-TTAAA---------------------------------------------
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ------------------------------------------------------------
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS3A02G019600      ------------------------------------------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CAACGATCTGTAGCAGTACTCCTTTAGCAAATTATAGTATTATTTTATTCAGTGTAAATA
TraesCS3D02G003600      CACCGATCTGCACCAGTACTCCTTTAGCAAACTATAGTATTATTTTATTCAGTGTAAATA
TraesCS3B02G011600      CACCGAT---TAGCAGTACTCCTTTAGCAAATTATAGTATTATTTTATTCAGTGTAAATA
TraesCS3B02G006900      -----------AGCAGTACTCCTTTAGC--------------------------------
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------GCCGAT
TraesCS4D02G313000      ----------------------------GCCATGCATGTAGCCAGTGCTCATGAACTGCG
AT3G18200               ----------------------------ATGTTCC-------------------TTTGGC
TraesCS3B02G026700      ------------------------------------------------------GCTGGT
TraesCS3A02G019600      ------------------------------------------------------GCTGGT
TraesCS3D02G027300      ------------------------------------------------------GCTGGT
TraesCS7A02G281700      ------------ATTAGTGGAAGCCATGATGATCCATGCCTCGGATCTTAA---GCTGCC
TraesCS3A02G007100      TATATCAAGTCAGTGAGTGGAAGGCATGATGATCCATGTCTCAGATCTTAA---GCTGCT
TraesCS3D02G003600      TACATCAAGTCAGTGAGTGGAAGGCATGATGATCCATGTCTCAGATCTTAAGCTGCTGCT
TraesCS3B02G011600      TATATCAAGTCACTGAGTGGAAGGCATGATGATCCATGTCTCAGATCTTAA---GCTGCT
TraesCS3B02G006900      -ATATCAAGTCAGTGAGTGGAAGGCATGATGATCCATGTTTCAGATCTTAA---GCTGCT
                                                                                 *  

TraesCS4A02G386700      CGT---------------------CGTAACTGATTAATTGTGCCTGA-------------
TraesCS4D02G313000      CGC----------------------GTGCACGA---------------------------
AT3G18200               CGT---------------------------------------------------------
TraesCS3B02G026700      GGC---------------------------------------------------------
TraesCS3A02G019600      GGC---------------------------------------------------------
TraesCS3D02G027300      GGC---------------------------------------------------------
TraesCS7A02G281700      TGC-TTTTGACTCTCAAAGAGATATGGAAATGATTATGTTGGCCTATGCATATATCGCGA
TraesCS3A02G007100      TGC-TTTTGACTCTC-AAGAGATATGGAAATGATTATGCAAACGGAA-------------
TraesCS3D02G003600      TGC-TTTTGACTCTC-AAGAGATATGGAAATGATTATGCAAATGTAA-------------
TraesCS3B02G011600      TGC-TTTTGACTCTC-AAGAGATATGCAAATGATTACGCAGACGTAA-----------GG
TraesCS3B02G006900      TGCTTTTTGACTCTC-AAGAGATATGGAAATGATTATGCAGACGTAA-----------GG
                         *                                                          

TraesCS4A02G386700      -------------------ACTGAAT-------------GAATTCAGGGCGTGGTGGCGA
TraesCS4D02G313000      ---------------------------------------ACGTGCAGGGGC---TCGCGT
AT3G18200               ---------------------------------------GTTTACAGGGAATAATAGCGT
TraesCS3B02G026700      ----------------------------------------------------------CT
TraesCS3A02G019600      ----------------------------------------------------------CT
TraesCS3D02G027300      ----------------------------------------------------------CT
TraesCS7A02G281700      GCTAGCAGCTGACATGGCAAATGAAAACGGTG---------ATGCAGGGCTTCATCGCGT
TraesCS3A02G007100      GGTGGCAGCTGACATGGCAAATGAAAACGGTAATATAT-ACATGCAGGGCTTCATCGCGT
TraesCS3D02G003600      GCTGGCTGCTGACATGGCAAATGAAAACGGTAATATATAATATGCAGGGCTTCATCGCCT
TraesCS3B02G011600      CGTGGCAGCTGACATGTCAAATGAAAACGGTAATATAT-GCATGCAGGGTTTCATCGCGT
TraesCS3B02G006900      CGTGGCAGCTGACATGTCAAATGAAAACGGTAATATAT-ATATGCAGGGTTTCATCGCGT
                                                                                    

TraesCS4A02G386700      CGGGCA------TGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAGCGGGGGGCGGTGT
TraesCS4D02G313000      GCAGCGGGTTCACGGTGTTCGC---GCAGCTGTGGTGCACAGAGAAGAAGGGCCCCGTGT
AT3G18200               CAGGGT------TGGTGGTTTATCTTCAAACATGGTGTATCTACAAAAGCGGTCCAGTTT
TraesCS3B02G026700      CCGGCG------TGGCGTTCGCCCTGCAGATCTGGTGCATCGACCGCGGCGGCCCGCTCT
TraesCS3A02G019600      CCGGCG------TGGCGTTCGCGCTGCAGATCTGGTGCATCGACCGCGGGGGCCCGCTCT
TraesCS3D02G027300      CCGGCG------TGGCGTTCGCGCTGCAGATCTGGTGCATCGACCGCGGCGGCCCGCTCT
TraesCS7A02G281700      CCGGCG------TGGCGTTCGCCGTGCAGATCTGGTGCATCGACCACGGGGGGCCGGTGT
TraesCS3A02G007100      CCGGCG------TGGCGTTCGCAGTGCAGATCTGGTGCATCGACCGCGGGGGCCCGGTGT
TraesCS3D02G003600      CCGGCG------TGGCGTTCGCAGTGCAGATATGGTGCATCGACCGCGGGGGCCCGGTGT
TraesCS3B02G011600      CCGGCG------TGGCGTTCGCAGTGCAGATCTGGTGCATCGACCGCGGGGGCCCGGTGT
TraesCS3B02G006900      CCGGCG------TGGCGTTCGCAGTACAGATCTGGTGCATCGACCGCGGGGGCCCGGTGT
                           *         *    *       *     ***** *   *       **  *  * *

TraesCS4A02G386700      TCGTCGCCGCCTTCGTCCCGGTGTCGCAGGTCATCGTCTGCATCATGGACTTCACCGTCC
TraesCS4D02G313000      TCGTCACCATGTTCAACCCGGTGTCCACCATCATGGTGGCCATCCTCGCCTACTTCATCT
AT3G18200               TTGTCGCTGTTTTCCAGCCTCTCCAGACACTTCTTGTTGCTGCGATGGCGTTTCTTATTC
TraesCS3B02G026700      TCACCGCCGTGTTCCAGCCCGTGCAGACCGTCGCCGTCGCCGTCATGGCCGCCATCATCC
TraesCS3A02G019600      TCACCGCCGTCTTCCAGCCCGTGCAGACCGTCGCGGTCGCCGTCATGGCCGCCATCATCC
TraesCS3D02G027300      TCACCGCCGTGTTCCAGCCCGTGCAGACCGTCGCCGTCGCCGTCATGGCCGCCGTCATCC
TraesCS7A02G281700      TCGTGGCGGTGTACCAGCCTGTGCAGACGCTCGTCGTCGCCATCATGGCCTCCATCACCC
TraesCS3A02G007100      TTGTGGCGGTGTACCAGCCCGTGCAGACGCTGGTCGTCGCCATCATGGCCTCCCTCACCC
TraesCS3D02G003600      TCGTGGCCGTGTACCAGCCCGTGCAGACGCTCGTCGTCGCCATCATGGCCTCCCTCACCC
TraesCS3B02G011600      TCGTGGCCGTGTACCAGCCCGTGCAGACGCTCGTCGTCGCCATCATGGCCTCCCTCACCC
TraesCS3B02G006900      TCGTGGCCGTGTACCAGCCCGTGCAAACGCTCGTCGTCGCCATCATGGCCTCCCTCACCC
                        *     *    * *   **  *        *    **        * *            

TraesCS4A02G386700      TGCATGAACCGCTCTACCTTGGAAGGTGCAAACATACATACTGCTTACCCATGGCATGGC
TraesCS4D02G313000      TCGGCGAGAACCTATACGTCGGAAGGTACGTAGTAGTACATGCGTGCGGTGCATGCTTGC
AT3G18200               TTGGTGATCAGTTATACTCGGGAGGGTAAGCGCATTGAAAACGGGATGTATCGGGTTTTG
TraesCS3B02G026700      TCGGAGACCAGCTCTACACCGGAGGGTAAGTAGAGAGTAA-----------AATCCACAT
TraesCS3A02G019600      TCGGCGACCAGCTCTACACCGGAGGGTAAGCACGGAGATA----------CAATCCACAT
TraesCS3D02G027300      TCGGCGACCAGCTCTACACCGGAG------------------------------------
TraesCS7A02G281700      TCGGAGAGAAGTTCTACCTCGGCG------------------------------------
TraesCS3A02G007100      TCGGCGAGAAGTTCTACCTCGGCG------------------------------------
TraesCS3D02G003600      TCGGCGAGAAGTTCTACCTCGGCG------------------------------------
TraesCS3B02G011600      TCGGCGAGAAGTTCTACCTCGGCG------------------------------------
TraesCS3B02G006900      TCGGCGAGAAGTTCTACCTCGGCG------------------------------------
                        *    **     * ***   **                                      

TraesCS4A02G386700      ATGGCGTGATTGGCATCTGACACTCATGCTTTGC--------------------------
TraesCS4D02G313000      CTCTGCTCAGCTCAACTAAATCGGTGCTCCATTCCGGCATGGCACGGCAACCTGGACACA
AT3G18200               TTTCTCTCGATTACTCGATCTAATAGAATCTTTTTGGC----------------------
TraesCS3B02G026700      ACACCAACATTGTGACAGCACCATTGCACTCTTG--------------------------
TraesCS3A02G019600      ACACGAGCATTTTGACAGCACCATTGCACTTGTC--------------------------
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      ACATGCGCATGAGCGCCCGTGCTCTGCTGCGTGCGTGCGTGCACCAACTATGTGTGTCTC
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      --------------------------------------------------------TCTG
TraesCS3A02G019600      ----------------------------------------------------------TG
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

TraesCS4A02G386700      ---------AAACGTGTATGCATGCATGCAGTGTGGTGGGATCTGTGATTGTGATATGTG
TraesCS4D02G313000      ACCAGCCTAATTACTGTTGCTAATGAACCAGCATAATCGGAGGAGTGGTGGTCATCCTGG
AT3G18200               ------------------------TTTGCAGGATTGTTGGTGCAGTGTTTATAATGCTAG
TraesCS3B02G026700      ACTGACATGATTCATGGCTGCTTGTGCGCAGGATCATCGGCGCGGTGCTGATCGTCATCG
TraesCS3A02G019600      ACTGACATGATCCATGGCTGCTTGTGCGCAGGATCATCGGCGCGGTGCTGATCGTCATCG
TraesCS3D02G027300      ------------------------------GGATCATCGGCGCGGTGCTGATCGTCATCG
TraesCS7A02G281700      ------------------------------GGATCATCGGCGCCGCGCTCATCATCACCG
TraesCS3A02G007100      ------------------------------GGATCATCGGCGCCGCGCTCATCATCACCG
TraesCS3D02G003600      ------------------------------GGATCATCGGTGCCGCGCTCATCATCACCG
TraesCS3B02G011600      ------------------------------GGATCATCGGCGCCGCGCTCATCATCACCG
TraesCS3B02G006900      ------------------------------GGATCATCGGCGCCGCGCTCATCATCACCG
                                                      *  *  * **    * * *  *  *    *

TraesCS4A02G386700      GCCTGTATCTTCTGCTGTGGGGCAAGAGGCAGGA--GGCCTTGCAACAGCATCCAGAAGG
TraesCS4D02G313000      GCCTCTACATGCTGCTCTGGGGCAAGGACAAGGACCAGGAGTACAACGCTG---CAGGAG
AT3G18200               GGCTCTACTTAGTTCTTTGGGGCAAAAACGAAGAAAGA----------------------
TraesCS3B02G026700      GGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAG-------AAGACG---AGGAGC
TraesCS3A02G019600      GGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAG-------AAGACG---AGGAGC
TraesCS3D02G027300      GGCTCTACTTCGTGCTGTGGGGCAAGAGCGAGGAGAAG-------AAGACG---AGGAGC
TraesCS7A02G281700      GGCTCTACCTTGTGCTCTGGGGCAAGAGCGAGGAGAGGTCGCGCAACGGCA---AGGAGG
TraesCS3A02G007100      GCCTCTACCTCGTGCTCTGGGGCAAGAGCGAGGAGAGGTCGCGCATCGGCA---AGGAGG
TraesCS3D02G003600      GCCTCTACCTCGTGCTCTGGGGCAAGAGCGAGGAGAGGTCGCGCATCGGCA---AGGAGG
TraesCS3B02G011600      GCCTCTACCTCGTGCTCTGGGGCAAGAGCGAGGACAGGTCGCGCATCGGCA---AGGAGG
TraesCS3B02G006900      GCCTCTACCTCGTGCTCTGGGGCAAGAGCGAGGAGAGGTCGCGCATCGGCA---AGGAGG
                        * ** **  *  * ** ********     * **                          

TraesCS4A02G386700      TGCTAAAGATGACCA-------------------------------AGAACAACAG----
TraesCS4D02G313000      CGGCGACCGGCGAGGAGCAGGGCGGCTCGCCGGATCTGGACTGCGAGAAGCAGCAGCGGC
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      CAAGATCCCGAGATG-----------------------------GCGAGGCACCTGCT--
TraesCS3A02G019600      CAGGACCCGGAGATG-----------------------------GCGAGGCACCTGCT--
TraesCS3D02G027300      CAAGACCCGGAGATG-----------------------------GTGAGGCGCCTGCT--
TraesCS7A02G281700      CGGTGGCCATGGCCG-----------------------------CGGCGTCCGCAGCTTC
TraesCS3A02G007100      CGGCGGTCATGGCCG--------------------------------------CAGCTTC
TraesCS3D02G003600      C---------GGCCG-----------------------------CCGCATCGGCAGCTTC
TraesCS3B02G011600      CCGCGGTCATGGCCG-----------------------------CCGCGTCCGCAGGTTC
TraesCS3B02G006900      CCGCGGTCATGGCCG-----------------------------CCGCGTCCGCAGGTTC
                                                                                    

TraesCS4A02G386700      ---CAGCAGCAGCAAGT------------GCAAT--------------------------
TraesCS4D02G313000      AGGGGAAGAAGATGGTCGGCGTCTCCTTGGCGCGGGATGGCTCAGAAGAACAGACCAAGG
AT3G18200               ----------------------------------------------------AAACTGG-
TraesCS3B02G026700      ---GGGGGAAGACGGCG------------GCGAGG------CTGACAAAGATCAGCAAGT
TraesCS3A02G019600      ---CGGGGAAGACGGCG------------GCGCGG------CTGACAAAGATCAGCAAG-
TraesCS3D02G027300      ---CGGGGAAGACGGCG------------GCGCAG------CTGACAAAGATCAGCAAGT
TraesCS7A02G281700      CTCCGGCGG---CGAGC------------GCGAGG------TCCGGAGCGCCAAGCTGGG
TraesCS3A02G007100      CTCCGGCAGTGGCGAGC------------GCGAGG------TCCGGAGCGCCAAGCTGGC
TraesCS3D02G003600      CTCCGGCAGCGGCGAGC------------GCGAGG------TCCGGAGCGCCAAGCTGGC
TraesCS3B02G011600      CTCCGGCGGCGCCGAGC------------GCGAGG------TCCGGAGCGCCAAGCTCGC
TraesCS3B02G006900      CTCCGGCGGCGCCGAGC------------GCGAGG------TCCGGAGCGCCAAGCTCGC
                                                                                    

TraesCS4A02G386700      -------------------CGCAGCC----------------------------------
TraesCS4D02G313000      CGATGAGATAAGAGGAGGGCTCAGAATTGCCTGCCAC---------------------CA
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      GAGCACCGCTG--------TGCTGGCGTGAAAGCTGCTAGCTGCTGGATATCCCTTGGAG
TraesCS3A02G019600      -------------------TGCTGGCGTGACAGCTGC----TGCTTGATATTCCTTGGAG
TraesCS3D02G027300      GAGCACCACTG--------TCCTGGCGTGAAAGCTGCTGCTTGCTGGA-----TTTGGAG
TraesCS7A02G281700      CTCCTCCATCA--------CCCAGCCTCTCCTGCCGC--CTTCCTCAACCACCTCCGACA
TraesCS3A02G007100      CTCCTCCATCA--------CCCAGCCTCTCCTCCCGC--------------CTTCCGACA
TraesCS3D02G003600      CTCCTCCATCA--------CCCAGCCTCTCCTGCCGC--CCTCCTCCACCACCTCCGACA
TraesCS3B02G011600      CTCCTCCATCA--------CCCAGCCTCTCCTGCCGC--CTTCCTCCACCACCTCCGACA
TraesCS3B02G006900      CTCCTCCATCA--------CCCAGCCTCTCCTGCCGC--CTTCCTCCACCACCTCCGACA
                                                                                    

TraesCS4A02G386700      ATGACTGAAGATT---GAGA----------------------------------------
TraesCS4D02G313000      GTGTGCGTGCCGTCCAGAAG--AAGCGGCCTGCATCAATGGCTCT-----GCAGTTGTTC
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ATGTGTGTA--CT---GATG--TGGGTGTTTGAACGTACTCCTACC----------TTTT
TraesCS3A02G019600      ATGTGTGTA--CT---GATG--TGGGTGTTTGTACCTACGTTTTT---------------
TraesCS3D02G027300      ATGTGTGTA--CT---GATG--TGGGTGTTTGTACCTACGTTTTT---------------
TraesCS7A02G281700      ACGTCTGGAACTT---AGTTGCTTGCTGTCCGTTCTCAACGAT-----------------
TraesCS3A02G007100      ATGTCTGAAACTT---AATT----GCTACTGTACCCTACTGTCCTTCTCGACGAC-----
TraesCS3D02G003600      ACGTCTGAAACTT---AATT----GCTACCTAG-CTACCGTCGCTTCTCAACGAT-----
TraesCS3B02G011600      ATGTCTGAAACTT---AATT--GTGCTACCTTG---------------------------
TraesCS3B02G006900      ATGTCTGAAACTT---AATT--GTGCTACCTTG---------------------------
                                                                                    

TraesCS4A02G386700      -----------------------------GACAGAGA-----------------------
TraesCS4D02G313000      TACGTACTAGTACTTCTT----------TGTTCGAAAGAAACACAATTCTGTAGTTGATC
AT3G18200               ----------------------------CTCTTGAAGAGAG-------------------
TraesCS3B02G026700      TAACTACTAGTGTTTCAAGCGTGCGATGCGACCAAGAAGAAGAAGACCCG----------
TraesCS3A02G019600      ----AACTAGTGTTTCAAGCGTGCGTTACGACCAAGAAGAAGAAGACTCG----------
TraesCS3D02G027300      ----AACTAGTGTTTCAAGCGTG-----CGACCAAGAAGAAGAAGACTCG----------
TraesCS7A02G281700      ----------------------------CGACTGAGAGTAA-------TT----------
TraesCS3A02G007100      ----------------------------CGACTGAGAGGAA-------CT----------
TraesCS3D02G003600      ----------------------------GGATTGTGAGGAG-------TT----------
TraesCS3B02G011600      ----------------------------CTACTGCGAGGAG-------TT----------
TraesCS3B02G006900      ----------------------------CTACTGCGAGGAG-------TT----------
                                                                                    

TraesCS4A02G386700      ---------TCCTCAATTG-GGTGTTAACAAGTGCA------------------------
TraesCS4D02G313000      GTGGCAAAATTCTTTGACATGGATCCACCAACGGGGCATCCATCTGAACTTTTGTTGCAG
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ---------TACTAGTTGACGATGTGAACTGCCAAACACAC-------------------
TraesCS3A02G019600      ---------TACTAGTTGACGATGTGAACTGCCAAACACAC-------------------
TraesCS3D02G027300      ---------TACTAGTTGACGATGTGAACTGCCAAACACAC-------------------
TraesCS7A02G281700      ---------TTCCTGTTTAAATT-------------------------------------
TraesCS3A02G007100      ---------TTCTTGTTTAAATTTTAGGCGGGCATGCATGCACGCCTAGCTATGGTGTGG
TraesCS3D02G003600      ---------TTCTTGTTTA-AATTCAGGCGGGCATGCATGCACGCCTA----TGGTGTGG
TraesCS3B02G011600      ---------TTCTCGTTTA-AATTCAGGCGGGCATGCATGCACGCCTA-----TGTGTGG
TraesCS3B02G006900      ---------TTCTCGTTTA-AATTCAGGCGGGCATGCATGCACGCCTA-----TGTGTGG
                                                                                    

TraesCS4A02G386700      -----------GCAAATAAGTTTTA-------------CAATA------ATTTTT-----
TraesCS4D02G313000      CATCAGTATGTGCA---CTGTTTAACCCGCAAAAAAAAGCATGTGCTATGTTTTTTGGCG
AT3G18200               -----------TCAACAAGATCCAG-----------------------------------
TraesCS3B02G026700      -----------TCAGACATATTTGG---TACCTACTGTGTATA------GCCCCTT----
TraesCS3A02G019600      -----------TCAGTCATATTTGG---TACCTACTGTGTATA------GCCCCT-----
TraesCS3D02G027300      -----------TCAGTCATATTTGG---TACCTACTGTGTATA------GCCCCTT----
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TGAGCGAGTATGCAGACGGATTTGATTGTTAAAACTAGCTAGG------ATTGTTTGG--
TraesCS3D02G003600      TGAGCGAGTATGCAGACGGATTTGA---TTAAAACTAGCTAGG------ATTGTTTGG--
TraesCS3B02G011600      TGAGCGAGTATGCAGACGGATTTGA---TTAAAACTAGCTAGG------GTTGTTTGG--
TraesCS3B02G006900      TGAGCGAGTATGCAGACGGATTTGA---TTAAAACTAGCTAGG------GTTGTTTGG--
                                                                                    

TraesCS4A02G386700      -------------------------------CCATGTTCTAGTAATTATTGTGATCACTA
TraesCS4D02G313000      AAATGCCGCGTATCTCCGGCACAAGCCCAAATCATGTATGACAAAACAGCATGAACATAA
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      ---------------------------------GTCTTCGAG--T----TGTGTGTGTCT
TraesCS3A02G019600      ---------------------------------GTCTTCGAG--TTGTGTGTGTGTGTCT
TraesCS3D02G027300      ---------------------------------GTCTTCGAG----TTGTGTGTGTGTCT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------GTCGTGCTTGAT--TATGGTGTGTGCATTA
TraesCS3D02G003600      ------------------------------ATCGTGCTTGAT--TATGGTGTGTGCATTA
TraesCS3B02G011600      ------------------------------ATCGTGCTTGAT--TATGGTGTGTGCATTA
TraesCS3B02G006900      ------------------------------ATCGTGCTTGAT--TATGGTGTGTGCATTA
                                                                                    

TraesCS4A02G386700      TT------------------------------CTGCCGCAAATTAGGCTTCACGATGGTT
TraesCS4D02G313000      GCATTTCCTATTCGGACCTTCAGACGCCGGTTATAGTACAAACTAAAACCGGCACACACA
AT3G18200               ------------------AGTCA---------CTGACCAAACATCTACTTGAGGCAC---
TraesCS3B02G026700      ATA---------------AATAC---------ACTATGCTCCCTAATTTTGAAGCTCT--
TraesCS3A02G019600      ATA---------------AATAC---------ACTATGCTCCCTAATTTTGAAGCTCTCC
TraesCS3D02G027300      ATA---------------AATAC---------ACTATGCTCCCTAATTTTGAAGCCCTCC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AGGCTTGTTAATTAGTACTGTAG---------ATCAGAAAACTTGCGCTTGATGTATTGG
TraesCS3D02G003600      AGGCTTGTCAATTGG---AGTAG---------ATCAGAAAACTTGTGCTTGATGTATTGG
TraesCS3B02G011600      AGGCTTGTCAATTGG---AGTAG---------ATCAGAAAACTTGTGCTTGATGTATTGG
TraesCS3B02G006900      AGGCTTGTCAATTGG---AGTAG---------ATCAGAAAACTTGTGCTTGATGTATTGG
                                                                                    

TraesCS4A02G386700      TCATTCACGAAGTTGT------TTAGGTTCAGGATG----CTATTATAAAT---------
TraesCS4D02G313000      CACCCTCCTTCACTTG----GGCTCGGCTCATTTCACTATTTTTCCTTCTTCGACAGCAC
AT3G18200               ---------------------------AACACAAGAAGAGTAATTCTGAAT---------
TraesCS3B02G026700      --CCCAGTCTAGTTGTGGTGTTCAATTTTAGAATTTTGGATTATGATTTTC---------
TraesCS3A02G019600      CATTCTATTGGGGTGTTCAATTTAGAATTTAGAATTTGGTTTATGGTTTTT---------
TraesCS3D02G027300      CATTCTATATTGGGGT-----GTTCGATTTAGAATTTGGTT-------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TACTTTACCTAATTAT-------TATTATCACAACAGGGTTTGT--TCACT---------
TraesCS3D02G003600      TACCCTATCTAATGAT----TATTACTATCACAATAGGGTTTGT--TCACT---------
TraesCS3B02G011600      TACCCTATCTAATTAT----TATTACTATCACAATAGGGTTTGT--TCACT---------
TraesCS3B02G006900      TACCCTATCTAATTAT----TATTACTATCACAATAGGGTTTGT--TCACT---------
                                                                                    

TraesCS4A02G386700      --ATGTAGTGTACTATATGTAGCAATATTTTTAGAAATTAT-------------------
TraesCS4D02G313000      AGCCTGAGCGAACGACCTGCG-CGAGGCTGTTTGCATTTTTTTGGCCAATGACCAACCAG
AT3G18200               --CTGAAGTGTAA-----------------------------------------------
TraesCS3B02G026700      --ACTGGGTCAACGATTTTGATTGAGGTTATTTTAAATTTGGTTTACAATTTTTCTTCAG
TraesCS3A02G019600      --GTGGGGTCAACTATTTTGA-TGAAGTTATTTTGAATTTGGTTCATAGTTTTTATTCGG
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      --ACGAAGGCACCTTCA-----------TGTTTAC-------------------------
TraesCS3D02G003600      --ATGGATTCTACGTACTTAA-------TGTCTACATCGTTTTTGCAATCAGTAATT---
TraesCS3B02G011600      --ATAGATTGCCTTAG------------TGTTTACACTGTTTTTGCAATCAGTAATT---
TraesCS3B02G006900      --ATGGATTGCCTTAG------------TGTTTACACTGTTTTTGCAATCAGTAATT---
                                                                                    

TraesCS4A02G386700      ------------------------------------------------------------
TraesCS4D02G313000      AATTGA------------------TGGAGATTCTATAAGCTTTTAAAGGATTATGACTCT
AT3G18200               ------------------------------------------------------------
TraesCS3B02G026700      T-----------------------------------------------------------
TraesCS3A02G019600      TTTTGTGTGTGGGTGGGGAGGGGGGAGTGATATCTGACCGTTGGCACTATTTTTAATTGT
TraesCS3D02G027300      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------AAGTGCCCCTCTG-----------------------
TraesCS3B02G011600      ------------------------AAGTAATTTCACAAC---------------------
TraesCS3B02G006900      ------------------------AAGTAATTTCACAACAACGAAAAAATC---------
                                                                                    

TraesCS4A02G386700      -----------
TraesCS4D02G313000      TTTT-------
AT3G18200               -----------
TraesCS3B02G026700      -----------
TraesCS3A02G019600      TTGGATTGCTT
TraesCS3D02G027300      -----------
TraesCS7A02G281700      -----------
TraesCS3A02G007100      -----------
TraesCS3D02G003600      -----------
TraesCS3B02G011600      -----------
TraesCS3B02G006900      -----------
                                   
