CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGCTCATTGTG
TraesCS6A02G008800      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGCTCATTGTG
TraesCS6D02G009800      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGATCATTGTG
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ---------------ATGCGCAGCCCAAGCGAAGGCAACCGACCTAGGCTTGCA------
TraesCS6B02G015400      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
TraesCS6A02G008800      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
TraesCS6D02G009800      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
TraesCS4A02G464200      -----------GCCTATAAGTAGTCCATGACAAGGGCATCATC-----------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      AGTGTACCAAATGATTACAGAAAAAACACTCGTCGGCGGGTTTTACCGCCTTCATTGGAA
TraesCS6A02G008800      AGTGTACCAAATGATTACAG--AAAACACTCGTTGGTGGGTTTTACCGCCTTCATTGGAA
TraesCS6D02G009800      AGTGTACCAAATGATTACAG--AAAACACTCGTTGGTGGGTTTTACCGCCTTCATTGGAA
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      TGC-AAAACTTGCCCTGATTTGTCATTGAAAATGACAGTTGGGCAGGAGCAAAATCACAC
TraesCS6A02G008800      TGCAAAAACTAGCCTTAATTTGTCATTGAAAATGACAGTTGCGCAGGAGTAAAATCACAC
TraesCS6D02G009800      TGC-AAAACTAGCCCTAATTTGTCATTGAAAATGACAGTTGGGCAGGAGCAAAATCACAC
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      TAACAAGCACAAAGGTGAATGGCCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
TraesCS6A02G008800      TAACAAGCACAAAGGTGAATGGTCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
TraesCS6D02G009800      TAACAAGCGCAAAGGTGAATGGTCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ---------------------------------------------------CATATCTTC
TraesCS6B02G015400      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTGGTTGTTGACATATACCAGCTCACT
TraesCS6A02G008800      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTG---GTTGACATATACCAGGTCAC-
TraesCS6D02G009800      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTG---GTTGACATATACCAGGTCAC-
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      TTCTTGTTCCAGCGGCA-------------------------------------------
TraesCS6B02G015400      TTTTTTTACTAATGGCAAGTATTAGGTTCTTTTAGATGCTTTTGGAAGCACTTTTAATGT
TraesCS6A02G008800      CTTTTTTACTAATGGCAAGTATTAGGTT----------CTTTTGGAAGTTTTCTTTATGT
TraesCS6D02G009800      CTTTTTTACTAATGGCAAGTATTAGGTT----------CTTTTGGAAGTTTTCTTTATGT
TraesCS4A02G464200      -----------ATGGCAA------------------------------------------
TraesCS7A02G024800      -----------ATGGCA-------------------------------------------
                                                                                    

AT4G01440               --------------------TCATATACACAAA---------------------------
TraesCS4B02G086600      -----------------CGTGCGTGTGTGTGACTTGGTGTACT-----------------
TraesCS7A02G087800      -----------------TTCGTGCGTGTGCGTCTTGGTGACTTGGTGTACTC--------
TraesCS6B02G015400      TAGCAAGTGAGAGGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
TraesCS6A02G008800      TAGGAAGTGAGGCGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
TraesCS6D02G009800      TAGGAAGTGAGACGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
TraesCS4A02G464200      ---------------------TACAAGTGAAGGAAGGTGTGTCAAAGATTCA--------
TraesCS7A02G024800      ------------------------ATACAAGTAAAGGTGTGTCAAAGA------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      CGTCTTTTCTCCACCTTCTCGGCATCTTATGTAATTTTTGGTCGGGGCACCAGAAAAGGT
TraesCS6A02G008800      CGTCCTTTCTCCACTTTCTTGGCATCTTATGTAA-TTTTGGTCGGGGCACCAGAAAAGGT
TraesCS6D02G009800      CATCTTTTCTCCACTTTCTTGGCATCTTATGTAA-TTTTGGTCGGGGCACCAGAAAAGGT
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      AAGGGACTAAATCAGGATATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCCTA
TraesCS6A02G008800      AAGGGGCTGAATCAGGACATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCCTA
TraesCS6D02G009800      AAGGGGCTGAATCAGGACATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCGTA
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------CCCCTTAGAGAAACAAAA
TraesCS4B02G086600      ------------------------------------------CTACGAAGTGGTGGTATA
TraesCS7A02G087800      ------------------------------------------TACTACGGTGGTGGTATA
TraesCS6B02G015400      CTGTCTACTGATATGCCATTTTATAGATTATTATTAATAATCTTCAGTAGTACGAGTAAG
TraesCS6A02G008800      CTGTCTACTGATATGCCATTTTATAGATTATTATTAAAAATCTTCAGTAGTACGAGTAAG
TraesCS6D02G009800      CTGTCTACTGATATGCCATTTTATAGATTATTATTAAAAATCTTCAGTAGTACTAGTAAG
TraesCS4A02G464200      ------------------------------------------TTCAGCAGCG--------
TraesCS7A02G024800      ------------------------------------------TTCAGCAGCA--------
                                                                         *          

AT4G01440               AGAATACAAAAAGAAGAGAGAG-ATTAGTTATTAACTTATTCATAATAAGTGTAATTACT
TraesCS4B02G086600      GCGCGAGACAGAATAGAGAGAG--------------------------------------
TraesCS7A02G087800      GCGCGAGACAGAATAGAGAGAG--------------------------------------
TraesCS6B02G015400      TTGTCACAAAGAGTAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCATTTACT
TraesCS6A02G008800      TTGTCAC-AAGAGAAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCATTTACT
TraesCS6D02G009800      TTGTCAC-AAGAGTAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCATTTACT
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               TCGTATTTACTTTTTTTTGGTTAGCAGTCG--ACTAGTAATCAATAATGGGTTACTGCGA
TraesCS4B02G086600      -----------------------------------------CGAT-ATGGGGAGCGGCGG
TraesCS7A02G087800      -----------------------------------------CGAT-ATGGGGAGCGGCGG
TraesCS6B02G015400      TTTTTGCCCCCCTTGCATGAATGACCGCCGTCACTTCTGGTCAGT-GAGTAGCATTGCAG
TraesCS6A02G008800      TTTTTGCCCCCCTTGCATGAATGACGGCCGTCACTTTTGGTCAGT-GAGTAGCATTGCAG
TraesCS6D02G009800      TTTTTGCCCCCCTTGCATGAATGACCGCCGTCACTTTTGGTCAGT-GAGTAGCATTGCAG
TraesCS4A02G464200      -----------------------------------------CAAT-GTGGGGGATGGC--
TraesCS7A02G024800      -----------------------------------------CAAT-GTGGGGGATGGC--
                                                                 *  *   *       **  

AT4G01440               TGGT--------------------------------------------------------
TraesCS4B02G086600      GTT---------------------------------------------------------
TraesCS7A02G087800      GTT---------------------------------------------------------
TraesCS6B02G015400      GGCTATATA--------------------ATCAGACAGTTAATGAGCGTATCCGTCATCT
TraesCS6A02G008800      GGCTATATATA---------------ATCATCAGACAGTTAATGAGCGTATCAGTCATCT
TraesCS6D02G009800      GGCTATATATATATATATATATATATATAATCAGACAGTTGATGAGCGTATCAGTCATCT
TraesCS4A02G464200      ---------------------------------------------GCGCATCGAT-----
TraesCS7A02G024800      ---------------------------------------------GCGCATCGAT-----
                                                                                    

AT4G01440               ------------------------------AAATGGACACCGGTGATTATTATGGTTATG
TraesCS4B02G086600      --------------------------------GTTGTTGCCGACCGTGGTGATGCTGGCG
TraesCS7A02G087800      --------------------------------GTTGTTGCCGACGGTGGTGATGCTGGCG
TraesCS6B02G015400      TGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCCGGTGATGGGAATGCTGGCC
TraesCS6A02G008800      TGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCCGGTGATGGGAATGCTGGCC
TraesCS6D02G009800      TGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCTGGTGATGGGAATGCTGGCC
TraesCS4A02G464200      ------------------------------GAGTGGAAACCGGTGATCGCAATGCTGGTC
TraesCS7A02G024800      ------------------------------GAGTGGAAACCGGTGATGGCAATGCTGGTC
                                                         * *   * *    *    *** *    

AT4G01440               ATCAATTCAGCGCTGGGTTTAGCTAATGCTTTGGTTAAAAAAGTACTCGATGGTGGTGTT
TraesCS4B02G086600      CTCAACGTGTTGTCGGCGGTGATGGTGGCGCTGGTCAAGGTGGCCATGGCCGGCGGCCTC
TraesCS7A02G087800      CTCAACGTGTTGTCGGCGGTGATGGTGGCGCTGGTGAAGGTGGCCATGGCCGGCGGCCTC
TraesCS6B02G015400      TTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGGAGCAAGGTCTG
TraesCS6A02G008800      TTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGGAGCAAGGGCTG
TraesCS6D02G009800      TTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGGAGCAAGGGCTG
TraesCS4A02G464200      TTCGACCTCATCTCTGCCGTGACAACGGCCCTGATCAAGGCGGCGCTCGAGGAAGGGCTC
TraesCS7A02G024800      TTCGACCTCATCTCTGCCGTGACAACGGCCCTGATCAAGGCGGCGCTCGAGGAAGGGCTC
                         ** *          *   *       **  ** * **    *   * *     **  * 

AT4G01440               AACCATATGGTTATCGCAACATATCGTCTTGCTATTTCAACCCTATTTTTGGCACCAATC
TraesCS4B02G086600      GACCCGCTCGTGCTCGTCACGCTGCAGCAGCTCGCCGCCGCCATCTTCCTCGGCCCCATC
TraesCS7A02G087800      GACCCGCTCGTGCTCGTCACGCTGCAGCAGCTCGCCGCCGCCATCTTCCTCGGCCCCATC
TraesCS6B02G015400      AACCGCCTGGTCCTCGTTACCCTCCGGCAGCTGGTCGCAACCATCTTCCTTGCCCCGATA
TraesCS6A02G008800      AACCGCCTGGTCCTCGTCACCCTCCGGCAGCTGGTCGCCACCATCTTCCTTGCTCCAATA
TraesCS6D02G009800      AACCGCCTGGTCCTCGTCACGCTCCGGCAGCTGGTCGCCACCATCTTTCTTGCCCCAATA
TraesCS4A02G464200      GACCGTCTAGTGCTCATCACGCTGCGTCAACTGGTGGCCACGGTCTTCCTTTCTCCGGTC
TraesCS7A02G024800      GACCGTCTAGTGCTCATCACGCTGCGTCAACTGGTGGCCACGGTCTTCCTTTCTCCGATC
                         ***   * **  **   **    *  *         *  *  * **  *    **  * 

AT4G01440               GCATTTTTTTGGGAACGGTAAGTA-----------TATTATATTCATTAAAGAACTTTGG
TraesCS4B02G086600      GCGCACTGGAGAGAGGGGTGAGTGAGTCCACACGACATCATCC-----------------
TraesCS7A02G087800      GCGCACTTCACAGAGGGGTGAGTGAGTCCACACGACGTCCATTTCGATTGCATATTCATT
TraesCS6B02G015400      GCCTTTTTCAAAGAACGGTATGCAAACACATGCATCCTTCCTTGTACATACATACAATCT
TraesCS6A02G008800      GCCTTTTTCAAAGAACGGTA----------TGCATCCTTGT--------ACATACAATCT
TraesCS6D02G009800      GCCTTTTTCAAAGAACGGTATGCAAACACATGCATCCTTGT--------ACATACAATCT
TraesCS4A02G464200      GCATTTTTCAAAGAACGGTA-----CTGCATAAATTTTGATTTGCAGAAGATGATCAGCA
TraesCS7A02G024800      GCATTTTTCAAAGAACGGTA--------CATAAATTTTGATTTGCAGAAGATGACCAGA-
                        **    *     **  ***                  *                      

AT4G01440               TCTTGATGATATATATATGTTTGTAATAATTAACGTTAAAAATGATT--CGTTATATGTT
TraesCS4B02G086600      ----------ATACATAGCCTTTTTCTCATC-----TTCGGTTGATT--GGTCTCAT---
TraesCS7A02G087800      GCATGAAGCTATATATAGCCTTGTTCTGATT-------ATACTGGTTTCGGTTTCATACT
TraesCS6B02G015400      GC--------GTTCAT------TCCCCGGGTGAGACTGAAACTGCAT--AGCGCCGTGGC
TraesCS6A02G008800      GC--------ATTCAT------TCCCTGGGT--GACTGAAACTGCAT--AGCGCCACGAC
TraesCS6D02G009800      GC--------GTTCAT------TCCCTGGGT--GACTGAAACTGCAT--AGCGCCATGGC
TraesCS4A02G464200      GA--------GTTCAGAACTTATCCTAGAAT----ATGATGCTAC------TGTTGTTTT
TraesCS7A02G024800      ----------GTTCAGAACTTATCCTAGAAT----ATGATGCTGC---------TGTTGT
                                   *  *                           *                 

AT4G01440               TTT--------TAGGAAAACGAGACCGACACTAACGCTCAACATCTTGGTTCAGCTTTTC
TraesCS4B02G086600      -------CCATCAGCAAGTCGAGGCCCAAGATGACGCTCGAGATCTTCGCCCACCTCTTC
TraesCS7A02G087800      TTCATATCCATCAGCAAGTCGAGGCCCAAGATGACGCTCGAGATCTTCGCCTACCTCTTC
TraesCS6B02G015400      ATTCCTGCATGCAGGAGCACGAGGCCCAAGCTCACATTGGAGATCCTGGCGTACCTCTTC
TraesCS6A02G008800      ATT----CCTGCAGGAACACGAGGCCCAAGCTCACATTGGAGATCCTGGTGTACCTCTTC
TraesCS6D02G009800      ATT----CCTGCAGGAGCACGAGGCCCAAGCTCACACTGGAGGTCCTGGCGTACCTCTTC
TraesCS4A02G464200      TTT----CTTTCAGGAACACACGGCCTAAGCTCACACTGGAGATCCTCGTGTACCTCTTC
TraesCS7A02G024800      TTT----CTTTCAGGAACACACGGCCTAAGCTCACACTGGAGATCCTGGTGTACCTCTTC
                                    ** *   *  * ** *   * **  *  *  ** * *   * ** ***

AT4G01440               TTCAGTGCTCTTGTTGGGTTCGTTCTTTTTCTAATTTTCGCTTGGAACTCCTAATAGTTG
TraesCS4B02G086600      ATCAGCGC----------------------------------------------------
TraesCS7A02G087800      GTCAGCGC----------------------------------------------------
TraesCS6B02G015400      TTCAGCGC----------------------------------------------------
TraesCS6A02G008800      TTCAGCGC----------------------------------------------------
TraesCS6D02G009800      TTCAGCGC----------------------------------------------------
TraesCS4A02G464200      TTCAGCGC----------------------------------------------------
TraesCS7A02G024800      TTCAGCGC----------------------------------------------------
                         **** **                                                    

AT4G01440               TAGGAATAATAAGGAAATATTCTAAATAAAAATAGGTTGACTGTTTGAAATTTAAGAAAA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               TAAACCATTTTGTTTAGATTTTTGGATGAAGAATTTAATATTTAAGAGTTAGGATTTTGG
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ATTTCGAAGTTATGGTTAAGCTTTTAGCGTTTAGGTTTTAGAATTTAAATTTTCTATTAC
TraesCS4B02G086600      -------------------------CGCGCTCGGGT------------------------
TraesCS7A02G087800      -------------------------CGCGCTCGGGT------------------------
TraesCS6B02G015400      -------------------------CGTG-------------------------------
TraesCS6A02G008800      -------------------------CGTG-------------------------------
TraesCS6D02G009800      -------------------------CGTG-------------------------------
TraesCS4A02G464200      -------------------------AGCGTTAGGGT------------------------
TraesCS7A02G024800      -------------------------AGCGTTAGGGT------------------------
                                                  * *                               

AT4G01440               TTAATTAGTTTTTACTTTTTAGAAATATAGACAATTTCTTCTAATTGATATAGAATTTTG
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      -----------------------ACGGTTGGCAAACATAGCATCACAGCAATCACTT---
TraesCS7A02G024800      -----------------------ACGGTTGGCAAACATAGCATCACAACAATCACTTCCT
                                                                                    

AT4G01440               AATGTTTGCGTAATTGTCCTGTTGTTGCATTCTAACCGATTTTTAGTCTTTTTCTTTTGT
TraesCS4B02G086600      ------------------------ACTCTTTCTTTCCTTGATCAAATCTTCTCTGTTCGA
TraesCS7A02G087800      ------------------------ACGTATTCTTTCCTTGATCAAATCTTCTCAGTTTGA
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------CCTGATATGATTCTGTTTGATTCA
TraesCS7A02G024800      CATATTAGTACAGCGACCCGGCTATAGAATGCTCTGCCAGATATGATTCTGCTTGATTCA
                                                                                    

AT4G01440               TTTTTTATTGTTAAGAATGTAAATATTTTATAAAAAATGAAACATGATAGGTTTACGGTC
TraesCS4B02G086600      TCTT--------------------------------------------------------
TraesCS7A02G087800      TCTT--------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      TCAT--------------------------------------------------------
TraesCS7A02G024800      TCAT--------------------------------------------------------
                                                                                    

AT4G01440               CGTGGCAAAAAAGATAAAAACATGAAAGCATAAAAATAACCACTGGTTTTTAGTCAAATT
TraesCS4B02G086600      ------------------------CGAACTAAGTAACAACGGCTGGATCATTTCTTGTAC
TraesCS7A02G087800      ----------------------------CCAATCAACGACGGTTGGATCATA--TAGTGT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               AAGAGCTTTATTTTGTACTGAAATATATGATCATTCTGAACATATTTTAGG---GCAAGT
TraesCS4B02G086600      TACTACACCATCTTG---------------------------CATGGTGGCAGGGCGGCG
TraesCS7A02G087800      ACACAATCGATCTTG---------------------------CATGGTGGCAGGGCGGCG
TraesCS6B02G015400      ---------------------------------------------TTTGGC---GCGGCG
TraesCS6A02G008800      ---------------------------------------------TTTGGC---GCGGCG
TraesCS6D02G009800      ---------------------------------------------TTTGGC---GCGGCG
TraesCS4A02G464200      --TGATTTTTCCTCC---------------------------CATTTTAGC---GCCGCG
TraesCS7A02G024800      --TGACTTTTCCTCC---------------------------CATTTTAGC---GCTGCG
                                                                       * *    **    

AT4G01440               TTGACTCAGTATTTCTTCCTATTGGGGCTATCATACACATCGGCTACGTTGGCATGTGCT
TraesCS4B02G086600      ATGAGACAGTACACGGTCTTCGTGGGGCTGCGCTACACCACGGCGACCTTCGTCAGCGCC
TraesCS7A02G087800      ATGAGGCAGTACATGGTCTTCGTGGGGCTGCGCTACACCACGGCGACCTTCGTCAGCGCC
TraesCS6B02G015400      CTCTCGCAGTACACCTTCTTCTACGGCCTGCAGTACACCACCGCCACCTTCGCCATAACC
TraesCS6A02G008800      CTCTCGCAGTACACCTTCTTCTATGGCCTGCAGTACACCACCGCCACCTTTGCTATAACC
TraesCS6D02G009800      CTCTCGCAGTACACCTTCTTCTACGGCCTGCAGTACACCACCGCCACCTTCGCCATAACC
TraesCS4A02G464200      CTCTCTCAGTATACCTTCTTCTACGGGCTGCAGTACACAACAGCAACGTTTGCAATAACT
TraesCS7A02G024800      CTCTCTCAGTATACCTTCTTCTACGGGCTGCAGTACACAACGGCAACGTTTGCAATAACT
                         *    *****     ** *    ** **    *****  * ** ** ** *      * 

AT4G01440               TTTATTAGCATGACGCCTGCGATTACATTCGTTATGGCTCTAATATTCAGGTAAACTATA
TraesCS4B02G086600      TTCTCCAACATCGCGCCTGTGCTCACCTTCGTGCTTGCCGTCGCCACC------------
TraesCS7A02G087800      TTCTCCAACATCGCGCCCGTGCTCACCTTCGTGCTCGCCGTCGCCACC------------
TraesCS6B02G015400      TTCATCAACCTCTCCCCTGTGCTCACCTTCCTCATCGCCGTCGT----------------
TraesCS6A02G008800      TTCATCAACCTCTCTCCTGTGCTCACCTTCCTCATCGCCGTCGT----------------
TraesCS6D02G009800      TTCATCAACCTCTCTCCTGTGCTCACCTTCCTCATCGCCGTCGT----------------
TraesCS4A02G464200      TTCACCAACCTGGCTCCAGTGCTGACTTTCCTCATCGCGGTCTTGCTCAGGTGTGTGTGT
TraesCS7A02G024800      TTCACCAACCTGGCTCCTGTGCTCACTTTCCTCATCGCTGTCTTGCTCCGGTGTGTGTGT
                        **    * * *  * ** * * * ** *** *  * **  *                   

AT4G01440               A----GTGTCTAATATTAATTCAATTATTACTAGACAAACTAAGTTTATTATGATAATAT
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      GTACCAATTTTCAAATTTACCTGGTGGTACCTTGCTCATGCACCTTGCTCCTGCCAATAT
TraesCS7A02G024800      GTGCCGATTTTCAAATTTACC---TGGTACCTTTCTCATGCACTTTGTTCTTGCTAATAT
                                                                                    

AT4G01440               GTAAACACAATTCTTTG------------------GGTGTAGGGTAGAGAAGCTAAACAT
TraesCS4B02G086600      ----------------------------------------CGCTCCGAGTCGCTCCACCT
TraesCS7A02G087800      ----------------------------------------CGCGCCGAGTCGCTCCACCT
TraesCS6B02G015400      -----------------------------------GATG-AGGATGGAACCGCTGAAGTT
TraesCS6A02G008800      -----------------------------------GATG-AGGATGGAGCCGCTGAAGTT
TraesCS6D02G009800      -----------------------------------GATG-AGGATGGAGCCGCTCAAGTT
TraesCS4A02G464200      CTGAAACCTTCCCTCTGGGAATACTACCCATCATGGATGTAGGGTGGAGTCACTGAACAT
TraesCS7A02G024800      CTAAACCCTTT--------GGGAATACGGCTCATGGATGTAGGGTGGAGTCACTGAACAT
                                                                 *    **    **  *  *

AT4G01440               GAAAAGCAAAGCAGGTATGGGGATGGTGATGGGCGCGTTGATATGCATAGGAGGAGCTTT
TraesCS4B02G086600      CAGGGCCGCCACCGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTCGCTCGCCGGCGCCAT
TraesCS7A02G087800      CAGGTCCGCCACCGGCGCCGCCAAGCTCGCCGGCACGCTCGTCTCGCTCGCCGGCGCCAT
TraesCS6B02G015400      GAAGAGCATGGCGGGAGCCGCAAAGATCACCGGAACACTCACGTCGCTGGCCGGCTTGCT
TraesCS6A02G008800      GAAGAGCATGGCGGGAGCTGCGAAGATCACCGGAACGCTCACGTCGCTGGCCGGCTTGCT
TraesCS6D02G009800      GAAGAGCATGGCGGGAGCCGCAAAGATCACCGGGACGCTCACGTCGCTGGCCGGCCTGCT
TraesCS4A02G464200      GAAGAACAAGGCAGGAGCTGCGAAGATCATCGGGACGCTCATGTCGTTCGCCGGCGTCAT
TraesCS7A02G024800      GAAGAACAAGGCAGGAGCTGCGAAGATCATCGGGACACTCATGTCGTTCGCAGGCGTCAT
                         *    *    * **    *  * * *    **  *  *    *   * *  **     *

AT4G01440               ATTATTAACAATGTACAAAGGTGTTCCCTTGAC-----AAAACTTC-------GGAAACT
TraesCS4B02G086600      GCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACGCCAACAGC-------GCCCACC
TraesCS7A02G087800      GCTGCTCACCTTCTACAGAGGCGTGGCCCTCACCCACCCAAACAGC-------GCCCACC
TraesCS6B02G015400      GCTGCTGAGTCTCTACAAGGGAGTGCCGCTGACGCAC-CAGGCCGCCGCT---GCAC-CT
TraesCS6A02G008800      GCTGCTGAGTCTCTACAAGGGTGTGCCGCTGACGCAC-CAGGCCGCCACTTCTGCAC-CT
TraesCS6D02G009800      GCTGCTGAGTCTCTACAAGGGTGTGCCGCTGACGGAC-CAGGCTGCCACTGACGCAC-CT
TraesCS4A02G464200      GCTCCTGACCCTCTACAAGGGTGTGGCCTTGACACAC-CAAGCAGA-------GCCT-TC
TraesCS7A02G024800      GCTCCTGACCCTCTACAAGGGTGTGGCCTTGACACAC-CAAGCAGA-------GCCT-TC
                          *  * *   * ****  ** **  *  * **         *          *      

AT4G01440               AGAAACCCATCAGTTGATAAACAATAACCACG--CTATGAAACCAG------------AG
TraesCS4B02G086600      AG---CTCCACCGCCCCCCTTC-TTCCCCACCGTCCCCGGCAACCGACTCCGGCAGGCTG
TraesCS7A02G087800      AG---CTCCACCGCTCCCCTTCAT-CCCCGCTGTCGCCAGGAGCGGACTCCGGCAGGCGG
TraesCS6B02G015400      AG---CCCAGCTGCTTCTCACCATGCAGCACC--CTCTGACAGCAG----TGGCAACAGG
TraesCS6A02G008800      AG---CCCAGCTGCTCAC---CATGCAGCACC--CTCTGACAGCAG----TGGCAACAGG
TraesCS6D02G009800      AG---CCCAGCTGCTCTTCACCATGCAGCACC--CTCCGACAGCAG----TGGCAACCGG
TraesCS4A02G464200      AG---GCCAG-----------CATGCAGAAGCAGAAGCAGCAGCAGAATCTGGCAAGAAG
TraesCS7A02G024800      AG---GCCAG-----------CATGCAGAAAT---AGCAGCAGCAGAATCTGGCAAGAAG
                        **     *             *                   * * *             *

AT4G01440               AATTGGATAATAGGATGCGTACTTCTCTTTGCGGGTAGTAGCTGTTTCGGGTCGTGGATG
TraesCS4B02G086600      ---TGGACGCTGGGAACGGTGGCGATCCTCGGCAACTGCGTCTGCCTCGCCTGCTGGTAC
TraesCS7A02G087800      ---TGGACGCTGGGCACGGTGGCGATCCTCGGCAACTGCGTCTGCCTCGCCTGCTGGTAC
TraesCS6B02G015400      AGCTGGATGCTGGGAACCATGGCGTTGCTGTTCAACTGCCTGTGCTTCTCCTTCTGGCTG
TraesCS6A02G008800      AGCTGGATGCTGGGCACCATCGCGTTGCTGTTCAACTGCCTGTGCTTCTCCTTCTGGCTG
TraesCS6D02G009800      AGCTGGATGCTGGGCACCATGGCGTTGCTGTTCAACTGCCTGTGCTTCTCCTTCTGGCTG
TraesCS4A02G464200      AGCTGGACCCTGGGCACTCTAGCATTACTGGCAAACTGCCTGTGCTTCTCCTTTTGGCTC
TraesCS7A02G024800      AGCTGGACCCTGGGCACTCTAGCGTTACTGGCAAACTGCCTGTGCTTCTCCTTTTGGCTC
                           ****   * **     *     *  *        *    **  **   *  ***   

AT4G01440               CTGATACAAGCCAAAGTGAACGAGAAATACCCTTGTCAATACTCGAGTACTGTCGTATTA
TraesCS4B02G086600      CTGCTTCAGGGCAGGATCGCCAGGAAGTACCCCTACGTCTACTCCTGCAACGCCTTCCTG
TraesCS7A02G087800      CTGCTCCAGGGCAGGATCGCCAGGAAGTACCCCTACGTCTACTCCTGCAACGCCTTCCTG
TraesCS6B02G015400      CTGCTGCAGACAAAGCTGACCAAGAAGTACCCAGCCATCTATTCAAGCACCGCCATCATG
TraesCS6A02G008800      CTACTGCAGACAAAGCTGACCAAGAAGTACCCGGTCATCTACTCGAATACTGCCATCATG
TraesCS6D02G009800      CTGCTGCAGACAAAGCTGACCAAGAAGTACCCGGCCATCTACTCCAGCACCGCCATCATG
TraesCS4A02G464200      CTGCTGCAGTCCAAGCTCACCAAGAAGTACCCAGCACTCTACTCCAGCACTGCATACATG
TraesCS7A02G024800      CTGCTGCAGTCCAAGCTCACCAAGAAGTACCCAGCACTCTACTCCAGCACTGCATACATG
                        **  * **    *   *   *  *** *****       ** **    *  *      * 

AT4G01440               TCCTTCTTTGGCACCATCCAATGCGCCCTTCTAAGCCTCATCAA-ATCTCGAGATATCAC
TraesCS4B02G086600      TCCACCTTCAGCTTCCTCCAGGTCGCCGTAGTTGGCCTCTGCG-TGCAGCGCAACCTCTC
TraesCS7A02G087800      TCTACCTTCAGCTTCCTCCAGGTCGCCATCGTCGGCCTCTGCG-TGAAGCGCAACCTCGC
TraesCS6B02G015400      TTCTTCATCAGCACGCTGCAGGGCGGGGCGGT-GACGTTGGCGATGGAGAGACACGTGTC
TraesCS6A02G008800      TTCTTCATCAGCACTCTGCAGGGCGGGGCGGT-CACCTTGGCGATGGAGAGACACGTGTC
TraesCS6D02G009800      TTCTTCATCAGCACTCTGCAGGGCGGGGCGGT-GACGTTGGCGATGGAGAGACACGTGTC
TraesCS4A02G464200      TTCCTCATCAGCTCCCTGCAGGGAGGTGGCCT-GACAGCGGCGATACAGCGGAGGGCATC
TraesCS7A02G024800      TTCCTCATCAGCTCCCTGCAGGGCGGGGGCCT-GACGGCGGCGATACAGCGGCGGGCATC
                        *    * *  **    * **    *      *   *     *        *        *

AT4G01440               GGCTTGGATCCTCACAGATAAACTTGATATCGTTACCATTGTTTACGCGGTAAG------
TraesCS4B02G086600      CGCCTGGATCATCACCGACAAGCTCCAGATCATCACCGTCCTCTACTCCGTAAGTAACCA
TraesCS7A02G087800      CGCCTGGATCATCACCAACAAGTTCCAGATCCTCACCGTCCTCTACTCAGTAAG------
TraesCS6B02G015400      GTCGTGGATGCTGACCAGCAAGCTGGAGATCGTTACCGTCTTGTATGCAGTAAG------
TraesCS6A02G008800      GCTCTGGATGCTGACCAGCAAGCTGGAGATCGTTACCGTCTTGTATGCAGTAAG------
TraesCS6D02G009800      GCCGTGGATGCTGACCAGCAAGCTGGAGATCGTTACCGTCTTGTATGCAGTAAG------
TraesCS4A02G464200      GGTGTGGGTCCTCACAAAGCCAGTGGAGATTGTTACAGTACTATACACAGTAAG------
TraesCS7A02G024800      GGTGTGGGTCCTCACAAAGCCAGTGGAGATTGTTACAGTACTATACACAGTAAG------
                            *** *  * **        *  * **  * **  *  * **  * *****      

AT4G01440               ---------------------TGTT--TTT-----------------------AGTATTA
TraesCS4B02G086600      ACCAACCAGCCCTCATACGTATATG--CTTCTGAAATCTGAATTGCTTGCTACAAT----
TraesCS7A02G087800      ---------------------------CTT-------CTGAATTACTTGCAACGGT----
TraesCS6B02G015400      -----TTAAACATCACCATCATCTTGACTT------------------GTACCACCTTCG
TraesCS6A02G008800      -----TTAAACATCACCATCATCTT--CTTCATCTCCTTGACTTGTACGTACCACCTTCA
TraesCS6D02G009800      -CTAATTAAACATCACCATCATCTT--CTTCATCTCCTTGACTT----GTACCACCTTCA
TraesCS4A02G464200      --------------------ATCTT--TTT------------------GTTGCAGTTTAC
TraesCS7A02G024800      --------------------ATCTT--TTT------------------GTTGCAGTTTAC
                                                    **                              

AT4G01440               CTGAAAAAG---------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ------------------------------------------------------------
TraesCS6B02G015400      CAAGGAGAAGAAAAAAAGGA--ACTTCTCCAAAAGGGGCAAGTACTTATAAAAGCCATTG
TraesCS6A02G008800      CAAAGAGAAGAAAACAGGAACCACTTATCCAAAAGGGGCAACTACTTATAAAAGCCATTG
TraesCS6D02G009800      CAAAGAGAAGAGAACAGGAACTGCTTATCCAAAAGGGGCAACTACTTATAAAAGCCATTG
TraesCS4A02G464200      CGAAAAAAGAGTTAAGAGA-----------------------------------------
TraesCS7A02G024800      CAAAAAAGAGTGAAC---------------------------------------------
                                                                                    

AT4G01440               ------T----TGGCAGTAT---------------------------------------T
TraesCS4B02G086600      -----------ATGCAGCTGGC-------------------------------------T
TraesCS7A02G087800      -----------ATGCCGCTGA--------------------------------------T
TraesCS6B02G015400      CTTTAGC----TTGCAGCTAACACTAGTCT----ATGCAATCAATACACGCCAGCTAC-T
TraesCS6A02G008800      CTTTAATTATCTTGCAGCTAACACTAGTCTATATATGCAATCAATACACGCCAGCTACTT
TraesCS6D02G009800      CTTTAGC----TTGCAGCTAACACTAGTCT-TCTATGCAATCAATACACCCCAGCTAC-T
TraesCS4A02G464200      ------A----CTCTAGTGAA--------------------------------------T
TraesCS7A02G024800      ------T----CTGCAGAGAA--------------------------------------T
                                        *                                          *

AT4G01440               TGTTTAATTTTATAACTTCTAGTAAAATATAATTAAGTTATACGGACCTATGTCTATC--
TraesCS4B02G086600      TG-------CCACTGATTTTGCCTGAATAAA-----------------------------
TraesCS7A02G087800      TG---------ATTAATTGTGCCTGAATAAA-----------------------------
TraesCS6B02G015400      TGACCAACTTGAACAACTGAAACCAAAAATAGATG-----TGAAATAATAGTAGTAGACT
TraesCS6A02G008800      TGACCAACTTGAACAACTGAAACCCAAAGTACGTGGTGGTGAAAATAATAATAGATATTA
TraesCS6D02G009800      TGACCAACTTGAACAACTGAAACCAAAAATAGTTG-----TGAAAATATACAATGAA---
TraesCS4A02G464200      TG-------------ACTGAACCAAAGACCACTTG-----T-------------------
TraesCS7A02G024800      TG-------------GCTGAACCAAAGAACACTTG-----T-------------------
                        **               *       *    *                             

AT4G01440               -------------------------------------ACAACGTGTTATAGGGAGCAGTA
TraesCS4B02G086600      ----------------------------------------------TTCAGGGCGTGGTC
TraesCS7A02G087800      ----------------------------------------------TTCAGGGCGTGGTG
TraesCS6B02G015400      AGTAGGTAAGTACCCAACTGCTTAATCTTGCAATGAAATTACATG-TGCAGGGGATAGTC
TraesCS6A02G008800      AGTACTTAACATATTGTTAATCATACAATGAAATT--ATTACATG-TGCAGGGGATAGTC
TraesCS6D02G009800      -------------------------------------ATTGCACA-TGCAGGGGATAGTC
TraesCS4A02G464200      -------------------------------------TCCATATGTTGCAGGGAATCTTG
TraesCS7A02G024800      -------------------------------------TTCATATGTTGCAGGGAATCTTG
                                                                      *  ****     * 

AT4G01440               GCACAAGGAATATGTACGGTTGGAACGTCTTGGTGCATCAGAAAGAGAGGACCTATCTTT
TraesCS4B02G086600      GCGACCGGCATGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAGTGGGGGGCTGTGTTC
TraesCS7A02G087800      GCGACCGGCATGTCCTTCGTGCTGCTGACGTGGTGCATCCAGAAGCGGGGGGCTGTGTTC
TraesCS6B02G015400      GGATCTGGAGCCGGGTACCTGATAATGACGTGGTGCGTCGAGAAGAAGGGCCCGGTCTTC
TraesCS6A02G008800      GGATCTGGAGCCGGGTACCTGATAATGACGTGGTGCGTGGAGAAGAAGGGCCCGGTCTTC
TraesCS6D02G009800      GGATCTGGAGCTGGGTACCTGATAATGACGTGGTGTGTGGAGAAGAAGGGTCCGGTCTTC
TraesCS4A02G464200      GGGTCTGGAGTGGGATATGTACTGATGACATGGTGTGTGGAGAAGCGAGGGCCGGTGTTC
TraesCS7A02G024800      GGGTCTGGAGTGGGATATGTACTGATGACATGGTGTGTGGAGAAGAGAGGGCCAGTGTTC
                        *     **           *      * * *****  *    ***   **  *  * ** 

AT4G01440               ACTTCTATATTTACCCCGGTGGGGCTTATATTTGCAACACTATTTGATTTCTTGATCCTT
TraesCS4B02G086600      GTGGCCGCCTTCATCCCGGTGTCTCAGGTCATCGTCTGCATCATGGACTTCACTGTCCTG
TraesCS7A02G087800      GTCGCTGCCTTCATCCCGGTGTCGCAGGTCATCGTCTGCATCATGGATTTCACCGTCCTG
TraesCS6B02G015400      ACCGCAGCCTTCATCCCCATGATGCAGATCATGGTAGCCATCATCGATTTCTTCTTCCTC
TraesCS6A02G008800      ACCGCAGCCTTCATCCCCATGATGCAGATTATGGTAGCCATCATTGATTTCTTCTTCCTC
TraesCS6D02G009800      ACCGCAGCCTTCATCCCCATGATGCAGATCATGGTAGCCATCATCGATTTCTTCTTCCTC
TraesCS4A02G464200      ACTTCAGCCTTCATCCCCATCATCCAGATCATGGTTGCCATAATTGATTTCTTCTTTCTC
TraesCS7A02G024800      ACTTCAGCTTTCATCCCCATCATCCAGATCATGGTGGCCATAATTGATTTCTTCTTTCTC
                            *    ** * ***  *    *   *  * *      *  * ** ***    * ** 

AT4G01440               CATCGTCAAATTTTCCTAGGAAGGTACGTCGAATTGTATTTATACACATATATCATAAAA
TraesCS4B02G086600      CATGAACCGCTCTACCTTGGAAGGTGC---AAACACACTGCACCTATAGAGAT-------
TraesCS7A02G087800      CATGAACCGCTCTACCTTGGAAGGTGC--------AAACACACCTATAGAAAT-------
TraesCS6B02G015400      CATGAACAAATCTACCTTGGAAGGTAA-------------TACATATGTAGTTCTTCTCA
TraesCS6A02G008800      CATGAACAAATCTACCTTGGAAGGTAA-------------TACATATATACTTCTTCTCA
TraesCS6D02G009800      CATGAACAAATCTACCTTGGAAGGTAA-------------TACATATATAGTTCCTCTCA
TraesCS4A02G464200      CATGAGAACATCTACCTTGGAAGGTAAACCTGTCTTGCCTGAGTTAT-TAAATCACTACG
TraesCS7A02G024800      CATGAGAACATCTACCTTGGAAGGTAAACCAGATTTGCCTCAGATAT-TAAATCAGTACA
                        ***       * * *** *******                *   *   *  *       

AT4G01440               ATCTGAAT----------------------------------------------------
TraesCS4B02G086600      ---TCATG--CATGTGTCTGTTTACC---------------------------------C
TraesCS7A02G087800      ---TCATG--CGTGTATCTGTTTACC---------------------------------C
TraesCS6B02G015400      GTTTCATGCCTCCCTGTCCTTTTGCGATGATCATTGTCATCGCTGCCAACTGAATTGTTA
TraesCS6A02G008800      GTTTCATGCCTCCCTGTCCTTTTGTGATGATCATTGTCACTGCCGAAGTTTCATGTATAC
TraesCS6D02G009800      GTTTCATG----------------------------------CCGAAGTTTCATGTATAC
TraesCS4A02G464200      GTATCATGATCAGTCATTCATTTCCCAT----------------------------ATTC
TraesCS7A02G024800      GTCTCATGATCATTCATTCATTTCCCAT----ACTGAAATAAATGATGCATAATCTTTTC
                           * *                                                      

AT4G01440               ----------------------------------GTGATCGATTTT-----CTTTTTGA-
TraesCS4B02G086600      ATGGC-----------------------------ATGATTGGCATCTGAAACTTATGCT-
TraesCS7A02G087800      ATGGC-----------------------------ATGATTGCCATCTGAAACTTATGCT-
TraesCS6B02G015400      TTGTT---------------------GGCTGGAGATAAACTAAGTTAATGGTTTCAGCA-
TraesCS6A02G008800      ATTGTTGCCAACTGAATTGCTGTTGCTGCTGGAGATAAACAAAGTTAATTGTTTCCGCA-
TraesCS6D02G009800      ATTGT---------------TGTTGCTGCTGGAGATAAACAAAGTTAATTGTTTCCGCA-
TraesCS4A02G464200      AGTTT-----------------------------ATGAGTGATTTTTTACACTTTTGTAC
TraesCS7A02G024800      AGTTT-----------------------------ATGAGTGAGTTTATCCACTTTTGCAC
                                                           * *      *       **      

AT4G01440               ----------------------------------------TGTGGAT-------------
TraesCS4B02G086600      --------TTGCAA---------------------ACGTGTATGCAT-------------
TraesCS7A02G087800      --------TTGCAA---------------------ACGTGTATGCAT-------------
TraesCS6B02G015400      --ATCAAATTGTAATGACAAAATT------TATCTCTGCTTGTTAAT--------CATGG
TraesCS6A02G008800      --GTCGAGTTGTAATGA--AAATTTATACATATTTATGCGTGTTGATTATCGTTACATCG
TraesCS6D02G009800      --ATCGAGTTTTAATGACAAAATT------TATTTCTGCTTGTTAAT--------CATCG
TraesCS4A02G464200      TTGTAGAACTGCAATGCCTGGTCCAAATGGCATCATCTTTTGTATTT----------TTG
TraesCS7A02G024800      TTGTAGAACTGCAATGGCTGGTCCAAATGGCATCACCTTTTGTATTT---------TTTG
                                                                * *   *             

AT4G01440               ------------AGTGTTGTCGGATCTGGGGTTGTAATCTTCGGACTATACATATTCTTG
TraesCS4B02G086600      ------GCATGCAGTGTGGTGGGATCTGTGATTGTGATAAGTGGCCTGTATCTTCTGCTG
TraesCS7A02G087800      ------GCATGCAGTGTGGTGGGATCTGTGATTGTGATAGCTGGCCTGTATCTTCTGCTG
TraesCS6B02G015400      GCGTGCATGTACAGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTGTGCTG
TraesCS6A02G008800      GCGTGCATGTACAGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTTTGCTG
TraesCS6D02G009800      GCGTGCATGTACAGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTTTGCTG
TraesCS4A02G464200      TTTTGGCCTTGCAGTGTGCTGGGATCCATACTGATGATCATGGGCCTCTATATTCTGCTG
TraesCS7A02G024800      TTTTGCCCTTGCAGTGTGCTGGGATCCACACTGATGATCTTGGGCCTCTATATTCTGCTG
                                    ** **  * *****     *  * **    ** ** **  *  *  **

AT4G01440               TTGGGAAAAGTCAGGCTAATGAAAGAAGAGTGTGAAAAGAAGTTACCTTGTC----GTTT
TraesCS4B02G086600      TGGGGCAAGAGGCAG--------------------------GAGGCCTTG----------
TraesCS7A02G087800      TGGGGCAAGAGGCAG--------------------------GAGGCCTTG----------
TraesCS6B02G015400      TGGGGAAAGAAGAGG--------------------------GATGAAGCAGC--------
TraesCS6A02G008800      TGGGGAAAGAAGAGG--------------------------GATGAAGCATCTGTATCTT
TraesCS6D02G009800      TGGGGAAAGAAGAGG--------------------------GATGAATCATCTGTATCTT
TraesCS4A02G464200      TGGGGAAAGAGCAGG--------------------------GATGCCTCGGC--------
TraesCS7A02G024800      TGGGGAAAGAGCAGG--------------------------GATGCCTCGGC--------
                        * *** **      *                          *                  

AT4G01440               TAATGAAGATGATC--------AAGAAGAAGATGATGATGAACAATACAA-----AAAGG
TraesCS4B02G086600      ----CAACAGCATC--------CAAGAGTTGCTAAAGATGACCAAG---------AACAA
TraesCS7A02G087800      ----CAACAGCATC--------CAAGAGTTGCTAAAGATGACCAAG---------AACAA
TraesCS6B02G015400      ----TACTACCACT----------------------AACAAGCAAGTC-------GGCGA
TraesCS6A02G008800      GTACCACTACCACT----------------------GACAAGCAAGTC-------GACGA
TraesCS6D02G009800      GTACCACTACCACT----------------------GACAAGCAAGTC-------GACGA
TraesCS4A02G464200      --GACAGTACCACCTGCCAAAGAGGAAGAGGATAAGGAGAAGCAAATCAAATCATGAGGA
TraesCS7A02G024800      --GACAGTACCACCTGCCAAAGAGGAAGAGGATAAGGAGAAGCAAATCAAATCATAAGGA
                             *  *  *                         *  * ***               

AT4G01440               GTCATCTTATGGTTGTTCCAATGA-CTCCTTGA----------TAAGATTAGACTTTTTT
TraesCS4B02G086600      CAGCAGCAGCAGCAATTGCAGTCGCAGCCATGA---------------------------
TraesCS7A02G087800      CAGCAGCAGCAGCAAGTGCAGTCGCAGCCATGACTGAAGATTGAAAAACAGAGATCCTCC
TraesCS6B02G015400      ACAAGCTGACGACA-----------AGCCGTGA----------AACTCTAGAGATTATAC
TraesCS6A02G008800      ACCAGCTGACGACA-----------AGCCGTGA---------------------------
TraesCS6D02G009800      ACAAGCTGACGACA-----------AGCCGTGA----------AACTGCAGAGATTA--C
TraesCS4A02G464200      CCAAAACTATGCAATTCTTA-----GATTGTAA----------AACTATGGCATATATTC
TraesCS7A02G024800      CCAAGCT-ATGGCACTCTTA-----GGTTGTAA----------AACTATGGCATATATTC
                                                      * *                           

AT4G01440               TTTTTTCTTCTTCTTCACTT----------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ATTCGGTGATCTGTTAACATGTGCAGCAAATCAGTTCTCCAATAATTTTTCCATGTTCTA
TraesCS6B02G015400      ACCATTGGATTCGGTCATC-----------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ATCCTTTGATTCGGTCATT-----------------------------------------
TraesCS4A02G464200      CTCCTTGGTTTCCTACGCCTACGTAG----------------------------------
TraesCS7A02G024800      CTCCTTAGTTTTCTACACCTACGTAG----------------------------------
                                                                                    

AT4G01440               -------------------------CGTACATTAT--TTAGTAAAACCATTGACC-----
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GTAATTATTATGATCACAATTCTGGCGCAAATTAGGCTTCAGGATGCTATCATTCATGAA
TraesCS6B02G015400      ------------------GCAATGCAACACATAAT--------ATGTAGTTTTTC-----
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------GCACTGCAACACATAAT--------ATGTAGTTTTTC-----
TraesCS4A02G464200      -------TTTAACCAAGAGGAATGCTATACAGTACTGTTAGTAATGCAGTTGTCA-----
TraesCS7A02G024800      -------TTTAACCAAGAGGAATAGTATACAGTACTGTTAGTAATGCAGTTGTCG-----
                                                                                    

AT4G01440               ----GGTGAAAATTACAT------------GGACTAGTCTAACAACGGTT----------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GCTGTTTAGGCTCTAATCCAAACAACAGTAGGGTGACTATTACCATGTTTCTGGAGAAGC
TraesCS6B02G015400      ----TTCCCATTTTACTT-----GACTGCTGGATGCAGCTAGCTACATAC----------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ----TTCCCATTTTACTT------GCCGCTGGATGCAGCTAGCTATATAT----------
TraesCS4A02G464200      ----TATGCGTTTTCGCTCGCACAACGAGACGATACGTCGGGCTAATTTC----------
TraesCS7A02G024800      ----TATGCGTTTTCGCTCGCACAACGAGACGATACGTCGGGCAAATTTC----------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GTAGTTTGTGGGGACATATATATGTAAAAGTTAACTTTATTTCTGGCTATACATGTAATT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      -----------------------------GTTATATATAAGGTTGTTCCTAGCTGGTACT
TraesCS4A02G464200      ---------------------------------------TGCCTAAATGAAGCCCAAATT
TraesCS7A02G024800      -----------------------------TGCAGCTATATGCCTAAATGTAGCCCAAATT
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      TTGGGGGTAAAAGACAGCTGTTTTTTTTTTGGCAACCAGCCCACGGGAGATACATGCATA
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      GTTGACATATGTCCAAGCTACT--------------------------------------
TraesCS4A02G464200      CTTCAGGTGATAAAGAGCGG----------------------------------------
TraesCS7A02G024800      CTTCAGGTGATAAAGAGCGG----------------------------------------
                                                                                    

AT4G01440               -----------------------------------------------------CAAAAAA
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      CATCTTGATCGCACGAGTAGGCATGCACACAGTGCAACAGAAAGTGTTGAGAATAAAAAT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ----------------------------------------GAAATAATGGGATTTAGTAA
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               CTAGTCACATGTTTTTTTTTTTTTGCTTTTTCTTTTCTTTC-------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      CCAAGAATTAGTAGACATCGTCATTCAATTGCTCGGATTTCTTACTTGCTTCAAGTAATC
TraesCS6B02G015400      ---------------------------------------TC-------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      CTGAGCAGAGAGCTCATTTACCATACAGCTGCGCCAATGCC-------------------
TraesCS4A02G464200      -TGGGCATAGGTTGCCCATATCTCAGTACGTTAGAAGGTCA-------------------
TraesCS7A02G024800      -TGGGCATAGGTTGCCAATATCTCAGTACGTTAGAAGGTCA-------------------
                                                                                    

AT4G01440               ------------------------------------------CCT---------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      CTACTAATTTCTATCATTGAAACAATCTAAATTTCAGTACAACTTGCATTTATTGAATTA
TraesCS6B02G015400      ------------------------------------------CCT---------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------CTTCGGTAGCTGCATATG
TraesCS4A02G464200      ------------------------------------------CAT---------------
TraesCS7A02G024800      ------------------------------------------CAT---------------
                                                                                    

AT4G01440               -------------------------------------------TTTTTTTGTTTTGCAAT
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      AACTGCTTAAAAGATTGGATAGACACAAATTCATAACTATATACTGTAGTATTGTGCAAA
TraesCS6B02G015400      -------------------------------------------CCGTCCCAAAATATAA-
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      GGAAAATTATATGCGATTACTGTTCAAATGGTACTTCTTACTTCTCAAACACTTTGTAGT
TraesCS4A02G464200      -------------------------------------------CTGTCACACTGAGCAAG
TraesCS7A02G024800      -------------------------------------------CTGTCATATTGAGCATG
                                                                                    

AT4G01440               GTAAAACTTTTATTGCAATAATAA------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      AAAAATCATATACTGTAGCGATATTTTTAGAAATTTTGTGTGGTCAGTGTAAGTTATCAT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      TTTGAACATTTTCTTACGTAGTACC-----------------------------------
TraesCS4A02G464200      AAAAGAAATAAAAGAAAAGAA---------------------------------------
TraesCS7A02G024800      AAAAGAAATAAAAGAAAAGAA---------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GTGACTACAATTAGAAGATATGTCGTGATGGTTGCTGAATGCAATAGATTTGAATTGTGG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      -------------------------------------GATGCCTTGTAATTTCGTCTGCA
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ----AAAAATCTCCTTTGCAATCAAATGCTTCTAATTTTGAGTGTTTGAGAAA-------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GTTTTAAATCCTTATCTTCTCTCTATTTTTTTTAAGTTATCCTCTCCCGATATTAATCAT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      TTTCATGGAAATATTCTTGGTGATATTATTTT----------------------------
TraesCS4A02G464200      ----AAGAAAATATTCTCCACACGATTTTT------------------------------
TraesCS7A02G024800      ----AAGAAAATATTCTCC-----------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      CATAGCTATATCTATATCTATATCTATATCTATACAAAGGGGCTATGGGTGAACCAACCT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GTGGTTGGATGGTTAGAGGGACTATGGTATCCCCACCCCATCAGGGTTCAAATCCTGATG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      CTCGCATTTATTCCTATATTTATTTCAGGATTTCTGACGATACGCATTTAATGGGAGAAG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      ACGTTCCCGTCGACAACGAGGCACCTACGGTGACTTCGTAAATCTCAACATGATATGCTG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS4B02G086600      ------------------------------------------------------------
TraesCS7A02G087800      GCTCAGTCTTTCAGAGGTGCTCATAGGGGTAGGGTGTGTGTTCATAGGGGTGAGTGTATG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
                                                                                    

AT4G01440               ------
TraesCS4B02G086600      ------
TraesCS7A02G087800      CGCGTG
TraesCS6B02G015400      ------
TraesCS6A02G008800      ------
TraesCS6D02G009800      ------
TraesCS4A02G464200      ------
TraesCS7A02G024800      ------
                              
