CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------AGTATCACACTCAT----------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGCTCATTGTG
TraesCS6A02G008800      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGCTCATTGTG
TraesCS6D02G009800      ATGCTCTATGTACGTTGCTACAACTTTGAATAAGTCAGTGTCATATTTGTGATCATTGTG
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
TraesCS6A02G008800      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
TraesCS6D02G009800      CACTTTACTTTCTGGTAGTGTGGTGCCTGGTGAGGTTGCCTTCCTTGCCTGGTATTCAAC
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      AGTGTACCAAATGATTACAGAAAAAACACTCGTCGGCGGGTTTTACCGCCTTCATTGGAA
TraesCS6A02G008800      AGTGTACCAAATGATTACAG--AAAACACTCGTTGGTGGGTTTTACCGCCTTCATTGGAA
TraesCS6D02G009800      AGTGTACCAAATGATTACAG--AAAACACTCGTTGGTGGGTTTTACCGCCTTCATTGGAA
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      TGC-AAAACTTGCCCTGATTTGTCATTGAAAATGACAGTTGGGCAGGAGCAAAATCACAC
TraesCS6A02G008800      TGCAAAAACTAGCCTTAATTTGTCATTGAAAATGACAGTTGCGCAGGAGTAAAATCACAC
TraesCS6D02G009800      TGC-AAAACTAGCCCTAATTTGTCATTGAAAATGACAGTTGGGCAGGAGCAAAATCACAC
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      TAACAAGCACAAAGGTGAATGGCCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
TraesCS6A02G008800      TAACAAGCACAAAGGTGAATGGTCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
TraesCS6D02G009800      TAACAAGCGCAAAGGTGAATGGTCAGTAGTGGTGTTTGAGTTGAGCAATTCACTGCATCT
                                                                                    

AT4G01440               -------------------------------------------TCATATACACAAACCCC
TraesCS6A02G009400      --------------------------------------------CATATAG---------
TraesCS4A02G464200      ---------------------------------------GCCTATAAGTAGTCCATGACA
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTGGTTGTTGACATATACCAGCTCACT
TraesCS6A02G008800      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTG---GTTGACATATACCAGGTCAC-
TraesCS6D02G009800      TGTCATAGTATTGCTGACTCAAGGATAGCATTGCTG---GTTGACATATACCAGGTCAC-
                                                                                    

AT4G01440               TTAGAGAAACAAAAAGAA------------------------------------------
TraesCS6A02G009400      CTTTTTTCCGAAAAGGAA------------------------------------------
TraesCS4A02G464200      AGGGCATCATCATGGCAA------------------------------------------
TraesCS7D02G022700      -----------ATGGCAA------------------------------------------
TraesCS7A02G024800      -----------ATGGCAA------------------------------------------
TraesCS6B02G015400      TTTTTTTACTAATGGCAAGTATTAGGTTCTTTTAGATGCTTTTGGAAGCACTTTTAATGT
TraesCS6A02G008800      CTTTTTTACTAATGGCAAGTATTAGGTT----------CTTTTGGAAGTTTTCTTTATGT
TraesCS6D02G009800      CTTTTTTACTAATGGCAAGTATTAGGTT----------CTTTTGGAAGTTTTCTTTATGT
                                   *    **                                          

AT4G01440               -------------------------TACAAAAAGAAGA----------------------
TraesCS6A02G009400      ------GACAAAGCCCCTCTCACCATACAT------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      TAGCAAGTGAGAGGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
TraesCS6A02G008800      TAGGAAGTGAGGCGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
TraesCS6D02G009800      TAGGAAGTGAGACGACTAGTCCACATACATAAAAAGGAGTTTCTGCAGTCTCAGTGCTTC
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      CGTCTTTTCTCCACCTTCTCGGCATCTTATGTAATTTTTGGTCGGGGCACCAGAAAAGGT
TraesCS6A02G008800      CGTCCTTTCTCCACTTTCTTGGCATCTTATGTAA-TTTTGGTCGGGGCACCAGAAAAGGT
TraesCS6D02G009800      CATCTTTTCTCCACTTTCTTGGCATCTTATGTAA-TTTTGGTCGGGGCACCAGAAAAGGT
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      AAGGGACTAAATCAGGATATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCCTA
TraesCS6A02G008800      AAGGGGCTGAATCAGGACATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCCTA
TraesCS6D02G009800      AAGGGGCTGAATCAGGACATATATTTTACTTTCACGTTTGCACTACCAATTTGATTCGTA
                                                                                    

AT4G01440               ---------GAGAGATTAGTTATTAACTTATTCATAATAAGTGTAATTACTTCGTAT---
TraesCS6A02G009400      ----------------------------------------------------CGAGCTAG
TraesCS4A02G464200      --------------------------------------------------TACAAGTGAA
TraesCS7D02G022700      --------------------------------------------------TACAAGT---
TraesCS7A02G024800      --------------------------------------------------TACAAGT---
TraesCS6B02G015400      CTGTCTACTGATATGCCATTTTATAGATTATTATTAATAATCTTCAGTAGTACGAGT---
TraesCS6A02G008800      CTGTCTACTGATATGCCATTTTATAGATTATTATTAAAAATCTTCAGTAGTACGAGT---
TraesCS6D02G009800      CTGTCTACTGATATGCCATTTTATAGATTATTATTAAAAATCTTCAGTAGTACTAGT---
                                                                            *       

AT4G01440               --------TTAC--------------------TTTTTTTTGGTTAGCAGTCGACTAGTAA
TraesCS6A02G009400      TGAACTTG----------------------------ATTGTGTTGATC------------
TraesCS4A02G464200      GGAAGGTGTGTCAAAG----------------ATTCAT----TCAGCAGCG---------
TraesCS7D02G022700      -GAAGGTGTGTCAAAG----------------ATTCAT----TCGGCAGCG---------
TraesCS7A02G024800      -AAAGGTGTGTCAAAG----------------ATTCA--------GCAGCA---------
TraesCS6B02G015400      --AAGTTGTCACAAAGAGTAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCAT
TraesCS6A02G008800      --AAGTTGTCAC-AAGAGAAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCAT
TraesCS6D02G009800      --AAGTTGTCAC-AAGAGTAGCAAAGGAAATAATTTATTATGTTGATAGCATATTAGCAT
                                                                                    

AT4G01440               T---------------------------------------------CAATAATGGGTTAC
TraesCS6A02G009400      ----------------------------------------------AAGAGAGGAG----
TraesCS4A02G464200      ----------------------------------------------CAATGTGGGG----
TraesCS7D02G022700      ----------------------------------------------CAATGTGGGG----
TraesCS7A02G024800      ----------------------------------------------CAATGTGGGG----
TraesCS6B02G015400      TTACTTTTTTGCCCCCCTTGCATGAATGACCGCCGTCACTTCTGGTCAGTGAGTAG----
TraesCS6A02G008800      TTACTTTTTTGCCCCCCTTGCATGAATGACGGCCGTCACTTTTGGTCAGTGAGTAG----
TraesCS6D02G009800      TTACTTTTTTGCCCCCCTTGCATGAATGACCGCCGTCACTTTTGGTCAGTGAGTAG----
                                                                       *       *    

AT4G01440               TGCGATGGT---------------------------------------------------
TraesCS6A02G009400      ---AATG-----------------------------------------------------
TraesCS4A02G464200      ---GATGGC-----------------------------------------------GCGC
TraesCS7D02G022700      ---GATGGC-----------------------------------------------GCGC
TraesCS7A02G024800      ---GATGGC-----------------------------------------------GCGC
TraesCS6B02G015400      ---CATTGCAGGGCTATATA--------------------ATCAGACAGTTAATGAGCGT
TraesCS6A02G008800      ---CATTGCAGGGCTATATATA---------------ATCATCAGACAGTTAATGAGCGT
TraesCS6D02G009800      ---CATTGCAGGGCTATATATATATATATATATATATATAATCAGACAGTTGATGAGCGT
                            **                                                      

AT4G01440               -----------------------------------------AAATGGACACCGGTGATTA
TraesCS6A02G009400      -----------------------------------------GATTGGAAGCCTATAGTGA
TraesCS4A02G464200      ATCGAT-----------------------------------GAGTGGAAACCGGTGATCG
TraesCS7D02G022700      ATCGAT-----------------------------------GAGTGGAAACCGGTGATCG
TraesCS7A02G024800      ATCGAT-----------------------------------GAGTGGAAACCGGTGATGG
TraesCS6B02G015400      ATCCGTCATCTTGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCCGGTGATGG
TraesCS6A02G008800      ATCAGTCATCTTGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCCGGTGATGG
TraesCS6D02G009800      ATCAGTCATCTTGTAGCGGCAATCTTACAATGTGGGTGCAGGAGTGGAAGCTGGTGATGG
                                                                  * ****  *   *  *  

AT4G01440               TTATGGTTATGATCAATTCAGCGCTGGGTTTAGCTAATGCTTTGGTTAAAAAAGTACTCG
TraesCS6A02G009400      CGATGTTGGCGGTGGTGACCGTGTTCGCGGTGATGAACACGCTGACAAAGATGGCTTTTA
TraesCS4A02G464200      CAATGCTGGTCTTCGACCTCATCTCTGCCGTGACAACGGCCCTGATCAAGGCGGCGCTCG
TraesCS7D02G022700      CAATGCTGATCTTCGACCTCATCTCTGCCGTGACAACGGCCCTGATCAAGGCGGCGCTCG
TraesCS7A02G024800      CAATGCTGGTCTTCGACCTCATCTCTGCCGTGACAACGGCCCTGATCAAGGCGGCGCTCG
TraesCS6B02G015400      GAATGCTGGCCTTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGG
TraesCS6A02G008800      GAATGCTGGCCTTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGG
TraesCS6D02G009800      GAATGCTGGCCTTCGACCTCATCTCTGCTGTGATGACGGCGCTGGTGAAGAAGGCTCTGG
                          *** *     *             *   *    *   *  **   **    *   *  

AT4G01440               ATGGTGGTGTTAACCATATGGTTATCGCAACATATCGTCTTGCTATTTCAACCCTATTTT
TraesCS6A02G009400      ACGAAGGGATGCACACCACCGTCCTCATCGTCCTCCGCCAGCTCACCGCCACGCTCTTCC
TraesCS4A02G464200      AGGAAGGGCTCGACCGTCTAGTGCTCATCACGCTGCGTCAACTGGTGGCCACGGTCTTCC
TraesCS7D02G022700      AGGAAGGGCTCGACCGTCTGGTGCTCATCACGCTGCGTCAACTGGTGGCCACAGTCTTCC
TraesCS7A02G024800      AGGAAGGGCTCGACCGTCTAGTGCTCATCACGCTGCGTCAACTGGTGGCCACGGTCTTCC
TraesCS6B02G015400      AGCAAGGTCTGAACCGCCTGGTCCTCGTTACCCTCCGGCAGCTGGTCGCAACCATCTTCC
TraesCS6A02G008800      AGCAAGGGCTGAACCGCCTGGTCCTCGTCACCCTCCGGCAGCTGGTCGCCACCATCTTCC
TraesCS6D02G009800      AGCAAGGGCTGAACCGCCTGGTCCTCGTCACGCTCCGGCAGCTGGTCGCCACCATCTTTC
                        *    **  *  **      **  **         ** *         * **  * **  

AT4G01440               TGGCACCAATCGCATTTTTTTGGGAACGGTAAGTATATTATATTCATT------------
TraesCS6A02G009400      TCGCCCCGATCGCCTACTTCAAAGAGAGGTTCGTG-TCAGCACTAATTATGTCGTTGCAA
TraesCS4A02G464200      TTTCTCCGGTCGCATTTTTCAAAGAACGGT------ACTGCATAAATTTTGAT-TTGCAG
TraesCS7D02G022700      TTTCTCCAATCGCATTTTTCAAAGAACGGT------ACTACATAAATTTTGAA-TTGCAG
TraesCS7A02G024800      TTTCTCCGATCGCATTTTTCAAAGAACGG---------TACATAAATTTTGAT-TTGCAG
TraesCS6B02G015400      TTGCCCCGATAGCCTTTTTCAAAGAACGGTATGCA-AACACATGCATCCTTCC-TTGTAC
TraesCS6A02G008800      TTGCTCCAATAGCCTTTTTCAAAGAACGGT-----------ATGCATCCTTGT-------
TraesCS6D02G009800      TTGCCCCAATAGCCTTTTTCAAAGAACGGTATGCA-AACACATGCATCCTTGT-------
                        *  * **  * ** *  **    **  **            *   **             

AT4G01440               --AAAGAACTTTGGTCTTGATGATATATATATGTTTG--------TAATAATTAACGTTA
TraesCS6A02G009400      ATATAGACCAGGAGTAATGAAAGCTTTTATATTTTCACAAGATACTAGTTTCTGATGTTG
TraesCS4A02G464200      AAGATGATCAGCAGAGTTCAGAACTT----------A-----TCCTAGAATATGATGCTA
TraesCS7D02G022700      AAGATGACCAGCAGAGTTCAGAACTC----------A-----TCCTAGAATATGATGCTA
TraesCS7A02G024800      AAGATGAC---CAGAGTTCAGAACTT----------A-----TCCTAGAATATGATGCTG
TraesCS6B02G015400      ATACATACAATCTGCGTTCATTCCCC----------GGGTGAGACTGAAACTGCATAGCG
TraesCS6A02G008800      --ACATACAATCTGCATTCATTCCCT------------GGGTGACTGAAACTGCATAGCG
TraesCS6D02G009800      --ACATACAATCTGCGTTCATTCCCT------------GGGTGACTGAAACTGCATAGCG
                              *      *   * *                         *        *     

AT4G01440               A-------AAATGATTCGTTATATGT-------TTTTTAGGAAAACGAGACCGACACTAA
TraesCS6A02G009400      AGTTTGCTAATTTATGTGTGGTTTTCATGTATATATGTAGGAAGACTAGGCCTAAGATGA
TraesCS4A02G464200      C---------------TGTTGTTTTTT-T----CTTTCAGGAACACACGGCCTAAGCTCA
TraesCS7D02G022700      C---------------TGTTGTTTTTT-C----CTTTCAGGAACACACGGCCTAAGCTCA
TraesCS7A02G024800      C---------------TGTTGTTTT--------CTTTCAGGAACACACGGCCTAAGCTCA
TraesCS6B02G015400      C---------------CGTGGCATTCCTG----CATGCAGGAGCACGAGGCCCAAGCTCA
TraesCS6A02G008800      C---------------CACGACATT--------CCTGCAGGAACACGAGGCCCAAGCTCA
TraesCS6D02G009800      C---------------CATGGCATT--------CCTGCAGGAGCACGAGGCCCAAGCTCA
                                               *           *  ****  **  * ** *   * *

AT4G01440               CGCTCAACATCTTGGTTCAGCTTTTCTTCAGTGCTCTTGTTGGGTTCGTTCTTTTTCTAA
TraesCS6A02G009400      CCACAGAGATCTTCGTCTACCTCTTCTTGAGTGC--------------------------
TraesCS4A02G464200      CACTGGAGATCCTCGTGTACCTCTTCTTCAGCGC--------------------------
TraesCS7D02G022700      CACTGGAGATCCTCGTGTACCTCTTCTTCAGCGC--------------------------
TraesCS7A02G024800      CACTGGAGATCCTGGTGTACCTCTTCTTCAGCGC--------------------------
TraesCS6B02G015400      CATTGGAGATCCTGGCGTACCTCTTCTTCAGCGC--------------------------
TraesCS6A02G008800      CATTGGAGATCCTGGTGTACCTCTTCTTCAGCGC--------------------------
TraesCS6D02G009800      CACTGGAGGTCCTGGCGTACCTCTTCTTCAGCGC--------------------------
                        *     *  ** * *   * ** ***** ** **                          

AT4G01440               TTTTCGCTTGGAACTCCTAATAGTTGTAGGAATAATAAGGAAATATTCTAAATAAAAATA
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               GGTTGACTGTTTGAAATTTAAGAAAATAAACCATTTTGTTTAGATTTTTGGATGAAGAAT
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               TTAATATTTAAGAGTTAGGATTTTGGATTTCGAAGTTATGGTTAAGCTTTTAGCGTTTAG
TraesCS6A02G009400      ---------------------------------------------------CTTGCTCGG
TraesCS4A02G464200      ---------------------------------------------------AGCGTTAGG
TraesCS7D02G022700      ---------------------------------------------------AGCGTTAGG
TraesCS7A02G024800      ---------------------------------------------------AGCGTTAGG
TraesCS6B02G015400      ---------------------------------------------------CGTG-----
TraesCS6A02G008800      ---------------------------------------------------CGTG-----
TraesCS6D02G009800      ---------------------------------------------------CGTG-----
                                                                              *     

AT4G01440               GTTTTAGAATTTAAATTTTCTATTACTTAATTAGTTTTTACTTTTTAGAAATATAGACAA
TraesCS6A02G009400      GTAATTAATTTATTTTGCTTAATTACACCAAATGTTGACAG-----------AGCTTAAT
TraesCS4A02G464200      GTA----------------CGGTTGGCAAACATAGCATCAC-----------AGCAATCA
TraesCS7D02G022700      GTA----------------CGGTTGGCAAACATAGCATCAC-----------AGCAATCA
TraesCS7A02G024800      GTA----------------CGGTTGGCAAACATAGCATCAC-----------AACAATCA
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               TTTCTTCTAATTGATATAGAATTTTGAATGTTTGCGTAATTGTCCTGT-TGTTGCATTCT
TraesCS6A02G009400      TTCTTTTGCTTAACTATAGCAAGAGTAACAAGTGCGGATCAGTCATAAATTTCGTATGCT
TraesCS4A02G464200      CTTCCT---------------------------------------GATATGATTCTGTTT
TraesCS7D02G022700      CTTCCTCATATTAGTACATCAACCCGGTTATATAATGTTCTGCCAGAAATGATTCTGTTT
TraesCS7A02G024800      CTTCCTCATATTAGTACAGCGACCCGGCTATAGAATGCTCTGCCAGATATGATTCTGCTT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               AACCGATTTTTAGTCTTTTTCTTTTGTTTTTTTATTGTTAAGAATGTAAATATTTTATAA
TraesCS6A02G009400      AATTGATGCATGG---------CA------------------------------------
TraesCS4A02G464200      GATTCATCATTGA-----TTTTTC------------------------------------
TraesCS7D02G022700      GATTCATCATTGACTTTCCTTTTC------------------------------------
TraesCS7A02G024800      GATTCATCATTGA-----CTTTTC------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               AAAATGAAACATGATAGGTTTACGGTCCGTGGCAAAAAAGATAAAAACATGAAAGCATAA
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               AAATAACCACTGGTTTTTAGTCAAATTAAGAGCTTTATTTTGTACTGAAATATATGATCA
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               TTCTGAACATATTTTAGGGCAAGTTTGACTCAGTATTTCTTCCTATTGGGGCTATCATAC
TraesCS6A02G009400      -----ATGGCATGGCAGAGCGTCGCTGACCCAGTGGCTCTTCTTCTTCGGCCTGCGGTAC
TraesCS4A02G464200      -----CTCCCATTTTAGCGCCGCGCTCTCTCAGTATACCTTCTTCTACGGGCTGCAGTAC
TraesCS7D02G022700      -----CTCCCATTTTAGCGCCGCGCTCTCTCAGTATACCTTCTTCTACGGGCTGCAGTAC
TraesCS7A02G024800      -----CTCCCATTTTAGCGCTGCGCTCTCTCAGTATACCTTCTTCTACGGGCTGCAGTAC
TraesCS6B02G015400      ------------TTTGGCGCGGCGCTCTCGCAGTACACCTTCTTCTACGGCCTGCAGTAC
TraesCS6A02G008800      ------------TTTGGCGCGGCGCTCTCGCAGTACACCTTCTTCTATGGCCTGCAGTAC
TraesCS6D02G009800      ------------TTTGGCGCGGCGCTCTCGCAGTACACCTTCTTCTACGGCCTGCAGTAC
                                        * **     *  * ****    **** * *  ** **    ***

AT4G01440               ACATCGGCTACGTTGGCATGTGCTTTTATTAGCATGACGCCTGCGATTACATTCGTTATG
TraesCS6A02G009400      ACGACGGCCACGTTCGCGAGCGCCTTCATCAATATGACCCCCATGTTCACCTTCCTGCTG
TraesCS4A02G464200      ACAACAGCAACGTTTGCAATAACTTTCACCAACCTGGCTCCAGTGCTGACTTTCCTCAT-
TraesCS7D02G022700      ACAACAGCAACGTTTGCCATAACTTTCACCAACCTGGCTCCTGTGCTGACTTTCCTCAT-
TraesCS7A02G024800      ACAACGGCAACGTTTGCAATAACTTTCACCAACCTGGCTCCTGTGCTCACTTTCCTCAT-
TraesCS6B02G015400      ACCACCGCCACCTTCGCCATAACCTTCATCAACCTCTCCCCTGTGCTCACCTTCCTCAT-
TraesCS6A02G008800      ACCACCGCCACCTTTGCTATAACCTTCATCAACCTCTCTCCTGTGCTCACCTTCCTCAT-
TraesCS6D02G009800      ACCACCGCCACCTTCGCCATAACCTTCATCAACCTCTCTCCTGTGCTCACCTTCCTCAT-
                        **  * ** ** ** **     * ** *  *   *  * **   * * ** *** *  * 

AT4G01440               GCTCTAATATTC------AGGTAAACTATAAGTGTCTAATATTAATTCAATTATTACTAG
TraesCS6A02G009400      GCGCTGCCCTTC------------------------------------------------
TraesCS4A02G464200      -CGCGGTCTTGCTCAGGTGTGTGTGTGTACCAATTTTCAAATTTACCTGGTGGTACCTTG
TraesCS7D02G022700      -CGCGGTCTTGCTCAG----GTGTGTGCGCAAATTTTCAAATTTACC---TGGCACCTTT
TraesCS7A02G024800      -CGCTGTCTTGCTCCGGTGTGTGTGTGTGCCGATTTTCAAATTTACC---TGGTACCTTT
TraesCS6B02G015400      -CGCCGTCGT--------------------------------------------------
TraesCS6A02G008800      -CGCCGTCGT--------------------------------------------------
TraesCS6D02G009800      -CGCCGTCGT--------------------------------------------------
                         * *     *                                                  

AT4G01440               ACAAACTAAGTTTATTATGATAATATGTAAACACAATTCTTTG-----------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      CTCATGCACCTTGCTCCTGCCAATATCTGAAACCTTCCCTCTGGGAATACTACCCATCAT
TraesCS7D02G022700      TTCATGCACTTTGTTCTTGCTAATATCTGAAA----CCCTTTGGGAATACTGC---TCAT
TraesCS7A02G024800      CTCATGCACTTTGTTCTTGCTAATATCT-AAA----CCCTTTGGGAATACGGC---TCAT
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      ------------------------------------------------------------
                                                                                    

AT4G01440               -GGTGTAGGGTAGAGAAGCTAAACATGAAAAGCAAAGCAGGTATGGGGATGGTGATGGGC
TraesCS6A02G009400      ------AAGATCGAGAAGCTCGACGTGACCACCGGCTCCGGCGCCGCCAAGCTCACCGGC
TraesCS4A02G464200      GGATGTAGGGTGGAGTCACTGAACATGAAGAACAAGGCAGGAGCTGCGAAGATCATCGGG
TraesCS7D02G022700      GGATGCAGGGTGGAGTCACTGAACATGAAGAACAAGGCAGGAGCTGCGAAGATCATCGGG
TraesCS7A02G024800      GGATGTAGGGTGGAGTCACTGAACATGAAGAACAAGGCAGGAGCTGCGAAGATCATCGGG
TraesCS6B02G015400      -GATG-AGGATGGAACCGCTGAAGTTGAAGAGCATGGCGGGAGCCGCAAAGATCACCGGA
TraesCS6A02G008800      -GATG-AGGATGGAGCCGCTGAAGTTGAAGAGCATGGCGGGAGCTGCGAAGATCACCGGA
TraesCS6D02G009800      -GATG-AGGATGGAGCCGCTCAAGTTGAAGAGCATGGCGGGAGCCGCAAAGATCACCGGG
                              * * * **    **  *  ***  * *    * **    *  * * * *  ** 

AT4G01440               GCGTTGATATGCATAGGAGGAGCTTTATTATTAACAATGTACAAAGGTGTTCCCTTGACA
TraesCS6A02G009400      ACGGCCGTGGGGCTGGCCGGAGCGATTTTGATGGCGCTCTACCAAGGCCCGGCCCTGACG
TraesCS4A02G464200      ACGCTCATGTCGTTCGCCGGCGTCATGCTCCTGACCCTCTACAAGGGTGTGGCCTTGACA
TraesCS7D02G022700      ACACTCATGTCGTTCGCCGGCGTCATGCTCCTGACCCTCTACAAGGGTGTGGCCTTGACA
TraesCS7A02G024800      ACACTCATGTCGTTCGCAGGCGTCATGCTCCTGACCCTCTACAAGGGTGTGGCCTTGACA
TraesCS6B02G015400      ACACTCACGTCGCTGGCCGGCTTGCTGCTGCTGAGTCTCTACAAGGGAGTGCCGCTGACG
TraesCS6A02G008800      ACGCTCACGTCGCTGGCCGGCTTGCTGCTGCTGAGTCTCTACAAGGGTGTGCCGCTGACG
TraesCS6D02G009800      ACGCTCACGTCGCTGGCCGGCCTGCTGCTGCTGAGTCTCTACAAGGGTGTGCCGCTGACG
                         *           * *  **     *  *  *     * *** * **     *  **** 

AT4G01440               ----AAACTTCG------GAAACTAGAAACCCATCAGTTGA-------TAAACAATAACC
TraesCS6A02G009400      ----GGGACGCG------GACCACAG------ACCAC-----------CACGCCG---CC
TraesCS4A02G464200      CACCAAGCAGA-------GCCTTCAG------GCCAG-----------CATGCAGAAGCA
TraesCS7D02G022700      CACCAAGCAGA-------GCCTTCAG------GCCAG-----------CATGCAGAAGCA
TraesCS7A02G024800      CACCAAGCAGA-------GCCTTCAG------GCCAG-----------CATGCAGAAATA
TraesCS6B02G015400      CACCAGGCCGCCGCT---GCACCTAG------CCCAGCTGCTTCTCACCATGCAGCACCC
TraesCS6A02G008800      CACCAGGCCGCCACTTCTGCACCTAG------CCCAGCTGCTCAC---CATGCAGCACCC
TraesCS6D02G009800      GACCAGGCTGCCACTGACGCACCTAG------CCCAGCTGCTCTTCACCATGCAGCACCC
                                          *     **        **             *  *       

AT4G01440               AC----GCTATGAAACCAG------AGAATTGGATAATAGGATGCGTACTTCTCTTTGCG
TraesCS6A02G009400      GCGGCTGCTGCCCACGGTGGCGCGTGGAGGTGGGCGATCGGGTCGGCGGCGCTGCTGGGC
TraesCS4A02G464200      GAAGCAGCAGCAGAATCTGGCAAGAAGAGCTGGACCCTGGGCACTCTAGCATTACTGGCA
TraesCS7D02G022700      GCAGCTGCAGCAGAATCTGGCAAGAAGAGCTGGACCCTGGGCACTCTAGCATTACTGGCA
TraesCS7A02G024800      GCA---GCAGCAGAATCTGGCAAGAAGAGCTGGACCCTGGGCACTCTAGCGTTACTGGCA
TraesCS6B02G015400      TCTG--ACAGCAG----TGGCAACAGGAGCTGGATGCTGGGAACCATGGCGTTGCTGTTC
TraesCS6A02G008800      TCTG--ACAGCAG----TGGCAACAGGAGCTGGATGCTGGGCACCATCGCGTTGCTGTTC
TraesCS6D02G009800      TCCG--ACAGCAG----TGGCAACCGGAGCTGGATGCTGGGCACCATGGCGTTGCTGTTC
                               *          *       **  ***    * **           *  *    

AT4G01440               GGTAGTAGCTGTTTCGGGTCGTGGATGCTGATACAAGCCAAAGTGAACGAGAAATACCCT
TraesCS6A02G009400      GGCTCGGCGAGCTGGTCGCTGTGGTTCATACTACAGTCCAAGATCGGCACCAAGTACCCC
TraesCS4A02G464200      AACTGCCTGTGCTTCTCCTTTTGGCTCCTGCTGCAGTCCAAGCTCACCAAGAAGTACCCA
TraesCS7D02G022700      AACTGCCTGTGCTTCTCCTTTTGGCTCTTGCTGCAGTCCAAGCTCACCAAGAAGTACCCA
TraesCS7A02G024800      AACTGCCTGTGCTTCTCCTTTTGGCTCCTGCTGCAGTCCAAGCTCACCAAGAAGTACCCA
TraesCS6B02G015400      AACTGCCTGTGCTTCTCCTTCTGGCTGCTGCTGCAGACAAAGCTGACCAAGAAGTACCCA
TraesCS6A02G008800      AACTGCCTGTGCTTCTCCTTCTGGCTGCTACTGCAGACAAAGCTGACCAAGAAGTACCCG
TraesCS6D02G009800      AACTGCCTGTGCTTCTCCTTCTGGCTGCTGCTGCAGACAAAGCTGACCAAGAAGTACCCG
                                  * *        *** *  *  * **  * **  *   *   ** ***** 

AT4G01440               TGTCAATACTCGAGTACTGTCGTATTATCCTTCTTTGGCACCATCCAA---------TGC
TraesCS6A02G009400      GCTCTGTACTCCAGCACGGCGTGGATGTTCCTGCTGAGCACCGCGCAGATGGCCGCCGTC
TraesCS4A02G464200      GCACTCTACTCCAGCACTGCATACATGTTCCTCATCAGCTCCCTGCAG---------GGA
TraesCS7D02G022700      GCACTCTACTCCAGCACCGCATACATGTTCCTCATCAGCTCCCTGCAG---------GGC
TraesCS7A02G024800      GCACTCTACTCCAGCACTGCATACATGTTCCTCATCAGCTCCCTGCAG---------GGC
TraesCS6B02G015400      GCCATCTATTCAAGCACCGCCATCATGTTCTTCATCAGCACGCTGCAG---------GGC
TraesCS6A02G008800      GTCATCTACTCGAATACTGCCATCATGTTCTTCATCAGCACTCTGCAG---------GGC
TraesCS6D02G009800      GCCATCTACTCCAGCACCGCCATCATGTTCTTCATCAGCACTCTGCAG---------GGC
                              ** ** *  ** *      * * * *  *  ** *    **             

AT4G01440               GCCCTTCTAAGCCTCATCAAATCTCGAGATATCACGGCTTGGATCCTCACAGATAAACTT
TraesCS6A02G009400      GGGGCCGCGACGGAGGCGATGACCCTCCA------GGTGTGGCTCCCCGGCACGGCGCTG
TraesCS4A02G464200      GGTGGCCTGACAGCGGCGATACAGCGGAGGGCATCGGTGTGGGTCCTCACAAAGCCAGTG
TraesCS7D02G022700      GGGGGCCTGACGGCGGCGATACAGCGGCGGGCATCGGTCTGGGTCCTCACAAAGCCAGTG
TraesCS7A02G024800      GGGGGCCTGACGGCGGCGATACAGCGGCGGGCATCGGTGTGGGTCCTCACAAAGCCAGTG
TraesCS6B02G015400      GGGGCGGTGACGTTGGCGATGGAGAGACACGTGTCGTCGTGGATGCTGACCAGCAAGCTG
TraesCS6A02G008800      GGGGCGGTCACCTTGGCGATGGAGAGACACGTGTCGCTCTGGATGCTGACCAGCAAGCTG
TraesCS6D02G009800      GGGGCGGTGACGTTGGCGATGGAGAGACACGTGTCGCCGTGGATGCTGACCAGCAAGCTG
                        *        *        *                *   *** * *            * 

AT4G01440               GATATCGTTACCATTGTTTACGCGGTAAG--------------------TGTT--TTTAG
TraesCS6A02G009400      AAGGCCGTGACGGTGCTGTTCGT-------------------------------------
TraesCS4A02G464200      GAGATTGTTACAGTACTATACACAGTAAG-------------------ATCTT--TTT--
TraesCS7D02G022700      GAGATTGTTACAGTACTATACACAGTAAG-------------------ATCTT--TTT--
TraesCS7A02G024800      GAGATTGTTACAGTACTATACACAGTAAG-------------------ATCTT--TTT--
TraesCS6B02G015400      GAGATCGTTACCGTCTTGTATGCAGTAAG----TTAAACATCACCATCATCTTGACTT--
TraesCS6A02G008800      GAGATCGTTACCGTCTTGTATGCAGTAAG----TTAAACATCACCATCATCTT--CTTCA
TraesCS6D02G009800      GAGATCGTTACCGTCTTGTATGCAGTAAGCTAATTAAACATCACCATCATCTT--CTTCA
                         *    ** **  *  * *                                         

AT4G01440               TA----------------------TTACTGAAAAAG------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ----------------GTTGCAGTTTACCGAAAAAAGAGTT-AAGAGAAC----------
TraesCS7D02G022700      ----------------GTTGCAGTTTACTGAAAAAAGGATTTAAGAGAAC----------
TraesCS7A02G024800      ----------------GTTGCAGTTTACCAAAAAA-------GAGTGAAC----------
TraesCS6B02G015400      ----------------GTACCACCTTCGCAAGGAGAAGAAAAAAAGGAAC---------T
TraesCS6A02G008800      TCTCCTTGACTTGTACGTACCACCTTCACAAAGAG-------AAGAAAACAGGAACCACT
TraesCS6D02G009800      TCTCCTTGACTT----GTACCACCTTCACAAAGAG-------AAGAGAACAGGAACTGCT
                                                                                    

AT4G01440               -----------------------------------------T----TGGCAGTAT-----
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      -----------------------------------------T----CT--AGTGAA----
TraesCS7D02G022700      -----------------------------------------T----CTGCAGAGAG----
TraesCS7A02G024800      -----------------------------------------T----CTGCAGAGAA----
TraesCS6B02G015400      TCTCCAAAAGGGGCAAGTACTTATAAAAGCCATTGCTTTAGC----TTGCAGCTAACACT
TraesCS6A02G008800      TATCCAAAAGGGGCAACTACTTATAAAAGCCATTGCTTTAATTATCTTGCAGCTAACACT
TraesCS6D02G009800      TATCCAAAAGGGGCAACTACTTATAAAAGCCATTGCTTTAGC----TTGCAGCTAACACT
                                                                                    

AT4G01440               ----------------------------------TTGTTTAATTTTATAACTTCTAGTAA
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ----------------------------------TTG-------------ACTGAACCAA
TraesCS7D02G022700      ----------------------------------TTG-------------ACTGAACCAA
TraesCS7A02G024800      ----------------------------------TTG-------------GCTGAACCAA
TraesCS6B02G015400      AGTCT----ATGCAATCAATACACGCCAGCTAC-TTGACCAACTTGAACAACTGAAACCA
TraesCS6A02G008800      AGTCTATATATGCAATCAATACACGCCAGCTACTTTGACCAACTTGAACAACTGAAACCC
TraesCS6D02G009800      AGTCT-TCTATGCAATCAATACACCCCAGCTAC-TTGACCAACTTGAACAACTGAAACCA
                                                                                    

AT4G01440               AATATAATTA-----AGTTATACGGACCTATGTCTATC----------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      AGACCACTTG-----T--------------------------------------------
TraesCS7D02G022700      AGAACACTTG-----T--------------------------------------------
TraesCS7A02G024800      AGAACACTTG-----T--------------------------------------------
TraesCS6B02G015400      AAAATAGATG-----TGAAATAATAGTAGTAGACTAGTAGGTAAGTACCCAACTGCTTAA
TraesCS6A02G008800      AAAGTACGTGGTGGTGAAAATAATAATAGATATTAAGTACTTAACATATTGTTAATCATA
TraesCS6D02G009800      AAAATAGTTG-----TGAAAATATACAATGAA----------------------------
                                                                                    

AT4G01440               ------------ACAACGTGTTATAGGGAGCAGTAGCACAAGGAATATGTACGGTTGGAA
TraesCS6A02G009400      -------------------------GGGGGTGGTGGGGTCCGGGCTGGGGTTCCTGGCCA
TraesCS4A02G464200      ------------TCCATATGTTGCAGGGAATCTTGGGGTCTGGAGTGGGATATGTACTGA
TraesCS7D02G022700      ------------TTCATATGTTGCAGGGAATTTTGGGGTCTGGAGTGGGATATGTACTGA
TraesCS7A02G024800      ------------TTCATATGTTGCAGGGAATCTTGGGGTCTGGAGTGGGATATGTACTGA
TraesCS6B02G015400      TCTTGCAATGAAATTACATG-TGCAGGGGATAGTCGGATCTGGAGCCGGGTACCTGATAA
TraesCS6A02G008800      CAATGAAATT--ATTACATG-TGCAGGGGATAGTCGGATCTGGAGCCGGGTACCTGATAA
TraesCS6D02G009800      ------------ATTGCACA-TGCAGGGGATAGTCGGATCTGGAGCTGGGTACCTGATAA
                                                 ***     * *     **     *     *    *

AT4G01440               CGTCTTGGTGCATCAGAAAGAGAGGACCTATCTTTACTTCTATATTTACCCCGGTGGGGC
TraesCS6A02G009400      TGTCGTGGTGCGTGGAGCGGCGGGGGCCCGTGTTCACCACGGCGTTCATGCCGCTCATCC
TraesCS4A02G464200      TGACATGGTGTGTGGAGAAGCGAGGGCCGGTGTTCACTTCAGCCTTCATCCCCATCATCC
TraesCS7D02G022700      TGACATGGTGTGTGGAGAAGAGAGGGCCAGTGTTCACTTCAGCCTTCATCCCCATCATCC
TraesCS7A02G024800      TGACATGGTGTGTGGAGAAGAGAGGGCCAGTGTTCACTTCAGCTTTCATCCCCATCATCC
TraesCS6B02G015400      TGACGTGGTGCGTCGAGAAGAAGGGCCCGGTCTTCACCGCAGCCTTCATCCCCATGATGC
TraesCS6A02G008800      TGACGTGGTGCGTGGAGAAGAAGGGCCCGGTCTTCACCGCAGCCTTCATCCCCATGATGC
TraesCS6D02G009800      TGACGTGGTGTGTGGAGAAGAAGGGTCCGGTCTTCACCGCAGCCTTCATCCCCATGATGC
                         * * *****  *      *   ** **  * ** **  *    ** *  **  *    *

AT4G01440               TTATATTTGCAACACTATTTGATTTCTTGATCCTTCATCGTCAAATTTTCCTAGGAAGGT
TraesCS6A02G009400      AGATGATCGCCGCCGGGATCAACGTCACGGTGCTCCGCGAGCAGCTCCACCTCGGG----
TraesCS4A02G464200      AGATCATGGTTGCCATAATTGATTTCTTCTTTCTCCATGAGAACATCTACCTTGGAAGGT
TraesCS7D02G022700      AGATCATGGTGGCCATAATTGATTTCTTCTTTCTCCATGAGAACATCTACCTAGGAAGGT
TraesCS7A02G024800      AGATCATGGTGGCCATAATTGATTTCTTCTTTCTCCATGAGAACATCTACCTTGGAAGGT
TraesCS6B02G015400      AGATCATGGTAGCCATCATCGATTTCTTCTTCCTCCATGAACAAATCTACCTTGGAAGGT
TraesCS6A02G008800      AGATTATGGTAGCCATCATTGATTTCTTCTTCCTCCATGAACAAATCTACCTTGGAAGGT
TraesCS6D02G009800      AGATCATGGTAGCCATCATCGATTTCTTCTTCCTCCATGAACAAATCTACCTTGGAAGGT
                          **  * *   *     *  *  **    * ** *      *  *   *** **     

AT4G01440               ACGTCGAATT--------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      AAACCTGTCTTGCCTGAGTTATTAAATCACTACGGTATCATG------------------
TraesCS7D02G022700      AAACCTGATTTGCTTCAGATTATAAATCAGTACAATCTCATG------------------
TraesCS7A02G024800      AAACCAGATTTGCCTCAGATATTAAATCAGTACAGTCTCATG------------------
TraesCS6B02G015400      AATACATATGTAGTTCTTCT------------CAGTTTCATGCCTCCCTGTCCTTTTGCG
TraesCS6A02G008800      AATACATATATACTTCTTCT------------CAGTTTCATGCCTCCCTGTCCTTTTGTG
TraesCS6D02G009800      AATACATATATAGTTCCTCT------------CAGTTTCATGCCG---------------
                                                                                    

AT4G01440               ------------------------GTATTTATACACATATATCATAAAAAT---------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      -------------------A----TCAGTCATTCATTTCCCATA----------------
TraesCS7D02G022700      -------------------ATCATTCATTCATTCATTTCTCATACTGAAATAAATAATGC
TraesCS7A02G024800      -------------------A----TCATTCATTCATTTCCCATACTGAAATAAATGATGC
TraesCS6B02G015400      ATGA--------------------TCATT--GTCATCGCTGCCAACTGAATTGTTATTGT
TraesCS6A02G008800      ATGATCATTGTCACTGCCGAAGTTTCATGTATACATTGTTGCCAACTGAATTGCTGTTGC
TraesCS6D02G009800      -------------------AAGTTTCATGTATACATTGTTGTTGCTG-------------
                                                                                    

AT4G01440               ----------CTGAATGTGATCGATTTT--------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      --------TTCAGTTTATGAGTGATTTTTTACACTTTTGTACTTGTAGAACTGCAATGCC
TraesCS7D02G022700      TTAATCTTTTCAGTTTA-GAGTGAGTCTATCCACTTATGCACTTGCAGAACTGCAATGGC
TraesCS7A02G024800      ATAATCTTTTCAGTTTATGAGTGAGTTTATCCACTTTTGCACTTGTAGAACTGCAATGGC
TraesCS6B02G015400      TGG-------CTGGAGATAAACTAAGTTAATGGTTTCAGCA---ATCAAATTGTAATGAC
TraesCS6A02G008800      TG--------CTGGAGATAAACAAAGTTAATTGTTTCCGCA---GTCGAGTTGTAATGAA
TraesCS6D02G009800      ----------CTGGAGATAAACAAAGTTAATTGTTTCCGCA---ATCGAGTTTTAATGAC
                                                                                    

AT4G01440               --------------------------CTTTTTGAT-------------------GTGGAT
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      TGGTCCAAATGGCATCATCTTTTGTA-TTTTTGTT----------TTGGCCT-----TGC
TraesCS7D02G022700      TGGTCCAAATGGCATCACCTTTTGTATTTTTTGTT----------TTGGCCT-----TGC
TraesCS7A02G024800      TGGTCCAAATGGCATCACCTTTTGTATTTTTTGTT----------TTGCCCT-----TGC
TraesCS6B02G015400      AAAATT------------TATCTCTGCTTGTTAAT--------CATGGGCGTGCATGTAC
TraesCS6A02G008800      AATTT--------ATACATATTTATGCGTGTTGATTATCGTTACATCGGCGTGCATGTAC
TraesCS6D02G009800      AAAATT------------TATTTCTGCTTGTTAAT--------CATCGGCGTGCATGTAC
                                                                                    

AT4G01440               AGTGTTGTCGGATCTGGGGTTGTAATCTTCGGACTATACATATTCTTGTTGGGAAAAGTC
TraesCS6A02G009400      AGCGTGGTCGGGTCGGTGCTGGTCGTCGTGGGGCTCTACTTGGTCCTCTGGGGGAAGAGC
TraesCS4A02G464200      AGTGTGCTGGGATCCATACTGATGATCATGGGCCTCTATATTCTGCTGTGGGGAAAGAGC
TraesCS7D02G022700      AGTGTACTGGGATCCATACTGATGATAATGGGCCTCTATATTCTGCTGTGGGGAAAGAGC
TraesCS7A02G024800      AGTGTGCTGGGATCCACACTGATGATCTTGGGCCTCTATATTCTGCTGTGGGGAAAGAGC
TraesCS6B02G015400      AGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTGTGCTGTGGGGAAAGAAG
TraesCS6A02G008800      AGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTTTGCTGTGGGGAAAGAAG
TraesCS6D02G009800      AGCGTGCTAGGATCTGTACTGATGATACTGGGGCTCTATCTTTTGCTGTGGGGAAAGAAG
                        ** **  * ** **     *  *  *  * ** ** **  *  *  * * *** **    

AT4G01440               AGGCTAATGAAAGAAGAGTGTGAAAAGAAGTTACCTTGTCGTTTTAATGAAGATGATCAA
TraesCS6A02G009400      AAC--GAGGC--------------------------------------------------
TraesCS4A02G464200      AGG--GATGCCTCGGC----------GACAGTACCACCT------------GCCAAAGAG
TraesCS7D02G022700      AGG--GATGCCTCGGC----------GACAGTACCACCT------------GCCAAAGAG
TraesCS7A02G024800      AGG--GATGCCTCGGC----------GACAGTACCACCT------------GCCAAAGAG
TraesCS6B02G015400      AGG--GATGAAGCAGC------------TACTACCACT----------------------
TraesCS6A02G008800      AGG--GATGAAGCATCTGTATCTTGTACCACTACCACT----------------------
TraesCS6D02G009800      AGG--GATGAATCATCTGTATCTTGTACCACTACCACT----------------------
                        *     * *                                                   

AT4G01440               GAAGAAGATGATGATGAACAATACAA-----AAAGGGTCATCTTATGGTTGTTCCAATGA
TraesCS6A02G009400      ------------GAGCAGCAAACCCA-----CGCTGCCTCCTCCGTCACATTCCAAGCTC
TraesCS4A02G464200      GAAGAGGATAAGGAGAAGCAAATCAAATCATGAGGACCAAAACTATGCAATTCTTAGATT
TraesCS7D02G022700      GAAGAGGATAAGGAGAAGCAAATCAAATCATGAGGACCAAAGCTATGCAATTCTTAGGTT
TraesCS7A02G024800      GAAGAGGATAAGGAGAAGCAAATCAAATCATAAGGACC-AAGCTATGGCACTCTTAGGTT
TraesCS6B02G015400      ------------AACAAGCAAGTC-------GGCGAACAAGCTGACGA------CAAGCC
TraesCS6A02G008800      ------------GACAAGCAAGTC-------GACGAACCAGCTGACGA------CAAGCC
TraesCS6D02G009800      ------------GACAAGCAAGTC-------GACGAACAAGCTGACGA------CAAGCC
                                     *  * ***  *                               *    

AT4G01440               CTCCTTGATAAGATTAGACTTTTTTTTTTTTCTTCTTCTTCACTTCGTACATTATTTAGT
TraesCS6A02G009400      GCGTTGGATGAAGAAACAGAGCATGGTCATTCACGGAT-----CATGCAGAGCGTGTGAC
TraesCS4A02G464200      G-------TAAAACTATGGCATATATTCCTCCTTGGTTTCCTACGCCTACGTAGTTTAAC
TraesCS7D02G022700      G-------AAAAACTATGGCATATATTCCTCCTTAGTTTCCTACGCCTACGTAGTTTAAC
TraesCS7A02G024800      G-------TAAAACTATGGCATATATTCCTCCTTAGTTTTCTACACCTACGTAGTTTAAC
TraesCS6B02G015400      G-------TGAAACTCTAGAGATTATACACCATTGGATTCGGTCATC-------------
TraesCS6A02G008800      G-------TGA-------------------------------------------------
TraesCS6D02G009800      G-------TGAAACTGCAGAGATTA--CATCCTTTGATTCGGTCATT-------------
                                  *                                                 

AT4G01440               AAAACCATTGACCGGTGAAAATTAC--------ATGGACTAGTC----------------
TraesCS6A02G009400      --------GAGCCGCTGCGTCAAGGTGATTAAGGTGCAACTGTC-------TTTCGGCAC
TraesCS4A02G464200      CAAGA---GGAATGCTATACAGTACTGTTAGTAATGCAGTTGTCATATGCGTTTTCGCTC
TraesCS7D02G022700      CAAGA---GGAATGGTATACAGTACTGTTAGTAATGCAGTTGTCGTATGCGTTTTCGCTC
TraesCS7A02G024800      CAAGA---GGAATAGTATACAGTACTGTTAGTAATGCAGTTGTCGTATGCGTTTTCGCTC
TraesCS6B02G015400      --------GCAATGCAACACATAAT--------ATGTAGTTTTTCTTCCCATTTT-----
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      --------GCACTGCAACACATAAT--------ATGTAGTTTTTCTTCCCATTTTACTT-
                                                                                    

AT4G01440               TAACAACGGTTCAA-AAAACTAGTCACATGTTTTTTTTTTTTTGCTTTTTCTTTTCTTTC
TraesCS6A02G009400      CCAAAGGAGGAGGACATAGTTCGCTATTTTCTTCCATTTT--------------TCTTCA
TraesCS4A02G464200      GCACAACGAGACGATACGTCGGGCTAATTTC----------TGCCTAAATGAAGCCCAAA
TraesCS7D02G022700      GCACAACGAGACGATACGTCGGGCTAATTTC----------TGCCTAAATGTAGCCCAAA
TraesCS7A02G024800      GCACAACGAGACGATACGTCGGGCAAATTTCTGCAGCTATATGCCTAAATGTAGCCCAAA
TraesCS6B02G015400      ACTTGACTGCTGGATGCAGCTAGCTACATACTC---------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      -----GCCGCTGGATGCAGCTAGCTATATATGTTATATATAAGGTTGTTCCTAGCTGGTA
                                                                                    

AT4G01440               CCTTTTTTTTGTTTTGCAATGT--------------------------------------
TraesCS6A02G009400      TCTTTCTACTAGAATCAAGTGAACTATAGATAGGTTATTGGAAATAATTCACGTGGATTA
TraesCS4A02G464200      TTCTTCAGGTGATAAAGAGCGG--TGGGCATAGGTTGCCCATATCTCAGTACGTTAGAAG
TraesCS7D02G022700      TTCTTCAGGTGATAAAGAGCGG--TGGGCATAGGTTGCCCATATCTCAGTACGTTAGAAG
TraesCS7A02G024800      TTCTTCAGGTGATAAAGAGCGG--TGGGCATAGGTTGCCAATATCTCAGTACGTTAGAAG
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      CTGTTGACATATGTCCAAGCTACTGAAATAATGGGATTTAGTAACTGAGCAGAGAGCTCA
                                                                                    

AT4G01440               AA-----AACTTTTATTGCA------------------ATAATAAAAAA-----------
TraesCS6A02G009400      GT-----CA--------------------AAGTGGATTATAGTTCGAAC-----------
TraesCS4A02G464200      GT-----CACATCTGTCACACTGAGCAAGAAAAGAAATAAAAGAAAAGA-----------
TraesCS7D02G022700      GT-----CACATCTGTCACACTGAGCATGAAAAGAAATAAAAGAAAAGA-----------
TraesCS7A02G024800      GT-----CACATCTGTCATATTGAGCATGAAAAGAAATAAAAGAAAAGA-----------
TraesCS6B02G015400      ---------CCTCCGTCCCA--------------AAATATAA------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      TTTACCATACAGCTGCGCCAATGCCCTTCGGTAGCTGCATATGGGAAAATTATATGCGAT
                                                                                    

AT4G01440               ------------------------------------------------------------
TraesCS6A02G009400      ------------------------------------------------------------
TraesCS4A02G464200      ------------------------------------------------------------
TraesCS7D02G022700      ------------------------------------------------------------
TraesCS7A02G024800      ------------------------------------------------------------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      TACTGTTCAAATGGTACTTCTTACTTCTCAAACACTTTGTAGTTTTGAACATTTTCTTAC
                                                                                    

AT4G01440               ------------------------ATCTCCTTTGCAATCAAATGCTTCTAATTTTGAGTG
TraesCS6A02G009400      ------------------------G----------GGTAAAGTTTTTTT-----------
TraesCS4A02G464200      ------------------------A----------AAGAAAATATTCTCCACACGATTTT
TraesCS7D02G022700      ------------------------A----------AAGAAAGTATTCTCCGC--------
TraesCS7A02G024800      ------------------------A----------AAGAAAATATTCTCC----------
TraesCS6B02G015400      ------------------------------------------------------------
TraesCS6A02G008800      ------------------------------------------------------------
TraesCS6D02G009800      GTAGTACCGATGCCTTGTAATTTCGTCTGCATTTCATGGAAATATTCTTGGTGATATTAT
                                                                                    

AT4G01440               TTTGAGAAA
TraesCS6A02G009400      ---------
TraesCS4A02G464200      T--------
TraesCS7D02G022700      ---------
TraesCS7A02G024800      ---------
TraesCS6B02G015400      ---------
TraesCS6A02G008800      ---------
TraesCS6D02G009800      TTT------
                                 
