CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS2B02G545100      GCCCCGATCCCCTCCAAAAAAACTCGCCACCTTCGCCGTGCGCGTGCGCTCCCCGTCGCT
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      TGACTCCTCGTCTGGCTCCAATCGAGTAGAAACTTCCGGTGGTAGGTCACCCCGGCTTTA
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------CCCGGTTGGCTTTA----------------------------------------
                                                                                    

TraesCS2B02G545100      CCCCACCCCACCCCCGCCCCCAAAACCGTTCTCCTCCCTCCTCGCCGAACCCCTCTCTCT
TraesCS2A02G516300      ---------------------------------------------------CGACTCTCT
TraesCS2D02G518100      -----------CCCCGCCCCCAAAACCGTTCT----CCTCCTCGTGGAACTCGACTCTCT
                                                                           *  ******

TraesCS2B02G545100      TTCCGTGGGGAGCGAAGC-GGGGCGGGCGATGAGGCCGGGGGCGCCAACGCGGAGCTCAC
TraesCS2A02G516300      TTCCGTGGGGAGCGAAGC-GGGGCGGGCGATGAGGCCGGGGGCGCCAACGCGGAGCTCAC
TraesCS2D02G518100      TTCCGTGGGGAGCGAAGAGGGGGCGGGCGATGAGGCCGGGGGCGCCAACGCGGAGCTCAC
                        *****************  *****************************************

TraesCS2B02G545100      CCACTCAGTCCACCGCAAGCATGTGGCCGGGCAGGTGAACTCCACTCCCCAGCTCCCCAC
TraesCS2A02G516300      CCACCCAGTCCACCGCAAGCATGTGGCCGGGCAGGTGAACTCCACTCCCCCGCTCTCCCC
TraesCS2D02G518100      CCACCCAGTCCACCGCAAGCATGTGGCCGGGCAGGTGAACTCCACTGCCCCGCTCTCCCC
                        **** ***************************************** *** **** ** *

TraesCS2B02G545100      ACG---CGCGCGGTTAAATTGCTCGCCTCCGCCGCCTCTTCCTCCCGCACAGCAGCAGCA
TraesCS2A02G516300      ACGCGCCGCGCGGTTAAATTGCTCGCCTCCTCCAC--------CCCGCAGA-CCGCAGCA
TraesCS2D02G518100      CCGCGCCGCGCGGTTAAATTGCTCGCCTCCGCCGCCACCTCCTCCCGCACAGCAGCAGCA
                         **   ************************ ** *        ****** * * ******

TraesCS2B02G545100      GGATCGG-AGGGCGAGTCGCGGCGGCATGGGTCCCAACCTCAAGTACCGGGCCGGGCTGG
TraesCS2A02G516300      GCAGAGGCCGATCGAGCCGCGGCGGCATGGGTCCCAACCTCAAGTACCGGGCTGGGCTCG
TraesCS2D02G518100      GGAGTGGCCGATCGAGTCGCGGCGGCATGGGTCCCAACCTCAAGTACCGGGCTGGGCTCG
                        * *  **  *  **** *********************************** ***** *

TraesCS2B02G545100      TCCTCATCGTCGCCGTCGTGCTCATATGGGTCACCTCCGCCGAGGTCACGCAGGTATGGT
TraesCS2A02G516300      TCCTCATCGTCGCCGTCGTGCTCATATGGGTCACCTCCGCCGAGGTCACGCAGGTATGCT
TraesCS2D02G518100      TCCTCATCGTCGCCGTCGTGCTCATATGGGTCACCTCCGCCGAGGTCACGCAGGTATGCT
                        ********************************************************** *

TraesCS2B02G545100      CTTGTCCTGTCAAGCAGACCCTTT---TTCTCCTCTTCCTCACATGCTTGCTGTTCCTTT
TraesCS2A02G516300      CCTG-----CCAAGCCCAGCTTTTTCCTCCTCCTCTTCCTCACATGCTTGCTGCTCCTTT
TraesCS2D02G518100      CCTG--CCACCAAGCACAGCCTTTTCCTCCTCCTCTTCCTCACATGCTTGGTGTTCCTTT
                        * **      *****  * * ***   * ********************* ** ******

TraesCS2B02G545100      TCTGTACT---TTATCATTGGGATTGTTTATTGGAGGCCTCTGGATCTTGGCTGCTCTGC
TraesCS2A02G516300      TCTGTACT---TTATCATTATTGTTGTTTATTCGAGGCCTCTGGATCTTGGCTGCTCTTG
TraesCS2D02G518100      TCTGTACTTTATTATCATTATTGTTGTTTATTCGAGGCCTCTGGATCTTGGCTGCTCTTG
                        ********   ********    ********* *************************  

TraesCS2B02G545100      TTTGATAGTTTCCGCGGGCATTTTAAAGC------GCATTTATTCTTCATCTGAATTGTT
TraesCS2A02G516300      TTTGATAGTTTCCGCAGGCCTTTTGTATC------GCATTTATTCTTCATCTGAATTGTT
TraesCS2D02G518100      TTTGATAATGTCCGCAGGCCTTCTGTTTCTGTATGGCATTTATTCGTCATCTGAACTGTT
                        ******* * ***** *** ** *    *      ********** ********* ****

TraesCS2B02G545100      TAGTGTCATTCAGAAGGCTTTCCTGCAATAGATAATTG-TTCACGATGGTGGGATGTTAT
TraesCS2A02G516300      TAGTGTCATTGAGAAGTCTTTACTGCAATAGACAATTGTTTCACGGTGGTGGGATGTTAT
TraesCS2D02G518100      TAGTGTCATTCAGAAGGCTTTCCTGCAATAGATAATTG-CTCACGGTGGTGGGATGATAT
                        ********** ***** **** ********** *****  ***** ********** ***

TraesCS2B02G545100      GGCAGCATCTAGAATACGACCGAGCCTGCACATCGATATATTTTTAGTTCTAGTATACTC
TraesCS2A02G516300      GGCAGCGTGTAGAATACGACCGAGCCTGCGCATCGATATGTTT----TTC----------
TraesCS2D02G518100      -GCAGCATGTAGAATACGACCGAGCCTGCACATCGATATATTTTTAGTTC----------
                         ***** * ******************** ********* ***    ***          

TraesCS2B02G545100      CCTCTGTTCCCAAATATTTGTCTTTCTAGAATTTCACCAAGTGACTACATACGGAGTAAA
TraesCS2A02G516300      -----------------------TTCTAG-------------------------------
TraesCS2D02G518100      -----------------------TTCTAG-------------------------------
                                               ******                               

TraesCS2B02G545100      ATGAATAAATCTACACTCTAAAATACATACATCCGTATGTTGTGTCCTTTTGAAATGCCC
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      AGAAAGACAAATATTTGGGAACACAGGGAGTACTATTTTTCGACCTGGATTTGGTGGTTT
TraesCS2A02G516300      ---------------------------------TATTTTCCGACCTCGATTTGGTAGCTT
TraesCS2D02G518100      ---------------------------------TAATTTCCGACCTCGATTTGGTAGCCT
                                                         ** *** ****** ******** *  *

TraesCS2B02G545100      TTGCCACCGGGTGTCCGGGAGGAATTTGCTGTAG--------------------------
TraesCS2A02G516300      TTGCCACCGGGTGTCCTGGAGAAATTTGCTGTAC--------------------------
TraesCS2D02G518100      TTGCCACCGGGCGTCCGGGAGGAATTTGCTGTATTGATGGCTTTGTTAATTCAAAGCCGG
                        *********** **** **** ***********                           

TraesCS2B02G545100      ----------------------------AGAGTTGTTGCGTATGTGGATGGATGTCTGT-
TraesCS2A02G516300      ----------------------------AAAGTCGTTGCGTGTGTGGGTAGATGTCTGT-
TraesCS2D02G518100      GTTCTTCTTGAGCCTTCGTTCTAAAAAAAAAGTTGTTGCGTATGTTGATGGATGTCTGTA
                                                    * *** ******* *** * * ********* 

TraesCS2B02G545100      ATAAAAGGAAAAATTGCCGTGAATGCTCCATGGATGTGTGCATCTGTCAACATTTCAGTC
TraesCS2A02G516300      ACAAATGGAAAAATTGCTGTGAATGCTCCATGGATGTGTGCATCTGTCAGCATTTCAGTC
TraesCS2D02G518100      ATAAAAGGAAAAATTGCCGTGAATGCTCCATGGATGTGTGCATCTGTCAACATTTCAGTC
                        * *** *********** ******************************* **********

TraesCS2B02G545100      TTTACCTTCCAAGTGCTAGTTTGCTTGAGTTGGTTGC-GACACTTTGCATCACCAATACC
TraesCS2A02G516300      TTTGCCTTGCAAATGCTAGTTTGCTTGAGTTGGTTGCTGACACTTCACATCACCAATACC
TraesCS2D02G518100      CTTACCTTGCAAATGCTAGTTTGCTTGAGTTGGTTGCTGACACTTTGCGTCACCAGTACC
                         ** **** *** ************************ *******  * ****** ****

TraesCS2B02G545100      TGGATGATTGTAGGTGGTTGTGATATTCTTGCTCACCTAATGCATCATTGCAAGCAGGGG
TraesCS2A02G516300      CGGATGATTGTAGGTGGTTGTGATATTCTTACTCACCTAATGCATC--------------
TraesCS2D02G518100      TGGATGATTGTAGGTGGTTGTGATATTCTTGCTCACCTAATGCAGC--------------
                         ***************************** ************* *              

TraesCS2B02G545100      CGGAGACAGGACCCAGGCCCCCAGGGCCTGGGCCCGGGGCGTGAGGTCCAACTTCTTTGG
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      TAACTATAGTGCTACCCCGAGACGCGAGGCACAACTCCAGGGGCAGTGCTTGGAGGCGGC
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      CCAGGGCGCGTAGTTGGCCTGGCTCCGCCCCTGATTGCAAGGAACCATACTTCAGTTTTG
TraesCS2A02G516300      ---------------------------------ATTGCAAGGAACCTTACTTCAGTTTTG
TraesCS2D02G518100      ---------------------------------ATTGCAAGGAACCTTACCACAGTTTTG
                                                         ************* ***  ********

TraesCS2B02G545100      GCAATCAGTAGTTACATTTTACTGAAGAGCATTACATGGACCCACCCTACTAGTTCATCA
TraesCS2A02G516300      GCAATCAGTACTTACATTTTACTGAAGAGCACTACATGGACACACTCTACTAGTTCATC-
TraesCS2D02G518100      GCAATCAATAGTTACATTTTACTGACGGGCATTACATGGACCCGCCCTACTAGTTCATC-
                        ******* ** ************** * *** ********* * * ************* 

TraesCS2B02G545100      GGAGAGCACATGCTTTTACCCTTACATGAAAGTTTGTTTTGCATTTAACTCAATAACATC
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      ATGTGAACCCACCATACTAGTTCATAAGGAGAGCATATGCTTTTTACTCTTAAATGAAAG
TraesCS2A02G516300      --------------------------AGGAGAGCATATGCGTTTCACCCTTACATGAATG
TraesCS2D02G518100      --------------------------AGGAGAGCATATGCGTTTTACCCTTACATGAATG
                                                  ************** *** ** **** ***** *

TraesCS2B02G545100      TTTGTTTTGTTCCTTTTTATAAAAAACTCTAGTCA--AATGAAGTAAAATTTAACTTTAG
TraesCS2A02G516300      TTTGTTTTGTTCCTTTTGAT--AAATTTGTTGTTATCAATGAAGCAAATTTTAACTTGAG
TraesCS2D02G518100      TTTGTTTTGTTCCTTCTGAT--AAATTTGTTGTTATCAATGAAGCAAATTTTAACTTCAG
                        *************** * **  ***  * * ** *  ******* *** ******** **

TraesCS2B02G545100      TATCTGAACTGAACTTCTGTGTGCAGGGGATATTCGCTAACTACAAGCAACCATTTGCAA
TraesCS2A02G516300      CATCTGAACTGAACCTCTGTGTGCAGGGGATTTTCGCTAACTACAAGCAACCATTCGCAA
TraesCS2D02G518100      TATCTCAACTGAACTTCTGTGTGCAGGGGATATTCGCTAACTACAAGCAACCATTCGCAA
                         **** ******** **************** *********************** ****

TraesCS2B02G545100      TTACTTACTTGGGGGCCTCCCTTATGGTCATCTACATCCCGTTGGCATTTCTCAAGGATT
TraesCS2A02G516300      TTACTTACTTGGGGGCCTCCCTTATGGTGATCTACATCCCGTTGGCATTTCTGAAGGATT
TraesCS2D02G518100      TTACTTACTTGGGGGCCTCACTCATGGTCATCTACATCCCATTGGCATTTCTAAAGGATT
                        ******************* ** ***** *********** *********** *******

TraesCS2B02G545100      TTATATACAGATTGTTGAGAAGGAATTCTGGAAGCAGCAAAGCCTCAAAAATCGCGAGCA
TraesCS2A02G516300      TTATATACAGATTGCTGAGAAGGAATTCTGGAAGCAGCAAGGCCTCAAAAATCGCGAGCA
TraesCS2D02G518100      TCATATACAGATTGTTGAGAAGGAATTCTGGAAGCAGCAAAGCCTCAAAAATCGCGAGCA
                        * ************ ************************* *******************

TraesCS2B02G545100      AATCTTCCTTTGGCGGCAGCGCTCCTCTGAAGAATGGTGAATTTCACAAGATGCTCGAAA
TraesCS2A02G516300      AATCTTCATTTGGCGGTAGCGCTCCTCTGAAGAATGGTGAATTTCAGAAGATGCTGGAAA
TraesCS2D02G518100      AATCTTCATTTGGCGGTAGTGCTCCTCTGAAGAATGGTGAATTTCAGAAGATGCTGGAAA
                        ******* ******** ** ************************** ******** ****

TraesCS2B02G545100      TGGAACCACAGAAAACCGTGGTGATAAAAATTACTGATGTGGACCTTCCTGTACTAGAAG
TraesCS2A02G516300      TGGAACCACAGAAAACCGTGGTGATAAAAATTACTGATGTGGACATTCCTGTACTAGAAG
TraesCS2D02G518100      TGGAACCACAGAAAACCGTGGTGATAAAAATTACTGATGTGGACCTTCCTGTACTAGAGG
                        ******************************************** ************* *

TraesCS2B02G545100      AGACGAAACCGCTTATTTGTGGAATTGGTGAATGTGAGGGTGAGGTTTTGAAGGAGCAAC
TraesCS2A02G516300      AGACGAAACCACTCATCTGTGGAATTGGTGAATGTGAGGGTGGGGTTTTGAAGGAGCAAC
TraesCS2D02G518100      AGACAAAACCACTTATTTGTGGAATTGGTGAATGTGAGGGTGAGGTTTTGAAGGAGCAAC
                        **** ***** ** ** ************************* *****************

TraesCS2B02G545100      AGCTTTCCACCAAGGAGATTGCAATTTATGGGTTGTATCTTTGTCCCATATGGTTTGTTA
TraesCS2A02G516300      AGCTTTCCACCAAGGAGATTGCAATTTATGGGTTGTATCTTTGTCCCATATGGTTTGTCA
TraesCS2D02G518100      AGCTTTCCACCAAGGAGATTGCAATTTATGGACTGTATCTTTGTCCCATATGGTTTGTCA
                        *******************************  ************************* *

TraesCS2B02G545100      CAGAGGTAAA-TTTCCAGTTATCTTGCCTGTTACTTGTGATCCATGAAATAGTTTGATTT
TraesCS2A02G516300      CAGAGGTAAATTTTCCAGTTATCTTGCCTGTTACTTATGATTCATGAAATAGTTTGGTTT
TraesCS2D02G518100      CAGAGGTAAA-TTTCCAGTTATCTTGCCTGTTACTTATGATCCAGGAAATAGTTTGATTT
                        ********** ************************* **** ** *********** ***

TraesCS2B02G545100      CAGTCATACAGACCGTATTTTGATCGATACAGTTACTCATCTTCCCTTATGCTTTGGATG
TraesCS2A02G516300      CAGTCATACAGACAGTATTTTGATCGATACAGTTACTCATCTTCTCTTATGCTTTGGATG
TraesCS2D02G518100      CAGTCATACAGACAGTATTTTGATCGATACAGTTACTCATCTTCTCTTATGCTTTGGATG
                        ************* ****************************** ***************

TraesCS2B02G545100      CAGTATTTGTCAAATGCTGCACTTGCAAGAACTAGTGTGGCAAGCACTACTGTACTATCT
TraesCS2A02G516300      CAGTATTTGTCAAATGCGGCACTTGCAAGAACCAGTGTGGCAAGCACTACTGTACTATCT
TraesCS2D02G518100      CAGTATTTGTCAAATGCTGCACTTGCAAGAACTAGTGTCGCAAGCACTACTGTACTATCT
                        ***************** ************** ***** *********************

TraesCS2B02G545100      TCAACTTCGGGGCTCTTCACCCTTTTCATTGGTGTGCTACTTGGCCAAGATTCCATAAAT
TraesCS2A02G516300      TCAACTTCGGGACTCTTCACCCTTTTCATTGGTGTGCTACTGGGCCAAGATTCCATAAAT
TraesCS2D02G518100      TCAACTTCGGGACTCTTCACCCTTTTCATCGGTGTGCTACTTGGCCAAGATTCCATAAAT
                        *********** ***************** *********** ******************

TraesCS2B02G545100      GCTGCCAAAGTTATTGCTGTTTTTGTTAGCATGGCCGGTGTAGCAATGACAACTATGGGC
TraesCS2A02G516300      GCTGCCAAAGTTATTGCTGTTTTTGTTAGCATGGCTGGTGTGGCAATGACAACTATGGGC
TraesCS2D02G518100      GCTGCCAAAGTTATTGCCGTTTTTGTTAGCATGGCTGGTGTGGCAATGACAACTATGGGC
                        ***************** ***************** ***** ******************

TraesCS2B02G545100      CAGACTTGGGCAACAGATGAATCAGAAGTAAGCAATTCAGGGTGAGTGGGTTTACCCTGG
TraesCS2A02G516300      CAGACTTGGGCAACAGATGAATCAGAAGTAAGCAATTCAGGGTGAGTGGGTTTACCCTGG
TraesCS2D02G518100      CAGACTTGGGCAACAGATGAATCAGAAGTAAGCAATTCAGGGTGAGTGGGTTTACCCTGG
                        ************************************************************

TraesCS2B02G545100      CAATTAAGCTTCTCAGCTGTGCATTTGTACCAACTGCCAAGTGGGCTATATACTGTCCAT
TraesCS2A02G516300      CAATTAAGCTTCTCAGCTGTGCATTGGTACCAACTGCCAAGT-GGCTGTATACTGTCCAT
TraesCS2D02G518100      CAATTAAGCTTCTCAGCTGTGCATTGGTACCAACTACCAAGTGGGCTATATATTGTCCAT
                        ************************* ********* ****** **** **** *******

TraesCS2B02G545100      ACTTAATTTAGCTTCTCAGTTGTGCATTGGTACCAACTGCCAAGTGGGCTGTATATTGTC
TraesCS2A02G516300      ACCTAATTTAGCTTCTCACCTGTGCATTGGTACCAACTACCAAGTGGGCTGTATATTGTC
TraesCS2D02G518100      ACTTAATTTAGCTTCTCAGCTGTGCATTGGTACCAACTGCCAAGTGGGCTGTATATTGTC
                        ** ***************  ****************** *********************

TraesCS2B02G545100      CATACCTAATTAGCTTCTCAGCTGTTCACTTGCTTTCTTTTTAGTAAAGATGGTCAGCTG
TraesCS2A02G516300      CA----TAATTAGCTTCTCAGCTGTGCACTTGCTTTCTTTTTAGTAAAGATGGTTAGCTG
TraesCS2D02G518100      TATACTTAATTAGCTTCTCAGCTGTGCACTTGCTTTCTTTTTAGTAAAGATGGTTAGCTG
                         *    ******************* **************************** *****

TraesCS2B02G545100      CAATCAAATTATTTTTCTTGAAAAGGAGAAACTAAAAACATTTGGCATTCCTATTCCATG
TraesCS2A02G516300      CAATCAAATTATTTTTCTTAAAAAGGAGAAACTAAAAGCATTTGACATTCCTGTTTCATG
TraesCS2D02G518100      CAATCAAATTATTTTTCTTAAGAAGGAGAAACTAAAAACATTTGGCATTCCTATTTCATG
                        ******************* * *************** ****** ******* ** ****

TraesCS2B02G545100      GGGCAATTAATGAGCCAGTTATACCAGCAAAAAAATAAATAAATATGAGCCTATTTTAAT
TraesCS2A02G516300      GGGTAATTA-----------------------------------ATGAGGCTGTTT----
TraesCS2D02G518100      GGGCAATTA-----------------------------------GTGAGCCTGTTTTAAT
                        *** *****                                    **** ** ***    

TraesCS2B02G545100      GAGCATGGAACTTTGGGGATGGACTAATGGCTTTGCCAACTGTCTAATTCTTGAGCTTTA
TraesCS2A02G516300      ------------TTGGGGATGAACTCATCACTTTGCCAATTGTCTAATTCTTGAGCTTTA
TraesCS2D02G518100      GAGCATGGAACCTTGGGGATAAACTTATCGCTTTGCCAACTGTCTAATTCTTGAGCTTTA
                                    ********  *** **  ********* ********************

TraesCS2B02G545100      CAACCGCAGGGCCACACAGAGGACTCTTCTAGGTGACATGTTTGGTCTTATGTCAGCTAT
TraesCS2A02G516300      CAACCACAGGGCCACACAGAGGACTCTTCTAGGAGACATGTTTGGTCTTATGTCAGCTAT
TraesCS2D02G518100      CAACCGCAGGGCCACACAGAGGACTCTTCTAGGTGACATGTTTGGTCTTATGTCAGCTAT
                        ***** *************************** **************************

TraesCS2B02G545100      GTCATATGGTCTATTCACTGGTTAGTTGTTGCACTCTTCTGTTCAGTTTTTAGTC---TA
TraesCS2A02G516300      GTCATATGGTCTATTCACAGGTTGGTTATTGCACTCTTCTCTTCAGTTTGTAGTC---TA
TraesCS2D02G518100      GTCATATGGTCTTTTCACTGGTTGGTTGTTGCATTCTTCTGTTCAGTTT-TAATCGAGTG
                        ************ ***** **** *** ***** ****** ******** ** **   * 

TraesCS2B02G545100      TGCACTGGTTGGTTCTCGCCTGATCGTGACTGTTTCACATCATTCCAGTGCTTCTCAAAA
TraesCS2A02G516300      TTCACTGGTTGGTTGTTGCCTGATCCTGATTGTTTCACATCATTCCAGTGCTTCTCAAAA
TraesCS2D02G518100      TTCTCAGTTCAAT----GCCTGATCCTTATTGTTTCACATCATTCCAGTGCTTCTCAAAA
                        * * * * *   *    ******** * * ******************************

TraesCS2B02G545100      AGTTTGCTGGAGGAGAAGGATCAGAAAAGGTTGATGTCCAAAAACTGTTTGGTTTTCTCG
TraesCS2A02G516300      AGTTTGCT---GGAGAAGGATCAGAAAAGGTTGATGTCCAAAAACTGTTTGGTTTTCTCG
TraesCS2D02G518100      AGTTTGCTGGAGGAGAAGGATCAGAAAAGGTTGATGTCCAAAAACTGTTTGGTTTTCTCG
                        ********   *************************************************

TraesCS2B02G545100      GACTTTTCAGTCTCTGTCTTCTCTGGTGGCTTGGTAAGGTTTTTCCCTTTTGCACATTTT
TraesCS2A02G516300      GACTTTTCAGTCTTTGTCTTCTCTGGTGGCTTGGTAAGATTTTTCATTTTTGCACATTTT
TraesCS2D02G518100      GACTTTTCAGTCTTTGTCTTCTCTGGTGGCTTGGTAAG-TTATTCCTTTTTGCACATTTT
                        ************* ************************ ** ***  *************

TraesCS2B02G545100      ATAGTTCTAATAGTGCTCAATATTCAAATATTCATTGATATAAATAGCATGTACTCCCTC
TraesCS2A02G516300      ATTGTTCTAATAGTGCTCAGTATTCAAATATTCATTGATATAAATAGCAT----------
TraesCS2D02G518100      ATTGTTCCAATAGCACTCAGTATTTAAATATTCATTGATATAAGTAGCAT----------
                        ** **** *****  **** **** ****************** ******          

TraesCS2B02G545100      TGTAAACGAATATAAGAGTGTTTAGATCGCTATTTTAGTGATCTATAAACGCTCTTATAT
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      TTCTTTATGGAGGGAGTACTAAACATAAACTGCTGACATACAAGCCTTTTGGCATTGGAT
TraesCS2A02G516300      ---------------GTACTAAACATAAACTGCTGACATACAAGCCTTATGGCATTGGAC
TraesCS2D02G518100      ---------------GTACTAAAGATAACCTGCTGACATACAAGCCTTATGGCATTGGAT
                                       ******** **** ******************* ********** 

TraesCS2B02G545100      GTGAGTCTCATCGAAAGCTACAGGGACTGGCTGAATTCACTCGTTCATGATCCAAAATGT
TraesCS2A02G516300      GTGAGTCTCATCGGAAGCTACAGGGACTGGCTGTATTCACTCATTCATGACCCAAAATGT
TraesCS2D02G518100      GTGAGTCTCATCGAAAGCTACAGGGACTGGCTGTATTCACTCATTCATGATCCAAAATGT
                        ************* ******************* ******** ******* *********

TraesCS2B02G545100      TCTGTATGTTGTGCATGCCAACATTTTATTTCGTATATTGGTAGAATTGGTCAGGAATAG
TraesCS2A02G516300      TCTGTATGTTGTGCATGCAAGTATTTTATTTGGTATTTTGGTCGAATC-GTCAGGAATAG
TraesCS2D02G518100      TCTGTATGTTGTGCATGCCAGTATTTTATTTAGTATTTTGGTCGAATCAGTAAGGAATAG
                        ****************** *  ********* **** ***** ****  ** ********

TraesCS2B02G545100      TTTTGTGTGGAGGTCCACATGTAGTTTGCATGTATTTATAGCTTGTTCTTCTTGGTCTAA
TraesCS2A02G516300      TTTTGTGTCGAGGTCCACATGTACTTTGTATGTATTTATAGTTTGTTCTTCCTGGTCTAA
TraesCS2D02G518100      TTTTGTTTCGAGGTCCACATGTACTTTGCATGTATTTATAGTTTGTTCTTCTTTGTCTAA
                        ****** * ************** **** ************ ********* * ******

TraesCS2B02G545100      ATATACC--AATATCCTGAAGTGCTTGTATCTTTTCAGTGTGGCCATTAACTGCACTTGG
TraesCS2A02G516300      ATATACC--AATATGCTGAAGTGTTTGTATCTTTTCAGTGTGGCCATTAACTGCACTTGG
TraesCS2D02G518100      ATATACCAAAATATGCTTAAGTGCTTGTATCTTTTCAGTCTGGCCATTAACTGCACTTGG
                        *******  ***** ** ***** *************** ********************

TraesCS2B02G545100      CATTGAGCCAAAGTTTACAATGCCCCACTCAGCTAAAGTGGATGAAGTGGTGCTGGCAAA
TraesCS2A02G516300      CATTGAGCCAAAGTTTACAATGCCCCACTCAGCTAAAGTGGATGAAGTGGTGCTGGCAAA
TraesCS2D02G518100      CATTGAGCCAAAGTTTACAATGCCCCACTCAGCTAAAGTGGATGAAGTGGTGCTGGCAAA
                        ************************************************************

TraesCS2B02G545100      TGGCCTTATTGGGAGCGTGCTATCGGACTACTTCTGGTACGCATGAACAGAAGGCTAATG
TraesCS2A02G516300      CGGCCTTATTGGGAGTGTGCTATCAGACTACTTTTGGTACGCATTAAGAGAAGGCTAATG
TraesCS2D02G518100      TGGCCTCATTGGGAGCGTGCTATCTGACTACTTCTGGTACGCATTAACAGAAGGCTAATG
                         ***** ******** ******** ******** ********** ** ************

TraesCS2B02G545100      T---TTTTTTAACAATATTGCATAACTGCGGTGTTTTGACAACTGAACTTTTTCGCAGGG
TraesCS2A02G516300      TT--TTTTTTTACAATATTGCATAACTGCGGTGTTTTGACAACGTAACTTCTGCACAGGG
TraesCS2D02G518100      TTCCTTTTTTAACAATATTGCATAACTGCGGTACTTTGACAATGGAACTTCTGCGCAGGG
                        *   ****** *********************  ********   ***** * * *****

TraesCS2B02G545100      CTCTTTCCGTGGTTTGGACTAATCCCTTGGTGGCCACGTTAGGCATGTCGCTCACAATTC
TraesCS2A02G516300      CTCTTTCCGTGGTTTGGACTAATCCCTTGGTGGCCACGTTAGGCATGTCGCTCACAATTC
TraesCS2D02G518100      CTCTTTCTGTTGTTTGGACTAATCCCTTGGTGGCCACGTTAGGCATGTCGCTCACAATTC
                        ******* ** *************************************************

TraesCS2B02G545100      CACTAGCAATGGTTGCTGACATGGTCATCCACGGTCGACATTATTCAGCAGTCTACATTT
TraesCS2A02G516300      CACTAGCGATGGTTGCTGACATGGTCATCCACGGCCGACATTATTCAGCAGTCTACATTT
TraesCS2D02G518100      CACTAGCGATGGTTGCTGACATGGTCATCCACGGTCGACATTATTCAGTAGTCTACATTT
                        ******* ************************** ************* ***********

TraesCS2B02G545100      TTGGCTCTGTCCAGGTAACTAACTGTTTTGCCCTGCATCTCAGAACTGTTTATTCCAGGT
TraesCS2A02G516300      TTGGCTCTGTCCAGGTATCTAACTCTTTTGCCCTGCATCTCAGAACTGTTTATTTTAGGT
TraesCS2D02G518100      TTGGCTCTGTCCAGGTAACTACCTGTTTTGCCCTGCATCTCAGAACTGTTT----CAGGT
                        ***************** *** ** **************************     ****

TraesCS2B02G545100      TCTGCTGAAAAGCTATAATTGTAACCAGTTCTGATGCATAGACAGTGATAAAAACTGGTG
TraesCS2A02G516300      TTTGTTGAAAAGCTATAATTCTAACCACTTCTGATGCACAAATACTGACAAAAACTACTG
TraesCS2D02G518100      TTTGTTGAAAAGCTATAATTCTAACCACTTCTCATGCACAAATACTGTTGAAAACTACTG
                        * ** *************** ****** **** ***** * * * **   ******  **

TraesCS2B02G545100      TTATTATTTCGAAAGTTAAGATAG-------TTAGTTGCATCCCCGTATTCAGTTATGTC
TraesCS2A02G516300      TTATCATTTCGAAAGTTGAAATAGCTATTGCCTATTGGTATCCCCATGTTCAGTTCTCTG
TraesCS2D02G518100      TTATCATTTGCAAAGTTGAAATAG-------CTATTGGTAACCCCATGTTCAGTTCTCTG
                        **** ****  ****** * ****        ** * * * **** * ******* * * 

TraesCS2B02G545100      AACCTCTCTATCTGCTCAAGATCACTCTTGATTTGCATTTGCCATTTGTTTTACTCTGTC
TraesCS2A02G516300      AACCTCTTTGCCTGCTCAAGATCACTCTT-ACTTGCATTTGCCATCTGTTTTACTCTGTT
TraesCS2D02G518100      AATCTCTTTGCCTGCTCAAGATCATTCTT-ACTTGCATTTACCATTTGTTTTACTCTGTC
                        ** **** *  ************* **** * ******** **** ************* 

TraesCS2B02G545100      TGCCCGTGTGCTGCCTTTGCAGGTATTTTCTGGGTTCGTCATCGCCAACCTTGCCGACCG
TraesCS2A02G516300      TACC--TGTGCTGCTCTTGCAGGTATTTTCTGGGTTCGTCATCGCCAATCTTGCCGACCG
TraesCS2D02G518100      TACC--TTTGCTGCTTTTGCAGGTATTTTCTGGGTTCGTCATCGCCAATCTTGCCGACCG
                        * **  * ******  ******************************** ***********

TraesCS2B02G545100      CGTTTCACGTTTCTTAGGTCTATAGCCTTGAAATCTACAAGGTTGAAATCGGAGTGTACA
TraesCS2A02G516300      CGTTTCACGTTTCTTAGGTCTATAGTCGTGAAATGTACAAGGTTG-AATCGGAGTGTACA
TraesCS2D02G518100      CGTTTCACGTTTCTTAGGTCTATAGCCTTGAAATCTACAAGGTGG-AATCGGAGTGTACA
                        ************************* * ****** ******** * **************

TraesCS2B02G545100      TCTGGAAGGTTGGATAGGGTTAGTTACGAAGTGTACATTGGACGTTTGGGTTAGTTAGT-
TraesCS2A02G516300      TCTGGAAGGTTGGGTAGGGTTAGTAACGAAGTGTACATTGGGTGTTTGGGTTAGTTAGTT
TraesCS2D02G518100      TCTGGAAGGTTCGATAGGGTTAGTTACGAAGTGTACATTGGATATTTGGGTTAGTTAGT-
                        *********** * ********** ****************   *************** 

TraesCS2B02G545100      -TAAGGACAACTCTGTCTTCTCTGTAAATCATAAGGATGGGGGAAATGGCACTGCAGCTC
TraesCS2A02G516300      ATAAGGACAGCTCTGTCTTCTCTGTAAATCATAAGGATGGGGGAAATGGCATTGCAGCTC
TraesCS2D02G518100      -TAAGGACAACTCTGTCTTCTCTGTAAATCATAAGGATGGGGAAAATGGCACTGCAGCTC
                         ******** ******************************** ******** ********

TraesCS2B02G545100      TGTTT------------------CCTTTACACGCAGGAATGGATAATTTTGGTGTGGTGG
TraesCS2A02G516300      TGTTTCCTTTTTACCTTCGGCCCCCTTTACACGCAGGAATGGATAATTTTGGTGTGGTGG
TraesCS2D02G518100      TGTTTCCTTTTTAATTTCGGCCCCCTTTACACGCAGGAATGGATAATTTTGGTGTGGTGG
                        *****                  *************************************

TraesCS2B02G545100      AATTGAAACAGTGAAAGATTAGCATACGTAAGGAACATTATGATGTTGTGGCAGACCTTT
TraesCS2A02G516300      AATTGAAACAGTGAAAGCTTAGCATACGTAAGGAACATTATGAATTT-------------
TraesCS2D02G518100      AATTGAAACAGTGAAAGCTTAGCATACATAAGGAACATTATGATGTTG------------
                        ***************** ********* ***************  **             

TraesCS2B02G545100      GCAACTGTAAATTATTAGCTTTTGCTACGAAATGCTCTGTCAACGCGTACTGTATAGCGC
TraesCS2A02G516300      ------------------------------------------------------------
TraesCS2D02G518100      ------------------------------------------------------------
                                                                                    

TraesCS2B02G545100      TGAAATTTTCAGCGCCCTCTC
TraesCS2A02G516300      ---------------------
TraesCS2D02G518100      ---------------------
                                             
