CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TraesCS7A02G409900      -------------AGCAAACGGGGCAGCTCACGCCAACCGGCACAGTGTCTACATTCCTT
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      AGTCGTTCCCCAAGACAAATGGAACAGCTCACGCTACTCATGGCAGCGACCGTACTGCAG
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ACTCCGT---------------------------------------------ATGGTTGC
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      CATGTGATGTGCTACTGCAGAGGATCCTAACCCCTGCATACGGGCAGGTTGCGTGCGTGG
AT4G19185               -------------------------------------------------TGAGTATGAGC
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ----------------------------------------------------ATGGGGAA
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      GTGGAGCCAGAAGCCA----------CCGCAGCCTTTCCCCAATAAGTCCGCCACACGAC
TraesCS7B02G309300      ----------------------------------------------------------GA
TraesCS7D02G403100      AGCCAGCAGCCACCGG----------CCGCATACCTTCCCCCAATAAATC-CGCCACGAC
AT4G19185               CTGATGTCCTAACCAGATTTAATAATACACGAATATATTTTGATAAAATGATACAGACTC
TraesCS3B02G026700      ----------------------------------------------------------AT
TraesCS6B02G298700      ---------------------------------------------------------GAA
TraesCS6A02G271500      ATCACCTAAAAAACAG----------TGGGGAAAAGTCCTAAAAAAAACAGTGGGGAAAA
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      GGCCGGCAGAGCCGCAGAGGCAGACACCA--------------------------CAATC
TraesCS7B02G309300      GATTCG-------------------------------------------------CTTCT
TraesCS7D02G403100      GGCACGCAGGCGAAAAATCTGGAGTTTTG--------------------------CTTCT
AT4G19185               AAATAAAAGTAGATCGATTTGAGAATTAAATCTCCTAGATATTGTATATGAAAATTTGCA
TraesCS3B02G026700      AGCTAGCGGTCGAGT-----------------------------------------TACC
TraesCS6B02G298700      AGTTCAAAGAGGAGTAG---------TCG--------------------------CTACT
TraesCS6A02G271500      GGTTCAAAGAGGAGTAT---------TCG--------------------------CTACT
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      AGGGGCCGGTGACATCGCCGTCCATCGCAGAAAAGTCCAGGTGAGATAGAGAGAGAGATC
TraesCS7B02G309300      CCTAGTCGGAG------------------------------------------------C
TraesCS7D02G403100      CCTAGTCGTCG------------------------------------------------C
AT4G19185               CAGAACCTATAGGACTCGACAAATAGAAGAAGCAGATTCGTTGCTAACGAAGTAAAGGAT
TraesCS3B02G026700      AGGACCATGCACGTCTGTC----------------------------------------C
TraesCS6B02G298700      CAGACCGTG---------------------------------------------------
TraesCS6A02G271500      CAGACCGTG---------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      TTTCTCCGAGCTCAGCCAGCTAGGCTCCCGCGGTAGCAGTAGCGCCTAGCGGCCGGCGTG
TraesCS7B02G309300      CTCGTCGGAGCCCAGC-------------AAGGCTGGAGTAGTGCCCAGCGGCCGGCGCG
TraesCS7D02G403100      CTCGTCGGAGCCCAGC----------AAGACTGCTGGAGTAGTGGCTAGCGGCCGGCGCG
AT4G19185               CTTACTTTTTTAGTCTTTGCTTTAGAAATAACTTATAACTACAAGTCAGAGAGGGGCCGA
TraesCS3B02G026700      TGTGTCCGTCTACTGC----------TCCACGACAGGACAACCACACCGGGATAGGTAGG
TraesCS6B02G298700      -----------------------------------GGACGACGACCGTGGGATCGG----
TraesCS6A02G271500      -----------------------------------GGACGACGACCGGGGGATCGG----
TraesCS6D02G251700      ----------------------------------GGGACGACGACCGTGGGATCGG----
                                                             *  *       * *   **    

TraesCS7A02G409900      -----------------------------GAGAGAGGA--TGGGGACGGAGCCGACGATG
TraesCS7B02G309300      AGAGGGAGTC----------------AGAGAGAGAAGGGATGGGGACGGAGCCGACGATG
TraesCS7D02G403100      CAGAGAGAGCGAGAGAGAGACAGAGGAGAGAGAGAGGGGATGGGGACGGAGCCGACGATG
AT4G19185               GTAA-----------------------------ATCGGAAAGATGACGGCGCCGATGATC
TraesCS3B02G026700      AGAGGCCACC----------CAGAGGATGCGCTAGTGG--CAACAATGGCGCCCACTATG
TraesCS6B02G298700      ---------------------------------ATCGG--CGGCGATGGCG---------
TraesCS6A02G271500      ---------------------------------ATCGG--CGGCGATGGCG---------
TraesCS6D02G251700      ---------------------------------ATCGG--CG-CGATGGCG---------
                                                            *        * ** *         

TraesCS7A02G409900      ---------CTGCAGCGGTGGTCGTCGT--------------------------------
TraesCS7B02G309300      ---------CTGCAGCGGTGGTCGTCGT--------------------------------
TraesCS7D02G403100      ---------CTGCAGCGGTGGTCGTCGT--------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      GCACTATATATACCCCTGCACCCTCCAATTCCTCTCAACACAACCACAAGCAGTTAGTAA
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ----------------------------------CGATGTGGGGGATGAGCGGGCGCGAC
TraesCS7B02G309300      ----------------------------------CGATGTGGGGGATGAGCGGCCGCGAC
TraesCS7D02G403100      ----------------------------------CGATGTGGGGGATGAGCGGCGGCGAC
AT4G19185               ----------------------------------CTGACCGGAAGTGGATCGGCGGCG--
TraesCS3B02G026700      TCTGCATTCTTTCTCTGTACGTAGATCACTGACAAGTTGTAGAGAGAAAGTGAGGAGGA-
TraesCS6B02G298700      -------------------------------------------------GCGGCGGCGC-
TraesCS6A02G271500      -------------------------------------------------GCGGCGGCGC-
TraesCS6D02G251700      -------------------------------------------------GCGGCGGCGC-
                                                                           *     *  

TraesCS7A02G409900      CGGCTGCGGCTGTGGGAGGACAAGGCGT-GGCGGGCGCACGCGGGCATGGC---------
TraesCS7B02G309300      AGGCTGCGGCTGTGGGAGGACAAGGCGT-GGCGGGCGCACGCGGCCATGGC---------
TraesCS7D02G403100      CGGCTGCGGCTGTGGGAGGACAAGGCGT-GGCGGGCGCACGCGGCCATGGC---------
AT4G19185               ---------------GAGAGAGACGCTC-GGATGGCGCACACTGCTATGGC---------
TraesCS3B02G026700      -------------GAGATGGGGAGGGATCAGCAGGCGGGCGCGGCGGCGGCGCACCGGGA
TraesCS6B02G298700      -------------GGGATGGGGAAGCGA-GGCGGGCGCACGCGGCGATGGT---------
TraesCS6A02G271500      -------------GGGATGGGGAAGCGA-GGCGGGCGCACGCGGCGATGGT---------
TraesCS6D02G251700      -------------GGGATGGGGAAGCGA-GGCGGGCGCACGCGGCGATGGT---------
                                       **     * *     *  ****  * * *    **          

TraesCS7A02G409900      ---------------------------CTTCACGCAGCTCGCCTACGGCGGCTACCACGT
TraesCS7B02G309300      ---------------------------CTTCACGCAGCTCGCCTACGGCGGCTACCACGT
TraesCS7D02G403100      ---------------------------CTTCACGCAGCTCGCCTACGGCGGCTACCACGT
AT4G19185               ---------------------------GTTTGTTCAGCTCTTTAATGGTGGATACCATGT
TraesCS3B02G026700      GAAGGTGAAGCTGTTCATGGGCGTGCTGGCGCTGCAGTTCCTGCTCGCCGGCTTCCACAT
TraesCS6B02G298700      ---------------------------GGGGTCGCAGTTCATCAACGCGGGGTACCACGT
TraesCS6A02G271500      ---------------------------GGGGTCGCAGTTCATCAACGCGGGGTACCACGT
TraesCS6D02G251700      ---------------------------GGGGTCGCAGTTCATCAACGCGGGGTACCACGT
                                                          *** **      *  ** * ***  *

TraesCS7A02G409900      CCTCACCAAGTCCGTGCTCAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGA
TraesCS7B02G309300      CCTCACCAAGTCCGTCCTGAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGA
TraesCS7D02G403100      CCTCACCAAGTCCGTCCTCAACGTCGGCATGAACCAGATCGTCTTCTGCGTCTACCGCGA
AT4G19185               GATTACTAAAGTAGCTCTTAATGTTGGAGTCAACCAGCTTGTCTTCTGTGTATGCCGTGA
TraesCS3B02G026700      CGTCAGCCGCGCCGCGCTCAACATGGGCATCAGCAAGCTCGTCTTCATCGTCTACCGCAA
TraesCS6B02G298700      CATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTTGTCTTCTGCGTCTACCGCGA
TraesCS6A02G271500      CATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGA
TraesCS6D02G251700      CATCGCGAAGCAGGCGCTCAACGTCGGCGTCAACCGCGTCGTCTTCTGCGTCTACCGCGA
                          *          *  ** **  * **  * * *    * ******   ** * ***  *

TraesCS7A02G409900      CCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTA-CGTCGCAC
TraesCS7B02G309300      CCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTA-CGCACCGT
TraesCS7D02G403100      CCTCGTCGCGCTCGCCCTCCTCGCCCCCGCCGCCTACTTCCGAGAGAGGTA-CGTCGTGC
AT4G19185               TCTTCTTGCTCTCTCTATTCTCGCTCCTCTTGCTTACTTCCGCGAAAGGTCTCTTCTTTT
TraesCS3B02G026700      CGTCATCTCCCTCGCCCTCCTCGCCCCCTTCGCCTACTTCCTCGAGAAGTA-CGTC----
TraesCS6B02G298700      CCTCCTCGCGCTCTGCGTGCTTGCTCCCATCGCCTTCTTCC-------------------
TraesCS6A02G271500      CCTCCTCGCGATCTGCGTGCTTGCTCCCATCGCCTTCTTCC-------------------
TraesCS6D02G251700      CCTCCTCGCGCTCTGCGTGCTTGCTCCCATCGCCTTCTTCC-------------------
                          *  *  *  **    * ** ** **    ** * *****                   

TraesCS7A02G409900      TATCATCCCCATGCCCATGGCTGCTCTGATCTAGAGTT----------------------
TraesCS7B02G309300      ACCATCC------CCCATGGCTGCTCTG--------------------------------
TraesCS7D02G403100      TAGGCGCCTCAC-CCCATGGCTGCTCTG---CTCTGAT----------------------
AT4G19185               TCAACTTGTTTTTGTTTCCTCTGTTTTTAGTTCTGAATTCTCGAGATGGGTTTCAATGGT
TraesCS3B02G026700      -------------GCCGCCTCCATTCTT--------------------------------
TraesCS6B02G298700      -------------GCCACCGCGGCTCGC--------------------------------
TraesCS6A02G271500      -------------GCCACCGCGGCTCGC--------------------------------
TraesCS6D02G251700      -------------GCCACCGCGGCTCGC--------------------------------
                                            *   *                                   

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               TTCCTGGTTTTATGATCAATTTGTGGGTTTATATATGAAGTGAGAACTATACACAGTCCC
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ----------CTAGACCAATTGACATCGAATTTGACTAGACGCTATTCGGGTGCGGATTC
TraesCS7B02G309300      --------ATCTGGACCAATTGACATCGAATTTGACTAGATACTATTCGGGTGCGGATTC
TraesCS7D02G403100      ----------CTGGACGAATTGACATCGAATTTGACTTGATACTCTTCGGCTGCGGATTC
AT4G19185               CTTGTAATTGCCTGATCCATTAGTATGGATTTTCGTATTTTGCTTTTGGGTTTTTCTCTG
TraesCS3B02G026700      ------------------------------------------CTTCTCTGCTTCATCTTC
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      TGAATTTCCCGCAGGAGGGTGCG-------------------------------------
TraesCS7B02G309300      TGAAT-TTCCGCAGGAGGGTGCG-------------------------------------
TraesCS7D02G403100      TGAATATCCCGCAGGAGGGTGCG-------------------------------------
AT4G19185               ATGAATCTGTAGAAGTTCTCCTGAGGATTTAAAGTCAATGTGATCTGCATTATAGAAGAA
TraesCS3B02G026700      CAGCAGTTTCAAGAAAGCTTCTG-------------------------------------
TraesCS6B02G298700      ------CCGCGCAGGCTCGTCCG-------------------------------------
TraesCS6A02G271500      ------CCGCGCAGGCTCGTCCG-------------------------------------
TraesCS6D02G251700      ------CCGCGCAGGCTCGTCCG-------------------------------------
                                              *                                     

TraesCS7A02G409900      -----------------------------------------------GCGCCCCGTC---
TraesCS7B02G309300      -----------------------------------------------GCGCCCCGTC---
TraesCS7D02G403100      -----------------------------------------------GCGCCCCGTC---
AT4G19185               CTAGATTTCAGAGTTGGAGCAATGTGCCTAGACTTAAGTTGAGATCTGTGTTCCGTTTAC
TraesCS3B02G026700      -----------------------------------------------CCAGTCAGTC---
TraesCS6B02G298700      -----------------------------------------------CCG-CCCGTC---
TraesCS6A02G271500      -----------------------------------------------CCG-CCCGTC---
TraesCS6D02G251700      -----------------------------------------------CCG-CCCGTC---
                                                                            * **    

TraesCS7A02G409900      ---------------------ACCCCGCAGCT------------GCTCGGCTCCTTCGCG
TraesCS7B02G309300      ---------------------ACCCCGCAGCT------------GCTCGGCTCCTTCGCG
TraesCS7D02G403100      ---------------------ACCCCGCAGCT------------GCTCGGCTCCTTCGCG
AT4G19185               TTCCACTGTTAGTAGATTTAGATACAATGTCTTTGATAATGTTCTCTGAGTTCCATGTCT
TraesCS3B02G026700      ---------------------AGAAAACAA-----------------TGGCGGTGTACAG
TraesCS6B02G298700      ---------------------ACGCGTCGCCT------------CCTTACCTCCTTCTTC
TraesCS6A02G271500      ---------------------ACGCGTCGCCT------------CCTTACCTCCTTCTTC
TraesCS6D02G251700      ---------------------ACGCGTCGCCT------------CCTTACCTCCTTCTTC
                                             *                                 *    

TraesCS7A02G409900      CTGCTTGGATTCACCGGGTAA-----------TTCCCCCACTCCTCCTCCTCCTCCTCAT
TraesCS7B02G309300      CTCCTTGGGTTCACCGGGTAA-----------CTCTCCT-------------------CT
TraesCS7D02G403100      CTCCTTGGATTCACCGGGTAA-----------TTTTCCC---------CCTCGTCCTCAT
AT4G19185               CTTCTTCGGGTTTTGGGATAAATAGGATCTGGTTTCTCGAGCTAGGGTTGTCTAGTTCTA
TraesCS3B02G026700      TTTTTTGAA-TCCTGGCGTGT-----------CTGTTCT---------TTTTTCCATCAT
TraesCS6B02G298700      TTCCTCGGGCTCACGGGGTAA-----------G-CCTGG---------CCACCCGGTCGC
TraesCS6A02G271500      TTCCTCGGGCTCACGGGGTAA-----------G-CCTGG---------CCACGCGGTCGC
TraesCS6D02G251700      TTCCTCGGGCTCACGGGGTAA-----------G-CCTGG---------CCTCCCGGTCGC
                         *  *     *    *  *                                         

TraesCS7A02G409900      GCTGCTGCTGCTACTGCTGAT-----------------GCCCGATGGAGCAATAAGAGTC
TraesCS7B02G309300      GCTGCTACTGCTGCTGCTGCT-----------------GCCTGATGGGGCGA-GCAACAA
TraesCS7D02G403100      GCTGCTGCTGAT--------------------------GCCTGATGGAGCAATAAGAGTC
AT4G19185               TCAGTAAATGAAAGAATGGTTTAGGAGGTTGTAATGCGTCAAGTTTAAGCGAGACCACTC
TraesCS3B02G026700      TCAG-----GAAGGACCGGCC--------------------------------GCCGCTC
TraesCS6B02G298700      TCGGTGTCAGACACGCTGACC-----------------GCTTG---AAGCAATGCTGCTT
TraesCS6A02G271500      TCGGTGTCAGACACGCCGACC-----------------GCTTG---AAGCAATGCTGCTT
TraesCS6D02G251700      TCGGTGTCAGACACGCTGACC-----------------GCTTG---AAGCAATGCTGCTT
                         * *     *                                                  

TraesCS7A02G409900      ACATT-----------------------------CTGACG--------------------
TraesCS7B02G309300      TAACTCTCTTCAGTCTCGTGCTGTCTTCCATCGACTAACTCATCACATTCT---------
TraesCS7D02G403100      ACATT-----------------------------CTGACG--------------------
AT4G19185               TCAAACTTTGAATGTTCAAGTTTTCAAAATCTAATCAGTGAACAGTGTTCGTCTTTCATG
TraesCS3B02G026700      ACCTTCTCGCTG----------------------CTGGCG-----GAGTTC---------
TraesCS6B02G298700      ATGTACTTGCAAATTTCGTGCT------------CTGATGCGTC-TGGTTG---------
TraesCS6A02G271500      ATGTACTTGCAAATGTCGTGCT------------CTGATGCGTC-TGGTTG---------
TraesCS6D02G251700      ATGTACTTGCAAATTTCGTGCT------------CTGATGCGTC-TGATTG---------
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               TATGTAGAAAGATCAGAACTCCAATGAATAAAAGCCTTCTCTTGTCATTCTTCTTTCTGG
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               GCTTAGCAGGGTAAGAAATCATCTCTATCCAGTCTCAATATCTTGTGTTCATGTTTATAG
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ------------------------------------------------------------
                                                                                    

TraesCS7A02G409900      -----------------------------------GCGTG--------CAGGATCTTCGG
TraesCS7B02G309300      -------------------------------GGCGGCGTG--------CAGGATCTTCGG
TraesCS7D02G403100      -----------------------------------GCGTG--------CAGGATCTTCGG
AT4G19185               AGGTTAAATATCTCAGTAAAGCCACCTCTGCTTTGTTCTCAATTTTGATAGGGTATTTGG
TraesCS3B02G026700      -------------------------------TTCGTGCTGGCGCTCATCGGGATCACGGC
TraesCS6B02G298700      -------------------------------TTTGTCCTG--------TAGCATCTTTGG
TraesCS6A02G271500      -------------------------------TTTGTCCTG--------TAGCATCTTTGG
TraesCS6D02G251700      -------------------------------TTTGTCCTG--------TAGCATCTTTGG
                                                              *           *  *    * 

TraesCS7A02G409900      GAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTT
TraesCS7B02G309300      TAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTT
TraesCS7D02G403100      GAACCAGCTCCTCTTCCTGCTCGGCCTCGGCTTCACCAACGCCTCCTACGCCGCCGCGTT
AT4G19185               GAACCAGTTGTTATTTCTTATCGGTCTTACATACACAAATCCCACTTATGCTGCTGCCAT
TraesCS3B02G026700      GAACCAGGGGTTCTACCTGCTGGGGCTGTACCACCTGTCGCCGACCTACGCCTCCGCGAT
TraesCS6B02G298700      CAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAATCCGACATACGCCGCCGCCAT
TraesCS6A02G271500      CAACCAGCTGCTGTTCTTGTTCGGCCTCGGCTACACCAATCCGACATACGCCGCCGCCAT
TraesCS6D02G251700      CAACCAGCTACTGTTCTTGTTCGGCCTCGGCTACACCAATCCAACCTACGCCGCCGCCAT
                         ******    * *   *  * ** **      *       *  * ** **  * **  *

TraesCS7A02G409900      CCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCAATCGTCGGGTGAG---CAAC
TraesCS7B02G309300      CCAGCCCGCCATACCCGTCTTCACCTTCCTCCTGGCCGCAATCGTCGGGTGAG---CAAT
TraesCS7D02G403100      CCAGCCCGCCATACCCGTCTTCACCTTCCTCCTCGCCGCAATCGTCGGGTGAGCACTGAG
AT4G19185               TCAACCATCCATCCCGGTCTTCACCTTTCTCTTGGCTGTCATGATGGGGTGAGTATGATT
TraesCS3B02G026700      CCAGAACATGGTGCCGGCCATCACCTTCGTGCTGGCCGCGGTCCTCCGGCTGG-------
TraesCS6B02G298700      TCAGCCATCAATTCCCGTCTTCACTTTCATCTTGGCCCTCATCATGGGGTCAGTCTCACT
TraesCS6A02G271500      TCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTCGTCATGGGGTCAGTCTCGCT
TraesCS6D02G251700      TCAGCCGTCAATTCCCGTCTTCACTTTCATCTTGGCCCTCATCATGGGGTCAGTCTCACT
                         **        * ** * * **** **  *  * **     *  *  **   *       

TraesCS7A02G409900      CAATCAATCAACGGATGCACATACAC--------------------GTTTCAGAGTTCTG
TraesCS7B02G309300      CAACCT---------------GACCC----------------------------------
TraesCS7D02G403100      CAATCAACCAATCAATCAACGGATGCACATACAC------------GTTTCAGAGTTCTG
AT4G19185               C------------TTTATAAGGGTTCTCTTCTTAGATATGCCTTCAGTTTTGGTTTTTTG
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CAATCTTGAAAAATGTTCAGAGACTCGCATCTCTCTTTGTTTGCTGGTTTAAGCATTTTA
TraesCS6A02G271500      CAATCTTGAAAAATGTTCAGAGACTCGCATCTCTCTTTGTTTGTCGGTTTAAGCATTTTA
TraesCS6D02G251700      CAATCTTGAAAAATATTCAGAGACTCGCATCTCTCTTTCTTTGCTGGTTTAAGCATTTTA
                                                                                    

TraesCS7A02G409900      ACATCGCCT----------TGGATGCAAAATGCCAAACT-------------GAACCGTA
TraesCS7B02G309300      -------------------TTGGATGCAAATGCCAACCT-------------GAACCGTA
TraesCS7D02G403100      ACATCGCCT----------TGGATGCAAAATGCCAAACT-------------GAACCGTA
AT4G19185               ATGTCTCCTACTTGGTATGCAGTACAGAAAGAGTGAATTTGTTGAGAATCGAAGGTCAAA
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CAAT--TTT----------CAGGACTGAAACGGCGAGCTTGGTCACACACGAGGGCCGTG
TraesCS6A02G271500      CCAT--TTT----------CAGCACTGAAACGGCGAGCTTCGTCACACACGAGGGCCGTG
TraesCS6D02G251700      CCAT--TTT----------CAGCACTGAAACGGCGAGCTTGGTCACACACGAGGGCCGTG
                                                                                    

TraesCS7A02G409900      ACAAACCCCGAAAT------GTCCCATTGCCCTGGATACACTTCTGGATTCTGATCAAAT
TraesCS7B02G309300      ACGAACTACGAAATGTCAATGC-----------------ATTTCTGGATTCTGACCAGAT
TraesCS7D02G403100      ACAAACCCCGAAAT------GTCCCATTGCCGCGGATACACTTCTGGATTCTGATCAAAT
AT4G19185               CTAAGGTTGGAGGCACACTTGTGTGTGTTATGGGTGCTGTCTTCATGGTTGTATTTCGAG
TraesCS3B02G026700      -----------------------------------------------------AGCAGGT
TraesCS6B02G298700      CCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGG
TraesCS6A02G271500      CCAAGGTTGGTGGCACCATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGG
TraesCS6D02G251700      CCAAGGTTGGTGGCACAATCGTCTGTGTGCTTGGTGCTGTTCTCATGGTGTTGTACAGGG
                                                                                    

TraesCS7A02G409900      GCTGA-------------------ACCAAAATGT----TCTTATTCCAGTGTCGAAGTGA
TraesCS7B02G309300      GCTGAACCGAACCGTAACAGAATTACCAAAATGA----TCTTGTTCCAGCGTCGAAGTGA
TraesCS7D02G403100      GCTGA-------------------ACCAAAATGT----TCTTATTCCAGTGTCGAAGTCA
AT4G19185               GTCCGGCCTTGTTAGGA------GATAAAGATGCAGACTTTGCGATGAACAATGAAATCA
TraesCS3B02G026700      G-----------------------------------------------------------
TraesCS6B02G298700      GGGCAGCTGTGTTTGGTAGCAGCGATCTAGATCTTGATGTTCCTCGTAATGTCGTCATCA
TraesCS6A02G271500      GGGCAGCTGTGTTTGGTAGCAGCGAGTTAGATCTTGATGTTCAGAGCAATGTCGTCATCA
TraesCS6D02G251700      GGGCAGCTGTGTTTGGTAGCAGCGAGCTAGATCTTGATGTTCATAGCAATGTCGTCATCA
                        *                                                           

TraesCS7A02G409900      TCAACGTCTT--CACCAGAGAC---------GGCCTCTTC--------------------
TraesCS7B02G309300      TCAACGTCTT--CACCAGAGAC---------GGCGTCTTC--------------------
TraesCS7D02G403100      TCCACGTCTT--CACCAGAGAC---------GGCGTCTTC--------------------
AT4G19185               GTGCTAAAGGTCAACCTGAGCCTACTGGTTGGTTAGTCTCTGGTTTTCTCGATCTTGGAT
TraesCS3B02G026700      ------------GACCTGGGCC---------GGCGGCAT-----------------GGGG
TraesCS6B02G298700      CTGAGATGTTGCAACCTGAGCC---------AGGATCATCTTGGTTCATTGCATATGGGC
TraesCS6A02G271500      CCGAGATGTTGCAACCTGAGCC---------AGGATCATCTTGGTTCATTGCATATGGGC
TraesCS6D02G251700      CCGAGATGTTGCAACCTGAGCC---------AGGATCATCTTGGTTCATTGCATATGGGC
                                     *** * * *                *                     

TraesCS7A02G409900      -----AAG------------GTGGTCGGCACGGCCGTG---TGCGTCTTCGGCGCC----
TraesCS7B02G309300      -----AAG------------GTCGTCGGCACGGCCGTG---TGCGTCTTCGGCGCC----
TraesCS7D02G403100      -----AAG------------GTCGTCGGCACGGCCGTG---TGCGTCTTCGGCGCC----
AT4G19185               TTGAGCAATGGCACATTGGAGTTTTATGCTTGATTGGAAACTGCATGTGTATGGCTACTT
TraesCS3B02G026700      TGGCCAAG------------GTGGTGGGCACGGTGGTGA---GCATCGGCGGCGCCAC--
TraesCS6B02G298700      TGGAAAAGTGGCATATCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTT
TraesCS6A02G271500      TGGAAAAGTGGCATATCGGAGTGCTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTT
TraesCS6D02G251700      TGGAAAAGTGGCATATCGGAGTGTTATGTTTAATAGGGAACTGCCTCTGTATGGCAACTT
                              *             **  *  *       *      ** *       **     

TraesCS7A02G409900      --------------GTCCTCATGGTCTTCTACCGA-GGCCCCTCCCTGATCGG-------
TraesCS7B02G309300      --------------GTCCTCATGGTCTTCTACCGA-GGCCCCTCCCTGATCGG-------
TraesCS7D02G403100      --------------CTCCTCATGGTCTTCTACCGA-GGCCCCTCCCTGATCGG-------
AT4G19185               TTCTTGCCATTCAGGTAAAT---------------------CTCTTCATT----------
TraesCS3B02G026700      -------------GGTGATCACGCTCTACAAGGGCCTGCCGCTCTTCAGCC---------
TraesCS6B02G298700      ATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGCCGCGCTCTATTCCATTTGCAT
TraesCS6A02G271500      ATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTATTGTCGCACTCTATTCCGTTTGCA-
TraesCS6D02G251700      ATCTTGCTTTGCAGGTATTAATGATTTTCAGGCTGTTGTCGCTCTCTATTCCGTTTGCAT
                                       *                         * *                

TraesCS7A02G409900      ------------------------CCTTGG----------------------AGGCGC--
TraesCS7B02G309300      ------------------------CCTCGG----------------------AGATGC--
TraesCS7D02G403100      ------------------------CCTCGG----------------------AGGCGC--
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ---------------------ACAACCTGC----------------------ACGTGC--
TraesCS6B02G298700      TTTGATGTTTGTCAACTCGGAACACCTTGAGCTTTAGTTTTCTATCAGGCATATATGCAT
TraesCS6A02G271500      TTTGATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATATGCAT
TraesCS6D02G251700      TTTGATGTTTGTCAACTCGGAACACCTCGAGCTTTAGTTTTCTATCAAGC--ATATGCAT
                                                                                    

TraesCS7A02G409900      -----------CAATGCGCTGGACGGCGCCG--------------ACGCGTCGTGGAGCG
TraesCS7B02G309300      -----------CAATGCGCTGTCTGGCGCCG--------------GCGCGTCATGGAGCG
TraesCS7D02G403100      -----------CAATGCGCTGGCCGGCGCCG--------------ACGCGTCATGGAGCG
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ---------------AGGCCGTGCTCTCCTG----------------------------G
TraesCS6B02G298700      GGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTGTAGGGCA
TraesCS6A02G271500      GGCACAAGTACTGAAAGGCTGAAAGCCTCTGTAAGTTAGATCAGTAAATCTTATAGGGCA
TraesCS6D02G251700      GGCACAAGTTCTGAAAGGCTGAAAGCCTCTGTAAGTTACATCAGTAAATCTTATAGGGCA
                                                                                    

TraesCS7A02G409900      --------------------------------------------------GCAGTTCCTA
TraesCS7B02G309300      --------------------------------------------------GCAGTTCCTA
TraesCS7D02G403100      --------------------------------------------------GCAGTTCCTA
AT4G19185               -----------------------------------------------------GTTTTTG
TraesCS3B02G026700      ACCTCCG-------------------------------------------GCAGCCCCAT
TraesCS6B02G298700      ACTTCAGATCACATCAACTCTATTTAGAACACTCTATTTTGATGAATATTTCAGTCCCAA
TraesCS6A02G271500      ACTTCAGATCACAGCAACTCTATTTAGTACACTCTGTTTTGATGAATATTTCAGTCCCAA
TraesCS6D02G251700      ACTTCAGATCACATCAACTCTATTTAGAGCACTCTATTTTGATGAATATTTCAGTCCCAA
                                                                             *      

TraesCS7A02G409900      TCCTGCTCAGTGGCT------------------------------------------GAC
TraesCS7B02G309300      TCCTGCTCAGTGGCT------------------------------------------GAC
TraesCS7D02G403100      TCCTGCTCAGTGGCT------------------------------------------GAC
AT4G19185               TTTCTTATGGT-------------------------------------------------
TraesCS3B02G026700      CTTCAACTGGACCCT---------------------------------------------
TraesCS6B02G298700      TTCCTAATGGTTTCTCTGCCTTCTTGACATTCTTAAAGTGAGAAGGATATTAAAACTTAG
TraesCS6A02G271500      TTCCTAACAGTTTCTCTGCCTTCTTGCCATTCTTGAAGTGAGAAGGATACTAAAATTTAG
TraesCS6D02G251700      TTCCTAACGGTTTCTCTGCCTTCTTGACATTCTTGAAGTGAGAAGGATATTAAAACTTAG
                                 *                                                  

TraesCS7A02G409900      GCCAGCCACGCTCC---------AGTTCAGTTTTGGAACCTGGAACCTTGGTGTCCTGTG
TraesCS7B02G309300      GCCAACCACGCTCC---------AGTTCAATTTTGGAACCTGGAACCTCGGTGTCCTGTG
TraesCS7D02G403100      GCCAGCCGTGCTCC---------AGTTCAGTTTTGGAACCTGGAACCTTGGTGTCCTGTG
AT4G19185               --TAGGTTT--------------AGACCAACGCATAAACT--GCAGCCTACTAACCTCTG
TraesCS3B02G026700      --CGGCTGCG--------------------TCTTCATCCT-----------CGGCCACTG
TraesCS6B02G298700      GCCGGGTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAACTGGCCATTG
TraesCS6A02G271500      GCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGGCCAACTGGCCTTTG
TraesCS6D02G251700      GCCGGCTTTGCTCTTCCTAGAAAAGGCCCATATTTATGCTGTGTGACCAACTGGCCTTTG
                                                              *               **  **

TraesCS7A02G409900      C--------------------CTCTTAGGCAA----------------------------
TraesCS7B02G309300      C--------------------CTCTTAGGCAA----------------------------
TraesCS7D02G403100      C--------------------CTCTTAGGCAA----------------------------
AT4G19185               T-----------------------------------------------------------
TraesCS3B02G026700      C-----------------------------------------------------------
TraesCS6B02G298700      CTTAATACTGAACATGGTATGTTATTTGGTGAATTGTCACAAGAAGATTTGTCATGGGCC
TraesCS6A02G271500      CTTAATATTGAACATGGTATGTTTTTTGGTGAATTGTCACAAGAAGATTTGTCATGGGCC
TraesCS6D02G251700      CTTATTATTGAACATGGTATGTTGTTTGGTGAATTCTCACAAGAAGATTTGTCATGGGCC
                                                                                    

TraesCS7A02G409900      ---------CTGCTTCCTCATGGGGGCTTATCTTGTCATACAGGTAATGCAGATTGG---
TraesCS7B02G309300      ---------CTGCTTCCTCATGGGAGCTTATCTTGTCATACAGGTGATGCAGATTGGGTT
TraesCS7D02G403100      ---------CTGCTTCCTCATGGGGGCTTATCTTGTCATACAGGTAATGCGGAATGGGAT
AT4G19185               -----------------------GCATGTGTCTTTTAATGTGGATATAATGGAAAC----
TraesCS3B02G026700      -----------------------------------CTCTCCTGGTCGGGATGGATGGT--
TraesCS6B02G298700      GAGCAAATCATACTTCATTTTAAGAACCAATATCACTATACTAACAGAAGGAGATCACCC
TraesCS6A02G271500      GAGGAAATCATACTTCATTTTAAGAACCAATATCACTATACTAATAGAAGGAAATCACCC
TraesCS6D02G251700      GAGGAAATCAAACTTCATTCTAAGAACCAATATCACTATACTAATAGAAGGAGATCACCC
                                                              *                     

TraesCS7A02G409900      --------------------------------------------GTTGTTTGCTCT----
TraesCS7B02G309300      GTTT--------------------------TCAGCTTCATGATAGTTTTTTGCTCT----
TraesCS7D02G403100      TTGT------------------------TTTTAGCTTCATGATAGTTTTTTGCTCT----
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TTTTAACATTGTTGAAGATATGTTTATGTATTAGACTTACTCTAGTATCTTGCTATTCAA
TraesCS6A02G271500      TTTTAACATTGTTGAAAATATGTTTATGTATTAGACTTACTTTGGTATCTTGCTATTCAA
TraesCS6D02G251700      TTTTAACGTTGTTGAAAATATGTTTATGTATTAGACTTACTTTAGTATCTTGCTCA----
                                                                                    

TraesCS7A02G409900      -----------------------------------------TAATGAGAA----------
TraesCS7B02G309300      -----------------------------------------TAATGAGAA----------
TraesCS7D02G403100      -----------------------------------------TAATGAGAA----------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GGTTGAAACTTATGCTAC-AAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTT
TraesCS6A02G271500      GGTTGAAACTTATGCTAC-AAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTT
TraesCS6D02G251700      ------------------CAAGATCTATGTGCTCTGATTTGTATTGCAGAAAGTTTTCTT
                                                                                    

TraesCS7A02G409900      ------CTATA-----TCTGAATTTGTGTCCTTTTCTGCCGTGACTGATTCCAGGCCCCG
TraesCS7B02G309300      ------TTACA-----TCTGAATTTGTGTCCTTTTCTGCTGTGACTGTTTCCAGGCCCCG
TraesCS7D02G403100      ------TTACATATA-TCTGAATTTGTGTCCTTTTCTGCTGTGACTGATTCCAGGCCCCG
AT4G19185               -----------------------------------------------TCTCCAGGCGCCA
TraesCS3B02G026700      -----------------------------------------------GCTCCAGGTGCCC
TraesCS6B02G298700      GTTATTTTATACTTATTATGTTCATGTGTTGTT--------------ATTTCAGGCTCCA
TraesCS6A02G271500      GTTATTTTATAC-TACTATGTTCATGTGTTGTT--------------ATTTCAGGCTCCA
TraesCS6D02G251700      GTTATTTTATACTTATTATGTTCATGTGTTGTT--------------ATTTCAGGCTCCA
                                                                         * ****  ** 

TraesCS7A02G409900      GTGTTAGTAAAATATCCCGCGAGCTTATCCTTGACAGCCTATTCTTATTCATTTGCCACC
TraesCS7B02G309300      GTGTTAGTAAAATATCCTGCGAGCTTATCCTTGACAGCCTATTCTTACTCATTTGCCACC
TraesCS7D02G403100      GTGTTAGTAAAATATCCTGCGAGCTTATCCTTGACAGCCTACTCTTACTCATTTGCCACC
AT4G19185               CTTTTGAAGAAGTATCCGGCAAATCTTTCTGTTGCTGCATTATCATACTTCTTTGGCACA
TraesCS3B02G026700      GTGCTCAAGCGGTACCCGGCGAGGCTGTCGGTCATCTCGCTCACCTGCGTCTTCGGGCTG
TraesCS6B02G298700      ATTTTGGTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCATACTTTTTTGGAGCT
TraesCS6A02G271500      ATTTTGGTGAAGTACCCTTGCAGTTTGTCATTGACAGCTTACTCATACTTTTTTGGAGCT
TraesCS6D02G251700      ATTTTGGTGAAGTACCCTTGCAGTTTATCATTGACAGCTTACTCATACTTTTTTGGAGCT
                         *  *       ** **    *   * **  *     *     * *     ** *     

TraesCS7A02G409900      ATCTTCATGGTGTTGACTGGGGTATTTGCAACCAACGGGCTCCATGAGTG-----GGCGC
TraesCS7B02G309300      ATATTCATGGTGTTGACTGGGGTATTTGCAACCAACGGGCTCCATGAGTG-----GGCAC
TraesCS7D02G403100      ATCTTCATGGTGTTGACTGGGGTTTTTGCAACCAACGGGCTCCATGAGTG-----GGCGC
AT4G19185               GTACTAATGTGCACAACAGCTTTCTTTATGGTAAAGGAGCCATTGGATTG-----GAAGC
TraesCS3B02G026700      CTCCAGTTCCTCGTCATCGCCGCCTT--CACCGAGGAGGACATGAGCCGGTGGAAGGTGC
TraesCS6B02G298700      CTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAAGAAGATTG-----GACTT
TraesCS6A02G271500      CTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAAGAAGATTG-----GACTT
TraesCS6D02G251700      CTTTTAATGCTTATTTCCGGAGTTTTTTCAACAACCAGTAAAGAAGATTG-----GACTT
                         *     *          *     **       *           *   *     *    

TraesCS7A02G409900      TGACAGGGACCGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAATA-ATATCCATG
TraesCS7B02G309300      TGACAGGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAATAATAATCTATG
TraesCS7D02G403100      TGACAGGGACAGAAATCATAGCCGTTCTATATGCTGTGAGTATCTGAACAATAATCTATG
AT4G19185               TAACACAATCTGAGGTTCTTGCAGTTATATATGCAGTAAGT---TACATCAAGATTTTTT
TraesCS3B02G026700      AGTCCGTCGGGGAGCTCTTCACCATCCTCTACGCCGGG----------------------
TraesCS6B02G298700      TGACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGATT--GTGTT-AGATTTATC
TraesCS6A02G271500      TGACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTT-TGTGTT-AGTTTTATT
TraesCS6D02G251700      TGACTGCATCTGAGTTTGCGGCTGTTGTATATGCTGTAAGCTT-TGTGTC-AGATTTATC
                           *       **  *     *  *  * ** ** *                        

TraesCS7A02G409900      GCTGCTGCCTGTGG-------------------------ATG----ACCATGCTAA----
TraesCS7B02G309300      GCCGCCCTTTAGG---------ATTACAATAGAACTTGTATG----ACCATGCTAC----
TraesCS7D02G403100      GCCGCCCTTTATG---------ATTACATTAGAACTTGTATG----ACCATGCTAT----
AT4G19185               TTTC-------------------------ATCTACTCACATGT-----------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TTTCCCATGCATGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGTGGTGAT
TraesCS6A02G271500      TTTCCCATGCGTGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGCGAAGAT
TraesCS6D02G251700      TTTCCCATGCACGGGACCATGAATTGAATTTCTACATGTATGTAGTACTGTGGCGGATAT
                                                                                    

TraesCS7A02G409900      -------------------GATGTGCT---------------------------------
TraesCS7B02G309300      -------------------GATGTGCTAACCTCTCCGAGCT-------------------
TraesCS7D02G403100      -------------------GATGTGCTAACCTCTCCGAGCT-------------------
AT4G19185               ---------------------------------------TTCTCGTGGAATCATTTGACA
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      AATTGTTGCAAACTTGC--AATAAGCTAGTTTGTGTAGGGTATAGAAG---TAGTTGACG
TraesCS6A02G271500      AATTGTTGCAAACTTGCAAAATACGCTAGTTTGTGTAGGCTATAGAAGAAATAGTTGACG
TraesCS6D02G251700      AATTGTTGCAAACTTGCAAAATACGCTAGTTTGTGTAGGCTATAGAAGAAATAGTTGACG
                                                                                    

TraesCS7A02G409900      --------------TGTTCT-------AACCACATTTCTTGCTTGC-GCCAACAGGGAGT
TraesCS7B02G309300      --------------TGTTCT-------AACCACATTTCTTGCTTGCAACCAACAGGGAGT
TraesCS7D02G403100      --------------TGTTCT-------AACCACATTTCTTGCTTGC-ACCAACAGGGAGT
AT4G19185               C--------------------------AATTTCATCTGGTTTTTCTTCTCTCTAGGGAGT
TraesCS3B02G026700      ----------------------------------CTGGTGGCCTCC------------GG
TraesCS6B02G298700      CATGCCACCATAAATATACT-ATACTGAAATTCCCCTATTTCCCCCCTATTTCAGGGAGT
TraesCS6A02G271500      CATGCCACCATAAATATTCT-ATACTGAAATTCTCCTATTTCCCCCCTATTTCAGGGAGT
TraesCS6D02G251700      CATGCCACCATAAATATTCTAATACTGAAATTCTCCTATTTCCCCCCTATTTCAGGGAGT
                                                                                  * 

TraesCS7A02G409900      TGTTGCATCTTGTCT-CAACTACGCAATCATGACTTGGGCGAACAAAATTCTTGGACCAT
TraesCS7B02G309300      TGTTGCGTCTTGTCT-CAACTACGCAATCATGACTTGGGCGAATAAAATTCTCGGACCTT
TraesCS7D02G403100      TGTTGCGTCTTGTCT-CAACTACGCAATCATGACTTGGGCGAACAAAATTCTTGGACCAT
AT4G19185               TATCGCATCAGCACT-AAACTATGGACTCTTGACTTGGTCCAATAAGATTATTGGTCCTG
TraesCS3B02G026700      CGTGGCGTTCGCCCTGCAGATCTGGTGCATCGACCGCGGC-------------GGCCCGC
TraesCS6B02G298700      TGTTTCATCTGCTCT-TAATACTGGTTTATTGACATGGTCCAACAAAATTCTGGGCCCAG
TraesCS6A02G271500      TGTTTCATCTGCTCT-TAATACTGGTTTATTGACATGGTCCAACAAAATTCTGGGCCCAG
TraesCS6D02G251700      TGTTTCATCTGCTCT-TAATACTGGTTTACTGACATGGTCCAACAAAATTCTGGGCCCAG
                          *  * *     **  *     *       ***   * *             ** **  

TraesCS7A02G409900      CTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTCTTT
TraesCS7B02G309300      CTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTCTTT
TraesCS7D02G403100      CTCTGGTCGCCCTCTACAATCCGCTCCAACCAGCATGCTCTACCATCCTCTCAACTATTT
AT4G19185               CCTTGGTTGCTCTCTACAATCCTCTTCAACCCGCTGCATCAGCTTTCCTATCGAGAATCT
TraesCS3B02G026700      TCTTCACCGCCGTGTTCCAGCCCGTGCAGACCGTCGCCGTCGCCGTCATGGCCGCCATCA
TraesCS6B02G298700      CTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGCTCT
TraesCS6A02G271500      CTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGCTCT
TraesCS6D02G251700      CTATGGTGGCACTATATATGCCTCTCCAGCCAGTGCTCTCTGCTCTCTTGTCAGTGCTCT
                           *    **  * *     **  * **  * *         *  ** *  *     *  

TraesCS7A02G409900      TTCTTGGTACCCCAATCTATCTAGGAAGGTA-----TG-----GACCAACCAACACTCTA
TraesCS7B02G309300      TTCTTGGTACCCCAATCTATCTAGGAAGGTA-----TG-----GACCAACCAACACTCTA
TraesCS7D02G403100      TTCTTGGTACCCCAATCTATCTAGGAAGGTA-----TG-----GACCAACCAACACTCTA
AT4G19185               TTCTCGGTAGCCCCATTTATCTCGGAAGGTT-----AG------------ATACATTTT-
TraesCS3B02G026700      TCCTCGGAGACCAGCTCTACACCGGAGGGTAAGTAGAGAGTAAAATCCACATACACC---
TraesCS6B02G298700      TTCTGGGCAGTCCAATTTATTTCGGAAGGTA-----AGAGTATGTTTATCATATGTTCTA
TraesCS6A02G271500      TTCTGGGCAGTCCAATTTATTTCGGAAGGTA-----AGAGTATGTTTATCATATGTTCTA
TraesCS6D02G251700      TTCTGGGCAGTCCAATTTATTTCGGAAGGTA-----AGAGTATGTTTATCATATGTTCTA
                        * ** **    *   * **    *** ***       *              *       

TraesCS7A02G409900      CCCTAT----------------------------CTGCTATTTTAACACTGTGACATCAT
TraesCS7B02G309300      CCCTATG----------------------------TGTTATTTGAACATTGTCACATCAT
TraesCS7D02G403100      CCCTATG-------------------TGTTATTTGAATTATTTGAACATTGTCACATCAT
AT4G19185               ----------------------------------------CTGGAATCTTTTTCAACCAT
TraesCS3B02G026700      --------------------------------------------AACATTGTGACAGCA-
TraesCS6B02G298700      CTCTTTAGAGTTAACCTTTTCCATTTTATCCTTTCTTTGAAGTGAAAAATACTTTTCCAG
TraesCS6A02G271500      TTCTTTAGAGTTAACATTTTCTA-TTTATCCTTTCTTTTAAGTGAAAAATACTTTTCCAG
TraesCS6D02G251700      CTCTTTAGAGTTAACCTTTTCTA-TTTATCCTTTCTTTGAAGTGAAAAATACTTTTCCAG
                                                                    **   *       ** 

TraesCS7A02G409900      GAGTTGTT-AGTTTCCGGTCATTCGAATTGGTCATTTCGCATTGTG---TTTATCAGTTG
TraesCS7B02G309300      GAGTCGTCAAGTTTCGGGTAATTCGAATTGGTTATTTTGCATTGTG---TTTATCGGTTG
TraesCS7D02G403100      GAGTTGTCAAGTTTCGGGTCATTCGAATTGGTCATTTTGCATTGTG---TTTATCGGTTG
AT4G19185               CCACAATCTTCACTTGCAAAATTAAACACTTTCACTTTTCAACATC--------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ACCTCTTCTACTTACTTGTTA----ATTTGTGTATGTAGTA-TGTAGGATATGCACATTG
TraesCS6A02G271500      ACCTCTTC----TACTTGTTA----ATATGTGTATGTAGTAATGTAGGATATGCACATTG
TraesCS6D02G251700      ACCTCTTCTACTTACTTGTTA----ATATGTGTATGTAGTAATGTAGGATATGCACATTG
                                                                                    

TraesCS7A02G409900      AGCTTGGTACTCTTTC---------AATACCACCGTAATGGTGATGGTGCTTGG----AG
TraesCS7B02G309300      AGCTTGGTGCTCTTTCAAGCAAAATGGTATGAC-ATAATGGCAATGGTGCTTGGCGTAAA
TraesCS7D02G403100      AGCTTGGTGCTCTTTCAAGCAAAATGATATGAT-ATAATGGCAATGGTGCTTGGCGTAAA
AT4G19185               ------TTGTTCCATTTCACAGTTT----------------------TCACTTGCAAAAT
TraesCS3B02G026700      ---CCATTGCACTCTT-------------------------------------GTCTGA-
TraesCS6B02G298700      ATGTC-TTGTTCTATTTGACCATC--------TGATAATCTGAAAGGTCAATAGTCTAAG
TraesCS6A02G271500      ATGTC-TTGTTCTATTTGACCATCTGATAAAGTGATAATCTGAAAGGTCGATAGTCCAAG
TraesCS6D02G251700      ATGTC-CTGTTCTATTTGACCATC--------TGATAATCTGAAAGGTCGATAGTCCAAG
                               *   *  *                                      *    * 

TraesCS7A02G409900      CTGATGTTGTTTTCCATGGATGCCGTTACTGAAATTTGATGTTTCTTTA-TTAGTTTGCC
TraesCS7B02G309300      CTGGTGTTGTTTTCCATGGATACCGTTACTGAAATTTGACTTTTTTTTTATTAGTTTGCC
TraesCS7D02G403100      CTGGTGGTGTTTTCCATGTATACCATTACTGAAATTTGACTTTTCTTGG-TTAGTTTGCC
AT4G19185               TT-------TCTAACTCGG---------------------TTTCTTTTCCTCTAC-----
TraesCS3B02G026700      ----------CTGACATGA-------------------------------TTCAT-----
TraesCS6B02G298700      TT-------TCTAACATATG-----GTAATAAAGTA-------ATTCTT-TTTGT-----
TraesCS6A02G271500      TT-------TCTAACATTGA-----TTATTAAAGTTCAG-TTTTTTTTC-TTCAT-----
TraesCS6D02G251700      TT-------TCTAACATTGA-----TTAATAAAGTACAGTTTTTTTTTC-TTCAT-----
                                   *  *                                   *         

TraesCS7A02G409900      T---------GCTATAGAATTCCCACGAATTTATGCAGAACTAAATGCCCACC-------
TraesCS7B02G309300      TCACTTATGGGCTATAGAATTCCCACGAATTTATGCAGAACTAAATACCCACCTTGTGAA
TraesCS7D02G403100      TCACTTATAGGCTACAGAATTCCCACGAATTTATGCAGAACTAAATACCCACCTTGTGCA
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------GGCTGC
TraesCS6B02G298700      ----------AGCAATAAATGTTTACCATCTCTTTTGATCTGAAGTA--ATCTGCTCTGT
TraesCS6A02G271500      ----------AGCAATAAATGTTTATCATCTCCTTTGATCTGAGGTATAATCTGCTCTGT
TraesCS6D02G251700      ----------AGCAATAAATGTTTATCATCTCTTTTGATCTGAGGTATAATCTGCTATGT
                                                                                    

TraesCS7A02G409900      TTACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTTGGG
TraesCS7B02G309300      CTACTTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTTGGG
TraesCS7D02G403100      CTACCTGCAGCCTCATTGGAGGAGTCTTCATCATTGCTGGTCTATACCTGGTTACTTGGG
AT4G19185               ------GCAGCGTTGTGGGTGGATTCTTCATCATTCTAGGACTCTATATGGTCACTTGGG
TraesCS3B02G026700      TTGTGCGCAGGATCATCGGCGCGGTGCTGATCGTCATCGGGCTCTACTTCGTGCTGTGGG
TraesCS6B02G298700      TTGCTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCTGGG
TraesCS6A02G271500      TTACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCTGGG
TraesCS6D02G251700      TTACTTGCAGTATTATTGGAGGGTTTCTAATCATCTCTGGTTTATACATTGTCACCTGGG
                              ****  *  * ** *   *  * *** *    **  * **  * **    ****

TraesCS7A02G409900      CCCGTTACAATGAGGCGCAGA-GAATACTGATGT--CTGGTTATCTGAATCCTCTTCTGG
TraesCS7B02G309300      CCCGTTACAATGAGGCGCAGA-GAATACTGATGT--CTGGTTATCTGAATCCTCTTCTTG
TraesCS7D02G403100      CCCGTTACAATGAGGCGCAGA-GAATACTGATGT--CTGGTTATCTGAATCCTCTTCTTG
AT4G19185               CATCGTTTAGAGAG----------------------------------------------
TraesCS3B02G026700      GCAAGAGCGAGGAGAAGAAGACGAGGAGCCAAGATCCCGAGATGGCGAGGCACCTGCTGG
TraesCS6B02G298700      CACGACATCGAGAAAAGTTGACTGCCACTGGAGTACCTTA---TGTAAAATGCGCATCGG
TraesCS6A02G271500      CGCGACGTAGAGAAAACTTGACTGCCACTGGAGTACCTTA---TGTAAAATGCGCATTGG
TraesCS6D02G251700      CGCGACGTAGAGAAAAGTTGACTGCCACTGGAGTACCTTA---TGTAAAATGCGCATTGG
                                   **                                               

TraesCS7A02G409900      TGGAGGTGGAGGATGCGCC--AGCTCCCAAGAGACAGGAA----AATTCCA---------
TraesCS7B02G309300      TGGAGGTGGAGGATGCGCC--AGCTCCCAAGAGACAGGAA----AATTCCA---------
TraesCS7D02G403100      TGGAGGTGGAGGATGCGCC--AGCTCCCAAGAGACAGGAA----AATTCCA---------
AT4G19185               ---------------------------CGAAAAACAGCGG--------------------
TraesCS3B02G026700      GGGAAGACGGCGGCGA-----GGCTGACAAAGATCAGCAA--------------------
TraesCS6B02G298700      AGCCATGTGACAGTGCTTCTCAAGTCATAAAGGGCGGTAACTTGAGCCCCAGGCCCTTTA
TraesCS6A02G271500      AGCCATGCGACGGTGCTTCTCAAGTCATAAAGGGCGGTAACCTCAGCCCCAGGCCCTTTA
TraesCS6D02G251700      AGCCATGCGACGGTGCTTCTCAAGTCATAAAGGGCGGTAACCTCAGCCCCAGGCCCTTTA
                                                     *    * *                       

TraesCS7A02G409900      -------------------------GCTCAATTGATCCCTAAGACTCGG--AGGAGAGAT
TraesCS7B02G309300      -------------------------GCTCAATCGATCCCTGAGACTCGA-------CG-A
TraesCS7D02G403100      -------------------------GCTCAATTGATCCCTGATACTCAG------ACGAA
AT4G19185               ------TTTCCGGGATTGGGATTGCGCCCCATGG-TCTAAAAACCTCAG----------A
TraesCS3B02G026700      ------------------------------GTGAGCACCGCTGTGCTGG-------CGTG
TraesCS6B02G298700      TATCCCTTTCCAGGCTGTGGAATGTGCCACATGAATCTTGAGAAGCTGGTGTTTTATGCA
TraesCS6A02G271500      TATCCCTTTCTAGGCTTTGGAATGTGCCACATGAATCTTGAGAAGTTGG---TCTACGCA
TraesCS6D02G251700      TATCCCTTTCTAGGCTGTGGAATGTTCCACATGAATCTTGAGAAGTTGGTGATCTATGCA
                                                       *                            

TraesCS7A02G409900      GACTCTGTTA-----------------TTTTTCCAGAACAGCAGCAGCAGAATTACGTTG
TraesCS7B02G309300      GAGTCCACTGTG-----TTTTTTTTTTTTTCATAACAGCAGCATCAGCAGAATTACGTTG
TraesCS7D02G403100      GACTCCACTGTG------------TTTTTTTTCCAGAACAGCAGCAGCAGAATTACGTTG
AT4G19185               GCCTCTGATA-----------------TTTAATGGGACAGTTAACAG-------------
TraesCS3B02G026700      AAAGCTGCTAGC-------------------------------------------TGCTG
TraesCS6B02G298700      ACTTATGCTAGGTATCTCACTATCTCCTTTGATGAGTAAAAATACAT----AATGCATTA
TraesCS6A02G271500      ACTTCTGCTAGG--------CATCTGCTTTGATGAGGAAAAATACAG----AATGCATTA
TraesCS6D02G251700      ACTTCTGTTAGG--------TATCTCCTTTGATGAGTAAAAATACAG----AATGCATTG
                                *                                                   

TraesCS7A02G409900      TATATTAGTATCAGAAAGCTTGTAT------TTACCTTCTCTACCATTGGATTAAGTTAC
TraesCS7B02G309300      TATATTAGTATCAGAAAGCTTGTAG------TTACCTTCTCTACCATTGGATTAGGTTAC
TraesCS7D02G403100      TATATTAGTATCAGAAAGCTTGTAG------TTACCTTCTCTACCATTGGATTAAGTTGC
AT4G19185               ------ACTAGGACAG---------------TTGTTTTCTGGATTA--------------
TraesCS3B02G026700      GATATCCCTTGGAGATG--------------------TGTGTACTGATGTGGGTGTTTGA
TraesCS6B02G298700      GATGTTGGGAAGAGAAGTGCTGCAGAGAAGATTGTACTGACGATTGGTAATGATGTTGGC
TraesCS6A02G271500      GATGTTAGGAAGAGAAGTGCTGCAGAGAAGATTGCACTGAAGATTGTTAACGATGTTGGC
TraesCS6D02G251700      GATGTTAGGAAGAGAAGTGCTGCAGAGAAGATTGCTCTGAAGATTGTTAATGATATTGGC
                                    * *                      *    *                 

TraesCS7A02G409900      ATC------------------TCATACCCAAATACCCTCAACATAAGCTGGAATGGAAAT
TraesCS7B02G309300      ATC----------ATTAAGGCTCATACCCAAATACCCTCAACATAAGCTGGAATCGAAAT
TraesCS7D02G403100      ATC----------ATTAAGGCTCATACCCAAATACCCTCGACATAAGCTGGAATGGAAAT
AT4G19185               ----------------------------CCCAGTTCCTCTGTGAAATCTGCA--------
TraesCS3B02G026700      A---------------------CGTACTCCTACCTTTTTAAC------------------
TraesCS6B02G298700      ATCTGTGTCGGCTGCAGAAAATCATACTCTCAGACCTTCCATAGGAGCAGTTAGGTTAAT
TraesCS6A02G271500      ATCTGTGTCCTCTGCAGAAAATCATACTCTCATACCTTCCATAGGAGCTGTTAGGTTAAT
TraesCS6D02G251700      ATC-----------------ATCATAATCTCATACCTTCCATAGGAGCAGTTAGGTTAAT
                                                    *  *     *                      

TraesCS7A02G409900      GGGTCGCAATTATCGTTCTCCTAGCAGCCGCAGAAGA-------------TGCTAACGAT
TraesCS7B02G309300      GTGTCGCAATTATCGTTTTCCTAGATGCTATTGGCACT------------GGCTAACGAT
TraesCS7D02G403100      GTGTCGCAATTATCGTTCTCCTAGCAGCCGCGGAAGATGCTACTGGCACTGGCTAACAAT
AT4G19185               --------------------------------------------------GACTAAAAAG
TraesCS3B02G026700      --------------------------------------------------TACTAGTG--
TraesCS6B02G298700      TTA-----------------------------------------------GGCAAAAGAG
TraesCS6A02G271500      TTA-----------------------------------------------GACAAAAGAG
TraesCS6D02G251700      TTA-----------------------------------------------GACAAAAGAG
                                                                            * *     

TraesCS7A02G409900      GTGCGATGATAGTTCAGTTTCAACAGTTGTCTTCATGGGTCAAGGAACAGCTTCAGTGAT
TraesCS7B02G309300      GTGCGATGATAGTTCAGTTTCAGCAGTTGTCTTCATGGGTCAAGGAACAGCTTCAGTGAT
TraesCS7D02G403100      GTGCAATGATAGTTCAGTTTCAGCAGTTGTCTTCACGGGTCAAGGAACAGCTTCAGTGAT
AT4G19185               ATACCA---------------------------------------AAAAGTTAAGATTCA
TraesCS3B02G026700      -------------------------------TTTCAAGCGTGCGATGCGACCAAGAAGAA
TraesCS6B02G298700      AAGCCATGCTCATTCTGCTT-----------TTTCAGACTAACA--ACATTGAGGATGCT
TraesCS6A02G271500      AAGCCATGTTCATGCTGTTT-----------TTCTAGGCTAACAACACACTGAGGATGCT
TraesCS6D02G251700      AAGCCATGTTCATCCTGTTT-----------TTCTAGACTAACA--ACATTGAGGATGCT
                                                                                    

TraesCS7A02G409900      CAAA----GGTAATTACTTCATCGAACCCAACTTGTTAATAGTTCATTAGTTATCATCGT
TraesCS7B02G309300      CAAA----GGTAATTACTTCATCGAACCCAACTTGTTAATAGTTCGTTAGCTATCATTGT
TraesCS7D02G403100      CAAA----GGTAATTACTTCATCCAACCCAACTTGTTAATAGTTCATTAGTTATCATCGT
AT4G19185               GACG-------------------AGATCCCATTTTACAACAGCTA--TAACT--TTTTGT
TraesCS3B02G026700      GAAG---------------------------------ACCCGTAC--TAGTTGACGATGT
TraesCS6B02G298700      GAGT---TGATGATTCTATTACCAAATGCAA------GGTAGCAC---CACCGACTTTGT
TraesCS6A02G271500      GAAT---TGATTATTCTATAACCAAATGCAA------GGTAGCTC---CACCGACTTCGT
TraesCS6D02G251700      GAATTGATGATTCTTCTGTAATCAAATGCAA------GGTAGCTC---CACCGATTTCGT
                         *                                       *                **

TraesCS7A02G409900      AATTGCTTAATTGGCAT--ATGGCTGCCATGATTGCTGGTGTTAACTTGCATTTTATCTT
TraesCS7B02G309300      AATTGCTTAATTGGCAT--ATGGTTGCCATGATTGCTGTTGTTAACTTGCATTTTATCTT
TraesCS7D02G403100      AATTGCTTAATTGGCAT--ATGGCTGCCATGATTGCTGCTGTTAACTTGCATTTCATCTT
AT4G19185               TAACTTTCATCTCTTATTAATATCTTCTTCGATTACTACTAATCACAG-------ATTCA
TraesCS3B02G026700      GAACTGCCAA---------ACACACTCAGACATATTTGGTACCTACT--------GTGTA
TraesCS6B02G298700      GAAATACAA--TAGTAT--GTATATCCCGTGA-AATCCCTACATACATACAT---ATGTA
TraesCS6A02G271500      GAAATCCAG--TAGTAT--GTATATCCCGTGA-AATCCCTACATACATACAT---ATGTA
TraesCS6D02G251700      GAAATCCAA---------------------------TAGCATGTACATACAT---ATGTA
                         *                                          **          *   

TraesCS7A02G409900      CTGCTTCAGCAGCCTCTATTACTGTCTGGGATCTGACTCTGCAATACAGT-ACAAACAAA
TraesCS7B02G309300      TTGCGTCAGCAGCTTCCGTTACTGCCAGGGCACCGACTCTGCAATACAGTATAAGACAAA
TraesCS7D02G403100      CTGCTTCAGCAGCCTCTATTACTGCCTGGGAACCGACGCTGCAATACAGTATAAGCCAAA
AT4G19185               CAAGTACTTGCTCCCTTGTTAAT-------------------------------------
TraesCS3B02G026700      TAGCCCCTT--GTCTTCGA-GTTGTGTG------------------TGTCTATAAATACA
TraesCS6B02G298700      TAAACTCTGTAGCCAGTGAGGTCATGTG-----------TGTAGAACTTTGAGAGAAATG
TraesCS6A02G271500      TGAACTCTGTAGCCATTGATGTCATGTG-----------TGTAAAACTTTGAGAGAAATG
TraesCS6D02G251700      TGAACTCTGTAGCCATTGAGGTCATG-------------TGTAAAACTTTGAGAGAAATG
                              *                                                     

TraesCS7A02G409900      CTGTTCTTCGTTGA----------TTTTCGTAATGCCATACTTGCGAAGCAATTATG---
TraesCS7B02G309300      CTGTTCTTCTGTGATGATTTCCAATTTTCATCGTGCCATACTTGCAAAGCAATTATG---
TraesCS7D02G403100      CTGTTCTTCTGTTATGATTTCCAATTTCCGTCATGCCATACTTGCGAAGCAATTATG---
AT4G19185               ---TACTCTTTAAT---CTTGAAGCTCATCT-----------------------------
TraesCS3B02G026700      CTATGCTCCCTAAT---TTTGAAGCTCTCCCAGTCTAGT---------------------
TraesCS6B02G298700      TTTTACTCTCTTACATCTGTTAAGTTCTTGTAGTTCATGCCTTGTTTCATACTACTACTC
TraesCS6A02G271500      --AAACTCTCTTAT--CTGTGAAGTTCTCGTAGTTCATACCTTGTTTCGT----------
TraesCS6D02G251700      --AAACTCTCTTAC--CTGTGAAGTTCGTGTAGTTCATACCTTGTTTCGTACTACTACTC
                             **                  *                                  

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GATGAGTTAGCAATTCTGCAGGCTGGACGTGTGTTGCAAGTATTTTCCAGGCTGTTTTTT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AATGAGTTGGCAATTCTGCAGTCTGGACGCGTGTTGCAACTATTTTTCAGGCTGTTCTTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TGTA------CTGCAGGTATGTTTTTCACCAACAATTCTTTCTTGTAAACATGTAAATGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGCACTGCACCTGCAAGTATGCTTTTCACCAATAGTTCGTTCTTGCAAACATGTAAATGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TACACATGAGATGACCTATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTAC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TACACATGAGATGACCTATTTCTCCTATGTGTATGTCATGGGATCCTATACATGACCTAC
                                                                                    

TraesCS7A02G409900      ----------------------------------TCTGGAGCTCAGTGCATAAGTGGGAA
TraesCS7B02G309300      ----------------------------------TCTGGAGCT-------------GGAA
TraesCS7D02G403100      ----------------------------------TCTGGAGCTCAGTGCATAAGTTGGAA
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ----------------------------------TGTGGTGTTCAATT------------
TraesCS6B02G298700      CCATGCACCACTCTATTGGTCTACTATTATACATCGTGGCGCGCAATCTATGGCGCGGAA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCATGCACCACTCTGTCGGTCTACTATTGTACATTGTCGCACGCAATCTATGGCGCGGAA
                                                                                    

TraesCS7A02G409900      AAATCAAAG---TAGGAGTTCCAAATTCTTTGGCACATCAG-------------------
TraesCS7B02G309300      AAATCAAAG---TAGGAGCTCCAAATTCTTTGGCACATCAG-------------------
TraesCS7D02G403100      AAATCAAAG---TAGGAGCTCCAAATTCTTTGGCACATCAG-------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------TTAGAATTTTGGATTATGATTTTCACTGG-------------------
TraesCS6B02G298700      ACATCGAACGTGTTGGCGTGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACATCGGACGTGTTGGCATGTCTGAATCTGATGATCATTGGTGCTGTGACCGGAGCTCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CCTGAGTGACGAATAGGCCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCTGCGTGACGAACAGGCCGTGGAAGCCGTAGGGGACGCGGGAGGGAAGCTGCACCTCGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGACGATGTCCAGGTCGGGCGACTGCGCGTCCATCACCACGAACCTGTTGTCGCCGGTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGACGATGTCCAGCTCGGGCGCCTGCGCGTCCATCACCACGAACCGGTTGTCGCCGGTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CCTCGTCGTGCACGTAGCACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCGACGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCTCGTCGTGCACGTAGCACACCACGTAGCCGTCGTCCTCGTCGCCGTTCCCCTCAACGT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CATCAGGGACGAAAAACGGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGTCGGGGACGAAGAACGGCTCCCCGGCGAAGCACCCCGGCCCGAAGTCCCGGCGCGCCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGGTGCAGTCGCCGTGGCCAGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGTGCAGTCGCCGTGGCCGGCGCGGTCGAAGTCGAGCTTGGCCACCCCGCCGATCTTGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCATGGGGTCGCCAACACCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCTCGGGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCATGGGGTCGCCCACGCCGAAGTAGCCGTAGCGGTTGCGGCGGCCGAGGCAGCCCGGGT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TGATCACCCCGAAGTCGAGGTTCGCCGCCGCGAGCGGCGTGCGTGTGACGTTGCCGGTGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGATCACGCCGAAGTCGAGGTTCGCCGCCGCGAGCGGCGTGCGGGTGACGTTGCCGGTGC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GGAGGTTGATGCGCACCAGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGAGGTTGATGCGCACCAGCTCCACGGAGGCGTGGATCAGCTCCATGCGCTCCAGCGTGT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCTCGATGGACAGGATGTTGGGTGCCACCATCACGATCTCGTCGCCGCCGGCCTCCTCCC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCTCGATGGACAGGATGTTGGGCGCCACCATCACGATCTCCTCGCCGCCGGCCTCCTCCC
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ACGCGTTCACCGAGTGCATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGCGTTCACCGAGTGCATCATGTTGAACCCCGGCACCTCGAACCACCGCATCTCCGACT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGTCCGCGGCGTACTTGGGGATCACGCCGAGGCGAGGCACCATGCCGGGGTCCGCCCCGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGTCCGCGGCGTACTTGGGGATCACGCCGAGGCGTGGCACCATGCCCGGGTCCGCCCCGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGGGCGAGCCGCCGCCCACCACCATGCCCATGGGGTTCATCACGATTTGTATCTCCGGGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGGGCGAGCCGCCGCCCACCACCATGCCCATGGGGTTCATCACGATCTGTATCTCCGGGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ATATCGCATAATGCTCCGTCACGGCGAAGTCGTGCAGGAAAGACGGTTGCTTCACGGAGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ATATCGCATAATGCTCCGTCACGGCGAAGTCGTGCAGGAATGACGGCTGCTTGACGGAGA
                                                                                    

TraesCS7A02G409900      -----GCCGCTCGAGTGTTCTTACT-----------------------------------
TraesCS7B02G309300      -----GCCGCTGGAGTGTTCTTACT-----------------------------------
TraesCS7D02G403100      -----GCCGCTTGAGTGTTCTTACT-----------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ----------GTCAACGATTTTGATT----------------------------------
TraesCS6B02G298700      AGATGGGCACGTCGGCGCCCTTGTTCCCTGCAGGGTCGAACCGGAAATAGGTGACGAACG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGATGGGCACGTCGGCGCCCTTGTTCCCTGCCGGGTCGAACCTGAAGTAGGTGACGAACG
                                                                                    

TraesCS7A02G409900      --------------------------------------TTGCTTCTGTTGTATCTGCCTT
TraesCS7B02G309300      --------------------------------------TTGCTTCTGTTGTATCTGCCTT
TraesCS7D02G403100      --------------------------------------TTGCTTCTGTTGTATGTGCCTC
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      --------------------------------------GAGGTTATTTTAAATTTGGTTT
TraesCS6B02G298700      GCGGCATGGGGCCGTAGCGGAACGCGAAGAGCTCGCCGGTGATGGGGTCCTTCTTGGGGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GTGGCATGGGGCCGTAGCGGAACGCGAAGAGCTCGCCAGTGATGGGGTCCTTCTTGGGGT
                                                                                    

TraesCS7A02G409900      CCACTGTTGTGT------------------------------------------------
TraesCS7B02G309300      CCACTGTTGTGCCTCTTGCGATGT------------------------------------
TraesCS7D02G403100      CCTCTTATGT--------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ACAATTTTTCTTCAGT--------------------------------------------
TraesCS6B02G298700      GCGCGGTCATGCCCATGCTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGCGGTCATGCCCATGCTGAGGCGGCCACCGAAGTCGCACCTGCCGAGCGTGGTCACCT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CACCGGTGGCCGGGTCGACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGTGCGTAGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CACCGGTGGCCGGGTCGACGCGCACGGCGTACGGGAGGTCCGACTCGCCGAGCGCGTAGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GGCGGCCGCCGAAGACGGCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGCGGCCGCCGAAGACGGCGAGGCTGGTGTTGGCGAGCCCCACGCCCTCCATCGGGTTCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TCTGGCCTGTCAGCACCCTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TCTGGCCTGTCAGCACCCTGGCCGCCGTGACGGCGCCGCGCGCCATCCCGGCCAGGCCAT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GGAAGCCGGAGAAGACGTTGGGCAAGACCGGCTCGCCCGCGTTGCGCTCCACGATGTACT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGAACCCGGAGAAGACGTTGGGCAAGACCGGCTCGCCGGCGTTGCGCTCCACGATGTACT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      TGTACGTCTGCACGTAGCGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TGTACGTCTGCACGTAGCGGGAGCAGAGGACGGGGTCGGAGTCGGGCGCCGTCGGGAGGA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCAGGGAGTGCAGCATGCCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGATGCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCAGGGAGTGCAGCATGCCGTCGCCGTCGAAGAGGTGGTGCGGCCCGCGCGGGAGGTGCT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCGGGTTGGGCCCGTTGCGGATGTAGGCGCCGCCGGCGAGGCAGCGCGGGATGACGCCGC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGGGTTGGGCCCGTTGCGGATGTAGGCGCCACCGGCGAGGCAGCGCGGGATGACGCCGC
                                                                                    

TraesCS7A02G409900      -------------------------------------------AAATTGTTGGCACGGT-
TraesCS7B02G309300      -------------------------------------------AAATTGTTGACACGGT-
TraesCS7D02G403100      -------------------------------------------AAATTGTTGGCACGGT-
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCACCACGGGGCAGGGCGTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCA
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCACCACGGGGCAGGGCGTGGGCGGCAGCTCGTCCACGGGCGCGAAGTTGGCGGACAGCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGTGCCGCGGGTCCACCGACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGTGCCGCGGATCCACCGACGGACGCAGCACCGGCGGGTCGACGAACGTGTTGATCGCCT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CCTCCAGCGCGTTGCAGAACGCCGCCTGTAGCGAAGTGACGGGCCGGCGGCGAGGCCTGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CCTCCAGCGCGTTGCAGAACGCCGCCTGTAGCGAAGCAGTAGGCCGGCGGCGAGGCCTGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ACGACCGAGCCGCCTGGCGCGGCGCATCGGATGCCCTGCTCGTTCTCGCGGTAGCAACTC
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ACGACCGA------------GGCGCATCAGACGGCCTGCTCGTTCTCGCGGTAGTCACTC
                                                                                    

TraesCS7A02G409900      --------------------------------------TACAAAACAATCTTGTGTTGCC
TraesCS7B02G309300      --------------------------------------TAGAAAGCCATCTTGTGTCGCC
TraesCS7D02G403100      --------------------------------------TACAAAACCATCTTGTGTCGCC
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GTGTACCAGTTGCATTGTTCACGGACGTGTCGACCAGGTGCTCTTCCGTTTCTTGTTGCT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      TTGTAGCACTTACATTGTTAGTCGACGTGTCGACCAAGTGCTCTTCCGTCTCTTGTTGCT
                                                                                    

TraesCS7A02G409900      CAACTGCTTATGTT----------------------------------------------
TraesCS7B02G309300      CAACTGCTTATGTT----------------------------------------------
TraesCS7D02G403100      CAACTTATGTTTTAGGGTATGTTTAGTTTGTGCCCAAGGTTGCCCCACCAAAGCATTGGC
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGACCGGCTTGGGCGGCGAGGTGAGGACGGTGGCGGTGGCGGCAGCCCACGGCGGCGGGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGACCGGCTTCGGCGGCGAGGTGAGGACGGTGGCGGTGGCGGCAGCCGACGGCGGCGGGG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      TGGTTGAGGTTTTGGTTGCCCATGATTTG---------GCAACATTGGTAAGAAAAATGA
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GCGACGTGCCCTTCCTCCTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCGG
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GCGACGTGCCCTTCCTCCTTCTGTAGCTGGGGTTCGGAGCAGCAGCAGAAGAGGCAGCAG
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ACTAGAGTTGGCTAGAGTTCATTTGGCATGCCAAAAATTTGGCAACCATCCAAACAAAGA
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      GGGAGATGTAGGAGAGCCTCCTCGATCTCGCAGCATGAGCAGCATTGGCTTTGGCAGGGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      GGGAGATGTAGGAGAGCCTCCTCGATCTCGGAGCATGAGCAGCATTGGCTTTGGCGGGGT
                                                                                    

TraesCS7A02G409900      -----------------------------------------------------------T
TraesCS7B02G309300      ----------------------------------------------------------TT
TraesCS7D02G403100      CCAATCTTTGGGTCCAAAATTTTGATAAGGTGCACTTTGGCCACAATCCAAACACACCCT
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      AGAGATCAGGCATGCTGAAGTTGGAGGTGACAAGTGCT----------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGAGATCAGACATGCTGAAGTTGGAGGTGACAAGTGCT----------------------
                                                                                    

TraesCS7A02G409900      TACCCCCTTTGCTTGTATATAGAGAAATTTTATTGTGTTTGTTCTTCCATATATTTGTGA
TraesCS7B02G309300      ACTCCCTTCGCTCACTATTATGAGATGTTCTAACTTTTTCCTGATT-TGTATGTATATAG
TraesCS7D02G403100      TACTCCCTTCGTCACTATTATGAGATGTTCCAACTTTTTTCTGAT---------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ---CCCTCCATTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTGTTAGTGGATGAGT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      ---CCCTCCATTTTCTGCAATCTGCAGATCAATGGCTCTTTGGATTACTAGTGGATAACT
                                                                                    

TraesCS7A02G409900      ACGGTGGTAGTACTTGGACAT---------------------------------------
TraesCS7B02G309300      ACAAATTTAGTATTTGTTCTTCCATATACTGTGAACCGAACGGA----------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      AGCAATTTCTTTGTTGGAACTTGGAACCCAGGTGAGTAGCAGCAAACGCTGATACCAGTT
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AGCAA-------TTTTTGTGTTGGAACCCAGGTGAGTAGCAGCAAATGCTGACACCAGTT
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      CGCAGGCTACTGCCTTT-------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      CGCACACTACTGCCTTTGCTACTTGTATGCTATGGCTATATATAGCCTCGGTAAAAGGCA
                                                                                    

TraesCS7A02G409900      ------------------------------------------------------------
TraesCS7B02G309300      ------------------------------------------------------------
TraesCS7D02G403100      ------------------------------------------------------------
AT4G19185               ------------------------------------------------------------
TraesCS3B02G026700      ------------------------------------------------------------
TraesCS6B02G298700      ------------------------------------------------------------
TraesCS6A02G271500      ------------------------------------------------------------
TraesCS6D02G251700      AACTTACCTGGTGGAAATGTTTATTTGGTGAAAACTTCAAAGATTACGTGGACCGCTGGA
                                                                                    

TraesCS7A02G409900      ----------------------------------------------
TraesCS7B02G309300      ----------------------------------------------
TraesCS7D02G403100      ----------------------------------------------
AT4G19185               ----------------------------------------------
TraesCS3B02G026700      ----------------------------------------------
TraesCS6B02G298700      ----------------------------------------------
TraesCS6A02G271500      ----------------------------------------------
TraesCS6D02G251700      TCACAGCGACCGCACAATGTGGGAGGATGAAGAGTTGCGCTAGGGT
                                                                      
