CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      ------------------------------------------------------------
TraesCS5B02G219500      ------------------------------------------------------------
TraesCS5D02G228400      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AATCCTGAGGCATTCATGATACGAGTGGGATGCATGAAGGGGTCGCTCGGTCGGCCTATG
TraesCS3D02G003600      ---------------AGGCATGCATGATAGGAGTGGGATGAAGGGGTCGGTCGGCCTATG
TraesCS3B02G011600      --------------------------------------------------TCGGCGTATG
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      ------------------------------------------------------------
TraesCS5B02G219500      ------------------------------------------------------------
TraesCS5D02G228400      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CCCATGCATGAAGGTCTTCTCCGACCAACCATCGCTCACTCCACTGTCTGCCTCTAGCTG
TraesCS3D02G003600      CCCATGCATGAAGGTCTTCTCCGACCAACCATCGCTCACTTCACTGTCTGCCTCTAGCTG
TraesCS3B02G011600      CCCATGCACCAAGGTCTTCTCCGACCAACCATGGCTCACTTCACTGTCTGCCTCTAGCTG
TraesCS3B02G006900      -------------------------------------------------------AGCTG
                                                                                    

AT4G30420               -----------------------TAACTATT-----------------------------
TraesCS5A02G220400      ------------------------------------------------------------
TraesCS5B02G219500      ------------------------------------------------------------
TraesCS5D02G228400      ------------------------------------------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AGTGTCACTCT--GTAGCATGCTTACCTACT---GTCCAAGTGGAATGTCGTCTATATAG
TraesCS3D02G003600      AGTGTCACTCT--GTAGCATGCTCACCTACT---GTCCAAGTGGAATGTCGCGCGTCTAT
TraesCS3B02G011600      AGTGTCACTCTCTGTAGCATGCTCACCTACTGACGTCCAAGTGGAATGTCGCGCGTCTAT
TraesCS3B02G006900      AGTGTCACTCTCTGTAGCATGCTCACCTACTGACGTCCAAGTGGAATGTCGCGCGTCTAT
                                                                                    

AT4G30420               -----------ATCATG----------AGGATTAATAGTTATATAATTAACAAGATCGTC
TraesCS5A02G220400      -----------------GCAGCCGCCC--GCCCACTCGAC--TAGTTTCTCGAGATCTCT
TraesCS5B02G219500      -------------------------CCTAGCCCGCCTCAGCCGTTCCT-TGGAAACCGGC
TraesCS5D02G228400      -----------------GCAGCCGCCC--GCCTACTCGATTATAGTTTCTCGAGATCTCT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      -----TAGACACCCCTGGCTGCACTTCTCACTCACCTCATCCCTCCTGGCCTAGGCCGTC
TraesCS3D02G003600      ATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCATCC---CTGGCCTAGGCCGTC
TraesCS3B02G011600      ATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCATCC---CTGGCCTAGGCCTTC
TraesCS3B02G006900      ATAGCTAGACACCCCTGGTTGCACTCCTCACTCACCTCATCC---CTGGCCTAGGCCTTC
                                                                                    

AT4G30420               CTAACAGTATATACACTACTATACATAGCTT-----------------AAGATCTAAAGA
TraesCS5A02G220400      CCGGCGCCCGGCTAGCTACTTAGTGGTACCT-----------------------------
TraesCS5B02G219500      CGCCTACTCGACTAGTTTCTCGAGATCTCTC-------------------GACCTAGGTA
TraesCS5D02G228400      CCGGCGCCCGGCTAGCTGCTACGCAGTACCT-----------------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CTCTCTCTCGTCTCTCAGCGTCACCTCGCTC---CAGCAGCTTCGAGCTCGATCT-----
TraesCS3D02G003600      CTCTCTCTCGTCTCTCAGTGCCACCTCGCTC---CAGCAGCTTCTATCTCGATCTAGGGA
TraesCS3B02G011600      CTCTCTCTAGTCTCTCATCGCCACCTCGCTCCAGCAGCAGCTTCTATCTCGATCTAGGGA
TraesCS3B02G006900      CTCTCTCTAGTCTCTCATCGTCACCTCGCTCCAGCAGCAGCTTCTATCTCGATCTAGGGA
                                                                                    

AT4G30420               GAACGCAAAGTAAGATTTACGAGGAGAAAGAAAGATAGAAGATCATG-------------
TraesCS5A02G220400      -------------------ACCTAAGCAGCGGCGGCGGCGGGCGTTGCC-----------
TraesCS5B02G219500      -------------------GCGGCGGTGGCGGTGGCGGTGGGCGTTGCC-----------
TraesCS5D02G228400      -------------------ACCTAGGCAGTGGCGGGCGTTGCCATGGCC-----------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      -----CAAGCGAGGAAAGGGCAGCAGCAATGGCGGACGCGGTGGATGCCCGTCGGGTCTG
TraesCS3D02G003600      GAGATCAAGTGAGGAGAG-GGTGCAGCAATGGCGGACGCGGTGGACGCCCGTCGGGTGTG
TraesCS3B02G011600      GAGATCAAGTGAGGAGAG-GGTGCAGCCATGGCGGACGCGGTGGATGCTCGCCGGGTCTG
TraesCS3B02G006900      GAGATCAAGTGAGGAGAG-GGTGCAGCCATGGCGGACGCGGTGGATGCTCGCCGGGTCTG
                                                                                    

AT4G30420               -GGGAAGATAGAGGAGTACAAGCCGGTAATGGCGATGACGATGATTCAACTATGTTATGC
TraesCS5A02G220400      -------ATGGAGGAGCACAAGCCGCTGGCGGCCATGGTGGTGGTGCAGTGCATCTACGC
TraesCS5B02G219500      -------ATGGAGGAGCACAAGCCGCTGGCGGCCATGGTGGTGGTGCAGTGCATCTACGC
TraesCS5D02G228400      -------ATGGAGGAGCACAAGCCGCTGGCGGCCATGGTGGTGGTGCAGTGCATCTACGC
TraesCS7A02G281700      ----------------------------------ATGCTGGCGCTGCAGTTCGGGTACGC
TraesCS3A02G007100      CGGGATGCCGGAGAAGGCGCAGCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTACGC
TraesCS3D02G003600      CGGGATGCCGGAGAAGGCGCAGCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTACGC
TraesCS3B02G011600      CGGGATGCCGGAGAAGGCGCAGCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTACGC
TraesCS3B02G006900      CGGGATGCCGGAGAAGGCGCAGCTCCACGTGGCGATGCTGGCGCTGCAGTTCGGCTACGC
                                                          ***  *  * * **       ** **

AT4G30420               AGGA----GTGACTCTCTTTGCAAGAGCTACTTTGGTTCATGGATTAAGCCCTCGGGTTT
TraesCS5A02G220400      GG----CCATGGCGCTGTGGGCCAAGGCCATGTTCAGCCGCGGCATGAGCCCCATGGTGT
TraesCS5B02G219500      GG----CCATGGCGCTGTGGGCCAAGGCCATGTTCAGCCGCGGCATGAACCCCATGGTGT
TraesCS5D02G228400      GG----CCATGGCGCTGTGGGCCAAGGCCATGTTCAGCCGCGGCATGAACCCCATGGTGT
TraesCS7A02G281700      CGGCTTCCACATGGTGTCACGTC----TGGCGCTCAACATGGGCATCAGCAAGCTCGTCT
TraesCS3A02G007100      CGGCTTCCACGTCGTGTCGCGCC----TCGCGCTCAACATGGGCATCAGCAAGCTCGTCT
TraesCS3D02G003600      CGGCTTCCACGTCGTGTCGCGCC----TCGCGCTCAACATGGGCATCAGCAAGCTCGTCT
TraesCS3B02G011600      CGGCTTCCACGTCGTGTCCCGCC----TCGCGCTCAACATGGGGATCAGCAAGCTCGTCT
TraesCS3B02G006900      CGGCTTCCACGTCGTGTCCCGCC----TCGCGCTCAACATGGGGATCAGCAAGCTCGTCT
                         *                  *            *       **  * * *      ** *

AT4G30420               TTATCCTCTATAGGCAAGCCTTTGCCACCATTTTCATCTTCCCATTTCTTTACTTATCCA
TraesCS5A02G220400      TCGTCGTCTACAGGCAGGCCATCGCCACCGCTGTCCTCGTCCCCATCACCTTGCTCGCCA
TraesCS5B02G219500      TCGTCGTCTACAGGCAGGCCATCGCCACCCTTGTCCTCGTCCCCATCACCGTGCTTGCCA
TraesCS5D02G228400      TCGTCGTCTACAGGCAGGCCATCGCCACCGCTGTCCTCGTCCCCATCACCTTGCTCGCCA
TraesCS7A02G281700      TGCCCGTGTACCGCAACATCATAGCA----------------------------------
TraesCS3A02G007100      TCCCCGTCTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACTTCCTCG
TraesCS3D02G003600      TCCCCGTCTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACTTCCTCG
TraesCS3B02G011600      TCCCCGTCTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACTTCCTCG
TraesCS3B02G006900      TCCCCGTCTACCGCAACATCATCGCGCTCTTCCTCCTCGTCCCCTTCGCCTACTTCCTCG
                        *   * * **  *  *   * * **                                   

AT4G30420               GGTAATTAAACC-CATTAACCC------------------------------------AT
TraesCS5A02G220400      ACAGGTAACACAAGATCGATCCCTCTCTCTCT--------------------------CT
TraesCS5B02G219500      ACAGGTAAGACAAGATCGACCCCTCTCTCTTTCCTG----------------------CT
TraesCS5D02G228400      ACAGGTAAGACAAGATCGATCCCCCCCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AGAAGAAGGACCGGCCGAGGCTCACCCTCAGCTTCGCCGTCCAGTTCT-----TCTTCCT
TraesCS3D02G003600      AGAAGAAGGACCGCCCCAGGCTCACCCTCGGCTTCGCCGTCCAGTTCT-----TCTTCCT
TraesCS3B02G011600      AGAAGAAGGACCGACCCAGGCTCACCCTCGGCCTCGCCGTCCACTTCT-----TCTTCCT
TraesCS3B02G006900      AGAAGAAGGACCGCCCCAGGCTCACCCTCGGCCTCGCCGTCCACTTCT-----TCTTCCT
                                                                                    

AT4G30420               CCCTATCTCCCAAAT---------------------------------------------
TraesCS5A02G220400      CTCCTTCTCCCACTTCATAGACATCCGTTGGCGTAAATAAATTGTTTGTGTAAATAAATT
TraesCS5B02G219500      CTCACTAGGCGATCATTTTGTCACTCGTGGTGAGCTGTAGATTGTCCTTTTAT-------
TraesCS5D02G228400      CTCCTTCTCCCACTTCATAGACATCCGTTGGTGTAAATATATTGTC--------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CGCCCTCTGCGGCATCACCGCCAACCA---------------------------------
TraesCS3D02G003600      CGCCCTCTGCGGCATCACCGCCAACCA---------------------------------
TraesCS3B02G011600      CGCCCTCTGCGGCATCACCGCCAACCA---------------------------------
TraesCS3B02G006900      CGCCCTCTGCGGCATCACAGCCAACCA---------------------------------
                                                                                    

AT4G30420               --------------------------GGAAATGTGAAT-TTACAATTTGTTAAGAGTTTT
TraesCS5A02G220400      GTCTTTTCTCCAGGAAGAGGCTGAAGGAGATTGT-----TTGCATCGGGACGACAGGCTT
TraesCS5B02G219500      ---TTTTCCTCAGGAAGAGGCTGAAGGAGATTCT-----TTGTATCGGGACGACAGGCTT
TraesCS5D02G228400      ---TTTTCTCCAGGAAGAGGCTGAAGGAGATTGT-----TTGCATCGGGACGACAGGCTT
TraesCS7A02G281700      --------------------------GGGCTTCTGCCTGCTGGGCCTGGACAACACGTCG
TraesCS3A02G007100      --------------------------GGGCTTCTACCTGCTCGGCCTCGACAACACCTCC
TraesCS3D02G003600      --------------------------GGGCTTCTACCTCCTGGGCCTCGACAACACGTCC
TraesCS3B02G011600      --------------------------GGGCTTCTACCTCCTCGGCCTCGACAACACCTCC
TraesCS3B02G006900      --------------------------GGGCTTCTACCTCCTCGGCCTCGACAACACCTCC
                                                  *    * *      *       *   * *     

AT4G30420               ------------ATTTGCTTCAGAATCACCTTTCTCCATATCCGAATATGCAATT-----
TraesCS5A02G220400      CGTGCTGGTGTTCTTGGCCTC-----TCTCGTCGGGTACGTCCATATATGCCTTCTCGCG
TraesCS5B02G219500      CGCGCTGGTGTTCTTGGCCTC-----TCTCGTCGGGTACGTCCATATATGCCTTCTCGCC
TraesCS5D02G228400      CGCGCTGGTGTTCTTGGCCTC-----TCTCGTCGGGTACGTCCAT----GCCTTCTCGCG
TraesCS7A02G281700      CCGAC-------GTTCGCCTC-----CGCCATCTAGAAC-TCCGTGCCGGCCATC-----
TraesCS3A02G007100      CCCAC-------CTTCGCCTC-----CGCCATCCAGAAC-TCCGTGCCGGCCATC-----
TraesCS3D02G003600      CCCAC-------CTTCGCCTC-----CGCCATCCAGAAC-TCCGTGCCCGCCATC-----
TraesCS3B02G011600      CCCAC-------CTTCGCCTC-----CGCCATCCAGAAC-TCCGTTCCGGCCATC-----
TraesCS3B02G006900      CCCAC-------CTTCGCCTC-----CGCCATCCAGAAC-TCCGTTCCGGCCATC-----
                                     ** ** **        * *     *  ***      **  *      

AT4G30420               TTTTTAAGTTTCATT----GGTTTTCTTCTAATCCAAAA--AGTGGAAATGAGTGAATTG
TraesCS5A02G220400      GTCTTGCGAACGGTCACGTAC---GTGCTGAGCTGAGCACCGAAGCGATCGAACAGTCTT
TraesCS5B02G219500      ATCTTGCGAACGATCACGTACTGAGCTGAGCAGTGAGCACCGAAGCGATCGAACAGTCTT
TraesCS5D02G228400      GTCTTGCGAACGGTCACGTGCTGAGCT-------GAGCACCGAAGCGATCGAACAGTCTT
TraesCS7A02G281700      ACCTTCGCCATGGCC----GCCGCGCTCCGGATCGAGAA--GGTGCGGCTCGACCGGCGC
TraesCS3A02G007100      ACCTTCGGCATGGCC----GCCGCGCTCCGCATCGAGAA--GGTGCGGCTCGACCGCCGC
TraesCS3D02G003600      ACCTTCGGCATGGCC----GCCGCGCTCCGCATCGAGAA--GGTGCGCCTCGACCGCCGC
TraesCS3B02G011600      ACCTTCGGCATGGCC----GCCGCGCTCCGCATCGAGAA--GGTGCGCCTCGACCGCCGC
TraesCS3B02G006900      ACCTTCGGCATGGCC----GCCGCGCTCCGCATCGAGAA--GGTGCGCCTCGACCGCCGC
                           **                              *  *     *               

AT4G30420               GTTCACATCTCGTA-----------------------------------------TAGTA
TraesCS5A02G220400      GTTTACATCACTGATCATTTCTTCCT--AAAAAAAACATTACTGATCATTTCATTTGGTG
TraesCS5B02G219500      GTTTACAATACTGA------------------------------------TCATTTGGTG
TraesCS5D02G228400      GTTTACATTACTGATCATTTCTTCCTCAGAAAAAAACATTACTGATCATTTCATTTGGTG
TraesCS7A02G281700      GACGGCGTGGCCAA---------------------------------------GGTGGTG
TraesCS3A02G007100      GACGGCGTCGCCAA---------------------------------------GGTGCTG
TraesCS3D02G003600      GACGGCGTCGCCAA---------------------------------------GGTGCTG
TraesCS3B02G011600      GACGGCGTCGCCAA---------------------------------------GGTGCTG
TraesCS3B02G006900      GACGGCGTCGCCAA---------------------------------------GGTGCTG
                        *    *    *  *                                         *  * 

AT4G30420               TATAT-------------------------------------------TATTTATAAGTT
TraesCS5A02G220400      TGTATATCTGCAACGAATTAACAGGGCGACGGCGAATCAGTA--CATGTACTACCAAGGC
TraesCS5B02G219500      TGTGTGTCTGCAACGAATGAACAGGGCGACGGCCAATCAGTA--CATGTACTACCAAGGC
TraesCS5D02G228400      TGTATATCTGCAATGAATCAACAGGGCGACGGCGAATCAGTA--CATGTACTACCAAGGC
TraesCS7A02G281700      GGCACGCTGGC---------GTGCGTGGCGGGCGCATCGGTGATCATGTTGTACAAGGGC
TraesCS3A02G007100      GGCACGCTCGC---------GTGCGTCGCCGGCGCGTCCGTCATCACGCTCTACCAGGGC
TraesCS3D02G003600      GGCACCCTCGC---------GTGCGTCGCGGGCGCGTCCGTCATCACGCTCTACCAGGGC
TraesCS3B02G011600      GGCACGCTCGC---------GTGCGTCGCAGGCGCGTCCGTCATCACGCTCTACCAAGGC
TraesCS3B02G006900      GGCACGCTCGC---------GTGCGTCGCAGGCGCGTCCGTCATCACGCTCTACCAAGGC
                                                                           *   * *  

AT4G30420               TTTTTCTAACTTTCTATG----------------TGACATAC-TAAAATAGTTAAT----
TraesCS5A02G220400      ATCTACCTGGGGTCATCGTCCATGGCGACGGCCATGACGAACCTGATACCGGCGATCACC
TraesCS5B02G219500      ATCTACCTGGGATCATCGTCCATGGCGACGGCCATGACGAACCTGATACCGGCGATCACC
TraesCS5D02G228400      ATCTACCTGGGATCATCGTCCATGGCGACGGCCATGACGAACCTAATACCGGCGATCACC
TraesCS7A02G281700      -----CCAACCATCTTCGGCCCTGCCGGCGCCGGCGACGATA------------------
TraesCS3A02G007100      -----CCAACCATCTTCGCCCCTGCCG------ACGACAAGC------------------
TraesCS3D02G003600      -----CCAACCATCTTCGCCCCTACCGCCGGCGACGACAAGC------------------
TraesCS3B02G011600      -----CCCACCATCTTCGCCCCTACCGGCG---ACGACAAGC------------------
TraesCS3B02G006900      -----CCCACCATCTTCGCCCCTACCGGCG---ACGACAAGC------------------
                             *      **   *                 ***                      

AT4G30420               ----------TTTTGCTGGCCGATGGATTTTTTTTGTTGGGATTGTAGGAGAAAATCA--
TraesCS5A02G220400      TTCGTGCTGGCGACGTCAGTAGGGTGAGTACCGTACCTGGAACTGCAAGCAGTAAGCCGG
TraesCS5B02G219500      TTCGTGCTGGCGACGTCAGTAGGGTGAGTACCGTTCCTGGAACTGCAAGCAGCAAGCAGC
TraesCS5D02G228400      TTCGTGCTGGCGACGTCAGTAGGGTGAGTACCGTTCCTGGAACTACAAGCACTAAGCAGC
TraesCS7A02G281700      ----------AGTCGTT------GCAGGTGCCGTTTTTGG--------------------
TraesCS3A02G007100      ----------CGTCGTTGCAGCAGGAGGTGCCGTTTCTGG--------------------
TraesCS3D02G003600      -------------CGTCGTTGCAGGAGGTGCCGTTTCTGG--------------------
TraesCS3B02G011600      ----------CGTCGTTGCAGCAGGAGGTGCCGTTTCTGG--------------------
TraesCS3B02G006900      -------------CGTCGTTGCACGAGGTGCCGTTTCTGG--------------------
                                      *             *    *   ***                    

AT4G30420               ----------------------------------------------AAGATAGCTATATC
TraesCS5A02G220400      CA-----TTGCATTTTATTCACATCGTGTGTTCACAGTTTCTCATCATGCAAGTTTCATC
TraesCS5B02G219500      CGGCATTGCACTTTTCATTCACATCGTGTGTTCACAGTTCCTCGTCA----AGTTTCATC
TraesCS5D02G228400      CGGCATTGCACTTTTCATTCACATCGTGTGTTCACAGTTCCACATAATGCAAGTTTCATC
TraesCS7A02G281700      -----------------------------------------------------------T
TraesCS3A02G007100      -----------------------------------------------------------C
TraesCS3D02G003600      -----------------------------------------------------------C
TraesCS3B02G011600      -----------------------------------------------------------C
TraesCS3B02G006900      -----------------------------------------------------------C
                                                                                    

AT4G30420               TTCTTTGGATCTAAAGAG------------------------CTTTTCTTTAATATTCTT
TraesCS5A02G220400      ATCTGTGGTCTAAAAATG-AAATCCAGGCCATGAGCGTGTGCGCACCTTGTAGATCTCT-
TraesCS5B02G219500      ATCTGTGGTCTAAAAATG--AAATCAGGCCATGAGCGTGTGCGCATCTTGTAGATCTGT-
TraesCS5D02G228400      ATCTGTGGTCTAAAAAGG--AAATCAGGCCATGAGCGCGTGCGCATCTTGTAGATCCCT-
TraesCS7A02G281700      AGCGGTGGCCGGGGAGGGGAAGAACTGGACGCTGGGGTGCGTGTACCTTATCGGGCACTG
TraesCS3A02G007100      GGCCGTGGCTGGGGAGGGCAAGAACTGGACGCTGGGGTGCGTGTACCTCATCGGCCACTG
TraesCS3D02G003600      CGCCGTGGCCGGGGAGGGCAAGAACTGGACGCTGGGCTGCGTCTACCTCATCGGCCACTG
TraesCS3B02G011600      GGCCGTGGCCGGGGAGGGCAAGAACTGGACGCTGGGGTGCGTCTACCTCATCGGCCACTG
TraesCS3B02G006900      GGCCGTGGCCGGAGAGGGCAAGAACTGGACGCTGGGGTGCGTCTACCTCATCGGCCACTG
                          *  ***      *  *                                *       * 

AT4G30420               GGTCTCGCTTATAGGGTAAGT---GTATATTAAATTTAATTTCTTAAGAACTCC------
TraesCS5A02G220400      CGCGTCACTGCTTAGTCAGCTGAAGGGTATCGGGGACGATAATTATGGAATTAACTAATG
TraesCS5B02G219500      CGCCTCACTGCTTAGTCAGCTGAAGGGTATCGGGGACGATAATTATGGAATTAACTAATG
TraesCS5D02G228400      CGCGTCACTGCTTAGTCAGCTGAAGGGTATCAGGCACGATAACT-ATGAATTAACTAATG
TraesCS7A02G281700      CCTGTCGTGGTCCGGCTGGCTG--GTGCTGCAGGCACCGGTGCTTAAGAAGTACCTCGCG
TraesCS3A02G007100      CCTCTCGTGGTCCGGCTGGCTG--GTGCTGCAGGCGCCCGTGCTCAAGAAGTACCCCGCG
TraesCS3D02G003600      CCTCTCGTGGTCCGGCTGGCTG--GTGCTGCAGGCGCCCGTGCTCAAGAAGTACCCCGCG
TraesCS3B02G011600      CCTCTCGTGGTCCGGCTGGCTG--GTGCTGCAGGCTCCCGTGCTCAAGAAGTACCCCGCG
TraesCS3B02G006900      CCTCTCGTGGTCCGGCTGGCTG--GTGCTACAGGCACCCGTGCTCAAGAAGTACCCCGCG
                            **        *     *   *                  *   *** *        

AT4G30420               ----AATTAGATG----AATCTTGGACCATTTTACTTAT---------------------
TraesCS5A02G220400      GGGCAGTTAGGGT----CATAATATATG-TACTACTTCTACAGTATATGTAGGTAAGGTA
TraesCS5B02G219500      GGGCAGTTAGGGT----CATAATATATG----TACTTCTACAG--TATGTAGGTGAGATA
TraesCS5D02G228400      GGGCACTTAGCTAGGGTCATCATATATG----TACTTCT-CAGTATGT---------ATA
TraesCS7A02G281700      AGGCTGTCAGTCA----CCTCCTACACC----TGCTTCTTCGG--TGT------------
TraesCS3A02G007100      AGGCTGTCCGTCA----CCTCCTACACC----TGCTTCTTCGG--CGT------------
TraesCS3D02G003600      AAGCTGTCCGTCA----CCTCCTACACC----TGCTTCTTCGG--CGT------------
TraesCS3B02G011600      AGGCTGTCGGTCA----CCTCCTACACC----TGCTTCTTCGG--CGT------------
TraesCS3B02G006900      AGGCTGTCGGTCA----CCTCCTACACC----TGCTTCTTCGG--CGT------------
                              *  *         *  *  *      * *** *                     

AT4G30420               -----------------TCTCATTATT--------------TGTTTGCAGCATTACAAT-
TraesCS5A02G220400      GATCCAGAGAATATATATCCTATTCCTATGGGACAATAAACTGTGGCTAACAAGACAACT
TraesCS5B02G219500      GATCCACAGAA----TATCCTATTCCTATGGTACAATTAACTGTGGCTAACAAGGCAACT
TraesCS5D02G228400      GATCCACAGAA----TATCCTATTCCTATGGGACAATTAACTGTGAATAACAAGGCAACT
TraesCS7A02G281700      ---------------CATCCAGTTCCT--------------------CGTCATCGC----
TraesCS3A02G007100      ---------------CATCCAGTTCCT--------------------CATCATCGC----
TraesCS3D02G003600      ---------------CATCCAGTTCCT--------------------CATCATCGC----
TraesCS3B02G011600      ---------------CATCCAGTTCCT--------------------CATCATCGC----
TraesCS3B02G006900      ---------------CATCCAGTTCCT--------------------CATCATCGC----
                                         **   **  *                       **   *    

AT4G30420               ----CAATCAAAATCTATAT------------------CTTGA-----------------
TraesCS5A02G220400      TGTGCCCTCAACCACTAAGTAATCCAATTTTGTCAGTGTTCGTGCTTATAATGGTGGTAA
TraesCS5B02G219500      TGTGCCCTCAACTACTAAGTAAT-CAATTTTGTCAGTGTTCGAGCTTATAATGGTG---A
TraesCS5D02G228400      TGTGCCCTCAACCACTAAGTAATCCAATTTTGTCAGCGTTCGAGCTTATAATGGTA---A
TraesCS7A02G281700      --CGCCTTC-----------------------------TTCGA-----------------
TraesCS3A02G007100      --CGCCTTC-----------------------------TTCGA-----------------
TraesCS3D02G003600      --CGCCTTC-----------------------------TTCGA-----------------
TraesCS3B02G011600      --CGCCTTC-----------------------------TTCGA-----------------
TraesCS3B02G006900      --CGCCTTC-----------------------------TTCGA-----------------
                            *  **                              * *                  

AT4G30420               -----------------------------------------------AGGTCTT------
TraesCS5A02G220400      GTGCGGGAAGCGCACGCATGCCTGAGCTGTGTGACAGATCGATGCTTGGAGCTTCCGCAG
TraesCS5B02G219500      GTGCGGGAAGCGCACGCATGTCTGCGCTGTGTGACTGATCGATGCTTGGAGCTTGCGCAG
TraesCS5D02G228400      GTGCGGGAAGCGCACGCATGTCTGCGCTGTGTGGCTGATCGATGCTTGGAGCTTGCGCAG
TraesCS7A02G281700      --GAGGGACGC----------------------------CGGCGCGTGGGTTTTCCAC--
TraesCS3A02G007100      --GAGGGATGC----------------------------CGGCGCCTGGGTCTTCCAC--
TraesCS3D02G003600      --GAGGGACGC----------------------------CGGCGCATGGGTCTTCCAC--
TraesCS3B02G011600      --GAGGGACGC----------------------------CGGCGCATGGGTCTTCCAG--
TraesCS3B02G006900      --GAGGGACGC----------------------------CGGCGCCTGGGTCTTCCAC--
                                                                        *   **      

AT4G30420               ----------------------------------------------------TACTTAAC
TraesCS5A02G220400      TATTCCTGCCTGCATGGTAGACGTAGACGTGAAATGTTATCTGGTGTGGGCGTGTGTGGC
TraesCS5B02G219500      CATTCGTGCCTGCATGGTAGACGTAGACGTGAAATGTTATGTAGTGTGGGCGTGTGTGGT
TraesCS5D02G228400      TATTCGTGCCTGCATGGTAGACGTAGACGTGAAATGTTATCTGGTGTGGGCGTGTGTGGC
TraesCS7A02G281700      ------------------------------------------------------TTCGGC
TraesCS3A02G007100      ------------------------------------------------------TCCGGC
TraesCS3D02G003600      ------------------------------------------------------TCCGGC
TraesCS3B02G011600      ------------------------------------------------------TCCGGC
TraesCS3B02G006900      ------------------------------------------------------TCCGGC
                                                                                    

AT4G30420               TTCATCATCAATGGGAAGTGCAGTGGGTAACATCATC-------------------CCTG
TraesCS5A02G220400      TTGAGTACGTAACATGTGTGCGGTGTTCATCATCCTCTGTGTGTAGTGTAGGTTACCTCC
TraesCS5B02G219500      TTGAGTAAGTAGCATGTGTCGGGTGTTCATCATCCTC-------TGTGTACGCCACCTCC
TraesCS5D02G228400      TTGAATACGTAACATGTGTGCGGTGTTCATCATCCTC-----TGTGTGTAGGTTACCTCC
TraesCS7A02G281700      TC----------------CGAAATCTTCACCATCCTC----------------TACGCCG
TraesCS3A02G007100      TC----------------CGAAGTCTTCACCATCCTC----------------TACGCCG
TraesCS3D02G003600      TC----------------CGAAGTCTTCACTATCCTC----------------TACGCCG
TraesCS3B02G011600      TC----------------CGAAGTCTTCACCATCCTC----------------TACGCCG
TraesCS3B02G006900      TC----------------CGAAGTCTTCACCATCCTC----------------TACGCCG
                        *                      *    *  *** **                       

AT4G30420               CAATCACCT---------------------------TCCTCATCTCATTTCTCGCC----
TraesCS5A02G220400      CAATTAGTTGTGGTGAACGACGATTCCCGGGGACTGTCGGCATCTTGTGCTCTTCCTGTT
TraesCS5B02G219500      CAATAAGTT-------------------GTGGACTCTCGGCATCTTTTGCTCTTCC----
TraesCS5D02G228400      CAATAAGTTGTGGTGAACGACGATTCCCCGGGACTGTCGGCATCTTGTGCTCTTCCTGTT
TraesCS7A02G281700      TAAGCAGC-------------------------------GCATCCT--------------
TraesCS3A02G007100      TAAGCATAT------------------------TCATTAGTATCTTATACAATTTC----
TraesCS3D02G003600      TAAGCATTT--------------------------ATTAGTGTCCTATATAATTTC----
TraesCS3B02G011600      TAAGCATTT------------------------CTATTAGCACCCTATATAATTTC----
TraesCS3B02G006900      TAAGCATTT------------------------CTATTAGCACCCTATATAATTTC----
                         **  *                                     *                

AT4G30420               ----------------GGGTATATGCATATACAC---ATTT-ATATGGAAATTGTGAAAA
TraesCS5A02G220400      TCTGTCAATTTTCCCACTGATCGTGCAGATCGAA---CATT-CTCT--TCTCTGTAAACA
TraesCS5B02G219500      -----------TCCCACTGATCGTGCAGATCGAA---CATT-CTCTGAAACAAATAAACA
TraesCS5D02G228400      TCTGTCAGTTTTCCCACTGATCGTGCAGATCGAA---CATT-CTCTGAAACAAATAAACA
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------GCAGTTAAGAATTAACTACTCCGTCTCATAACATAA
TraesCS3D02G003600      ------------------------GCAGTTAAAAATTAATT-ACTCCTTCCATCTCATAA
TraesCS3B02G011600      ------------------------GCAGTTAAGAGTTAGTT-GTTTTCT-----------
TraesCS3B02G006900      ------------------------GCAGTTAAGAGTTAGTT-GTTTTGT-----------
                                                                                    

AT4G30420               CAAGA-------------------------------------------------------
TraesCS5A02G220400      CATGGAATAGG-----------GCTAAAAGATTTAGGTCTAGTATGTGTCTTATGTTCCA
TraesCS5B02G219500      CCTGGGTACGGACTACGGAGGGATTAAAAGATTCAGGTCTAGCATGTTTCTTCTGTTCCA
TraesCS5D02G228400      CCTGGGTACAGA--------GGGCTAAATGCTTCGGGTCTAGCATGTTTCTTCTGTTCCA
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CATAAGAACGT-------------------------------------------------
TraesCS3D02G003600      TATAAAAGCGT------------------TTTTTTACACTAGTACTTTCTTCGTAAACTA
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      AAATGCTAGAAAATTACTTTTACTTATACTACATGTAAGGAGAATGACAAGTAACAGAAA
TraesCS5B02G219500      A-----------AGTGCTAAACACTACACTACCTGTAAGAAAAATG-CTAGTAACAGAAG
TraesCS5D02G228400      A--------AGTAGTACTAAACACTATATTACCTGTAAGGAAATTG-CTAGTAACAAAAG
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ----------------------------TTATATAATATATATTAGACCTGGAATCTCAA
TraesCS3D02G003600      A-------------TATAAAAGATGATCTAAACGCTCTTATATTAGGCCTGGAATCCCAA
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      TCATCTAGCACCCGACACTGCTGACT----------------------------------
TraesCS5B02G219500      TCAGCTCCCCTAGACCCCTGGTTCATCAAGCACAGATCTGTGACAAGCAGTAGCCGTTCC
TraesCS5D02G228400      TCATCTGCCCTAGACCCCTGGTTCATCAAGCACAGATCTGTGACAAGCAGTAGCAGTTCC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TCACGTACTAATTACT--------------------------------------------
TraesCS3D02G003600      TCACATACTAATTACTACT-----------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               ---------------------------------TTTATGTGCTAC---------------
TraesCS5A02G220400      ------GTACTACAAAATGCAATGAAGGCTGTCTTTCTAGGACACCAGCACAGTAGTGCC
TraesCS5B02G219500      ACTTGGCTACTACAGATTGCAATAAAGGCTGCCTTTCTAGGACACCAGTACAGTAGTGCC
TraesCS5D02G228400      ACTTGGCTACTACAGATTGCAATAAAGGCTGTCCTTCTAGGACACCAGTACAGTAGTGCC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ---------------------------ACTCTCTATCTGTGGTGCAAAT-----------
TraesCS3D02G003600      ---------------------------ACTCTCTATCTGAGGTGCAAAT-----------
TraesCS3B02G011600      ---------------------------ACTCTCCGTCTGTGGTGCAAAT-----------
TraesCS3B02G006900      ---------------------------ACTCTCCGTCTGTGGTGCAAAT-----------
                                                                                    

AT4G30420               -----------------------------------TTACTTACTAAA-------------
TraesCS5A02G220400      GACAACGTACGTGGGGGGCTACGTACGGGGCAGCATTATTTGTGGAACGCTTCGGGGCAA
TraesCS5B02G219500      GACCACGTACGTGGGGGGCTACGTACGGGACGTCATCATTTGTGAAA-CTCTTGGGACAA
TraesCS5D02G228400      GACTAGGTACTTGGGGGGCTACGTACGGGGCATCATTATTTGTGAAA-CCCTTGGGACAA
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ----------------------------GATACGATAATTTGCTAAAGGAGTAGAGGTA-
TraesCS3D02G003600      ---------------------------GAAAATGATAATTTGCTAAAGGAGTAGAGGTA-
TraesCS3B02G011600      ----------------------------GATACGATAATTTGCTAAAGGACTAGAGGTA-
TraesCS3B02G006900      ----------------------------GATACGATAATTTGCTAAAAGACTAGAGGTA-
                                                                                    

AT4G30420               -----TACTAATTTA---------------------------------------------
TraesCS5A02G220400      AATACAAATAATTGG------TACTGTCACACGTTGTCACTTATATACACTCTGTTCTCC
TraesCS5B02G219500      GATGCAAATAATTGGTACTATCACACCCCAACGTTGCCACTTATGTACGCTCTCTTCTCC
TraesCS5D02G228400      AATGCAAATAACTGT---------------------------------------------
TraesCS7A02G281700      -----AACTAAGTCG---------------------------------------------
TraesCS3A02G007100      -----AACAAATTGATTTAAAAGTGGTGCAATGCAACAACCTGTACACCTCTCT------
TraesCS3D02G003600      -----AACAAATTTA-TTAAAAGTGGTGCAATGCAACAACCTGTACACCTCTCTCTCT--
TraesCS3B02G011600      -----AACAAATTTA-TTAAAAGTGGTGCAATGCAACAACCTTTTACACCTCTCT-----
TraesCS3B02G006900      -----AACAAATTTA---------------------------------------------
                              *  ** *                                               

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      ATCACTGTGTATGAGTGTCAG--TGGGCACTCTAACTAAGTGGGCTTCTTGC---TATAA
TraesCS5B02G219500      ATCACTATGAGTGTTAGTGGGGCTGGGTAGTCTAAATAAGAGGGCTTCTTGC--------
TraesCS5D02G228400      --TACTATGAGTGTTAGTGGGGCTGGGCATTCTAAATAAGTGGGCTTCTTGC--------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ----------------GCCAGGATCAACGATCTGTAGCAGTACTCCTTTAGCAAATTATA
TraesCS3D02G003600      ----------------GTCAGGATCACCGATCTGCACCAGTACTCCTTTAGCAAACTATA
TraesCS3B02G011600      ----------------GTCAGGATCACCGATT---AGCAGTACTCCTTTAGCAAATTATA
TraesCS3B02G006900      ------------------------------TTAAAAGCAGTACTCCTTTAGC--------
                                                                                    

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      GTAGTACTCTATTTAGG------------GAAGTATTTTACTGGAA-ACTCAATTACGAA
TraesCS5B02G219500      ---------TCTTTAGTCAAAAAAAAGTAGGAGC-ATTTACTGAAACGCTGGATTACAAA
TraesCS5D02G228400      ---------TCTTTAGT-------------GAAGTATTTACTGAAACGCTGAATTACAAA
TraesCS7A02G281700      ------------------------------CACTTAATTAGTGGAAGCCATGATGATCCA
TraesCS3A02G007100      GTATTATTTTATTCAGTGTAAATATATATCAAGTCAGTGAGTGGAAGGCATGATGATCCA
TraesCS3D02G003600      GTATTATTTTATTCAGTGTAAATATACATCAAGTCAGTGAGTGGAAGGCATGATGATCCA
TraesCS3B02G011600      GTATTATTTTATTCAGTGTAAATATATATCAAGTCACTGAGTGGAAGGCATGATGATCCA
TraesCS3B02G006900      -------------------------ATATCAAGTCAGTGAGTGGAAGGCATGATGATCCA
                                                                                    

AT4G30420               ------TTCTGATCTT---------------------------------TAGATACGAGA
TraesCS5A02G220400      AGTGGAATTGGTTACTAATGAAATTACCGCCGGCTCATGAACGCAGTCTAGAATGCGTGG
TraesCS5B02G219500      AGTGGAATTAGTTACTAATGAAATTACCGGCGGCTCATGCACGCAGTCTAGAAAGCGTGG
TraesCS5D02G228400      AGTGGAATTAGTTACTAATGAAATTACCGCCGGCTCATGAACGCAGTCTAGAAAGCGTGG
TraesCS7A02G281700      TGC---CTCGGATCTTAA-------GCTGCCTGC-TTTTGACTC--TCAAAGAGATATGG
TraesCS3A02G007100      TGT---CTCAGATCTTAA-------GCTGCTTGC-TTTTGACTC---TCAAGAGATATGG
TraesCS3D02G003600      TGT---CTCAGATCTTAA----GCTGCTGCTTGC-TTTTGACTC---TCAAGAGATATGG
TraesCS3B02G011600      TGT---CTCAGATCTTAA-------GCTGCTTGC-TTTTGACTC---TCAAGAGATATGC
TraesCS3B02G006900      TGT---TTCAGATCTTAA-------GCTGCTTGCTTTTTGACTC---TCAAGAGATATGG
                               *  * *  *                                    *     * 

AT4G30420               AACTGAA----------TCTCCGAGATATAAGAGGCTTAGCAAAGATCGCAGGGACGATC
TraesCS5A02G220400      AGATGAG----------GAAGC------CGCGAAGCGTGGCCAAGATATTCGGCACCGCC
TraesCS5B02G219500      AGATCAG----------GAAGC------CGCGAAGCGTGGCCAAGATATTCGGCACCGCC
TraesCS5D02G228400      AGATCAG----------GAAGC------CGCGAAGCATGGCCAAGATATTCGGCACCGCC
TraesCS7A02G281700      AAATGATTATGTTGGCCTATGCATATATCGCGAG--CTAGC------AGCTGACATGGC-
TraesCS3A02G007100      AAATGAT----------TATGCAAA---CGGAAG--GTGGC------AGCTGACATGGC-
TraesCS3D02G003600      AAATGAT----------TATGCAAA---TGTAAG--CTGGC------TGCTGACATGGC-
TraesCS3B02G011600      AAATGAT----------TACGCAGA---CGTAAGGCGTGGC------AGCTGACATGTC-
TraesCS3B02G006900      AAATGAT----------TATGCAGA---CGTAAGGCGTGGC------AGCTGACATGTC-
                        *  * *               *          *    * **          *  *     

AT4G30420               CTATGTGTAGCAGGAGCGATCT-CCATGACTCTTCTTCGTGGACCAAAGATTCT------
TraesCS5A02G220400      GTCTGCGTCGGAGGCGCCATGG-TCATGACCTTCCTCAAGGGCCCCAAGCTGCTGCACGA
TraesCS5B02G219500      GTCTGCGTCGGAGGCGCCATGG-TGATGACCTTCCTCAAGGGCCCCAATCTGCTGCACGA
TraesCS5D02G228400      GTCTGCGTCGGAGGCGCCATGG-TCATGACCTTCCTCAAGGGCCCCAAGCTGCTGCACGA
TraesCS7A02G281700      --AAATGAAAACGG---------TGATG----------------CAGGGCTTCATCGCGT
TraesCS3A02G007100      --AAATGAAAACGGTAATATAT-ACATG----------------CAGGGCTTCATCGCGT
TraesCS3D02G003600      --AAATGAAAACGGTAATATATAATATG----------------CAGGGCTTCATCGCCT
TraesCS3B02G011600      --AAATGAAAACGGTAATATAT-GCATG----------------CAGGGTTTCATCGCGT
TraesCS3B02G006900      --AAATGAAAACGGTAATATAT-ATATG----------------CAGGGTTTCATCGCGT
                              *     **           ***                *     * *       

AT4G30420               -CAACTCAGAATCCGCTTTACCGATCGCTAAATCGGTATTAG------------GACATC
TraesCS5A02G220400      CTCGCTGGGCGTCGGCGGCGCCGGGC-------------TGGGCCTGGACGACCTGCTTC
TraesCS5B02G219500      CTCGCTGGGAGTCGACGGCGCCGGGC-------------TGGACCTCCAAGACCTGCTTC
TraesCS5D02G228400      CTCGCTGGGCGTCGGCGGCGCCGGGC-------------TGGACCTGGACGACCTGCTTC
TraesCS7A02G281700      CCGGCGTGGCGTTCGCCGTGCAGATC-------------TGG------------TGCATC
TraesCS3A02G007100      CCGGCGTGGCGTTCGCAGTGCAGATC-------------TGG------------TGCATC
TraesCS3D02G003600      CCGGCGTGGCGTTCGCAGTGCAGATA-------------TGG------------TGCATC
TraesCS3B02G011600      CCGGCGTGGCGTTCGCAGTGCAGATC-------------TGG------------TGCATC
TraesCS3B02G006900      CCGGCGTGGCGTTCGCAGTACAGATC-------------TGG------------TGCATC
                            *   *  *   *    * *                * *              * **

AT4G30420               TTAAAGACCAGAACACGTG---------GTTGATTGGCTGTTTGTTC-TTGTTTTCTAGC
TraesCS5A02G220400      TTCTCAACTCGCCGGGGAGCCGGAACTGGGTGATGGGCGCGCTGTTCCTCGTCG-GCAGC
TraesCS5B02G219500      ---TCAACTCGCCGGCGAGCCGGAAATGGGTGACCGGCGCGCTGTTCCTCGTCG-GCAGC
TraesCS5D02G228400      TTCTCAACTCGCCCGCGAGCCGGAACTGGGTGATGGGCGCGCTGTTCCTCGTCG-GCAGC
TraesCS7A02G281700      ----------GACCACGGG----------------GGGCCGGTGTTCGTGGCGGTGTACC
TraesCS3A02G007100      ----------GACCGCGGG----------------GGCCCGGTGTTTGTGGCGGTGTACC
TraesCS3D02G003600      ----------GACCGCGGG----------------GGCCCGGTGTTCGTGGCCGTGTACC
TraesCS3B02G011600      ----------GACCGCGGG----------------GGCCCGGTGTTCGTGGCCGTGTACC
TraesCS3B02G006900      ----------GACCGCGGG----------------GGCCCGGTGTTCGTGGCCGTGTACC
                                  *     * *                **     ****  * *      * *

AT4G30420               ACTCTTTGTTGGTCCTTTTGGCTTATACTTCAGGTAAACTTCATTAAATAAATCAAAAGT
TraesCS5A02G220400      AGCTCCTGCTGGTCGCTCTGGCTCATCATACAGGTCCGTGTCAGTCAGCCAGCCAGGA--
TraesCS5B02G219500      AGCTCCTGCTGGTCGCTGTGGCTCATCATACAGGTCGGTGTCAGTCAGCCAGCCAAGA--
TraesCS5D02G228400      AGCTCCTGCTGGTCGCTCTGGCTCATCATACAGGTCGGTGTCAGTCAGTCAGCCAAGG--
TraesCS7A02G281700      AGCCTGTGCAGAC-------GCTCGT----------------------------------
TraesCS3A02G007100      AGCCCGTGCAGAC-------GCTGGT----------------------------------
TraesCS3D02G003600      AGCCCGTGCAGAC-------GCTCGT----------------------------------
TraesCS3B02G011600      AGCCCGTGCAGAC-------GCTCGT----------------------------------
TraesCS3B02G006900      AGCCCGTGCAAAC-------GCTCGT----------------------------------
                        *     **            ***  *                                  

AT4G30420               CTAAACTTTTTGTTGTTGTTATGTTTCTTGTCTTACAAGAAATGTGAGTTTTGTTTCAAC
TraesCS5A02G220400      --AGATCTTCAGGGAAGAGGAGCACAATATTAACC-------------------TTCTAC
TraesCS5B02G219500      --------------------------ATATCCATCATGAGAACTTGAACCTTGT----AC
TraesCS5D02G228400      --AGATCTCCACGGAAGGGGAGCACAATATCCATCACGAGGACTTGAACCTTGT----AC
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               AAAACCCTAGGTTCCAATCTCTGCCTACTATCCAGATAACCTCTCTTTATCAGCATGGAT
TraesCS5A02G220400      TATTTCACAGGTGCCGATCTGCAAGTCGTACGTGGATCCCCTGACGCTGTCGGCCTGGAT
TraesCS5B02G219500      TGTTTCACAGGTTCCGATCTGCAAGTCGTACGTGGATCCCCTGACGCTGTCGGCCTGGAT
TraesCS5D02G228400      TATTTCACAGGTTCCGATCTGCAAATCGTACGTGGATCCCCTGACGCTGTCGGCCTGGAT
TraesCS7A02G281700      --------------------------------------------CGTCGCCATCATGG--
TraesCS3A02G007100      --------------------------------------------CGTCGCCATCATGG--
TraesCS3D02G003600      --------------------------------------------CGTCGCCATCATGG--
TraesCS3B02G011600      --------------------------------------------CGTCGCCATCATGG--
TraesCS3B02G006900      --------------------------------------------CGTCGCCATCATGG--
                                                                    *     *  * ***  

AT4G30420               GTGTTTATTCGGAACAATACAATGTGCAGTCGTCACTTTCTTCCTTGAGAAAGACCCAAA
TraesCS5A02G220400      GTGCTTCCTGTCCACGGCGCAGATGGCGTTGCTCAACTCCTTCGTGCTGCCGGGCCTCGA
TraesCS5B02G219500      GTGCTTCCTGTCCACGGCGCAGATGGCGTTACTCAACTCCTTCGTGCTGCCGGACCTCGA
TraesCS5D02G228400      GTGCTTCCTGTCCACGGCGCAGATGGCGTTGCTCAACTCCTTCGTGCTGCCGGACCTCGA
TraesCS7A02G281700      -----------------------------------CCTCCATCAC---------CCTCGG
TraesCS3A02G007100      -----------------------------------CCTCCCTCAC---------CCTCGG
TraesCS3D02G003600      -----------------------------------CCTCCCTCAC---------CCTCGG
TraesCS3B02G011600      -----------------------------------CCTCCCTCAC---------CCTCGG
TraesCS3B02G006900      -----------------------------------CCTCCCTCAC---------CCTCGG
                                                             * * **           **    

AT4G30420               CGCTTGGATTCTCCATTCCTACTCCGAGTTTGCCACATGTCTCTATGCAGTACGCACATA
TraesCS5A02G220400      CGCCTGGAAGATCCACTCGCTCTTCGAGCTCATGGGCTGCATCTTCGCCGTAAGCTCAT-
TraesCS5B02G219500      CGCCTGGAAGATCAACTCGCTCTTCGAGGTCATGGGCTGCATCTTCGCCGTAAGTTCAT-
TraesCS5D02G228400      CGCCTGGAAGATCAACTCGCTCTTCGAGCTCATGGGCTGCATCTTCGCCGTAAGTTCAT-
TraesCS7A02G281700      AG---AGAAGTTCTAC---CTCGGCGGGATCATCGG---------CGCCGC--GCTCAT-
TraesCS3A02G007100      CG---AGAAGTTCTAC---CTCGGCGGGATCATCGG---------CGCCGC--GCTCAT-
TraesCS3D02G003600      CG---AGAAGTTCTAC---CTCGGCGGGATCATCGG---------TGCCGC--GCTCAT-
TraesCS3B02G011600      CG---AGAAGTTCTAC---CTCGGCGGGATCATCGG---------CGCCGC--GCTCAT-
TraesCS3B02G006900      CG---AGAAGTTCTAC---CTCGGCGGGATCATCGG---------CGCCGC--GCTCAT-
                         *    **   ** *      *  ** * *                ** *   *  *** 

AT4G30420               CAACATT--CCTCTGTTTTTTTTG--------------------TCTTTCTTTGGATGTT
TraesCS5A02G220400      CGTCGCC-CCATCCACTTTCAGTATTTCCCGTACGTGTCGCCGCCGTTTCCGCGGACAAA
TraesCS5B02G219500      CGTCTTC-CCATCCACTTTCAGTATTTCCCGTGCGCGTCGCCGCCGTTTCCGCGGACAAA
TraesCS5D02G228400      CGTCGTC-CCATCCACTTTCAGTATTTCCCGGCCGTGTCGCCGCCGTTTCCGCGGACAAA
TraesCS7A02G281700      CATCACCGGGCTCTACCT--------------------------TGTGCTCTGGGGCAAG
TraesCS3A02G007100      CATCACCGGCCTCTACCT--------------------------CGTGCTCTGGGGCAAG
TraesCS3D02G003600      CATCACCGGCCTCTACCT--------------------------CGTGCTCTGGGGCAAG
TraesCS3B02G011600      CATCACCGGCCTCTACCT--------------------------CGTGCTCTGGGGCAAG
TraesCS3B02G006900      CATCACCGGCCTCTACCT--------------------------CGTGCTCTGGGGCAAG
                        *  *       **    *                            *      **     

AT4G30420               GATTAATCCAAAAATTA--------------ACG-----------TAAACACTAATGCAT
TraesCS5A02G220400      CA----ACCACGGAGTATGTACAACTGTTGAACAATGTCGATCGTTGGGCACGCAGGGCG
TraesCS5B02G219500      CA----ACTACAGAGAGTGTACAACTGTTAAACAATGTCGATCGTTGGGCATGCAGGGCG
TraesCS5D02G228400      TATCTTGCTACGGAGTATATACAACTGTTGAACAATGTGGATTGTTGGGCATGCAGGGCG
TraesCS7A02G281700      AG------CGAGGAGAG---------GTCGCGCA-----------ACGGCAAGGAGGCGG
TraesCS3A02G007100      AG------CGAGGAGAG---------GTCGCGCA-----------TCGGCAAGGAGGCGG
TraesCS3D02G003600      AG------CGAGGAGAG---------GTCGCGCA-----------TCGGCAAGGAGGCGG
TraesCS3B02G011600      AG------CGAGGACAG---------GTCGCGCA-----------TCGGCAAGGAGGCCG
TraesCS3B02G006900      AG------CGAGGAGAG---------GTCGCGCA-----------TCGGCAAGGAGGCCG
                                     *                  *                **   * *   

AT4G30420               TTGTTAGGGAATTGGGGCGTCAGCACTTTCTTTTACGGTCCAAGCTTGGGCTATTGCAAA
TraesCS5A02G220400      CGGTCGGGT--CAGGCGTG-----ACGTTCTACC----TGCAGTCGTGGTGCATAACGGT
TraesCS5B02G219500      CGGTTGGGT--CAGGCGTG-----ACGTTCTACC----TGCAGTCGTGGTGCATAACGGT
TraesCS5D02G228400      CGGTTGGGT--CAGGCGTG-----ACGTTCTACC----TGCAGTCGTGGTGCATAACGGT
TraesCS7A02G281700      TGGCCATGG--CCGCGGCGTCCGCAGCTTCCTCC----GGCGGCG------------AGC
TraesCS3A02G007100      CGGTCATGG-----------CCGCAGCTTCCTCC----GGCAGTGGCG---------AGC
TraesCS3D02G003600      -----------CCGCCGCATCGGCAGCTTCCTCC----GGCAGCGGCG---------AGC
TraesCS3B02G011600      CGGTCATGG--CCGCCGCGTCCGCAGGTTCCTCC----GGCGGCGCCG---------AGC
TraesCS3B02G006900      CGGTCATGG--CCGCCGCGTCCGCAGGTTCCTCC----GGCGGCGCCG---------AGC
                                                *  ***          *                   

AT4G30420               GAGAGGTCCTGTGTTTTCTGCACTGTTTAATCCTCTTTGTACAGTCATTGTCACAATCTT
TraesCS5A02G220400      GAGGGGCCCTCTCTACTCGGCCATGTTCAACCCCCTCTGCACCGTCGTCACCACCGTGCT
TraesCS5B02G219500      GAGGGGCCCGCTCTACTCGGCCATGTTCAACCCCCTCTGCACCGTCGTCACCACCGTGCT
TraesCS5D02G228400      GAGGGGCCCTCTCTACTCGGCCATGTTCAACCCCCTCTGCACCGTCGTCACCACCGTGCT
TraesCS7A02G281700      GCGAGGTCCGGAGCGCCAAGC------TGGGCTCCTC--------CATCACC-CAGCCTC
TraesCS3A02G007100      GCGAGGTCCGGAGCGCCAAGC------TGGCCTCCTC--------CATCACC-CAGCCTC
TraesCS3D02G003600      GCGAGGTCCGGAGCGCCAAGC------TGGCCTCCTC--------CATCACC-CAGCCTC
TraesCS3B02G011600      GCGAGGTCCGGAGCGCCAAGC------TCGCCTCCTC--------CATCACC-CAGCCTC
TraesCS3B02G006900      GCGAGGTCCGGAGCGCCAAGC------TCGCCTCCTC--------CATCACC-CAGCCTC
                        * * ** **          **          *  **         * *   * *      

AT4G30420               GGCTGCTTTGTTCTTCCATGAAGAGATTTACACTGGAAGG-------------TAAC---
TraesCS5A02G220400      CGCCACCGTCATCCTCCACGAACAGCCACACATCGGAAGG------TGCGTCTTACTGTC
TraesCS5B02G219500      CGCCACCGTCGTCCTCCACGAACAGCCACACGTCGGAAGGTGTGTGTGTGTGTTACTATT
TraesCS5D02G228400      CGCCACCGTCATCCTCCACGAACAGCCACACATCGGAAGG------TGCGTCTTACTGTC
TraesCS7A02G281700      TCCTGCCGCCTTCCTCAAC---------CACCTCCGA----------------CAACGTC
TraesCS3A02G007100      TCCTCCCGCCTTCC---------------------GA----------------CAATGTC
TraesCS3D02G003600      TCCTGCCGCCCTCCTCCAC---------CACCTCCGA----------------CAACGTC
TraesCS3B02G011600      TCCTGCCGCCTTCCTCCAC---------CACCTCCGA----------------CAATGTC
TraesCS3B02G006900      TCCTGCCGCCTTCCTCCAC---------CACCTCCGA----------------CAATGTC
                          *  *     **                      **                 *     

AT4G30420               -GAAATATATACTTGATAGAAAAACTTGAGATAAACTACAATCCATAA------------
TraesCS5A02G220400      TGCAACTTCAGCATGCAGTTCGGTTTTGCTGATCCTGCCATTTTATTACTACTGTACTTC
TraesCS5B02G219500      TGCAACTTAG-CATGCAGTTCAGTCTCGTTGAACCCACCACTT-----------------
TraesCS5D02G228400      TGCAACTTCA----GCTGTTCGGTTTTGCTGATCCTGCCATTCTATTACTCCCTCCGTTC
TraesCS7A02G281700      TGGAACTTAGT--TGC---------TTGCTGT----------------------------
TraesCS3A02G007100      TGAAACTTAAT--TGCTACTGTACCCTACTG-----------------------------
TraesCS3D02G003600      TGAAACTTAAT--TGCT-----ACCTAGCTACCGT-------------------------
TraesCS3B02G011600      TGAAACTTAATTGTGCT-----ACCTTGCT------------------------------
TraesCS3B02G006900      TGAAACTTAATTGTGCT-----ACCTTGCT------------------------------
                         * **  *      *                                             

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      GAGAACTAGGCTGTAGCCTACTGGCAAGGGAGCGCAGTGGCGTCTCCAGCAACCAGGGTT
TraesCS5B02G219500      ------------------------------------------------------------
TraesCS5D02G228400      CGAA--------------TTACTTGTCGCAGGTGTGGATGTATCTAGATGTATTTTAGTT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               ----ACTTA---------------------------------------------------
TraesCS5A02G220400      CGAGCCACGTCGGGGACGAATTTCTGGTTTCTCACAAGGGATGCTTCTCCTATATCAATA
TraesCS5B02G219500      ------------------------------------------------------------
TraesCS5D02G228400      CTAGATACATCCATTTCTATGACGAGTAATTTAGAACGGAGGGAG---------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      ------------------------------------------------------------
TraesCS3D02G003600      ------------------------------------------------------------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               --------------------------------------------ATCTTTTTGATCTATT
TraesCS5A02G220400      AACCATGGGTGCTAGTGCCCATGAGTTTCATCTTTTTACTACTGTACTTCTCAACTTACC
TraesCS5B02G219500      --------------------------------------------CACTTTTCAACTTACT
TraesCS5D02G228400      --------------------------------------------TACTTCTCGGCTTACT
TraesCS7A02G281700      --------------------------------------------CCGTTCTCAA------
TraesCS3A02G007100      --------------------------------------------TCCTTCTCGA------
TraesCS3D02G003600      --------------------------------------------CGCTTCTCAA------
TraesCS3B02G011600      ------------------------------------------------------------
TraesCS3B02G006900      ------------------------------------------------------------
                                                                                    

AT4G30420               GAA-A--------------------TAGTTTAATCGGAGGATTGGGCGTGATATTGGGAC
TraesCS5A02G220400      TAG-C--GAAACGGTTCTGCTTGTCCAGCTTGTTGGGTGCATTCGCCGTGGTAGCCGGGC
TraesCS5B02G219500      TAACGACGAAACGGTTCTGCTTGTCCAGCTTGTTGGGTGCATTCGCGGTGGTCGCCGGGC
TraesCS5D02G228400      TGAGA--AAACCGGTTCTGCTTGTCCAGCTTGTTGGGTGCATTGGCCGTCGTCGCCGGGC
TraesCS7A02G281700      -------------------------CGATCGACTGAGAGTA-------------------
TraesCS3A02G007100      -------------------------CGACCGACTGAGAGGA-------------------
TraesCS3D02G003600      -------------------------CGATGGATTGTGAGGA-------------------
TraesCS3B02G011600      -------------------------------ACTGCGAGGA-------------------
TraesCS3B02G006900      -------------------------------ACTGCGAGGA-------------------
                                                         *  * * *                   

AT4G30420               TTTACACTGTGCTCTGGGGTAAAGCAAAAGATGTCATGATGAA-----------------
TraesCS5A02G220400      TGTACATCGTGCTGTGGGGCAAAGCAGGCAACGTCAAGAGCCCGAGGGCGGCGGGGCACG
TraesCS5B02G219500      TGTACATCGTGCTGTGGGGCAAAGCAGGCGACGTCAAGAGCCCAAGGGCGGCGGAGCACG
TraesCS5D02G228400      TGTACATTGTGCTTTGGGGCAAAGCAGGGGACGCCAAGATCCGGCGGGCGGCGGAGCACG
TraesCS7A02G281700      --------ATTTTCCTGTTTAAATT-----------------------------------
TraesCS3A02G007100      --------ACTTTCTTGTTTAAATT--------------TTAGGCGGGCATGCATGCACG
TraesCS3D02G003600      --------GTTTTCTTGTTTAAATT---------------CAGGCGGGCATGCATGCACG
TraesCS3B02G011600      --------GTTTTCTCGTTTAAATT---------------CAGGCGGGCATGCATGCACG
TraesCS3B02G006900      --------GTTTTCTCGTTTAAATT---------------CAGGCGGGCATGCATGCACG
                                    *   *   ***                                     

AT4G30420               -----TCAAGATC-AGAGAGACAATGATCAGAA---------------------------
TraesCS5A02G220400      C----CGATGATCTGGAGAAGACATGGTCGGGCTCTCAGCTCCTCGACGCGGAAAGTACG
TraesCS5B02G219500      C----CGATGATCTGGAGAAGACATGGTCGGACTCGCAGCTCCTCGACGCGGAAAGTACG
TraesCS5D02G228400      C----CGAAGATCTGGAGAAGACATGGTCGGGCTCGCAGCTCCTCGACGCGGAAAGTACG
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CCTAGCTATGGTGTGGTGAGCGAGTATGCAGAC---------------------------
TraesCS3D02G003600      C----CTATGGTGTGGTGAGCGAGTATGCAGAC---------------------------
TraesCS3B02G011600      C----CTATG-TGTGGTGAGCGAGTATGCAGAC---------------------------
TraesCS3B02G006900      C----CTATG-TGTGGTGAGCGAGTATGCAGAC---------------------------
                                                                                    

AT4G30420               ------------------------------------------------------------
TraesCS5A02G220400      ATCACCGCGCCGCTCCTGGCGGACAAGAATCCGATCGAGAAGTAAT----GGCTCTACAA
TraesCS5B02G219500      ATCACCGAGCCGCTCCTAGCGGACGACAACCGGATCGAGAAGTAGT----GGCTCTACAA
TraesCS5D02G228400      ATCACCGAGCCGCTCCTAGCGGACGACAACCAGATCGAGAAGTAGCCAGGGGCTCTACAA
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      --------------------------------------------------GGATTTGATT
TraesCS3D02G003600      --------------------------------------------------GGATTTGA--
TraesCS3B02G011600      --------------------------------------------------GGATTTGA--
TraesCS3B02G006900      --------------------------------------------------GGATTTGA--
                                                                                    

AT4G30420               ----------------------------------GTCAGAAGTGAAGATTCATATAGAAG
TraesCS5A02G220400      TTTTGGAACAGCCAGTGATCTTTCTCAGCTTATGGTCGCATGTG-TTCTGTAGCTGCATG
TraesCS5B02G219500      TTTTGGAATAGCCAGTGATCTTTCTCAGCTCATGGTCCCATGTGTTTTTGTAGTTACAGG
TraesCS5D02G228400      TTTTGGAATGGCCAGTGATCTTTCCCAGCTCATGGTCCCATGTGTTTTTGTAGCTTCAGG
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      GTTAAAACTAGCTAGGATTGTTT---GGGTCGTGCTTGATTATG-GTGTGTGCATTAAGG
TraesCS3D02G003600      -TTAAAACTAGCTAGGATTGTTT---GGATCGTGCTTGATTATG-GTGTGTGCATTAAGG
TraesCS3B02G011600      -TTAAAACTAGCTAGGGTTGTTT---GGATCGTGCTTGATTATG-GTGTGTGCATTAAGG
TraesCS3B02G006900      -TTAAAACTAGCTAGGGTTGTTT---GGATCGTGCTTGATTATG-GTGTGTGCATTAAGG
                                                                                    

AT4G30420               ATTCTTCAAACACAACAATCTGTAATAAAGATCTGAAGAATCCTCTGTTG----------
TraesCS5A02G220400      GTTGTT---TTTCGAGGGAGAGTACTAGTGTGCTGGTGGACCATGTGGCCAAGCCCAT--
TraesCS5B02G219500      GTTGTT---TTCTGAGGGAGAGTACTAGTGTGCTGGTGAAGCATGTGGCCATGGGCATCA
TraesCS5D02G228400      GTTGTT---TTTTGAGGGAGAGTACTAGTGTGCTGGTGGAGCATGTGGGCATGGGCATCA
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      CTTGTT---AATTAGTACTGTAGATCAGAAAACTTGCGCTTGATGTATTGGTACTTTACC
TraesCS3D02G003600      CTTGTC------AATTGGAGTAGATCAGAAAACTTGTGCTTGATGTATTGGTACCCTATC
TraesCS3B02G011600      CTTGTC------AATTGGAGTAGATCAGAAAACTTGTGCTTGATGTATTGGTACCCTATC
TraesCS3B02G006900      CTTGTC------AATTGGAGTAGATCAGAAAACTTGTGCTTGATGTATTGGTACCCTATC
                                                                                    

AT4G30420               ----------TCCAAACACAAATCAACAGAAGAAATCCAAAC------------ACATCA
TraesCS5A02G220400      --GGTGTCGCCGCTAATGT-ACAAAAGATAATGGCCGTAAAT-----G---TTGTTGTGT
TraesCS5B02G219500      TGCATGTCGCCGCTAATGT-ACAAAATATAATGCCCGTAAAT-----G---TTGTTGTGA
TraesCS5D02G228400      T----GTCGCCGCTGATGT-ACAAAATATAATGCCCGTGAAT-----G---TTGCTGTGT
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      TA---ATTATTATTATCACAACAGGGTTTGTTCACTACGAAG----GCACCTTCATGTTT
TraesCS3D02G003600      TAATGATTATTACTATCACAATAGGGTTTGTTCACTATGGATTCTACGTACTTAATGTCT
TraesCS3B02G011600      TAATTATTATTACTATCACAATAGGGTTTGTTCACTATAGAT--TGCC---TTAGTGTTT
TraesCS3B02G006900      TAATTATTATTACTATCACAATAGGGTTTGTTCACTATGGAT--TGCC---TTAGTGTTT
                                                                                    

AT4G30420               ACAACTATACTAA-----------------------------------------------
TraesCS5A02G220400      CCCAC-------------------------------------------------------
TraesCS5B02G219500      CCCACGAATTTAAGATGAGGTAGGGGGTGCTTACCAATTACGGCAACATATATTGTCTTG
TraesCS5D02G228400      CCCACAAATTTAAGATGAGTCAGGGGGTGCTTACCAATTACG------------------
TraesCS7A02G281700      ------------------------------------------------------------
TraesCS3A02G007100      AC----------------------------------------------------------
TraesCS3D02G003600      ACATCGTTTTTGCAATCAGTAATTAAGTGCCCCTCTG-----------------------
TraesCS3B02G011600      ACACTGTTTTTGCAATCAGTAATTAAGTAATTTCACAAC---------------------
TraesCS3B02G006900      ACACTGTTTTTGCAATCAGTAATTAAGTAATTTCACAACAACGAAAAAATC---------
                                                                                    
